# Generated by splitting app.py lines 10130-10174. Keep execution order in wangcai_app/startup/loader.py.
@app.get("/", include_in_schema=False)
def index() -> Response:
    if not has_configured_admin_password():
        return RedirectResponse("/auth")
    return html_response("index.html")


@app.get("/auth", include_in_schema=False)
def auth_page() -> FileResponse:
    return html_response("auth.html")


@app.get("/memory", include_in_schema=False)
def memory_dashboard(request: Request) -> FileResponse:
    if not is_analysis_authenticated(request):
        return html_response("analysis_login.html")
    return html_response("memory.html")


@app.get("/memory-admin", include_in_schema=False)
def memory_admin_dashboard(request: Request) -> FileResponse:
    if not is_analysis_authenticated(request):
        return html_response("analysis_login.html")
    return html_response("memory_admin.html")


@app.get("/warn", include_in_schema=False)
def warn_dashboard() -> FileResponse:
    return html_response("warn.html")


@app.get("/artifacts", include_in_schema=False)
def artifacts_dashboard() -> FileResponse:
    return html_response("artifacts.html")


@app.get("/characters", include_in_schema=False)
def characters_dashboard() -> FileResponse:
    return html_response("characters.html")


@app.get("/analysis", include_in_schema=False)
def analysis_dashboard(request: Request) -> FileResponse:
    if not is_analysis_authenticated(request):
        return html_response("analysis_login.html")
    return html_response("analysis.html")


@app.get("/analysis-login", include_in_schema=False)
def analysis_login_page() -> FileResponse:
    return html_response("analysis_login.html")


@app.get("/background", include_in_schema=False)
def background_dashboard(request: Request) -> FileResponse:
    if not is_admin_authenticated(request):
        return html_response("background_login.html")
    return html_response("background.html")


@app.get("/favicon.ico", include_in_schema=False)
def favicon() -> Response:
    return Response(status_code=204)
