# Generated by splitting app.py lines 1683-1693. Keep execution order in qwen_app/startup/loader.py.
@asynccontextmanager
async def lifespan(_app: FastAPI):
    init_db()
    start_memory_agent_worker()
    start_idle_agent_worker()
    yield


app = FastAPI(title="Qwen3.6 Web Chat", version="1.1.0", lifespan=lifespan)
app.mount("/static", StaticFiles(directory=str(STATIC_DIR)), name="static")
