# Generated by splitting app.py lines 1683-1693. Keep execution order in wangcai_app/startup/loader.py.
@asynccontextmanager
async def lifespan(_app: FastAPI):
    init_db()
    start_memory_agent_worker()
    start_idle_agent_worker()
    yield


app = FastAPI(title="Wangcai Web", version="2.5.0", lifespan=lifespan)
app.mount("/static", StaticFiles(directory=str(STATIC_DIR)), name="static")
