# Generated by splitting app.py lines 1-72. Keep execution order in qwen_app/startup/loader.py.
import hmac
import base64
import hashlib
import html as html_lib
import io
import ipaddress
import json
import os
import re
import secrets
import sqlite3
import threading
import time
import uuid
from difflib import SequenceMatcher
from html.parser import HTMLParser
from contextlib import asynccontextmanager
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Any, Callable, Dict, Generator, Iterable, List, Optional, Tuple
from urllib.parse import parse_qs, unquote, urlparse
try:
    from zoneinfo import ZoneInfo
except ImportError:  # pragma: no cover - Python < 3.9 fallback
    ZoneInfo = None

try:
    from PIL import Image, ImageOps
except ImportError:  # pragma: no cover - Pillow should be installed in deployment
    Image = None
    ImageOps = None

import httpx
import embedding_client
import memory
import vector_memory
from fastapi import FastAPI, HTTPException, Query, Request
from fastapi.responses import FileResponse, JSONResponse, RedirectResponse, Response, StreamingResponse
from fastapi.staticfiles import StaticFiles
from openai import OpenAI
from schemas import (
    AdminLoginPayload,
    ArtifactCommentPayload,
    AuthPasswordPayload,
    ChatAttachment,
    ChatPayload,
    IdlePromptPayload,
    IdleStatusPayload,
    MemoryAdminPayload,
    ModelSettingsPayload,
    UserMemoryBindingPayload,
)
from streaming_utils import ThinkStripper, format_sse, split_think_text


APP_DIR = Path(__file__).resolve().parent
STATIC_DIR = APP_DIR / "static"
DATA_DIR = APP_DIR / "data"
DB_PATH = Path(os.environ.get("QWEN_WEB_DB", DATA_DIR / "chat_history.sqlite3"))
AUTH_CONFIG_PATH = Path(os.environ.get("QWEN_AUTH_CONFIG", DATA_DIR / "admin_auth.json"))


def env_bool(name: str, default: bool = True) -> bool:
    raw = os.environ.get(name)
    if raw is None:
        return default
    return raw.strip().lower() not in {"0", "false", "no", "off", "disabled"}


BASE_URL = os.environ.get("QWEN_MODEL_BASE_URL", "http://127.0.0.1:8000/v1")
MODEL_NAME = os.environ.get("QWEN_MODEL_NAME", "qwen3.6-35b-a3b-262k")
MODEL_API_KEY = os.environ.get("QWEN_MODEL_API_KEY", os.environ.get("OPENAI_API_KEY", "EMPTY")).strip() or "EMPTY"
REQUEST_TIMEOUT = float(os.environ.get("QWEN_MODEL_TIMEOUT", "1200"))
