# Generated by splitting app.py lines 6193-7407. Keep execution order in qwen_app/startup/loader.py.
def create_idle_agent_run(task_type: str, title: str, prompt_summary: str, status: str = "running") -> int:
    now = utc_now()
    with connect_db() as conn:
        cur = conn.execute(
            """
            INSERT INTO idle_agent_runs (
                task_type, title, prompt_summary, status,
                started_at, updated_at
            )
            VALUES (?, ?, ?, ?, ?, ?)
            """,
            (task_type or "other", title or "未命名任务", prompt_summary, status, now, now),
        )
        return int(cur.lastrowid)


def finish_idle_agent_run(run_id: int, status: str, interrupted_reason: str = "") -> None:
    now = utc_now()
    with connect_db() as conn:
        conn.execute(
            """
            UPDATE idle_agent_runs
            SET status = ?, interrupted_reason = ?, finished_at = ?, updated_at = ?
            WHERE id = ?
            """,
            (status, interrupted_reason or None, now, now, int(run_id)),
        )


def update_idle_agent_run_status(
    run_id: int,
    status: str,
    title: str = "",
    task_type: str = "",
    interrupted_reason: str = "",
) -> None:
    now = utc_now()
    assignments = ["status = ?", "updated_at = ?"]
    params: List[object] = [status, now]
    if title:
        assignments.append("title = ?")
        params.append(title)
    if task_type:
        assignments.append("task_type = ?")
        params.append(task_type)
    if interrupted_reason:
        assignments.append("interrupted_reason = ?")
        params.append(interrupted_reason)
    params.append(int(run_id))
    with connect_db() as conn:
        conn.execute(
            f"UPDATE idle_agent_runs SET {', '.join(assignments)} WHERE id = ?",
            tuple(params),
        )


def idle_agent_progress_from_reason(reason: str) -> Dict[str, object]:
    mapping = {
        "idle_disabled": ("disabled", "已关闭", 0),
        "idle_paused": ("paused", "已暂停", 0),
        "active_generation": ("interrupted", "由于对话中断", 28),
        "memory_agent_busy": ("interrupted", "等待记忆整理结束", 34),
        "idle_wait": ("interrupted", "等待用户空闲", 25),
        "recent_run": ("waiting", "等待开启", 8),
        "forced": ("waiting", "等待开启", 8),
        "idle": ("waiting", "等待开启", 8),
    }
    stage, label, percent = mapping.get(reason, ("waiting", "等待开启", 8))
    return {"stage": stage, "label": label, "percent": percent, "reason": reason}


def idle_agent_progress_from_status(status: str, interrupted_reason: str = "") -> Dict[str, object]:
    normalized = (status or "").strip().lower()
    mapping = {
        "running": ("writing", "撰写中", 52),
        "writing": ("writing", "撰写中", 52),
        "polishing": ("polishing", "润色中", 78),
        "completed": ("completed", "完成", 100),
        "cancelled": ("interrupted", "由于对话中断", 35),
        "skipped": ("waiting", "等待开启", 8),
        "failed": ("failed", "运行失败", 100),
    }
    stage, label, percent = mapping.get(normalized, ("waiting", "等待开启", 8))
    payload = {"stage": stage, "label": label, "percent": percent, "status": normalized}
    if interrupted_reason:
        payload["reason"] = interrupted_reason
    return payload


def parse_event_metadata(raw: str) -> Dict[str, object]:
    try:
        parsed = json.loads(raw or "{}")
        return parsed if isinstance(parsed, dict) else {"raw": parsed}
    except Exception:
        return {"raw": raw or ""}


def iso_seconds_ago(value: str) -> Optional[float]:
    text = (value or "").strip()
    if not text:
        return None
    try:
        parsed = datetime.fromisoformat(text)
    except ValueError:
        return None
    if parsed.tzinfo is None:
        parsed = parsed.replace(tzinfo=timezone.utc)
    return max(0.0, (datetime.now(timezone.utc) - parsed).total_seconds())


def idle_worker_last_event(event_type: str) -> Optional[Dict[str, object]]:
    with connect_db() as conn:
        row = conn.execute(
            """
            SELECT id, event_type, visitor_ip, created_at, metadata_json
            FROM events
            WHERE event_type = ?
            ORDER BY datetime(created_at) DESC, id DESC
            LIMIT 1
            """,
            (event_type,),
        ).fetchone()
    if not row:
        return None
    return {
        "id": int(row["id"]),
        "event_type": str(row["event_type"]),
        "visitor_ip": str(row["visitor_ip"] or "local"),
        "created_at": str(row["created_at"] or ""),
        "metadata": parse_event_metadata(str(row["metadata_json"] or "{}")),
    }


def latest_idle_artifact_created_at() -> str:
    with connect_db() as conn:
        row = conn.execute(
            """
            SELECT created_at
            FROM idle_agent_artifacts
            ORDER BY datetime(created_at) DESC, id DESC
            LIMIT 1
            """
        ).fetchone()
    return str(row["created_at"] or "") if row else ""


def record_idle_worker_watchdog_warning(kind: str, detail: Dict[str, object]) -> None:
    key = f"idle_worker_watchdog_last:{kind}"
    last = get_app_setting(key, "")
    if last:
        age = iso_seconds_ago(last)
        if age is not None and age < max(IDLE_WORKER_TICK_STALE_SECONDS, 600):
            return
    record_event(None, "warning_idle_worker_watchdog", "local", {"kind": kind, **detail})
    set_app_setting(key, utc_now())


def idle_worker_watchdog_status() -> Dict[str, object]:
    last_tick = idle_worker_last_event("idle_worker_tick")
    last_artifact_at = latest_idle_artifact_created_at()
    tick_age = iso_seconds_ago(str(last_tick.get("created_at", ""))) if last_tick else None
    artifact_age = iso_seconds_ago(last_artifact_at)
    warnings: List[Dict[str, object]] = []
    if tick_age is None:
        warnings.append({"kind": "no_tick", "message": "idle worker 尚未记录 heartbeat"})
        record_idle_worker_watchdog_warning("no_tick", {"message": "idle worker 尚未记录 heartbeat"})
    elif tick_age > IDLE_WORKER_TICK_STALE_SECONDS:
        payload = {
            "kind": "stale_tick",
            "message": f"idle worker heartbeat 已超过 {int(tick_age)} 秒未更新",
            "age_seconds": round(tick_age, 1),
        }
        warnings.append(payload)
        record_idle_worker_watchdog_warning("stale_tick", payload)
    if artifact_age is None:
        warnings.append({"kind": "no_artifact", "message": "尚未产生任何空闲成果"})
    elif artifact_age > IDLE_WORKER_ARTIFACT_STALE_SECONDS:
        payload = {
            "kind": "stale_artifact",
            "message": f"距离上次成果已超过 {int(artifact_age)} 秒",
            "age_seconds": round(artifact_age, 1),
        }
        warnings.append(payload)
        record_idle_worker_watchdog_warning("stale_artifact", payload)
    return {
        "ok": not warnings,
        "last_tick_at": last_tick.get("created_at") if last_tick else None,
        "last_artifact_at": last_artifact_at or None,
        "tick_age_seconds": round(tick_age, 1) if tick_age is not None else None,
        "artifact_age_seconds": round(artifact_age, 1) if artifact_age is not None else None,
        "warnings": warnings,
    }


def idle_agent_progress_from_reason(reason: str) -> Dict[str, object]:
    mapping = {
        "idle_disabled": ("disabled", "已关闭", 0),
        "idle_paused": ("paused", "已暂停", 0),
        "active_generation": ("interrupted", "由于对话中断", 28),
        "memory_agent_busy": ("interrupted", "等待记忆整理结束", 34),
        "idle_wait": ("interrupted", "等待用户空闲", 25),
        "recent_run": ("waiting", "等待开启", 8),
        "recent_run_exists": ("waiting", "等待开启", 8),
        "forced": ("waiting", "等待开启", 8),
        "idle": ("waiting", "等待开启", 8),
    }
    stage, label, percent = mapping.get(reason, ("waiting", "等待开启", 8))
    return {"stage": stage, "label": label, "percent": percent, "reason": reason}


def idle_agent_progress_from_status(status: str, interrupted_reason: str = "") -> Dict[str, object]:
    normalized = (status or "").strip().lower()
    mapping = {
        "running": ("writing", "撰写中", 52),
        "writing": ("writing", "撰写中", 52),
        "polishing": ("polishing", "润色中", 78),
        "completed": ("completed", "完成", 100),
        "cancelled": ("interrupted", "由于对话中断", 35),
        "skipped": ("waiting", "等待开启", 8),
        "failed": ("failed", "运行失败", 100),
    }
    stage, label, percent = mapping.get(normalized, ("waiting", "等待开启", 8))
    payload = {"stage": stage, "label": label, "percent": percent, "status": normalized, "task": "idle_write"}
    if interrupted_reason:
        payload["reason"] = interrupted_reason
    return payload


def memory_dedupe_agent_is_running() -> bool:
    acquired = MEMORY_DEDUPE_AGENT_WORKER_LOCK.acquire(blocking=False)
    if acquired:
        MEMORY_DEDUPE_AGENT_WORKER_LOCK.release()
        return False
    return True


def memory_refine_agent_is_running() -> bool:
    acquired = MEMORY_REFINE_AGENT_WORKER_LOCK.acquire(blocking=False)
    if acquired:
        MEMORY_REFINE_AGENT_WORKER_LOCK.release()
        return False
    return True


def idle_write_agent_is_running() -> bool:
    acquired = IDLE_AGENT_WORKER_LOCK.acquire(blocking=False)
    if acquired:
        IDLE_AGENT_WORKER_LOCK.release()
        return False
    return True


def current_idle_write_progress() -> Dict[str, object]:
    with connect_db() as conn:
        row = conn.execute(
            """
            SELECT id, status, title, task_type, interrupted_reason, started_at, finished_at, updated_at
            FROM idle_agent_runs
            ORDER BY id DESC
            LIMIT 1
            """
        ).fetchone()
    if row:
        progress = idle_agent_progress_from_status(str(row["status"] or ""), str(row["interrupted_reason"] or ""))
        progress.update(
            {
                "run_id": int(row["id"]),
                "title": str(row["title"] or ""),
                "task_type": str(row["task_type"] or ""),
                "started_at": str(row["started_at"] or ""),
                "finished_at": str(row["finished_at"] or "") if row["finished_at"] else None,
                "updated_at": str(row["updated_at"] or ""),
            }
        )
        return progress
    can_run, reason = idle_agent_can_run(force=False)
    progress = idle_agent_progress_from_reason("idle" if can_run else reason)
    progress["task"] = "idle_write"
    return progress

def current_idle_agent_progress() -> Dict[str, object]:
    watchdog = idle_worker_watchdog_status()
    with connect_db() as conn:
        row = conn.execute(
            """
            SELECT id, status, title, task_type, interrupted_reason, started_at, finished_at, updated_at
            FROM idle_agent_runs
            ORDER BY id DESC
            LIMIT 1
            """
        ).fetchone()
    if row and str(row["status"] or "").lower() in {"running", "writing", "polishing"}:
        progress = idle_agent_progress_from_status(str(row["status"] or ""), str(row["interrupted_reason"] or ""))
        progress.update(
            {
                "run_id": int(row["id"]),
                "title": str(row["title"] or ""),
                "task_type": str(row["task_type"] or ""),
                "started_at": str(row["started_at"] or ""),
                "finished_at": str(row["finished_at"] or "") if row["finished_at"] else None,
                "updated_at": str(row["updated_at"] or ""),
                "watchdog": watchdog,
            }
        )
        return progress
    if memory_dedupe_agent_is_running():
        return {"stage": "memory_dedupe", "label": "记忆去重中", "percent": 45, "task": "memory_dedupe", "watchdog": watchdog}
    if memory_refine_agent_is_running():
        return {"stage": "memory_refine", "label": "记忆精简中", "percent": 48, "task": "memory_refine", "watchdog": watchdog}
    if memory_agent_is_running():
        return {"stage": "memory_agent", "label": "记忆整理中", "percent": 38, "task": "memory_agent", "watchdog": watchdog}
    if idle_write_agent_is_running():
        return {"stage": "writing", "label": "撰写中", "percent": 52, "task": "idle_write", "watchdog": watchdog}
    can_run, reason = idle_agent_can_run(force=False)
    progress = idle_agent_progress_from_reason("idle" if can_run else reason)
    progress["task"] = "idle_worker"
    progress["watchdog"] = watchdog
    if row and progress.get("stage") == "waiting":
        progress.update(
            {
                "last_run_id": int(row["id"]),
                "last_status": str(row["status"] or ""),
                "last_updated_at": str(row["updated_at"] or ""),
            }
        )
    return progress


def list_idle_worker_activity(limit: int = 20) -> List[Dict[str, object]]:
    event_types = {
        "idle_worker_tick",
        "idle_worker_tick_done",
        "idle_worker_skip",
        "idle_worker_error",
        "warning_idle_worker_watchdog",
        "opening_cache_idle_refresh",
        "opening_cache_refresh_error",
        "memory_dedupe_agent_run",
        "memory_dedupe_agent_error",
        "memory_refine_agent_run",
        "memory_refine_agent_error",
        "idle_agent_artifact_created",
        "idle_agent_error",
    }
    placeholders = ",".join("?" for _ in event_types)
    max_rows = min(max(int(limit), 1), 500)
    with connect_db() as conn:
        rows = conn.execute(
            f"""
            SELECT id, event_type, visitor_ip, created_at, metadata_json
            FROM events
            WHERE event_type IN ({placeholders})
            ORDER BY datetime(created_at) DESC, id DESC
            LIMIT ?
            """,
            (*sorted(event_types), max_rows),
        ).fetchall()
    return [
        {
            "id": int(row["id"]),
            "event_type": str(row["event_type"]),
            "visitor_ip": str(row["visitor_ip"] or "local"),
            "created_at": str(row["created_at"] or ""),
            "updated_at": str(row["created_at"] or ""),
            "metadata": parse_event_metadata(str(row["metadata_json"] or "{}")),
        }
        for row in rows
    ]


def recent_device_identities_for_opening_cache(limit: int = IDLE_OPENING_CACHE_REFRESH_LIMIT) -> List[str]:
    with connect_db() as conn:
        rows = conn.execute(
            """
            SELECT visitor_ip, MAX(updated_at) AS latest
            FROM curated_memories
            WHERE visitor_ip LIKE 'device:%'
            GROUP BY visitor_ip
            ORDER BY datetime(latest) DESC
            LIMIT ?
            """,
            (max(1, int(limit)),),
        ).fetchall()
    return [str(row["visitor_ip"] or "") for row in rows if is_device_identity(str(row["visitor_ip"] or ""))]


def run_opening_cache_refresh_once(force: bool = False) -> Dict[str, object]:
    started_at = utc_now()
    started = time.perf_counter()
    if not force:
        last = get_app_setting("idle_opening_cache_refresh_last_at", "")
        age = iso_seconds_ago(last) if last else None
        if age is not None and age < IDLE_OPENING_CACHE_REFRESH_INTERVAL_SECONDS:
            return {"status": "skipped", "reason": "recent_prompt_cache", "started_at": started_at, "duration_ms": 0.0}
    try:
        devices = recent_device_identities_for_opening_cache()
        refreshed = 0
        for device_id in devices:
            refresh_cached_opening_prompt(device_id)
            refreshed += 1
        set_app_setting("idle_opening_cache_refresh_last_at", utc_now())
        duration_ms = round((time.perf_counter() - started) * 1000, 3)
        result = {
            "status": "completed" if refreshed else "skipped",
            "reason": "refreshed" if refreshed else "no_devices",
            "device_count": refreshed,
            "refreshed_devices": devices[:10],
            "started_at": started_at,
            "duration_ms": duration_ms,
        }
        record_event(None, "opening_cache_idle_refresh", "local", result)
        return result
    except Exception as exc:
        duration_ms = round((time.perf_counter() - started) * 1000, 3)
        result = {"status": "failed", "reason": "error", "error": str(exc), "started_at": started_at, "duration_ms": duration_ms}
        record_event(None, "opening_cache_refresh_error", "local", result)
        return result


def artifact_memory_text(
    artifact_id: int,
    title: str,
    artifact_type: str,
    content: str,
    series_title: str = "",
    episode_index: Optional[int] = None,
    summary: str = "",
) -> str:
    clean_title = normalize_idle_artifact_terms(title).strip()
    clean_type = normalize_idle_artifact_terms(artifact_type).strip()
    clean_content = normalize_idle_artifact_terms(content)
    clean_summary = normalize_idle_artifact_terms(summary)
    series = normalize_idle_artifact_terms(series_title).strip()
    episode_text = f"第 {int(episode_index)} 集" if episode_index is not None else ""
    short_summary = clean_summary.strip() or compact_idle_artifact_content(clean_content, 220)
    parts = [
        f"作品记忆：已创作成果 #{artifact_id}《{clean_title or '未命名成果'}》。",
        f"类型：{clean_type or 'other'}。",
    ]
    if series:
        parts.append(f"系列：{series}。")
    if episode_text:
        parts.append(f"进度：{episode_text}。")
    if short_summary:
        parts.append(f"摘要：{short_summary}")
    return "".join(parts)


def create_artifact_memory(
    artifact_id: int,
    title: str,
    artifact_type: str,
    content: str,
    series_title: str = "",
    episode_index: Optional[int] = None,
    summary: str = "",
) -> int:
    text = artifact_memory_text(
        artifact_id,
        title,
        artifact_type,
        content,
        series_title=series_title,
        episode_index=episode_index,
        summary=summary,
    )
    memory_id = save_curated_memory(
        source_session_id=f"artifact-{int(artifact_id)}",
        start_message_id=int(artifact_id),
        end_message_id=int(artifact_id),
        content=text,
        importance_label="artifact",
        confidence=0.85,
    )
    vector = embedding_client.embed_text(text)
    upsert_curated_memory_vector(memory_id, vector, embedding_client.EMBEDDING_MODEL)
    return memory_id


PREQUEL_ARTIFACT_MARKERS = (
    "前传",
    "外传",
    "番外",
    "起源",
    "过去篇",
    "特别篇",
    "origin",
    "prequel",
)


def is_prequel_idle_artifact(title: str, content: str = "") -> bool:
    text = f"{title}\n{content}".lower()
    return any(marker.lower() in text for marker in PREQUEL_ARTIFACT_MARKERS)


def current_series_mainline_episode(series_title: str) -> int:
    clean_series = normalize_idle_artifact_terms(series_title).strip()
    if not clean_series:
        return 0
    with connect_db() as conn:
        row = conn.execute(
            """
            SELECT MAX(episode_index) AS max_episode
            FROM idle_agent_artifacts
            WHERE series_title = ?
              AND episode_index IS NOT NULL
            """,
            (clean_series,),
        ).fetchone()
    return int(row["max_episode"] or 0) if row else 0


def resolve_idle_series_episode_index(
    series_title: str,
    requested_episode: object,
    title: str = "",
    content: str = "",
) -> Optional[int]:
    clean_series = normalize_idle_artifact_terms(series_title).strip()
    if not clean_series:
        return None
    if is_prequel_idle_artifact(title, content):
        return None
    current_episode = current_series_mainline_episode(clean_series)
    next_episode = current_episode + 1
    try:
        requested = int(requested_episode) if requested_episode not in (None, "", "null") else None
    except Exception:
        requested = None
    if requested == next_episode:
        return requested
    return next_episode


def renumber_idle_series_mainline_episodes(series_title: str) -> Dict[str, int]:
    clean_series = normalize_idle_artifact_terms(series_title).strip()
    if not clean_series:
        return {"updated": 0}
    updated_ids: List[int] = []
    with connect_db() as conn:
        rows = conn.execute(
            """
            SELECT id
            FROM idle_agent_artifacts
            WHERE series_title = ?
              AND episode_index IS NOT NULL
            ORDER BY created_at ASC, id ASC
            """,
            (clean_series,),
        ).fetchall()
        updated = 0
        for index, row in enumerate(rows, start=1):
            cur = conn.execute(
                """
                UPDATE idle_agent_artifacts
                SET episode_index = ?
                WHERE id = ?
                  AND COALESCE(episode_index, -1) != ?
                """,
                (index, int(row["id"]), index),
            )
            if cur.rowcount:
                updated += int(cur.rowcount or 0)
                updated_ids.append(int(row["id"]))
    reindexed = 0
    for artifact_id in updated_ids:
        try:
            index_idle_agent_artifact(artifact_id)
            reindexed += 1
        except Exception as exc:
            record_event(None, "idle_artifact_index_error", "local", {
                "artifact_id": artifact_id,
                "error": str(exc),
            })
    return {"updated": updated, "reindexed": reindexed, "total": len(rows)}


def save_idle_agent_artifact(
    run_id: int,
    title: str,
    artifact_type: str,
    content: str,
    series_title: str = "",
    episode_index: Optional[int] = None,
    summary: str = "",
) -> int:
    clean_title = normalize_idle_artifact_terms(title)
    clean_series = normalize_idle_artifact_terms(series_title)
    clean_summary = normalize_idle_artifact_terms(summary)
    text = normalize_idle_artifact_terms(content).strip()
    clean_type = normalize_artifact_type(artifact_type, clean_title, text)
    if not text:
        raise ValueError("idle artifact content is empty")
    artifact_id = 0
    series_value = clean_series.strip() or None
    episode_value = resolve_idle_series_episode_index(
        series_value or "",
        episode_index,
        title=clean_title,
        content=text,
    )
    summary_value = clean_summary.strip() or compact_idle_artifact_content(text, 260)
    with connect_db() as conn:
        cur = conn.execute(
            """
            INSERT INTO idle_agent_artifacts (
                run_id, title, artifact_type, content,
                series_title, episode_index, summary, created_at
            )
            VALUES (?, ?, ?, ?, ?, ?, ?, ?)
            """,
            (
                int(run_id),
                clean_title.strip() or "未命名成果",
                clean_type or "other",
                text,
                series_value,
                episode_value,
                summary_value,
                utc_now(),
            ),
        )
        artifact_id = int(cur.lastrowid)
    try:
        index_idle_agent_artifact(artifact_id)
    except Exception as exc:
        record_event(None, "idle_artifact_index_error", "local", {
            "artifact_id": artifact_id,
            "error": str(exc),
        })
    return artifact_id


def compact_idle_artifact_content(content: str, max_chars: int) -> str:
    text = " ".join(content.strip().split())
    if not text:
        return ""
    pieces = re.split(r"(?<=[。！？.!?])\s*", text)
    seen = set()
    selected: List[str] = []
    total = 0
    for piece in pieces:
        clean = piece.strip()
        if not clean:
            continue
        key = clean[:120]
        if key in seen:
            continue
        seen.add(key)
        if total + len(clean) > max_chars and selected:
            break
        selected.append(clean)
        total += len(clean)
    body = "".join(selected).strip() if selected else text
    if len(body) > max_chars:
        body = body[:max_chars].rstrip() + "..."
    return body


def load_idle_artifact_term_replacements() -> Dict[str, str]:
    replacements: Dict[str, str] = {}
    replacements.update(DEFAULT_IDLE_ARTIFACT_TERM_REPLACEMENTS)

    def merge_payload(payload: object) -> None:
        if not isinstance(payload, dict):
            return
        for source, target in payload.items():
            source_text = str(source).strip()
            target_text = str(target).strip()
            if source_text and target_text:
                replacements[source_text] = target_text

    if IDLE_ARTIFACT_TERM_REPLACEMENTS_FILE:
        try:
            payload = json.loads(Path(IDLE_ARTIFACT_TERM_REPLACEMENTS_FILE).read_text(encoding="utf-8"))
            merge_payload(payload)
        except Exception:
            pass
    if IDLE_ARTIFACT_TERM_REPLACEMENTS:
        try:
            payload = json.loads(IDLE_ARTIFACT_TERM_REPLACEMENTS)
            merge_payload(payload)
        except Exception:
            pass
    return replacements


def replace_idle_artifact_terms(text: str, replacements: Dict[str, str]) -> str:
    if not isinstance(text, str):
        return ""
    normalized = text
    for source, target in sorted(replacements.items(), key=lambda item: len(item[0]), reverse=True):
        normalized = re.sub(re.escape(source), target, normalized, flags=re.I)
    return normalized


def normalize_idle_artifact_terms(text: str) -> str:
    return replace_idle_artifact_terms(text, load_idle_artifact_term_replacements())


class TermReplacementStreamFilter:
    def __init__(self) -> None:
        self.replacements = load_idle_artifact_term_replacements()
        self.keep_chars = max((len(key) for key in self.replacements), default=1) - 1
        self.buffer = ""

    def feed(self, text: str) -> str:
        if not text:
            return ""
        self.buffer += text
        if self.keep_chars <= 0:
            chunk, self.buffer = self.buffer, ""
            return replace_idle_artifact_terms(chunk, self.replacements)
        if len(self.buffer) <= self.keep_chars:
            return ""
        chunk = self.buffer[:-self.keep_chars]
        self.buffer = self.buffer[-self.keep_chars:]
        return replace_idle_artifact_terms(chunk, self.replacements)

    def flush(self) -> str:
        chunk, self.buffer = self.buffer, ""
        return replace_idle_artifact_terms(chunk, self.replacements)


def format_idle_artifact_index_text(
    title: str,
    artifact_type: str,
    content: str,
    series_title: str = "",
    episode_index: Optional[int] = None,
    summary: str = "",
) -> str:
    body = compact_idle_artifact_content(content, 1600)
    series_line = f"系列：{series_title.strip()}\n" if series_title and series_title.strip() else ""
    episode_line = f"集数：{int(episode_index)}\n" if episode_index is not None else ""
    summary_line = f"摘要：{summary.strip()}\n" if summary and summary.strip() else ""
    return (
        f"标题：{title.strip() or '未命名成果'}\n"
        f"类型：{artifact_type.strip() or 'other'}\n"
        f"{series_line}"
        f"{episode_line}"
        f"{summary_line}"
        f"内容摘要：{body}"
    )


def index_idle_agent_artifact(artifact_id: int) -> None:
    with connect_db() as conn:
        row = conn.execute(
            """
            SELECT id, title, artifact_type, content, series_title, episode_index, summary
            FROM idle_agent_artifacts
            WHERE id = ?
            """,
            (int(artifact_id),),
        ).fetchone()
    if row is None:
        raise ValueError(f"idle artifact not found: {artifact_id}")

    index_text = format_idle_artifact_index_text(
        str(row["title"]),
        str(row["artifact_type"]),
        str(row["content"]),
        str(row["series_title"] or ""),
        int(row["episode_index"]) if row["episode_index"] is not None else None,
        str(row["summary"] or ""),
    )
    vector = embedding_client.embed_text(index_text)
    upsert_idle_artifact_vector(int(row["id"]), vector, embedding_client.EMBEDDING_MODEL, index_text)


def upsert_idle_artifact_vector(
    artifact_id: int,
    vector: object,
    model_name: str,
    index_text: str,
) -> None:
    arr = vector_memory.normalize_vector(vector)
    with connect_db() as conn:
        conn.execute(
            """
            INSERT INTO idle_artifact_vectors (
                artifact_id, dim, vector, model_name, index_text, created_at
            )
            VALUES (?, ?, ?, ?, ?, ?)
            ON CONFLICT(artifact_id) DO UPDATE SET
                dim = excluded.dim,
                vector = excluded.vector,
                model_name = excluded.model_name,
                index_text = excluded.index_text,
                created_at = excluded.created_at
            """,
            (
                int(artifact_id),
                int(arr.shape[0]),
                arr.tobytes(),
                model_name,
                index_text,
                utc_now(),
            ),
        )


def retrieve_idle_artifacts(query_vector: object) -> List[Dict[str, object]]:
    query = vector_memory.normalize_vector(query_vector)
    with connect_db() as conn:
        rows = conn.execute(
            """
            SELECT a.id, a.title, a.artifact_type, a.content,
                   a.series_title, a.episode_index, a.summary, a.created_at,
                   v.dim, v.vector, v.model_name
            FROM idle_agent_artifacts a
            JOIN idle_artifact_vectors v ON v.artifact_id = a.id
            ORDER BY a.id ASC
            """
        ).fetchall()

    scored: List[Dict[str, object]] = []
    for row in rows:
        vector = vector_memory.blob_to_vector(row["vector"], int(row["dim"]))
        if vector.shape != query.shape:
            continue
        score = float(vector.dot(query))
        if score < IDLE_ARTIFACT_MIN_SCORE:
            continue
        scored.append(
            {
                "id": int(row["id"]),
                "title": str(row["title"]),
                "artifact_type": str(row["artifact_type"]),
                "content": str(row["content"]),
                "series_title": str(row["series_title"] or ""),
                "episode_index": int(row["episode_index"]) if row["episode_index"] is not None else None,
                "summary": str(row["summary"] or ""),
                "created_at": str(row["created_at"]),
                "score": score,
            }
        )
    scored.sort(key=lambda item: (-float(item["score"]), int(item["id"])))
    return scored[:IDLE_ARTIFACT_TOP_K]


def format_idle_artifact_context(artifacts: List[Dict[str, object]]) -> str:
    if not artifacts:
        return ""
    lines = [
        "以下是模型空闲时创作过的成果，仅在当前话题相关时参考。",
        "不要强行复述作品；可以用它们作为设定、角色、风格或前文创作的线索。",
        "",
    ]
    for index, item in enumerate(artifacts, start=1):
        content = str(item.get("summary") or "").strip()
        if not content:
            content = compact_idle_artifact_content(str(item["content"]), IDLE_ARTIFACT_CONTEXT_CHARS)
        lines.append(
            f"[空闲创作成果 {index}] score={float(item['score']):.3f} "
            f"type={item['artifact_type']} title={item['title']} "
            f"series={item.get('series_title') or '-'} episode={item.get('episode_index') or '-'}"
        )
        lines.append(content)
        lines.append("")
    return "\n".join(lines).strip()


def backfill_idle_artifact_vectors(limit: int = 10000) -> Dict[str, int]:
    max_rows = min(max(int(limit), 1), 100000)
    with connect_db() as conn:
        rows = conn.execute(
            """
            SELECT a.id
            FROM idle_agent_artifacts a
            LEFT JOIN idle_artifact_vectors v ON v.artifact_id = a.id
            WHERE v.artifact_id IS NULL
            ORDER BY a.id ASC
            LIMIT ?
            """,
            (max_rows,),
        ).fetchall()

    indexed = 0
    failed = 0
    for row in rows:
        try:
            index_idle_agent_artifact(int(row["id"]))
            indexed += 1
        except Exception:
            failed += 1
    return {"indexed": indexed, "failed": failed}


def load_idle_series_context(
    max_series: int = IDLE_SERIES_CONTEXT_MAX_SERIES,
    max_episodes: int = IDLE_SERIES_CONTEXT_MAX_EPISODES,
) -> List[Dict[str, object]]:
    series_limit = min(max(int(max_series), 1), 12)
    episode_limit = min(max(int(max_episodes), 1), 200)
    with connect_db() as conn:
        series_rows = conn.execute(
            """
            SELECT series_title,
                   COUNT(*) AS total_count,
                   MAX(COALESCE(episode_index, 0)) AS max_episode,
                   MAX(id) AS newest_id
            FROM idle_agent_artifacts
            WHERE series_title IS NOT NULL
              AND TRIM(series_title) != ''
            GROUP BY series_title
            ORDER BY newest_id DESC
            LIMIT ?
            """,
            (series_limit,),
        ).fetchall()
        contexts: List[Dict[str, object]] = []
        for row in series_rows:
            series_title = str(row["series_title"])
            episode_rows = conn.execute(
                """
                SELECT id, title, episode_index, summary, content, created_at
                FROM idle_agent_artifacts
                WHERE series_title = ?
                ORDER BY
                    CASE WHEN episode_index IS NULL THEN 1 ELSE 0 END,
                    episode_index ASC,
                    id ASC
                LIMIT ?
                """,
                (series_title, episode_limit),
            ).fetchall()
            contexts.append(
                {
                    "series_title": series_title,
                    "total_count": int(row["total_count"] or 0),
                    "max_episode": int(row["max_episode"] or 0),
                    "episodes": [row_to_dict(item) for item in episode_rows],
                }
            )
    return contexts


def format_idle_series_context(series_context: List[Dict[str, object]]) -> str:
    if not series_context:
        return ""
    lines = [
        "已有连续系列资料：",
        "如果选择续写其中某个系列，必须先承接以下前情；主线 episode_index 只能使用提示中的下一集编号。",
        "前传、番外、起源故事可以丰富人物过去，但 episode_index 必须填 null，避免污染主线编号。",
    ]
    for series in series_context:
        title = str(series.get("series_title") or "").strip()
        max_episode = int(series.get("max_episode") or 0)
        next_episode = max_episode + 1
        total_count = int(series.get("total_count") or 0)
        lines.append("")
        lines.append(
            f"系列《{title}》：已有作品 {total_count} 个，主线最大集数 {max_episode}；"
            f"如果续写主线，episode_index 下一集必须填写 {next_episode}。"
        )
        lines.append("已有剧情摘要（按主线顺序；番外/前传列在后面）：")
        episodes = list(series.get("episodes") or [])
        for item in episodes:
            episode_index = item.get("episode_index")
            episode = f"第 {int(episode_index)} 集" if episode_index is not None else "前传/番外"
            summary = str(item.get("summary") or "").strip() or compact_idle_artifact_content(
                str(item.get("content") or ""),
                160,
            )
            lines.append(f"- {episode} #{item.get('id')}《{item.get('title') or '未命名成果'}》：{summary}")
        recent = episodes[-IDLE_SERIES_CONTEXT_RECENT_CONTENT:]
        if recent:
            lines.append("最近细节片段（用于衔接角色状态和伏笔，不要原样复读）：")
            for item in recent:
                episode_index = item.get("episode_index")
                episode = f"第 {int(episode_index)} 集" if episode_index is not None else "前传/番外"
                content = compact_idle_artifact_content(
                    str(item.get("content") or ""),
                    IDLE_SERIES_CONTEXT_RECENT_CHARS,
                )
                if content:
                    lines.append(f"[{episode} #{item.get('id')}] {content}")
    return "\n".join(lines)


def recent_curated_memory_summaries(limit: int = 12) -> List[Dict[str, object]]:
    with connect_db() as conn:
        rows = conn.execute(
            """
            SELECT id, content, importance_label, updated_at
            FROM curated_memories
            WHERE visitor_ip LIKE 'device:%'
              AND importance_label NOT IN ('identity', 'persona', 'preference', 'rule')
            ORDER BY id DESC
            LIMIT ?
            """,
            (int(limit),),
        ).fetchall()
    return [
        {
            "id": int(row["id"]),
            "content": str(row["content"]),
            "importance_label": str(row["importance_label"]),
            "updated_at": str(row["updated_at"]),
        }
        for row in rows
    ]


def build_active_recall_context(
    session_id: str,
    visitor_ip: str = "",
    limit: int = 12,
) -> str:
    ip = normalize_visitor_ip(visitor_ip) if visitor_ip else ""
    max_rows = min(max(int(limit), 1), 30)
    with connect_db() as conn:
        scope = binding_scope_for_device(conn, ip) if ip and is_device_identity(ip) else {}
        scoped_devices = list(scope.get("device_ids") or ([ip] if ip and is_device_identity(ip) else []))
        in_clause, params = sql_in_clause_params(scoped_devices)
        memory_rows = conn.execute(
            f"""
            SELECT id, content, importance_label, visitor_ip, timeline_at, supersedes_id, confidence, updated_at
            FROM curated_memories
            WHERE visitor_ip IN {in_clause}
            ORDER BY
              CASE WHEN visitor_ip = ? THEN 0 ELSE 1 END,
              CASE importance_label
                WHEN 'identity' THEN 0
                WHEN 'preference' THEN 1
                WHEN 'persona' THEN 2
                WHEN 'artifact' THEN 3
                ELSE 4
              END,
              COALESCE(timeline_at, updated_at) DESC,
              id DESC
            LIMIT ?
            """,
            (*params, ip, max_rows),
        ).fetchall()
        artifact_rows = conn.execute(
            """
            SELECT id, title, artifact_type, series_title, episode_index, summary, created_at
            FROM idle_agent_artifacts
            ORDER BY id DESC
            LIMIT 6
            """
        ).fetchall()

    if not memory_rows and not artifact_rows:
        return ""

    lines = [
        "主动回忆上下文：用户正在要求你主动想起你们之间的事。",
        "不要只按字面相似度回答；请综合长期记忆、作品记忆和时间线，挑一件最有意义的事。",
        "如果记忆冲突，较新的记忆和 confidence 更高的记忆优先。",
        "",
    ]
    if memory_rows:
        lines.append("可用长期记忆：")
        for row in memory_rows:
            memory_ip = str(row["visitor_ip"] or "")
            label = str(row["importance_label"] or "other")
            if memory_ip != ip and is_device_local_memory_label(label):
                continue
            supersedes = f" supersedes=#{row['supersedes_id']}" if row["supersedes_id"] is not None else ""
            lines.append(
                f"- #{row['id']} [{label}] "
                f"timeline={row['timeline_at'] or row['updated_at']} "
                f"confidence={float(row['confidence'] or 0.7):.2f}{supersedes}: "
                f"{str(row['content']).strip()}"
            )
    if artifact_rows:
        lines.append("")
        lines.append("近期作品线索：")
        for row in artifact_rows:
            episode = f" 第{row['episode_index']}集" if row["episode_index"] is not None else ""
            series = f"《{row['series_title']}》" if row["series_title"] else ""
            summary = str(row["summary"] or "").strip()
            lines.append(
                f"- 作品 #{row['id']} {series}{episode} {row['title']} "
                f"[{row['artifact_type']}]: {summary}"
            )
    return "\n".join(lines).strip()


def build_idle_agent_prompt() -> Tuple[str, str]:
    memories = recent_curated_memory_summaries()
    custom_prompt = get_idle_agent_custom_prompt()
    story_seeds = load_idle_story_seeds()
    series_context = load_idle_series_context()
    if memories:
        lines = [
            "以下是已整理长期记忆摘要，只能作为创作偏好和设定灵感，不要复述原文：",
        ]
        for item in memories:
            lines.append(f"- #{item['id']} [{item['importance_label']}] {item['content']}")
    else:
        lines = ["目前没有长期记忆。请自由创作一个短篇、剧本、世界观或自我设定。"]
    lines.append("")
    lines.append("请选择一个你认为值得在空闲时完成的小作品，保持自主性和创造性。")
    lines.append("")
    lines.append(GROSS_STORY_CONTENT_RULE)
    lines.append("你可以写短篇小说、诗歌、剧本、世界观、角色档案、自我设定或连续作品。")
    formatted_series_context = format_idle_series_context(series_context)
    if formatted_series_context:
        lines.append("")
        lines.append(formatted_series_context)
    if story_seeds:
        lines.append("以下是用户配置的可选创作种子，不是强制任务；请在空闲时轮换选择：")
        lines.extend(story_seeds)
    lines.append(
        "如果选择继续某个已有系列：series_title 必须与上方系列名完全一致；"
        "主线连载 episode_index 必须填写上方指定的下一集编号；"
        "前传、番外、起源故事可以写，但 episode_index 必须填 null，标题需明确标注前传/番外/起源；"
        "summary 必须写成本集对主线、角色状态或设定变化的摘要。"
        "如果创作其他内容，可以将 series_title 和 episode_index 留空。"
    )
    if custom_prompt:
        lines.append("")
        lines.append("用户配置的空闲创作 prompt：")
        lines.append(custom_prompt)
    summary = (
        f"curated_memories={len(memories)};"
        f"story_seeds={len(story_seeds)};"
        f"series_context={len(series_context)};"
        f"custom_prompt={'set' if custom_prompt else 'empty'}"
    )
    return "\n".join(lines), summary


def fallback_idle_agent_payload(text: str) -> Dict[str, object]:
    cleaned = normalize_idle_artifact_terms(text).strip()
    return {
        "task_type": "notes",
        "title": "未命名成果",
        "content": cleaned,
        "series_title": "",
        "episode_index": None,
        "summary": "idle agent returned malformed JSON; saved raw content",
        "image_count": 1,
        "image_plan": [{"title": "封面", "brief": compact_idle_artifact_content(cleaned, 220), "role": "cover"}],
    }


def load_idle_agent_json_payload(cleaned: str) -> Dict[str, object]:
    candidates = [cleaned]
    if cleaned.startswith("{") and not cleaned.rstrip().endswith("}"):
        candidates.append(f"{cleaned.rstrip()}}}")
    match = re.search(r"\{.*\}", cleaned, flags=re.S)
    if match:
        candidates.append(match.group(0))

    seen = set()
    for candidate in candidates:
        candidate = candidate.strip()
        if not candidate or candidate in seen:
            continue
        seen.add(candidate)
        try:
            payload = json.loads(candidate, strict=False)
            if isinstance(payload, dict):
                return payload
        except Exception:
            continue
    return fallback_idle_agent_payload(cleaned)


def parse_idle_agent_response(text: str) -> Dict[str, object]:
    cleaned = text.strip()
    if cleaned.startswith("```"):
        cleaned = re.sub(r"^```(?:json)?\s*", "", cleaned)
        cleaned = re.sub(r"\s*```$", "", cleaned)
    payload = load_idle_agent_json_payload(cleaned)
    raw_image_plan = payload.get("image_plan")
    image_plan = raw_image_plan if isinstance(raw_image_plan, list) else []
    normalized_image_plan: List[Dict[str, str]] = []
    for item in image_plan[:4]:
        if not isinstance(item, dict):
            continue
        title = normalize_idle_artifact_terms(str(item.get("title") or "配图")).strip() or "配图"
        brief = normalize_idle_artifact_terms(str(item.get("brief") or item.get("prompt") or "")).strip()
        role = normalize_idle_artifact_terms(str(item.get("role") or "")).strip() or ("cover" if not normalized_image_plan else "inline")
        if brief:
            normalized_image_plan.append({"title": title, "brief": brief, "role": role})
    if not normalized_image_plan:
        fallback_brief = normalize_idle_artifact_terms(str(payload.get("summary") or payload.get("title") or payload.get("content") or "")).strip()
        normalized_image_plan = [{"title": "封面", "brief": compact_idle_artifact_content(fallback_brief, 220), "role": "cover"}]
    try:
        image_count = int(payload.get("image_count") or len(normalized_image_plan) or 1)
    except Exception:
        image_count = len(normalized_image_plan) or 1
    image_count = max(1, min(4, image_count))
    normalized_image_plan = normalized_image_plan[:image_count]
    return {
        "task_type": normalize_idle_artifact_terms(str(payload.get("task_type", "other"))).strip() or "other",
        "title": normalize_idle_artifact_terms(str(payload.get("title", "未命名成果"))).strip() or "未命名成果",
        "content": normalize_idle_artifact_terms(str(payload.get("content", ""))).strip(),
        "series_title": normalize_idle_artifact_terms(str(payload.get("series_title", ""))).strip(),
        "episode_index": payload.get("episode_index"),
        "summary": normalize_idle_artifact_terms(str(payload.get("summary", ""))).strip(),
        "image_count": image_count,
        "image_plan": normalized_image_plan,
    }


def call_idle_agent_model(prompt: str) -> Dict[str, str]:
    client, http_client, model_slot = openai_client_for_slot(MODEL_SLOT_BACKGROUND, timeout=REQUEST_TIMEOUT)
    try:
        stream = client.chat.completions.create(
            **model_completion_kwargs(model_slot),
            messages=[
                {"role": "system", "content": IDLE_AGENT_SYSTEM_PROMPT},
                {"role": "user", "content": prompt},
            ],
            temperature=IDLE_AGENT_TEMPERATURE,
            top_p=IDLE_AGENT_TOP_P,
            max_tokens=IDLE_AGENT_MAX_TOKENS,
            stream=True,
        )
        chunks: List[str] = []
        for chunk in stream:
            if IDLE_AGENT_CANCEL_EVENT.is_set():
                return {
                    "task_type": "other",
                    "title": "已中断",
                    "content": "",
                    "cancelled": "true",
                }
            if not chunk.choices:
                continue
            content = extract_delta_content(chunk.choices[0].delta)
            if content:
                chunks.append(content)
        _, answer = split_think_text("".join(chunks))
        return parse_idle_agent_response(answer)
    finally:
        http_client.close()
