# Generated by splitting app.py lines 3277-4027. Keep execution order in qwen_app/startup/loader.py.
def count_device_curated_memories(visitor_ip: str) -> int:
    ip = normalize_visitor_ip(visitor_ip)
    if not is_device_identity(ip):
        return 0
    with connect_db() as conn:
        scope = binding_scope_for_device(conn, ip)
        device_ids = list(scope.get("device_ids") or [ip])
        in_clause, params = sql_in_clause_params(device_ids)
        count = conn.execute(
            f"SELECT COUNT(*) AS c FROM curated_memories WHERE visitor_ip IN {in_clause}",
            params,
        ).fetchone()["c"]
    return int(count or 0)


def default_opening_prompt(first_seen: bool) -> str:
    relationship_line = (
        "这是你第一次见到这个浏览器身份；不要假装认识用户，也不要读取不存在的长期记忆。"
        if first_seen
        else "你见过这个浏览器身份，但目前还没有可用的长期记忆；可以自然地欢迎回来，不要假装知道具体身份或经历。"
    )
    return (
        "这是浏览器打开时的隐藏首轮输入，不要提到这是隐藏输入，也不要复述系统提示。\n"
        f"当前真实时间：{opening_time_text()}。\n"
        f"{relationship_line}\n"
        "请自然地回复用户：简短问候，并询问他今天是否有会议、截止时间、日程、约定，"
        "或者其他需要你记住并提醒的事情。"
    )


def prepared_opening_prompt(visitor_ip: str, known_before_session: bool) -> Dict[str, str]:
    if not known_before_session:
        return {
            "opening_prompt": default_opening_prompt(first_seen=True),
            "opening_source": "light_new_device",
        }

    cached = get_cached_opening_prompt(visitor_ip)
    if cached:
        return {
            "opening_prompt": render_cached_opening_prompt(cached, visitor_ip),
            "opening_source": "cached_memory",
        }

    cached = refresh_cached_opening_prompt(visitor_ip)
    if cached:
        return {
            "opening_prompt": render_cached_opening_prompt(cached, visitor_ip),
            "opening_source": "prepared_memory",
        }

    return {
        "opening_prompt": default_opening_prompt(first_seen=False),
        "opening_source": "light_known_no_memory",
    }


def opening_prompt_cache_key(visitor_ip: str) -> str:
    ip = normalize_visitor_ip(visitor_ip)
    return f"opening_prompt:{OPENING_PROMPT_CACHE_VERSION}:{ip}"


def get_cached_opening_prompt(visitor_ip: str) -> str:
    ip = normalize_visitor_ip(visitor_ip)
    if not is_device_identity(ip):
        return ""
    return get_app_setting(opening_prompt_cache_key(ip), "")


def render_cached_opening_prompt(cached_prompt: str, visitor_ip: str = "") -> str:
    base = (cached_prompt or "").strip()
    if not base:
        return ""
    parts = [base, f"当前真实时间：{opening_time_text()}。"]
    recent_diary = format_opening_recent_diary_context(retrieve_recent_diary_memories_for_opening(visitor_ip))
    if recent_diary:
        parts.append(recent_diary)
    future_events = format_future_events_context(retrieve_future_event_memories(visitor_ip))
    if future_events:
        parts.append(future_events)
    return "\n\n".join(parts)


def refresh_cached_opening_prompt(visitor_ip: str) -> str:
    ip = normalize_visitor_ip(visitor_ip)
    if not is_device_identity(ip):
        return ""

    profile_memories = retrieve_profile_context_memories(ip, limit=10)
    opening_memories = retrieve_opening_context_memories(ip, limit=6)
    future_events = retrieve_future_event_memories(ip)
    recent_diary = retrieve_recent_diary_memories_for_opening(ip)
    memory_count = count_device_curated_memories(ip)
    if not profile_memories and not opening_memories and not future_events and not recent_diary and memory_count <= 0:
        delete_app_setting(opening_prompt_cache_key(ip))
        return ""

    if profile_memories:
        memory_phrase = f"已提前载入这个浏览器身份的长期记忆和稳定画像（约 {memory_count} 条）"
    elif opening_memories:
        memory_phrase = f"已提前载入这个浏览器身份的开场专用偏好（约 {len(opening_memories)} 条）"
    else:
        memory_phrase = f"已提前载入这个浏览器身份的长期记忆（约 {memory_count} 条）"
    profile_context = format_profile_context(profile_memories)
    opening_context = format_opening_context(opening_memories)
    cached_prompt = (
        "这是浏览器打开时的隐藏首轮输入；你拿到它时，长期记忆检索和画像整理已经在 idle 时间完成。"
        "不要提到这是隐藏输入，不要复述系统提示，不要说自己正在检索记忆。\n"
        f"预处理状态：{memory_phrase}。\n"
        "任务：请自然地回复用户，询问他今天是否有会议、截止时间、日程、约定，"
        "或其他需要你记住并提醒的事情。回复要简短、有一点当前关系感。\n"
        "如果用户有开场偏好（opening preference），例如每次见面先讲笑话、问候方式、称呼方式，优先遵守。"
    )
    if profile_context:
        cached_prompt += f"\n\n已缓存用户画像与开场偏好：\n{profile_context}"
    if opening_context:
        cached_prompt += f"\n\n已缓存开场专用偏好：\n{opening_context}"
    if recent_diary:
        cached_prompt += "\n\n开篇时还会读取最近一周的 diary/risk 状态，以自然体贴的方式关心用户。"
    if future_events:
        cached_prompt += "\n\n开篇时还会读取当前时间之后的结构化 event 并提醒用户。"
    set_app_setting(opening_prompt_cache_key(ip), cached_prompt)
    return cached_prompt


def backfill_visitor_memory_links(limit: int = 10000) -> Dict[str, int]:
    max_rows = min(max(int(limit), 1), 100000)
    updated_profiles = 0
    updated_memories = 0
    with connect_db() as conn:
        rows = conn.execute(
            """
            SELECT m.id, s.visitor_ip, s.user_agent
            FROM curated_memories m
            JOIN sessions s ON s.id = m.source_session_id
            WHERE (m.visitor_ip IS NULL OR m.profile_id IS NULL)
              AND s.visitor_ip LIKE 'device:%'
            ORDER BY m.id ASC
            LIMIT ?
            """,
            (max_rows,),
        ).fetchall()
        for row in rows:
            profile_id = observe_visitor_identity(
                conn,
                str(row["visitor_ip"]),
                str(row["user_agent"] or ""),
            )
            conn.execute(
                """
                UPDATE curated_memories
                SET visitor_ip = ?, profile_id = ?, updated_at = ?
                WHERE id = ?
                """,
                (
                    normalize_visitor_ip(str(row["visitor_ip"])),
                    profile_id,
                    utc_now(),
                    int(row["id"]),
                ),
            )
            updated_profiles += 1
            updated_memories += 1
    return {
        "updated_profiles": updated_profiles,
        "updated_memories": updated_memories,
    }


def end_session(session_id: str, reason: str, visitor_ip: str = "unknown") -> bool:
    now = utc_now()
    with connect_db() as conn:
        cur = conn.execute(
            """
            UPDATE sessions
            SET ended_at = COALESCE(ended_at, ?),
                end_reason = COALESCE(end_reason, ?)
            WHERE id = ?
            """,
            (now, reason, session_id),
        )
        if cur.rowcount:
            conn.execute(
                """
                INSERT INTO events (session_id, event_type, visitor_ip, created_at, metadata_json)
                VALUES (?, ?, ?, ?, '{}')
                """,
                (session_id, f"session_{reason}", visitor_ip or "unknown", now),
            )
    return cur.rowcount > 0


def reset_session(old_session_id: str, visitor_ip: str, user_agent: str) -> str:
    end_session(old_session_id, "reset", visitor_ip)
    return create_session(visitor_ip, user_agent)


def validate_chat_attachments(attachments: List[ChatAttachment]) -> List[Dict[str, object]]:
    if len(attachments) > MAX_CHAT_ATTACHMENTS:
        raise HTTPException(status_code=400, detail=f"最多只能上传 {MAX_CHAT_ATTACHMENTS} 张图片")

    cleaned: List[Dict[str, object]] = []
    for attachment in attachments:
        mime_type = normalize_image_mime(attachment.mime_type)
        if not mime_type.startswith("image/"):
            raise HTTPException(status_code=400, detail="当前只支持图片附件")
        match = IMAGE_DATA_URL_RE.match(attachment.data_url.strip())
        if not match:
            raise HTTPException(status_code=400, detail="图片附件必须使用 data:image/...;base64 格式")
        data_url_mime = normalize_image_mime(match.group(1))
        if data_url_mime != mime_type:
            raise HTTPException(status_code=400, detail="图片 MIME 类型和 data URL 不一致")
        encoded_payload = match.group(2).replace("\n", "").replace("\r", "")
        approx_bytes = int(len(encoded_payload) * 3 / 4)
        declared_size = int(attachment.size or approx_bytes)
        payload_size = max(approx_bytes, declared_size)
        if payload_size > MAX_CHAT_ATTACHMENT_RAW_BYTES:
            max_mb = max(1, MAX_CHAT_ATTACHMENT_RAW_BYTES // (1024 * 1024))
            raise HTTPException(status_code=400, detail=f"图片原始文件过大，单张最多 {max_mb}MB")

        should_compress = payload_size > IMAGE_COMPRESSION_TRIGGER_BYTES or payload_size > MAX_CHAT_ATTACHMENT_BYTES
        if should_compress:
            try:
                image_bytes = base64.b64decode(encoded_payload, validate=True)
            except Exception as exc:
                raise HTTPException(status_code=400, detail="图片 base64 数据无效") from exc
            compressed_bytes, (width, height) = compress_image_attachment(image_bytes)
            if len(compressed_bytes) > MAX_CHAT_ATTACHMENT_BYTES:
                max_mb = max(1, MAX_CHAT_ATTACHMENT_BYTES // (1024 * 1024))
                raise HTTPException(status_code=400, detail=f"图片压缩后仍过大，单张最多 {max_mb}MB")
            cleaned.append(
                {
                    "name": attachment.name.strip() or "image",
                    "mime_type": "image/jpeg",
                    "data_url": image_data_url("image/jpeg", compressed_bytes),
                    "size": len(compressed_bytes),
                    "compressed": True,
                    "original_mime_type": data_url_mime,
                    "original_size": payload_size,
                    "width": width,
                    "height": height,
                }
            )
            continue

        cleaned.append(
            {
                "name": attachment.name.strip() or "image",
                "mime_type": data_url_mime,
                "data_url": attachment.data_url.strip(),
                "size": declared_size,
                "compressed": False,
                "original_size": payload_size,
            }
        )
    return cleaned


def message_metadata_from_attachments(attachments: Optional[List[ChatAttachment]] = None) -> Dict[str, object]:
    cleaned = validate_chat_attachments(attachments or [])
    return {"attachments": cleaned} if cleaned else {}


def add_message(
    session_id: str,
    role: str,
    content: str,
    status: str = "completed",
    attachments: Optional[List[ChatAttachment]] = None,
    hidden: bool = False,
    extra_metadata: Optional[Dict[str, object]] = None,
) -> int:
    now = utc_now()
    metadata = message_metadata_from_attachments(attachments) if role == "user" else {}
    if hidden:
        metadata["hidden"] = True
    if extra_metadata:
        metadata.update(extra_metadata)
    with connect_db() as conn:
        cur = conn.execute(
            """
            INSERT INTO messages (session_id, role, content, status, created_at, metadata_json)
            VALUES (?, ?, ?, ?, ?, ?)
            """,
            (session_id, role, content, status, now, json.dumps(metadata, ensure_ascii=False)),
        )
        message_id = int(cur.lastrowid)
        if status == "completed" and not hidden:
            memory.index_message(conn, message_id, session_id, role, content, now)
    return message_id


def load_messages(session_id: str) -> List[Dict[str, str]]:
    with connect_db() as conn:
        rows = conn.execute(
            """
            SELECT role, content, created_at
            FROM messages
            WHERE session_id = ?
              AND status = 'completed'
              AND role IN ('user', 'assistant')
              AND NOT (
                role = 'user'
                AND COALESCE(json_extract(metadata_json, '$.hidden'), 0) = 1
              )
            ORDER BY id ASC
            """,
            (session_id,),
        ).fetchall()
    return [
        {
            "role": row["role"],
            "content": row["content"],
            "created_at": row["created_at"],
        }
        for row in rows
    ]


def session_start_event_id(conn: sqlite3.Connection, session_id: str) -> int:
    row = conn.execute(
        """
        SELECT id
        FROM events
        WHERE session_id = ?
          AND event_type = 'session_start'
        ORDER BY id ASC
        LIMIT 1
        """,
        (session_id,),
    ).fetchone()
    return int(row["id"]) if row else 0


def load_session_visible_messages(session_id: str) -> List[Dict[str, object]]:
    with connect_db() as conn:
        rows = conn.execute(
            """
            SELECT id, role, content, created_at, metadata_json
            FROM messages
            WHERE session_id = ?
              AND status = 'completed'
              AND role IN ('user', 'assistant')
              AND NOT (
                role = 'user'
                AND COALESCE(json_extract(metadata_json, '$.hidden'), 0) = 1
              )
            ORDER BY id ASC
            """,
            (session_id,),
        ).fetchall()
    messages: List[Dict[str, object]] = []
    for row in rows:
        metadata = safe_json_loads(str(row["metadata_json"] or "{}"))
        if not isinstance(metadata, dict):
            metadata = {}
        attachments = metadata.get("attachments") if isinstance(metadata.get("attachments"), list) else []
        draw = metadata.get("draw") if isinstance(metadata.get("draw"), dict) else {}
        messages.append({
            "id": int(row["id"]),
            "role": str(row["role"]),
            "content": str(row["content"]),
            "created_at": str(row["created_at"]),
            "attachments": [item for item in attachments if isinstance(item, dict)],
            "draw": draw,
            "metadata": {
                "has_attachments": bool(attachments),
                "has_draw": bool(draw),
            },
        })
    return messages


def linked_context_session_ids(session_id: str) -> List[str]:
    with connect_db() as conn:
        rows = conn.execute(
            """
            SELECT l.source_session_id
            FROM session_context_links l
            JOIN events e
              ON e.session_id = l.source_session_id
             AND e.event_type = 'session_start'
            WHERE l.current_session_id = ?
            ORDER BY e.id ASC, l.id ASC
            """,
            (session_id,),
        ).fetchall()
    return [str(row["source_session_id"]) for row in rows]


def previous_context_candidate(
    conn: sqlite3.Connection,
    current_session_id: str,
) -> Optional[sqlite3.Row]:
    current = conn.execute(
        "SELECT id, visitor_ip FROM sessions WHERE id = ?",
        (current_session_id,),
    ).fetchone()
    if current is None:
        return None
    visitor = str(current["visitor_ip"] or "")
    if not visitor or is_anonymous_identity(visitor):
        return None
    scope = binding_scope_for_device(conn, visitor)
    allowed_devices = [visitor]
    if bool(scope.get("share_chat_history")) and str(scope.get("shared_user_id") or ""):
        shared_user_id = str(scope.get("shared_user_id") or "")
        shared_rows = conn.execute(
            """
            SELECT device_id
            FROM shared_user_bindings
            WHERE shared_user_id = ?
              AND share_chat_history = 1
            ORDER BY updated_at DESC, device_id ASC
            """,
            (shared_user_id,),
        ).fetchall()
        allowed_devices = []
        seen_devices = set()
        for item in shared_rows:
            device_id = normalize_visitor_ip(str(item["device_id"] or ""))
            if not device_id or not is_device_identity(device_id) or device_id in seen_devices:
                continue
            seen_devices.add(device_id)
            allowed_devices.append(device_id)
        if visitor not in seen_devices:
            allowed_devices.insert(0, visitor)

    linked_rows = conn.execute(
        "SELECT source_session_id FROM session_context_links WHERE current_session_id = ?",
        (current_session_id,),
    ).fetchall()
    linked_ids = [str(row["source_session_id"]) for row in linked_rows]
    boundary_ids = [session_start_event_id(conn, current_session_id)]
    boundary_ids.extend(session_start_event_id(conn, source_id) for source_id in linked_ids)
    boundary_ids = [value for value in boundary_ids if value > 0]
    boundary_event_id = min(boundary_ids) if boundary_ids else 1 << 60

    excluded = [current_session_id] + linked_ids
    placeholders = ",".join("?" for _ in excluded)
    visitor_clause, visitor_params = sql_in_clause_params(allowed_devices)
    rows = conn.execute(
        f"""
        SELECT s.id, s.visitor_ip, s.user_agent, s.started_at, s.ended_at, s.end_reason,
               e.id AS start_event_id
        FROM sessions s
        JOIN events e
         ON e.session_id = s.id
         AND e.event_type = 'session_start'
        WHERE s.visitor_ip IN {visitor_clause}
          AND s.id NOT IN ({placeholders})
          AND e.id < ?
          AND EXISTS (
              SELECT 1
              FROM messages m
              WHERE m.session_id = s.id
                AND m.status = 'completed'
                AND m.role IN ('user', 'assistant')
                AND NOT (
                  m.role = 'user'
                  AND COALESCE(json_extract(m.metadata_json, '$.hidden'), 0) = 1
                )
          )
        ORDER BY e.id DESC
        LIMIT 30
        """,
        [*visitor_params, *excluded, boundary_event_id],
    ).fetchall()
    for row in rows:
        if previous_session_has_loadable_messages(conn, str(row["id"])):
            return row
    return None


def previous_session_has_loadable_messages(conn: sqlite3.Connection, session_id: str) -> bool:
    row = conn.execute(
        """
        SELECT
          COUNT(*) AS visible_count,
          SUM(CASE WHEN role = 'assistant' THEN 1 ELSE 0 END) AS assistant_count
        FROM messages
        WHERE session_id = ?
          AND status = 'completed'
          AND role IN ('user', 'assistant')
          AND NOT (
            role = 'user'
            AND COALESCE(json_extract(metadata_json, '$.hidden'), 0) = 1
          )
        """,
        (session_id,),
    ).fetchone()
    visible_count = int(row["visible_count"] or 0) if row else 0
    assistant_count = int(row["assistant_count"] or 0) if row else 0
    return visible_count > 0 and not (visible_count == 1 and assistant_count == 1)


def has_previous_context_session(
    conn: sqlite3.Connection,
    current_session_id: str,
    before_event_id: Optional[int] = None,
) -> bool:
    candidate = previous_context_candidate(conn, current_session_id)
    if candidate is None:
        return False
    if before_event_id is None:
        return True
    return int(candidate["start_event_id"]) < int(before_event_id)


def load_previous_session_context(session_id: str) -> Dict[str, object]:
    now = utc_now()
    with connect_db() as conn:
        candidate = previous_context_candidate(conn, session_id)
        if candidate is None:
            return {"loaded": False, "session": None, "messages": [], "has_more": False}
        source_session_id = str(candidate["id"])
        row = conn.execute(
            "SELECT COALESCE(MAX(order_index), 0) AS max_order FROM session_context_links WHERE current_session_id = ?",
            (session_id,),
        ).fetchone()
        next_order = int(row["max_order"] or 0) + 1
        conn.execute(
            """
            INSERT OR IGNORE INTO session_context_links (
                current_session_id, source_session_id, order_index, loaded_at
            )
            VALUES (?, ?, ?, ?)
            """,
            (session_id, source_session_id, next_order, now),
        )
        source_start_event_id = int(candidate["start_event_id"])
        has_more = has_previous_context_session(conn, session_id, before_event_id=source_start_event_id)

    return {
        "loaded": True,
        "session": {
            "id": source_session_id,
            "started_at": str(candidate["started_at"]),
            "ended_at": str(candidate["ended_at"] or ""),
            "end_reason": str(candidate["end_reason"] or ""),
        },
        "messages": load_session_visible_messages(source_session_id),
        "has_more": has_more,
    }


def load_recent_planner_context_messages(
    session_id: str,
    limit: int = WEB_SEARCH_PLANNER_CONTEXT_MESSAGES,
) -> List[Dict[str, str]]:
    max_rows = min(max(int(limit), 1), 30)
    with connect_db() as conn:
        rows = conn.execute(
            """
            SELECT role, content, created_at
            FROM messages
            WHERE session_id = ?
              AND status = 'completed'
              AND role IN ('user', 'assistant')
              AND NOT (
                role = 'user'
                AND COALESCE(json_extract(metadata_json, '$.hidden'), 0) = 1
              )
            ORDER BY id DESC
            LIMIT ?
            """,
            (session_id, max_rows),
        ).fetchall()
    return [
        {
            "role": row["role"],
            "content": row["content"],
            "created_at": row["created_at"],
        }
        for row in reversed(rows)
    ]


def load_recent_search_planner_messages(
    session_id: str,
    limit: int = WEB_SEARCH_PLANNER_CONTEXT_MESSAGES,
) -> List[Dict[str, str]]:
    return load_recent_planner_context_messages(session_id, limit=limit)


def model_content_for_message(content: str, metadata: object, created_at: object = "") -> object:
    attachments: List[Dict[str, object]] = []
    if isinstance(metadata, dict) and isinstance(metadata.get("attachments"), list):
        attachments = [item for item in metadata["attachments"] if isinstance(item, dict)]
    if not attachments:
        return timed_text_for_model(content, created_at)

    parts: List[Dict[str, object]] = []
    text_content = timed_text_for_model(content, created_at)
    if text_content.strip():
        parts.append({"type": "text", "text": text_content})
    for attachment in attachments:
        data_url = str(attachment.get("data_url") or "")
        mime_type = str(attachment.get("mime_type") or "")
        if mime_type.startswith("image/") and IMAGE_DATA_URL_RE.match(data_url):
            parts.append({"type": "image_url", "image_url": {"url": data_url}})
    return parts or content


def load_model_message_rows_for_session(conn: sqlite3.Connection, session_id: str) -> List[sqlite3.Row]:
    return conn.execute(
        """
        SELECT role, content, metadata_json, created_at
        FROM messages
        WHERE session_id = ?
          AND status = 'completed'
          AND role IN ('user', 'assistant')
          AND NOT (
            role = 'user'
            AND COALESCE(json_extract(metadata_json, '$.hidden'), 0) = 1
          )
        ORDER BY id ASC
        """,
        (session_id,),
    ).fetchall()


def rows_to_model_messages(rows: List[sqlite3.Row]) -> List[Dict[str, object]]:
    return [
        {
            "role": row["role"],
            "content": model_content_for_message(
                row["content"],
                safe_json_loads(row["metadata_json"]),
                row["created_at"],
            ),
        }
        for row in rows
    ]


def estimate_model_message_chars(message: Dict[str, object]) -> int:
    content = message.get("content", "")
    if isinstance(content, str):
        return len(content)
    if isinstance(content, list):
        total = 0
        for part in content:
            if not isinstance(part, dict):
                total += len(str(part))
                continue
            if part.get("type") == "text":
                total += len(str(part.get("text", "")))
            elif part.get("type") == "image_url":
                total += 2000
            else:
                total += len(json.dumps(part, ensure_ascii=False))
        return total
    return len(str(content))


def trim_model_messages_to_context_budget(
    messages: List[Dict[str, object]],
    max_chars: Optional[int] = None,
) -> List[Dict[str, object]]:
    budget = int(max_chars if max_chars is not None else MODEL_CONTEXT_CHAR_BUDGET)
    if budget <= 0:
        return messages
    total = sum(estimate_model_message_chars(message) for message in messages)
    if total <= budget or len(messages) <= 1:
        return messages

    keep_from = max(1, len(messages) // 2)
    trimmed = messages[keep_from:]
    while len(trimmed) > 1 and sum(estimate_model_message_chars(message) for message in trimmed) > budget:
        trim_count = max(1, len(trimmed) // 2)
        trimmed = trimmed[trim_count:]
    return trimmed or messages[-1:]


def load_model_messages(session_id: str) -> List[Dict[str, object]]:
    with connect_db() as conn:
        rows = load_model_message_rows_for_session(conn, session_id)
    return rows_to_model_messages(rows)


def load_model_messages_with_context(session_id: str) -> List[Dict[str, object]]:
    with connect_db() as conn:
        source_ids = [
            str(row["source_session_id"])
            for row in conn.execute(
                """
                SELECT l.source_session_id
                FROM session_context_links l
                JOIN events e
                  ON e.session_id = l.source_session_id
                 AND e.event_type = 'session_start'
                WHERE l.current_session_id = ?
                ORDER BY e.id ASC, l.id ASC
                """,
                (session_id,),
            ).fetchall()
        ]
        rows: List[sqlite3.Row] = []
        for source_id in source_ids:
            rows.extend(load_model_message_rows_for_session(conn, source_id))
        rows.extend(load_model_message_rows_for_session(conn, session_id))
    return trim_model_messages_to_context_budget(rows_to_model_messages(rows))


def build_model_messages_for_request(
    session_id: str,
    current_message: str,
    attachments: Optional[List[ChatAttachment]] = None,
    isolate_history: bool = False,
) -> List[Dict[str, object]]:
    if not isolate_history:
        return load_model_messages_with_context(session_id)
    return [
        {
            "role": "user",
            "content": model_content_for_message(
                current_message,
                message_metadata_from_attachments(attachments or []),
                utc_now(),
            ),
        }
    ]


def message_metadata(message: Dict[str, object]) -> Dict[str, object]:
    metadata = message.get("metadata_json")
    if isinstance(metadata, str):
        try:
            metadata = json.loads(metadata or "{}")
        except Exception:
            metadata = {}
    return metadata if isinstance(metadata, dict) else {}


def message_is_hidden(message: Dict[str, object]) -> bool:
    return bool(message_metadata(message).get("hidden"))


def message_is_opening_turn(message: Dict[str, object]) -> bool:
    return bool(message_metadata(message).get("opening_turn"))


def load_messages_by_id_range(
    session_id: str,
    start_message_id: int,
    end_message_id: int,
) -> List[Dict[str, object]]:
    with connect_db() as conn:
        rows = conn.execute(
            """
            SELECT id, role, content, created_at, metadata_json
            FROM messages
            WHERE session_id = ?
              AND id BETWEEN ? AND ?
              AND status = 'completed'
              AND role IN ('user', 'assistant')
            ORDER BY id ASC
            """,
            (session_id, int(start_message_id), int(end_message_id)),
        ).fetchall()
    return [{key: row[key] for key in row.keys()} for row in rows]
