# Generated by splitting app.py lines 501-1682. Keep execution order in qwen_app/startup/loader.py.
class SearchHTMLParser(HTMLParser):
    def __init__(self) -> None:
        super().__init__()
        self.results: List[Dict[str, str]] = []
        self._current: Optional[Dict[str, str]] = None
        self._capture_text = False

    def handle_starttag(self, tag: str, attrs: List[Tuple[str, Optional[str]]]) -> None:
        if tag.lower() != "a":
            return
        attr_map = {key.lower(): value or "" for key, value in attrs}
        href = clean_search_result_url(attr_map.get("href", ""))
        class_name = attr_map.get("class", "")
        if not href or not href.startswith(("http://", "https://")):
            return
        if "duckduckgo.com" in urlparse(href).netloc:
            return
        self._current = {"title": "", "url": href, "snippet": ""}
        self._capture_text = True
        if "result__snippet" in class_name or "snippet" in class_name:
            self._current["snippet"] = ""

    def handle_data(self, data: str) -> None:
        if self._capture_text and self._current is not None:
            self._current["title"] += data

    def handle_endtag(self, tag: str) -> None:
        if tag.lower() != "a" or self._current is None:
            return
        title = clean_search_text(self._current.get("title", ""))
        url = self._current.get("url", "")
        if title and url and not any(item["url"] == url for item in self.results):
            self.results.append({"title": title, "url": url, "snippet": ""})
        self._current = None
        self._capture_text = False


class PageTextParser(HTMLParser):
    def __init__(self) -> None:
        super().__init__()
        self.title = ""
        self.parts: List[str] = []
        self._capture_title = False
        self._capture_text = False
        self._skip_depth = 0

    def handle_starttag(self, tag: str, attrs: List[Tuple[str, Optional[str]]]) -> None:
        tag_name = tag.lower()
        if tag_name in {"script", "style", "noscript", "svg", "canvas"}:
            self._skip_depth += 1
            return
        if self._skip_depth:
            return
        if tag_name == "title":
            self._capture_title = True
            return
        if tag_name in {"h1", "h2", "h3", "p", "li", "article"}:
            self._capture_text = True

    def handle_data(self, data: str) -> None:
        if self._skip_depth:
            return
        cleaned = clean_search_text(data, 500)
        if not cleaned:
            return
        if self._capture_title:
            self.title += f" {cleaned}"
        elif self._capture_text:
            self.parts.append(cleaned)

    def handle_endtag(self, tag: str) -> None:
        tag_name = tag.lower()
        if self._skip_depth and tag_name in {"script", "style", "noscript", "svg", "canvas"}:
            self._skip_depth = max(0, self._skip_depth - 1)
            return
        if tag_name == "title":
            self._capture_title = False
        if tag_name in {"h1", "h2", "h3", "p", "li", "article"}:
            self._capture_text = False


def clean_search_text(text: str, max_chars: int = 240) -> str:
    cleaned = re.sub(r"\s+", " ", html_lib.unescape(str(text or ""))).strip()
    if len(cleaned) > max_chars:
        return cleaned[: max_chars - 1].rstrip() + "…"
    return cleaned


def clean_search_result_url(url: str) -> str:
    raw = html_lib.unescape(str(url or "").strip())
    if not raw:
        return ""
    parsed = urlparse(raw)
    query = parse_qs(parsed.query)
    for key in ("uddg", "u", "url", "h5_url", "target", "target_url"):
        if query.get(key):
            raw = unquote(query[key][0])
            break
    if raw.startswith("//"):
        raw = "https:" + raw
    return raw


def strip_html_fragment(fragment: str, max_chars: int = 240) -> str:
    return clean_search_text(re.sub(r"<[^>]+>", " ", fragment or ""), max_chars)


def should_skip_search_result(url: str, title: str = "") -> bool:
    parsed_url = urlparse(url)
    host = (parsed_url.hostname or "").lower()
    if not host:
        return True
    blocked_hosts = {
        "duckduckgo.com",
        "www.duckduckgo.com",
        "bing.com",
        "www.bing.com",
        "cn.bing.com",
        "microsoft.com",
        "www.microsoft.com",
        "go.microsoft.com",
        "i.360.cn",
        "www.so.com",
        "so.com",
        "www.sogou.com",
        "sogou.com",
        "weixin.sogou.com",
        "ai.so.com",
        "yz.m.sm.cn",
        "beian.miit.gov.cn",
        "beian.mps.gov.cn",
        "dxzhgl.miit.gov.cn",
    }
    if host in blocked_hosts or host.endswith(".microsoft.com"):
        return True
    cleaned_title = clean_search_text(title, 80)
    if host == "m.quark.cn" and parsed_url.path.startswith("/vsearch"):
        return True
    if cleaned_title in {"条款", "隐私", "此处", "帮助", "举报", "AI", "图片", "微信", "视频", "知乎", "医疗", "登录", "注册", "广告", "网页"}:
        return True
    if "预测" in cleaned_title:
        return True
    if "/adclick" in url or "ICP备" in cleaned_title or "公网安备" in cleaned_title:
        return True
    return False


def normalize_relative_years(text: str, now: Optional[datetime] = None) -> str:
    current_year = (now or datetime.now(local_timezone())).year
    replacements = {
        "前年": str(current_year - 2),
        "去年": str(current_year - 1),
        "今年": str(current_year),
        "明年": str(current_year + 1),
        "后年": str(current_year + 2),
    }
    normalized = text
    for marker, year in replacements.items():
        normalized = normalized.replace(marker, year)
    return normalized


def extract_search_results(html_text: str, max_results: int = WEB_SEARCH_MAX_RESULTS) -> List[Dict[str, str]]:
    if max_results <= 0:
        return []
    results: List[Dict[str, str]] = []
    seen_urls = set()
    for block in re.findall(r'<li[^>]+class="[^"]*\bb_algo\b[^"]*"[^>]*>.*?</li>', html_text or "", flags=re.S):
        match = re.search(r"<h2[^>]*>.*?<a[^>]+href=\"([^\"]+)\"[^>]*>(.*?)</a>", block, flags=re.S)
        if not match:
            continue
        url = clean_search_result_url(match.group(1))
        title = strip_html_fragment(match.group(2), 180)
        snippet_match = re.search(r"<p[^>]*>(.*?)</p>", block, flags=re.S)
        snippet = strip_html_fragment(snippet_match.group(1), 260) if snippet_match else ""
        if should_skip_search_result(url, title) or url in seen_urls:
            continue
        seen_urls.add(url)
        results.append({"title": title, "url": url, "snippet": snippet})
        if len(results) >= max_results:
            return results

    parser = SearchHTMLParser()
    parser.feed(html_text or "")
    for item in parser.results:
        title = clean_search_text(item.get("title", ""))
        if not title or should_skip_search_result(item["url"], title) or item["url"] in seen_urls:
            continue
        seen_urls.add(item["url"])
        results.append(
            {
                "title": title,
                "url": item["url"],
                "snippet": clean_search_text(item.get("snippet", "")),
            }
        )
        if len(results) >= max_results:
            break
    return results


def normalize_web_search_proxy(proxy: str = "") -> Optional[str]:
    selected = (proxy or "").strip() or WEB_SEARCH_PROXY.strip()
    if not selected:
        return None
    parsed = urlparse(selected)
    if parsed.scheme not in ("http", "https", "socks5", "socks5h"):
        raise ValueError("proxy must start with http://, https://, socks5:// or socks5h://")
    if not parsed.netloc:
        raise ValueError("proxy host is empty")
    return selected


def build_web_search_query(message: str) -> str:
    query = clean_search_text(message, 180)
    query = re.sub(r"^(请|帮我|麻烦你)?\s*(联网)?\s*(搜索|搜一下|查一下|查找|查询)\s*", "", query)
    query = re.sub(r"(请)?只回答[^，,。.!！?？]*", "", query)
    query = re.sub(r"(用)?(一|1|两|2)?句(话)?(中文|英文)?回答[。.!！]*$", "", query)
    query = re.sub(r"(简短|简单|直接|只)?(回答|说明|总结)[。.!！]*$", "", query)
    query = re.sub(r"[，,；;：:。.!！?？]+$", "", query).strip()
    query = normalize_relative_years(query)
    return query or clean_search_text(message, 180)


def is_authority_url(url: str) -> bool:
    hostname = (urlparse(clean_search_result_url(url)).hostname or "").lower()
    return any(hostname == domain or hostname.endswith(f".{domain}") for domain in AUTHORITY_DOMAINS)


def extract_relevance_terms(query: str) -> List[str]:
    text = clean_search_text(query, 240).lower()
    terms: List[str] = []
    for term in re.findall(r"\b[a-z0-9]{2,}\b|20\d{2}", text):
        if term not in terms:
            terms.append(term)
    for chunk in re.findall(r"[\u4e00-\u9fff]{3,}", text):
        reduced = re.sub(r"(官方|出处|来源|请|回答|联网|搜索|查询|查一下|告诉我|帮我)", "", chunk)
        if 3 <= len(reduced) <= 12 and reduced not in terms and not any(term in reduced for term in terms):
            terms.append(reduced)
    return terms


def search_required_terms(query: str, plan: Dict[str, object]) -> List[str]:
    terms: List[str] = []
    for raw in list(plan.get("required_terms", []) or []) + extract_relevance_terms(
        " ".join([query] + [str(item) for item in plan.get("queries", []) or []])
    ):
        term = clean_search_text(str(raw), 40)
        if term and term not in terms:
            terms.append(term)
        if len(terms) >= 12:
            break
    return terms


def search_result_relevance(item: Dict[str, Any], query: str) -> float:
    required_terms = item.get("required_terms")
    if isinstance(required_terms, list):
        terms = [clean_search_text(str(term), 40).lower() for term in required_terms if clean_search_text(str(term), 40)]
    else:
        terms = extract_relevance_terms(query)
    if not terms:
        return 0.0
    haystack = " ".join(
        clean_search_text(str(item.get(key, "")), 600).lower()
        for key in ("title", "snippet", "page_title", "page_excerpt", "url")
    )
    hits = 0.0
    for term in terms:
        if term and term in haystack:
            hits += 1.0
    score = hits / max(1, len(terms))
    if len(terms) >= 4 and hits <= 2:
        score = min(score, 0.49)
    return round(score, 3)


def rank_search_results(results: List[Dict[str, str]], query: str) -> List[Dict[str, str]]:
    ranked: List[Dict[str, str]] = []
    for item in results:
        enriched = dict(item)
        relevance = search_result_relevance(enriched, query)
        enriched["relevance"] = relevance
        if relevance >= 0.55:
            enriched.setdefault("matched_answer", "query_terms_matched")
        ranked.append(enriched)
    return sorted(
        ranked,
        key=lambda item: (
            float(item.get("relevance", 0)),
            bool(item.get("authority")),
            bool(item.get("snippet")),
        ),
        reverse=True,
    )


def source_confidence(item: Dict[str, Any]) -> float:
    haystack = " ".join(
        clean_search_text(str(item.get(key, "")), 500)
        for key in ("title", "snippet", "page_title", "page_excerpt", "matched_answer")
    )
    score = 0.35
    if is_authority_url(str(item.get("url", ""))):
        score += 0.22
    if item.get("page_excerpt"):
        score += 0.14
    if item.get("matched_answer"):
        score += 0.12
    relevance = item.get("relevance")
    if isinstance(relevance, (int, float)):
        score += min(0.18, max(0.0, float(relevance)) * 0.18)
    if any(marker in haystack for marker in ("官方", "发布", "考试院", "高考作文", "热搜", "热榜", "trending")):
        score += 0.08
    return round(min(0.98, max(0.05, score)), 3)


def decode_jsonish_text(text: str) -> str:
    if "\\u" not in text and "\\x" not in text:
        return text
    try:
        return bytes(text, "utf-8").decode("unicode_escape")
    except Exception:
        return text


def extract_hot_search_items(source_name: str, html_text: str, max_items: int = HOT_SEARCH_MAX_ITEMS) -> List[str]:
    source = source_name.lower()
    patterns = []
    if "百度" in source_name or "baidu" in source:
        patterns.extend([
            r'"word"\s*:\s*"([^"]{2,80})"',
            r'"query"\s*:\s*"([^"]{2,80})"',
        ])
    if "微博" in source_name or "weibo" in source:
        patterns.extend([
            r'<td[^>]*class="[^"]*td-02[^"]*"[^>]*>.*?<a[^>]*>(.*?)</a>',
            r'/weibo\?q=[^"]+?>(.*?)</a>',
        ])
    if "头条" in source_name or "toutiao" in source:
        patterns.extend([
            r'"Title"\s*:\s*"([^"]{2,80})"',
            r'"title"\s*:\s*"([^"]{2,80})"',
        ])
    if "b站" in source_name or "哔哩" in source_name or "bilibili" in source:
        patterns.extend([
            r'"title"\s*:\s*"([^"]{2,100})"',
            r'"name"\s*:\s*"([^"]{2,100})"',
        ])
    if "知乎" in source_name or "zhihu" in source:
        patterns.extend([
            r'"text"\s*:\s*"([^"]{2,100})"',
            r'"title"\s*:\s*"([^"]{2,100})"',
        ])
    patterns.append(r'"word"\s*:\s*"([^"]{2,80})"')

    items: List[str] = []
    for pattern in patterns:
        for raw in re.findall(pattern, html_text or "", flags=re.S):
            title = clean_search_text(re.sub(r"<[^>]+>", "", decode_jsonish_text(raw)), 80)
            if not title:
                continue
            if any(skip in title for skip in ("更多", "登录", "首页", "客户端", "广告")):
                continue
            if title not in items:
                items.append(title)
            if len(items) >= max_items:
                return items
    return items


def fetch_hot_search_results(
    proxy: str = "",
    on_visit: Optional[Callable[[str], None]] = None,
) -> List[Dict[str, str]]:
    selected_proxy = normalize_web_search_proxy(proxy)
    headers = {
        "User-Agent": (
            "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
            "AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0 Safari/537.36"
        ),
        "Accept": "text/html,application/json,*/*;q=0.8",
    }
    sources = [
        ("微博热搜", "https://s.weibo.com/top/summary"),
        ("百度实时热搜", "https://top.baidu.com/board?tab=realtime"),
        ("今日头条热榜", "https://www.toutiao.com/hot-event/hot-board/?origin=toutiao_pc"),
        ("B站热门", "https://api.bilibili.com/x/web-interface/popular?ps=20&pn=1"),
        ("知乎热榜", "https://www.zhihu.com/billboard"),
        ("巨量算数热点", "https://trendinsight.oceanengine.com/arithmetic-index"),
    ]
    results: List[Dict[str, str]] = []
    with httpx.Client(
        trust_env=False,
        timeout=WEB_SEARCH_TIMEOUT,
        proxy=selected_proxy,
        headers=headers,
        follow_redirects=True,
    ) as client:
        for source_name, url in sources:
            if on_visit:
                on_visit(url)
            try:
                response = client.get(url)
                response.raise_for_status()
            except Exception:
                continue
            items = extract_hot_search_items(source_name, response.text, HOT_SEARCH_MAX_ITEMS)
            if not items:
                continue
            results.append(
                {
                    "title": source_name,
                    "url": url,
                    "snippet": "；".join(items[:8]),
                    "page_title": source_name,
                    "page_excerpt": "；".join(f"{index}. {item}" for index, item in enumerate(items, start=1)),
                    "source_type": "hot_search",
                    "authority": False,
                }
            )
            if len(results) >= WEB_SEARCH_MAX_CANDIDATES:
                break
    return results


def perform_general_web_search(
    cleaned_query: str,
    max_results: int = WEB_SEARCH_MAX_CANDIDATES,
    proxy: str = "",
    on_visit: Optional[Callable[[str], None]] = None,
) -> List[Dict[str, str]]:
    if max_results <= 0:
        return []
    if not cleaned_query:
        return []
    selected_proxy = normalize_web_search_proxy(proxy)
    headers = {
        "User-Agent": (
            "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
            "AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0 Safari/537.36"
        )
    }
    search_urls = [
        ("https://duckduckgo.com/html/", {"q": cleaned_query}),
        ("https://so.toutiao.com/search", {"keyword": cleaned_query}),
        ("https://yz.m.sm.cn/s", {"q": cleaned_query}),
        ("https://cn.bing.com/search", {"q": cleaned_query, "mkt": "zh-CN", "setlang": "zh-Hans"}),
    ]
    collected: List[Dict[str, str]] = []
    seen_urls = set()
    last_error = ""
    with httpx.Client(
        trust_env=False,
        timeout=WEB_SEARCH_TIMEOUT,
        proxy=selected_proxy,
        headers=headers,
        follow_redirects=True,
    ) as client:
        for url, params in search_urls:
            try:
                if on_visit:
                    on_visit(url)
                response = client.get(url, params=params)
                response.raise_for_status()
                results = extract_search_results(response.text, max_results=max_results)
                for item in results:
                    cleaned_url = clean_search_result_url(item.get("url", ""))
                    title = clean_search_text(item.get("title", ""), 180)
                    if not cleaned_url or cleaned_url in seen_urls or should_skip_search_result(cleaned_url, title):
                        continue
                    seen_urls.add(cleaned_url)
                    item["url"] = cleaned_url
                    item["title"] = title
                    item.setdefault("source_type", "web_search")
                    item["authority"] = is_authority_url(cleaned_url)
                    collected.append(item)
            except Exception as exc:
                last_error = str(exc)
                continue
    if collected:
        return rank_search_results(collected, cleaned_query)[:max_results]
    if last_error:
        raise RuntimeError(last_error)
    return []


def parse_search_plan_response(text: str) -> Dict[str, object]:
    cleaned = (text or "").strip()
    if cleaned.startswith("```"):
        cleaned = re.sub(r"^```(?:json)?\s*", "", cleaned)
        cleaned = re.sub(r"\s*```$", "", cleaned)
    match = re.search(r"\{.*\}", cleaned, flags=re.S)
    if match:
        cleaned = match.group(0)
    payload = json.loads(cleaned)
    raw_queries = payload.get("queries", [])
    queries: List[str] = []
    if isinstance(raw_queries, list):
        for raw in raw_queries:
            query = clean_search_text(str(raw), 160)
            if query and query not in queries:
                queries.append(query)
            if len(queries) >= WEB_SEARCH_PLANNER_MAX_QUERIES:
                break
    raw_required_terms = payload.get("required_terms", [])
    required_terms: List[str] = []
    if isinstance(raw_required_terms, list):
        for raw in raw_required_terms:
            term = clean_search_text(str(raw), 40)
            if term and term not in required_terms:
                required_terms.append(term)
            if len(required_terms) >= 12:
                break
    return {
        "queries": queries,
        "required_terms": required_terms,
        "rationale": clean_search_text(str(payload.get("rationale", "")), 220),
    }


def fallback_search_plan(user_message: str) -> Dict[str, object]:
    query = build_web_search_query(user_message)
    return {
        "queries": [query] if query else [],
        "required_terms": extract_relevance_terms(query)[:8],
        "rationale": "search planner unavailable; using normalized user query",
        "fallback": True,
    }


def parse_memory_retrieval_query_response(text: str) -> Dict[str, object]:
    cleaned = (text or "").strip()
    if cleaned.startswith("```"):
        cleaned = re.sub(r"^```(?:json)?\s*", "", cleaned)
        cleaned = re.sub(r"\s*```$", "", cleaned)
    match = re.search(r"\{.*\}", cleaned, flags=re.S)
    if match:
        cleaned = match.group(0)
    payload = json.loads(cleaned)
    query = clean_search_text(str(payload.get("query", "")), 120)
    raw_keywords = payload.get("keywords", [])
    keywords: List[str] = []
    if isinstance(raw_keywords, list):
        for raw in raw_keywords:
            keyword = clean_search_text(str(raw), 30)
            if keyword and keyword not in keywords:
                keywords.append(keyword)
            if len(keywords) >= 8:
                break
    return {
        "query": query,
        "keywords": keywords,
        "rationale": clean_search_text(str(payload.get("rationale", "")), 160),
    }


def fallback_memory_retrieval_query(user_message: str) -> str:
    text = normalize_relative_years(clean_search_text(user_message, 180))
    reduced = re.sub(r"(请|帮我|告诉我|一下|吗|呢|啊|吧)", " ", text)
    return clean_search_text(reduced, 120) or clean_search_text(text, 120)


def build_memory_retrieval_query_prompt(
    user_message: str,
    context_messages: Optional[List[Dict[str, str]]] = None,
) -> str:
    context = format_search_planner_context(
        context_messages,
        max_chars=MEMORY_PLANNER_CONTEXT_CHARS,
    )
    context_block = f"{context}\n\n" if context else ""
    return (
        f"{current_date_context()}\n\n"
        f"{context_block}"
        "请为下面问题生成长期记忆检索词。"
        "检索词应描述要找的记忆类型，而不是照抄用户原话。"
        "如果当前问题依赖上文，例如“他、这件事、刚才那个、那我、它、这个”等，"
        "必须结合最近会话上下文补全要检索的用户身份、偏好、事件、称呼、作品或规则。\n\n"
        f"用户问题：{user_message}"
    )


def build_memory_retrieval_query(
    user_message: str,
    session_id: str = "",
    visitor_ip: str = "unknown",
    analysis_trace_id: str = "",
    context_messages: Optional[List[Dict[str, str]]] = None,
) -> str:
    fallback = fallback_memory_retrieval_query(user_message)
    user_prompt = build_memory_retrieval_query_prompt(user_message, context_messages=context_messages)
    planner_messages = [
        {"role": "system", "content": MEMORY_QUERY_PLANNER_SYSTEM_PROMPT},
        {"role": "user", "content": user_prompt},
    ]
    started = time.perf_counter()
    http_client = httpx.Client(trust_env=False, timeout=MEMORY_QUERY_PLANNER_TIMEOUT)
    try:
        client = OpenAI(api_key=MODEL_API_KEY, base_url=BASE_URL, http_client=http_client)
        resp = client.chat.completions.create(
            model=MODEL_NAME,
            messages=planner_messages,
            temperature=0.05,
            top_p=0.8,
            max_tokens=320,
            extra_body=build_extra_body(),
        )
        content = resp.choices[0].message.content or ""
        _, answer = split_think_text(content)
        parsed = parse_memory_retrieval_query_response(answer)
        query = str(parsed.get("query") or "").strip()
        if query and query != clean_search_text(user_message, 120):
            if analysis_trace_id:
                record_analysis_trace(
                    session_id=session_id,
                    trace_id=analysis_trace_id,
                    event_type="model_call",
                    visitor_ip=visitor_ip,
                    step_name="memory_query_planner",
                    duration_ms=round((time.perf_counter() - started) * 1000, 3),
                    payload={
                        "model": MODEL_NAME,
                        "messages": planner_messages,
                        "result": parsed,
                        "fallback_query": fallback,
                    },
                )
            return query
    except Exception as exc:
        if analysis_trace_id:
            record_analysis_trace(
                session_id=session_id,
                trace_id=analysis_trace_id,
                event_type="model_call_error",
                visitor_ip=visitor_ip,
                step_name="memory_query_planner",
                duration_ms=round((time.perf_counter() - started) * 1000, 3),
                payload={
                    "model": MODEL_NAME,
                    "messages": planner_messages,
                    "fallback_query": fallback,
                    "error": str(exc),
                },
            )
    finally:
        http_client.close()

    return fallback


def parse_memory_gate_response(text: str) -> Dict[str, object]:
    cleaned = (text or "").strip()
    if cleaned.startswith("```"):
        cleaned = re.sub(r"^```(?:json)?\s*", "", cleaned)
        cleaned = re.sub(r"\s*```$", "", cleaned)
    try:
        parsed = json.loads(cleaned)
    except json.JSONDecodeError:
        match = re.search(r"\{.*\}", cleaned, flags=re.S)
        parsed = json.loads(match.group(0)) if match else {}
    return {
        "needs_memory": bool(parsed.get("needs_memory")),
        "reason": str(parsed.get("reason") or "").strip(),
    }


def fallback_memory_gate(user_message: str) -> bool:
    text = (user_message or "").strip()
    if not text:
        return False
    return False


def build_memory_gate_user_prompt(
    user_message: str,
    context_messages: Optional[List[Dict[str, str]]] = None,
) -> str:
    context = format_search_planner_context(
        context_messages,
        max_chars=MEMORY_PLANNER_CONTEXT_CHARS,
    )
    context_block = f"{context}\n\n" if context else ""
    return (
        f"{current_date_context()}\n\n"
        f"{context_block}"
        "请判断下面用户消息是否需要调用长期记忆。"
        "如果当前消息承接上文，包含“他、这件事、那我、刚才那个、它、这个”等指代，"
        "必须结合最近会话上下文判断是否需要回忆；不要只看当前一句。\n\n"
        f"用户消息：{user_message}"
    )


def should_use_memory_recall(
    user_message: str,
    session_id: str = "",
    visitor_ip: str = "unknown",
    analysis_trace_id: str = "",
    context_messages: Optional[List[Dict[str, str]]] = None,
) -> bool:
    fallback = fallback_memory_gate(user_message)
    messages = [
        {"role": "system", "content": MEMORY_GATE_SYSTEM_PROMPT},
        {"role": "user", "content": build_memory_gate_user_prompt(user_message, context_messages=context_messages)},
    ]
    started = time.perf_counter()
    http_client = httpx.Client(trust_env=False, timeout=MEMORY_GATE_TIMEOUT)
    try:
        client = OpenAI(api_key=MODEL_API_KEY, base_url=BASE_URL, http_client=http_client)
        resp = client.chat.completions.create(
            model=MODEL_NAME,
            messages=messages,
            temperature=0.0,
            top_p=0.8,
            max_tokens=MEMORY_GATE_MAX_TOKENS,
            extra_body=build_extra_body(),
        )
        content = resp.choices[0].message.content or ""
        _, answer = split_think_text(content)
        decision = parse_memory_gate_response(answer)
        if analysis_trace_id:
            record_analysis_trace(
                session_id=session_id,
                trace_id=analysis_trace_id,
                event_type="model_call",
                visitor_ip=visitor_ip,
                step_name="memory_recall_gate",
                duration_ms=round((time.perf_counter() - started) * 1000, 3),
                payload={
                    "model": MODEL_NAME,
                    "messages": messages,
                    "decision": decision,
                    "fallback": fallback,
                },
            )
        return bool(decision.get("needs_memory"))
    except Exception as exc:
        if analysis_trace_id:
            record_analysis_trace(
                session_id=session_id,
                trace_id=analysis_trace_id,
                event_type="model_call_error",
                visitor_ip=visitor_ip,
                step_name="memory_recall_gate",
                duration_ms=round((time.perf_counter() - started) * 1000, 3),
                payload={
                    "model": MODEL_NAME,
                    "messages": messages,
                    "fallback": fallback,
                    "error": str(exc),
                },
            )
        return fallback
    finally:
        http_client.close()


def search_plan_display_query(plan: Dict[str, object], fallback: str = "") -> str:
    queries = [
        clean_search_text(str(item), 80)
        for item in plan.get("queries", [])
        if clean_search_text(str(item), 80)
    ]
    if queries:
        return "；".join(queries[:2])
    return clean_search_text(fallback, 120)


def format_search_planner_context(
    context_messages: Optional[List[Dict[str, str]]] = None,
    max_chars: int = WEB_SEARCH_PLANNER_CONTEXT_CHARS,
) -> str:
    if not context_messages:
        return ""
    lines: List[str] = []
    remaining = max(int(max_chars), 400)
    for message in context_messages:
        role = str(message.get("role", "")).strip()
        content = re.sub(r"\s+", " ", str(message.get("content", "")).strip())
        if role not in {"user", "assistant"} or not content:
            continue
        timestamp = format_message_time_for_model(message.get("created_at", ""))
        time_part = f" time={timestamp}" if timestamp else ""
        line = f"[{role}{time_part}] {clean_search_text(content, 420)}"
        if len(line) > remaining:
            if remaining > 80:
                lines.append(line[:remaining].rstrip() + "...")
            break
        lines.append(line)
        remaining -= len(line)
        if remaining <= 80:
            break
    if not lines:
        return ""
    return (
        "最近会话上下文（仅用于解析当前问题里的代词、承接对象、论文标题、人名、时间等，"
        "不是搜索结果，也不能当作事实来源）：\n"
        + "\n".join(lines)
    )


def build_search_planner_user_prompt(
    user_message: str,
    context_messages: Optional[List[Dict[str, str]]] = None,
) -> str:
    context = format_search_planner_context(context_messages)
    context_block = f"{context}\n\n" if context else ""
    return (
        f"{current_date_context()}\n\n"
        f"{context_block}"
        "请为下面用户问题生成搜索查询 JSON。"
        "注意不要把“昨天/前年/是什么/这个/那个”这类弱指代单独作为查询；"
        "查询必须保留用户问题里的核心对象和限定条件。"
        "如果当前问题依赖上文，例如“他、这篇、刚才那个、具体引用了几篇、第几作者”等，"
        "必须结合最近会话上下文补全搜索对象，再生成可直接搜索的完整查询。\n\n"
        f"用户问题：{user_message}"
    )


def build_search_plan(
    user_message: str,
    context_messages: Optional[List[Dict[str, str]]] = None,
) -> Dict[str, object]:
    user_prompt = build_search_planner_user_prompt(user_message, context_messages=context_messages)
    http_client = httpx.Client(trust_env=False, timeout=WEB_SEARCH_PLANNER_TIMEOUT)
    client = OpenAI(api_key=MODEL_API_KEY, base_url=BASE_URL, http_client=http_client)
    try:
        resp = client.chat.completions.create(
            model=MODEL_NAME,
            messages=[
                {"role": "system", "content": SEARCH_PLANNER_SYSTEM_PROMPT},
                {"role": "user", "content": user_prompt},
            ],
            temperature=0.1,
            top_p=0.8,
            max_tokens=500,
            extra_body=build_extra_body(),
        )
        content = resp.choices[0].message.content or ""
        _, answer = split_think_text(content)
        plan = parse_search_plan_response(answer)
        if plan.get("queries"):
            return plan
    finally:
        http_client.close()
    return fallback_search_plan(user_message)


def perform_web_search(
    query: str,
    max_results: int = WEB_SEARCH_MAX_CANDIDATES,
    proxy: str = "",
    on_visit: Optional[Callable[[str], None]] = None,
    search_plan: Optional[Dict[str, object]] = None,
) -> List[Dict[str, str]]:
    plan = search_plan or build_search_plan(query)
    queries = [str(item) for item in plan.get("queries", []) if str(item).strip()]
    required_terms = search_required_terms(query, plan)
    if not required_terms:
        required_terms = extract_relevance_terms(" ".join([query] + queries))[:8]
    if not queries:
        return []
    collected: List[Dict[str, str]] = []
    seen_urls = set()
    last_error = ""
    per_query_limit = max(4, min(max_results, WEB_SEARCH_MAX_CANDIDATES))
    for planned_query in queries[:WEB_SEARCH_PLANNER_MAX_QUERIES]:
        try:
            for item in perform_general_web_search(
                planned_query,
                max_results=per_query_limit,
                proxy=proxy,
                on_visit=on_visit,
            ):
                url = item.get("url", "")
                if not url or url in seen_urls:
                    continue
                seen_urls.add(url)
                item["planned_query"] = planned_query
                item["required_terms"] = required_terms
                collected.append(item)
        except Exception as exc:
            last_error = str(exc)
            continue
        if len(collected) >= max_results * 2:
            break
    if collected:
        return rank_search_results(collected, " ".join([query] + queries))[:max_results]
    if last_error:
        raise RuntimeError(last_error)
    return []


def fetch_web_page_summary(url: str, proxy: str = "") -> Dict[str, str]:
    cleaned_url = clean_search_result_url(url)
    if not cleaned_url.startswith(("http://", "https://")):
        return {"page_title": "", "page_excerpt": ""}
    selected_proxy = normalize_web_search_proxy(proxy)
    headers = {
        "User-Agent": (
            "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
            "AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0 Safari/537.36"
        ),
        "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.4",
    }
    with httpx.Client(
        trust_env=False,
        timeout=WEB_SEARCH_TIMEOUT,
        proxy=selected_proxy,
        headers=headers,
        follow_redirects=True,
    ) as client:
        response = client.get(cleaned_url)
        response.raise_for_status()
        content_type = response.headers.get("content-type", "").lower()
        if content_type and not any(kind in content_type for kind in ("text/html", "application/xhtml")):
            return {"page_title": "", "page_excerpt": ""}
        parser = PageTextParser()
        parser.feed(response.text[:300000])
    page_title = clean_search_text(parser.title, 180)
    excerpt = clean_search_text(" ".join(parser.parts), 700)
    return {
        "page_title": page_title,
        "page_excerpt": excerpt,
    }


def assign_source_registry(results: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    registry: List[Dict[str, Any]] = []
    seen_urls = set()
    for item in results:
        source = dict(item)
        url = clean_search_result_url(str(source.get("url", "")))
        dedupe_key = url or clean_search_text(str(source.get("title", "")), 120)
        if dedupe_key and dedupe_key in seen_urls:
            continue
        if dedupe_key:
            seen_urls.add(dedupe_key)
        source["url"] = url
        source["authority"] = bool(source.get("authority")) or is_authority_url(url)
        source["confidence"] = float(source.get("confidence") or source_confidence(source))
        source["source_id"] = f"S{len(registry) + 1}"
        relevance = source.get("relevance")
        if isinstance(relevance, (int, float)):
            source["used_in_answer"] = bool(source.get("used_in_answer")) or (
                float(relevance) >= WEB_SEARCH_MIN_RELEVANCE
                or (source["confidence"] >= WEB_SEARCH_MIN_CONFIDENCE and float(relevance) >= 0.35)
            )
        else:
            source["used_in_answer"] = bool(source.get("used_in_answer")) or (
                len(registry) < WEB_SEARCH_MAX_READ_PAGES or source["confidence"] >= WEB_SEARCH_MIN_CONFIDENCE
            )
        registry.append(source)
        if len(registry) >= WEB_SEARCH_MAX_CANDIDATES:
            break
    return registry


MARKDOWN_LINK_RE = re.compile(r"\[[^\]]+\]\(https?://[^\s)]+\)")


def append_source_footer_if_missing(answer: str, sources: List[Dict[str, Any]]) -> str:
    if not sources or MARKDOWN_LINK_RE.search(answer or ""):
        return answer
    usable = [
        source
        for source in sources
        if source.get("url") and source.get("used_in_answer")
    ]
    if not usable:
        return answer
    lines = ["", "## 来源"]
    for source in usable[:6]:
        title = clean_search_text(str(source.get("title") or source.get("page_title") or source.get("url")), 120)
        source_id = clean_search_text(str(source.get("source_id", "")), 12)
        url = str(source.get("url", ""))
        label = f"{source_id} {title}".strip()
        lines.append(f"- [{label}]({url})")
    return (answer.rstrip() + "\n" + "\n".join(lines)).strip()


def format_web_search_context(results: List[Dict[str, Any]]) -> str:
    if not results:
        return ""
    sources = assign_source_registry(results)
    lines = [
        "联网搜索参考（已由系统抓取，可能有噪声或过期；回答时不要编造来源）：",
        "必须基于已抓取到的条目回答；禁止让用户自行去微博、抖音、百度、知乎、小红书或其他平台查看。",
        "回答中的事实断言必须使用 Markdown 超链接给出处，例如：[来源标题](https://example.com)。",
        "精确事实类问题必须优先采用官方或主流媒体资料；资料不足时只能说明“未找到可靠出处”，不能凭记忆补全。",
    ]
    usable_sources = [source for source in sources if source.get("used_in_answer")]
    if not usable_sources:
        lines.append("本轮搜索没有找到和问题足够相关的可靠资料；回答时必须明确说明未找到可靠出处。")
        lines.append("不要解释训练数据、知识库或模型记忆不足；不要模拟、猜测或编造答案。")
        lines.append("不要声称检索过来源列表中没有出现的网站或数据库。")
        return "\n".join(lines).strip()
    for item in usable_sources[:WEB_SEARCH_MAX_CANDIDATES]:
        title = clean_search_text(str(item.get("title", "")), 160)
        url = clean_search_text(str(item.get("url", "")), 220)
        snippet = clean_search_text(str(item.get("snippet", "")), 260)
        if not title and not url:
            continue
        source_id = clean_search_text(str(item.get("source_id", "")), 12)
        source_type = clean_search_text(str(item.get("source_type", "")), 60)
        confidence = item.get("confidence", "")
        authority = "是" if item.get("authority") else "否"
        line = f"- [{source_id}] {title}"
        meta = []
        if source_type:
            meta.append(f"类型: {source_type}")
        if confidence != "":
            meta.append(f"置信度: {confidence}")
        meta.append(f"权威源: {authority}")
        line += "\n   " + "；".join(meta)
        if url:
            line += f"\n   URL: {url}"
        if snippet:
            line += f"\n   摘要: {snippet}"
        page_title = clean_search_text(str(item.get("page_title", "")), 180)
        page_excerpt = clean_search_text(str(item.get("page_excerpt", "")), 700)
        if page_title and page_title != title:
            line += f"\n   读取标题: {page_title}"
        if page_excerpt:
            line += f"\n   网页摘录: {page_excerpt}"
        lines.append(line)
    return "\n".join(lines).strip() if len(lines) > 1 else ""


def local_timezone():
    if ZoneInfo is not None:
        try:
            return ZoneInfo(LOCAL_TIMEZONE_NAME)
        except Exception:
            pass
    return timezone(timedelta(hours=8), LOCAL_TIMEZONE_NAME)


def current_date_context(now: Optional[datetime] = None) -> str:
    tz = local_timezone()
    current = now or datetime.now(tz)
    if current.tzinfo is None:
        current = current.replace(tzinfo=tz)
    else:
        current = current.astimezone(tz)
    weekdays = ["星期一", "星期二", "星期三", "星期四", "星期五", "星期六", "星期日"]
    weekday = weekdays[current.weekday()]
    clock = current.strftime("%H:%M")
    return (
        "当前真实日期与时间上下文："
        f"今天是 {current.year}年{current.month}月{current.day}日，{weekday}，"
        f"当前本地时间是 {clock}，"
        f"时区 {LOCAL_TIMEZONE_NAME}。"
        "如果用户询问今天、现在、昨天、明天、日期、星期或近期时间，"
        "必须优先使用这里的真实日期，不要依据训练数据或猜测回答。"
        "如果用户提到开会、提醒、截止时间、日程或约定，必须结合这里的真实日期和时间理解相对时间。"
        "如果当前时间已经过 0 点且仍在凌晨，用户首次含糊提到‘明天’时，可以提醒日期已经跨日并确认一次；"
        "如果用户已经解释、纠正或明确说按某个日期理解，就接受用户解释，不要反复追问。"
    )


LATE_NIGHT_TOMORROW_CONFIRM_BEFORE_HOUR = int(
    os.environ.get("QWEN_LATE_NIGHT_TOMORROW_CONFIRM_BEFORE_HOUR", "3")
)
TOMORROW_AMBIGUITY_PATTERN = re.compile(r"明\s*天")
TOMORROW_EXPLANATION_PATTERN = re.compile(
    r"(不是|其实|说错|刚刚|前面|解释|更正|纠正|按这个来|按我.*来|我说的|我指的是|是今天|今天.*明天|明天.*今天)"
)


def is_tomorrow_explanation_or_correction(user_text: str) -> bool:
    return bool(TOMORROW_EXPLANATION_PATTERN.search(user_text or ""))


def late_night_tomorrow_clarification(
    user_text: str,
    now: Optional[datetime] = None,
    already_prompted: bool = False,
) -> str:
    if already_prompted:
        return ""
    if not isinstance(user_text, str) or not TOMORROW_AMBIGUITY_PATTERN.search(user_text):
        return ""
    if is_tomorrow_explanation_or_correction(user_text):
        return ""
    tz = local_timezone()
    current = now or datetime.now(tz)
    if current.tzinfo is None:
        current = current.replace(tzinfo=tz)
    else:
        current = current.astimezone(tz)
    if not (0 <= current.hour < LATE_NIGHT_TOMORROW_CONFIRM_BEFORE_HOUR):
        return ""
    today = current.strftime("%Y年%-m月%-d日") if os.name != "nt" else current.strftime("%Y年%#m月%#d日")
    tomorrow = (current + timedelta(days=1)).strftime("%Y年%-m月%-d日") if os.name != "nt" else (current + timedelta(days=1)).strftime("%Y年%#m月%#d日")
    return (
        f"现在已经过 0 点了，当前是 {today} {current.strftime('%H:%M')}。"
        f"凌晨 3 点前说“明天”有时其实是在说今天（{today}），"
        f"但按日历计算，“明天”是 {tomorrow}。"
        "这一次你是指今天，还是日历上的明天？之后我会按你的解释来。"
    )


def session_has_late_night_tomorrow_clarification(session_id: str) -> bool:
    with connect_db() as conn:
        row = conn.execute(
            """
            SELECT 1
            FROM events
            WHERE session_id = ?
              AND event_type = 'late_night_tomorrow_clarification'
            LIMIT 1
            """,
            (session_id,),
        ).fetchone()
    return row is not None


def normalize_image_mime(mime_type: str) -> str:
    normalized = (mime_type or "").strip().lower()
    if normalized == "image/jpg":
        return "image/jpeg"
    if normalized == "image/pjpeg":
        return "image/jpeg"
    if normalized == "image/x-png":
        return "image/png"
    return normalized


def image_data_url(mime_type: str, payload: bytes) -> str:
    encoded = base64.b64encode(payload).decode("ascii")
    return f"data:{mime_type};base64,{encoded}"


def compress_image_attachment(image_bytes: bytes) -> Tuple[bytes, Tuple[int, int]]:
    if Image is None or ImageOps is None:
        raise HTTPException(status_code=500, detail="服务器未安装 Pillow，无法压缩大图")
    try:
        with Image.open(io.BytesIO(image_bytes)) as image:
            image = ImageOps.exif_transpose(image)
            if image.mode not in ("RGB", "L"):
                background = Image.new("RGB", image.size, (255, 255, 255))
                if "A" in image.getbands():
                    background.paste(image, mask=image.getchannel("A"))
                    image = background
                else:
                    image = image.convert("RGB")
            else:
                image = image.convert("RGB")

            max_side = max(64, int(IMAGE_COMPRESSION_MAX_SIDE))
            if max(image.size) > max_side:
                resampling = getattr(getattr(Image, "Resampling", Image), "LANCZOS", 1)
                image.thumbnail((max_side, max_side), resampling)

            target = max(32 * 1024, int(IMAGE_COMPRESSION_TARGET_BYTES))
            best = b""
            for quality in (85, 75, 65, 55, 45, 35):
                output = io.BytesIO()
                image.save(output, format="JPEG", quality=quality, optimize=True, progressive=True)
                payload = output.getvalue()
                best = payload
                if len(payload) <= target:
                    return payload, image.size

            while len(best) > target and max(image.size) > 384:
                next_size = (
                    max(1, int(image.size[0] * 0.82)),
                    max(1, int(image.size[1] * 0.82)),
                )
                resampling = getattr(getattr(Image, "Resampling", Image), "LANCZOS", 1)
                image = image.resize(next_size, resampling)
                output = io.BytesIO()
                image.save(output, format="JPEG", quality=35, optimize=True, progressive=True)
                best = output.getvalue()
            return best, image.size
    except HTTPException:
        raise
    except Exception as exc:
        raise HTTPException(status_code=400, detail=f"图片压缩失败：{exc}") from exc
