# Generated by splitting app.py lines 6193-7407. Keep execution order in wangcai_app/startup/loader.py.
COMPLETED_IDLE_PROMPT_MARKER = "【已完结】"
UNNAMED_IDLE_ARTIFACT_TITLE = "未命名成果"
MALFORMED_IDLE_ARTIFACT_SUMMARY = "idle agent returned malformed JSON; saved raw content"
IDLE_SERIES_TITLE_MAX_CHARS = 80


def effective_idle_agent_custom_prompt(prompt: str) -> str:
    prompt = str(prompt or "").strip()
    if COMPLETED_IDLE_PROMPT_MARKER in prompt:
        return ""
    return prompt


def completed_idle_agent_custom_prompt(prompt: str) -> str:
    prompt = str(prompt or "").strip()
    if not prompt:
        return ""
    if COMPLETED_IDLE_PROMPT_MARKER in prompt:
        return prompt
    return f"{prompt}\n{COMPLETED_IDLE_PROMPT_MARKER}"


def parse_idle_count_text(value: object) -> Optional[int]:
    text = normalize_idle_artifact_terms(str(value or "")).strip()
    if not text:
        return None
    digits = text.translate(str.maketrans("０１２３４５６７８９", "0123456789"))
    match = re.search(r"\d+", digits)
    if match:
        number = int(match.group(0))
        return number if number > 0 else None
    chinese_digits = {
        "零": 0,
        "一": 1,
        "二": 2,
        "两": 2,
        "三": 3,
        "四": 4,
        "五": 5,
        "六": 6,
        "七": 7,
        "八": 8,
        "九": 9,
    }
    if text == "十":
        return 10
    match = re.search(r"([一二两三四五六七八九])?十([一二三四五六七八九])?", text)
    if match:
        tens = chinese_digits.get(match.group(1) or "一", 1)
        ones = chinese_digits.get(match.group(2) or "零", 0)
        return tens * 10 + ones
    if len(text) == 1 and text in chinese_digits:
        return chinese_digits[text]
    return None


def canonical_idle_series_title(value: object) -> str:
    title = normalize_idle_artifact_terms(str(value or "")).strip()
    title = re.sub(r"^[《「『【\[\(（\s]+", "", title)
    title = re.sub(r"[》」』】\]\)）\s]+$", "", title)
    title = re.sub(r"\s+", " ", title).strip(" ：:，,。；;、")
    return title[:IDLE_SERIES_TITLE_MAX_CHARS]


def idle_series_title_key(value: object) -> str:
    return re.sub(r"\s+", "", canonical_idle_series_title(value)).lower()


def idle_series_title_variants(series_title: str) -> List[str]:
    canonical = canonical_idle_series_title(series_title)
    if not canonical:
        return []
    variants = [canonical, f"《{canonical}》"]
    seen: List[str] = []
    for item in variants:
        if item and item not in seen:
            seen.append(item)
    return seen


def idle_series_directive_from_prompt(prompt: str) -> Dict[str, object]:
    text = normalize_idle_artifact_terms(str(prompt or "")).replace(COMPLETED_IDLE_PROMPT_MARKER, "").strip()
    if not text:
        return {"series_title": "", "target_count": None, "explicit_series": False}
    count_match = re.search(
        r"(?:连载|續寫|续写|连续|系列|写成|生成|创作)?\s*([0-9０-９一二两三四五六七八九十]{1,8})\s*(?:篇|集|章|回)",
        text,
    )
    target_count = parse_idle_count_text(count_match.group(1)) if count_match else None
    quoted = [canonical_idle_series_title(item) for item in re.findall(r"《([^》]{1,120})》", text)]
    series_title = next((item for item in quoted if item), "")
    if not series_title and count_match:
        prefix = text[: count_match.start()]
        prefix = re.split(r"[\n。；;]", prefix)[-1]
        prefix = re.sub(r"(?:请|帮我|给我|来|搞|写|生成|创作|继续|续写|连载|系列|故事|作品|一组|一些)+", "", prefix)
        series_title = canonical_idle_series_title(prefix)
    if not series_title and count_match:
        leading_clause = re.split(r"[\n。；;，,]", text, maxsplit=1)[0]
        leading_clause = re.sub(r"(?:请|帮我|给我|来|搞|写|生成|创作|继续|续写|连载|系列|故事|作品|一组|一些)+", "", leading_clause)
        series_title = canonical_idle_series_title(leading_clause)
    explicit_series = bool(series_title and (target_count or "连载" in text or "续写" in text or "系列" in text))
    return {
        "series_title": series_title,
        "target_count": target_count,
        "explicit_series": explicit_series,
    }


def idle_series_status(series_title: str) -> Dict[str, object]:
    canonical = canonical_idle_series_title(series_title)
    if not canonical:
        return {"series_title": "", "total_count": 0, "max_episode": 0, "ids": []}
    variants = idle_series_title_variants(canonical)
    keys = {idle_series_title_key(item) for item in variants}
    with connect_db() as conn:
        rows = conn.execute(
            """
            SELECT id, title, series_title, episode_index
            FROM idle_agent_artifacts
            WHERE series_title IS NOT NULL
              AND TRIM(series_title) != ''
            ORDER BY id ASC
            """
        ).fetchall()
    matched: List[sqlite3.Row] = []
    max_episode = 0
    for row in rows:
        row_title = str(row["series_title"] or "")
        if idle_series_title_key(row_title) not in keys:
            continue
        matched.append(row)
        try:
            if row["episode_index"] is not None:
                max_episode = max(max_episode, int(row["episode_index"]))
        except Exception:
            pass
    return {
        "series_title": canonical,
        "total_count": len(matched),
        "max_episode": max_episode,
        "ids": [int(row["id"]) for row in matched],
    }


def idle_custom_prompt_target_reached(prompt: str) -> Dict[str, object]:
    active_prompt = effective_idle_agent_custom_prompt(prompt)
    directive = idle_series_directive_from_prompt(active_prompt)
    target_count = directive.get("target_count")
    series_title = str(directive.get("series_title") or "")
    if not active_prompt or not target_count or not series_title:
        return {"reached": False, "directive": directive, "status": {}}
    status = idle_series_status(series_title)
    reached = int(status.get("max_episode") or 0) >= int(target_count) or int(status.get("total_count") or 0) >= int(target_count)
    return {"reached": reached, "directive": directive, "status": status}


def apply_idle_series_directive_to_plan(plan: Dict[str, object], directive: Dict[str, object]) -> Dict[str, object]:
    series_title = canonical_idle_series_title(directive.get("series_title"))
    target_count = directive.get("target_count")
    if not series_title:
        return plan
    status = idle_series_status(series_title)
    max_episode = int(status.get("max_episode") or 0)
    total_count = int(status.get("total_count") or 0)
    if target_count:
        target_count = int(target_count)
    next_episode = max(max_episode, total_count) + 1
    plan["use_series"] = True
    plan["series_title"] = series_title
    plan["next_episode_index"] = next_episode
    plan["target_episode_count"] = target_count
    if target_count and next_episode >= target_count:
        plan["episode_policy"] = "finale"
        plan["release_prompt_after_this"] = True
    elif str(plan.get("episode_policy") or "").strip() not in {"continue", "new", "finale"}:
        plan["episode_policy"] = "continue" if max_episode or total_count else "new"
    if not str(plan.get("reason") or "").strip():
        plan["reason"] = "用户创作 prompt 明确要求连续系列，系统使用规范系列名和连续编号。"
    return plan


def normalize_idle_series_artifact_title(title: str, series_title: str, episode_index: Optional[int], title_idea: str = "") -> str:
    clean_title = normalize_idle_artifact_terms(str(title or "")).strip()
    clean_title = canonical_idle_series_title(clean_title) or clean_title
    canonical_series = canonical_idle_series_title(series_title)
    idea = normalize_idle_artifact_terms(str(title_idea or "")).strip()
    if canonical_series:
        clean_title = clean_title.replace(f"《{canonical_series}》", "").replace(canonical_series, "")
    clean_title = re.sub(r"^\s*[·:：,，。\\-—]*\s*", "", clean_title)
    clean_title = re.sub(r"^第\s*[0-9０-９一二两三四五六七八九十百]+\s*[集篇章回]\s*[：:·、\\-—]*\s*", "", clean_title)
    if not clean_title or clean_title in {"未命名成果", "未命名"}:
        clean_title = idea
    clean_title = normalize_idle_artifact_terms(clean_title).strip(" ：:，,。；;《》\"'")
    if episode_index is not None and canonical_series:
        suffix = clean_title or f"第{int(episode_index)}篇"
        return f"《{canonical_series}》第{int(episode_index)}篇：{suffix}"
    return clean_title or canonical_series or "未命名成果"


def idle_agent_decision_needs_repair(decision: Dict[str, object]) -> bool:
    title = normalize_idle_artifact_terms(str(decision.get("title") or "")).strip()
    summary = normalize_idle_artifact_terms(str(decision.get("summary") or "")).strip()
    content = normalize_idle_artifact_terms(str(decision.get("content") or "")).strip()
    if not content:
        return False
    if title == UNNAMED_IDLE_ARTIFACT_TITLE:
        return True
    if summary == MALFORMED_IDLE_ARTIFACT_SUMMARY:
        return True
    return False


def create_idle_agent_run(task_type: str, title: str, prompt_summary: str, status: str = "running") -> int:
    now = utc_now()
    with connect_db() as conn:
        cur = conn.execute(
            """
            INSERT INTO idle_agent_runs (
                task_type, title, prompt_summary, status,
                started_at, updated_at
            )
            VALUES (?, ?, ?, ?, ?, ?)
            """,
            (task_type or "other", title or "未命名任务", prompt_summary, status, now, now),
        )
        return int(cur.lastrowid)


def finish_idle_agent_run(run_id: int, status: str, interrupted_reason: str = "") -> None:
    now = utc_now()
    with connect_db() as conn:
        conn.execute(
            """
            UPDATE idle_agent_runs
            SET status = ?, interrupted_reason = ?, finished_at = ?, updated_at = ?
            WHERE id = ?
            """,
            (status, interrupted_reason or None, now, now, int(run_id)),
        )


def update_idle_agent_run_status(
    run_id: int,
    status: str,
    title: str = "",
    task_type: str = "",
    interrupted_reason: str = "",
) -> None:
    now = utc_now()
    assignments = ["status = ?", "updated_at = ?"]
    params: List[object] = [status, now]
    if title:
        assignments.append("title = ?")
        params.append(title)
    if task_type:
        assignments.append("task_type = ?")
        params.append(task_type)
    if interrupted_reason:
        assignments.append("interrupted_reason = ?")
        params.append(interrupted_reason)
    params.append(int(run_id))
    with connect_db() as conn:
        conn.execute(
            f"UPDATE idle_agent_runs SET {', '.join(assignments)} WHERE id = ?",
            tuple(params),
        )


def idle_agent_progress_from_reason(reason: str) -> Dict[str, object]:
    mapping = {
        "idle_disabled": ("disabled", "已关闭", 0),
        "idle_paused": ("paused", "已暂停", 0),
        "active_generation": ("interrupted", "由于对话中断", 28),
        "memory_agent_busy": ("interrupted", "等待记忆整理结束", 34),
        "idle_wait": ("interrupted", "等待用户空闲", 25),
        "recent_run": ("waiting", "等待开启", 8),
        "forced": ("waiting", "等待开启", 8),
        "idle": ("waiting", "等待开启", 8),
    }
    stage, label, percent = mapping.get(reason, ("waiting", "等待开启", 8))
    return {"stage": stage, "label": label, "percent": percent, "reason": reason}


def idle_agent_progress_from_status(status: str, interrupted_reason: str = "") -> Dict[str, object]:
    normalized = (status or "").strip().lower()
    mapping = {
        "running": ("writing", "撰写中", 52),
        "writing": ("writing", "撰写中", 52),
        "polishing": ("polishing", "润色中", 78),
        "completed": ("completed", "完成", 100),
        "cancelled": ("interrupted", "由于对话中断", 35),
        "skipped": ("waiting", "等待开启", 8),
        "failed": ("failed", "运行失败", 100),
    }
    stage, label, percent = mapping.get(normalized, ("waiting", "等待开启", 8))
    payload = {"stage": stage, "label": label, "percent": percent, "status": normalized}
    if interrupted_reason:
        payload["reason"] = interrupted_reason
    return payload


def parse_event_metadata(raw: str) -> Dict[str, object]:
    try:
        parsed = json.loads(raw or "{}")
        return parsed if isinstance(parsed, dict) else {"raw": parsed}
    except Exception:
        return {"raw": raw or ""}


def iso_seconds_ago(value: str) -> Optional[float]:
    text = (value or "").strip()
    if not text:
        return None
    try:
        parsed = datetime.fromisoformat(text)
    except ValueError:
        return None
    if parsed.tzinfo is None:
        parsed = parsed.replace(tzinfo=timezone.utc)
    return max(0.0, (datetime.now(timezone.utc) - parsed).total_seconds())


def idle_worker_last_event(event_type: str) -> Optional[Dict[str, object]]:
    with connect_db() as conn:
        row = conn.execute(
            """
            SELECT id, event_type, visitor_ip, created_at, metadata_json
            FROM events
            WHERE event_type = ?
            ORDER BY datetime(created_at) DESC, id DESC
            LIMIT 1
            """,
            (event_type,),
        ).fetchone()
    if not row:
        return None
    return {
        "id": int(row["id"]),
        "event_type": str(row["event_type"]),
        "visitor_ip": str(row["visitor_ip"] or "local"),
        "created_at": str(row["created_at"] or ""),
        "metadata": parse_event_metadata(str(row["metadata_json"] or "{}")),
    }


def latest_idle_artifact_created_at() -> str:
    with connect_db() as conn:
        row = conn.execute(
            """
            SELECT created_at
            FROM idle_agent_artifacts
            ORDER BY datetime(created_at) DESC, id DESC
            LIMIT 1
            """
        ).fetchone()
    return str(row["created_at"] or "") if row else ""


def record_idle_worker_watchdog_warning(kind: str, detail: Dict[str, object]) -> None:
    key = f"idle_worker_watchdog_last:{kind}"
    last = get_app_setting(key, "")
    if last:
        age = iso_seconds_ago(last)
        if age is not None and age < max(IDLE_WORKER_TICK_STALE_SECONDS, 600):
            return
    record_event(None, "warning_idle_worker_watchdog", "local", {"kind": kind, **detail})
    set_app_setting(key, utc_now())


def idle_worker_watchdog_status() -> Dict[str, object]:
    last_tick = idle_worker_last_event("idle_worker_tick")
    last_artifact_at = latest_idle_artifact_created_at()
    tick_age = iso_seconds_ago(str(last_tick.get("created_at", ""))) if last_tick else None
    artifact_age = iso_seconds_ago(last_artifact_at)
    warnings: List[Dict[str, object]] = []
    if tick_age is None:
        warnings.append({"kind": "no_tick", "message": "idle worker 尚未记录 heartbeat"})
        record_idle_worker_watchdog_warning("no_tick", {"message": "idle worker 尚未记录 heartbeat"})
    elif tick_age > IDLE_WORKER_TICK_STALE_SECONDS:
        payload = {
            "kind": "stale_tick",
            "message": f"idle worker heartbeat 已超过 {int(tick_age)} 秒未更新",
            "age_seconds": round(tick_age, 1),
        }
        warnings.append(payload)
        record_idle_worker_watchdog_warning("stale_tick", payload)
    if artifact_age is None:
        warnings.append({"kind": "no_artifact", "message": "尚未产生任何空闲成果"})
    elif artifact_age > IDLE_WORKER_ARTIFACT_STALE_SECONDS:
        payload = {
            "kind": "stale_artifact",
            "message": f"距离上次成果已超过 {int(artifact_age)} 秒",
            "age_seconds": round(artifact_age, 1),
        }
        warnings.append(payload)
        record_idle_worker_watchdog_warning("stale_artifact", payload)
    return {
        "ok": not warnings,
        "last_tick_at": last_tick.get("created_at") if last_tick else None,
        "last_artifact_at": last_artifact_at or None,
        "tick_age_seconds": round(tick_age, 1) if tick_age is not None else None,
        "artifact_age_seconds": round(artifact_age, 1) if artifact_age is not None else None,
        "warnings": warnings,
    }


def idle_agent_progress_from_reason(reason: str) -> Dict[str, object]:
    mapping = {
        "idle_disabled": ("disabled", "已关闭", 0),
        "idle_paused": ("paused", "已暂停", 0),
        "active_generation": ("interrupted", "由于对话中断", 28),
        "memory_agent_busy": ("interrupted", "等待记忆整理结束", 34),
        "idle_wait": ("interrupted", "等待用户空闲", 25),
        "recent_run": ("waiting", "等待开启", 8),
        "recent_run_exists": ("waiting", "等待开启", 8),
        "forced": ("waiting", "等待开启", 8),
        "idle": ("waiting", "等待开启", 8),
    }
    stage, label, percent = mapping.get(reason, ("waiting", "等待开启", 8))
    return {"stage": stage, "label": label, "percent": percent, "reason": reason}


def idle_agent_progress_from_status(status: str, interrupted_reason: str = "") -> Dict[str, object]:
    normalized = (status or "").strip().lower()
    mapping = {
        "running": ("writing", "撰写中", 52),
        "writing": ("writing", "撰写中", 52),
        "polishing": ("polishing", "润色中", 78),
        "completed": ("completed", "完成", 100),
        "cancelled": ("interrupted", "由于对话中断", 35),
        "skipped": ("waiting", "等待开启", 8),
        "failed": ("failed", "运行失败", 100),
    }
    stage, label, percent = mapping.get(normalized, ("waiting", "等待开启", 8))
    payload = {"stage": stage, "label": label, "percent": percent, "status": normalized, "task": "idle_write"}
    if interrupted_reason:
        payload["reason"] = interrupted_reason
    return payload


def memory_dedupe_agent_is_running() -> bool:
    acquired = MEMORY_DEDUPE_AGENT_WORKER_LOCK.acquire(blocking=False)
    if acquired:
        MEMORY_DEDUPE_AGENT_WORKER_LOCK.release()
        return False
    return True


def memory_refine_agent_is_running() -> bool:
    acquired = MEMORY_REFINE_AGENT_WORKER_LOCK.acquire(blocking=False)
    if acquired:
        MEMORY_REFINE_AGENT_WORKER_LOCK.release()
        return False
    return True


def idle_write_agent_is_running() -> bool:
    acquired = IDLE_AGENT_WORKER_LOCK.acquire(blocking=False)
    if acquired:
        IDLE_AGENT_WORKER_LOCK.release()
        return False
    return True


def current_idle_write_progress() -> Dict[str, object]:
    with connect_db() as conn:
        row = conn.execute(
            """
            SELECT id, status, title, task_type, interrupted_reason, started_at, finished_at, updated_at
            FROM idle_agent_runs
            ORDER BY id DESC
            LIMIT 1
            """
        ).fetchone()
    if row:
        progress = idle_agent_progress_from_status(str(row["status"] or ""), str(row["interrupted_reason"] or ""))
        progress.update(
            {
                "run_id": int(row["id"]),
                "title": str(row["title"] or ""),
                "task_type": str(row["task_type"] or ""),
                "started_at": str(row["started_at"] or ""),
                "finished_at": str(row["finished_at"] or "") if row["finished_at"] else None,
                "updated_at": str(row["updated_at"] or ""),
            }
        )
        return progress
    can_run, reason = idle_agent_can_run(force=False)
    progress = idle_agent_progress_from_reason("idle" if can_run else reason)
    progress["task"] = "idle_write"
    return progress

def current_idle_agent_progress() -> Dict[str, object]:
    watchdog = idle_worker_watchdog_status()
    with connect_db() as conn:
        row = conn.execute(
            """
            SELECT id, status, title, task_type, interrupted_reason, started_at, finished_at, updated_at
            FROM idle_agent_runs
            ORDER BY id DESC
            LIMIT 1
            """
        ).fetchone()
    if row and str(row["status"] or "").lower() in {"running", "writing", "polishing"}:
        progress = idle_agent_progress_from_status(str(row["status"] or ""), str(row["interrupted_reason"] or ""))
        progress.update(
            {
                "run_id": int(row["id"]),
                "title": str(row["title"] or ""),
                "task_type": str(row["task_type"] or ""),
                "started_at": str(row["started_at"] or ""),
                "finished_at": str(row["finished_at"] or "") if row["finished_at"] else None,
                "updated_at": str(row["updated_at"] or ""),
                "watchdog": watchdog,
            }
        )
        return progress
    if memory_dedupe_agent_is_running():
        return {"stage": "memory_dedupe", "label": "记忆去重中", "percent": 45, "task": "memory_dedupe", "watchdog": watchdog}
    if memory_refine_agent_is_running():
        return {"stage": "memory_refine", "label": "记忆精简中", "percent": 48, "task": "memory_refine", "watchdog": watchdog}
    if memory_agent_is_running():
        return {"stage": "memory_agent", "label": "记忆整理中", "percent": 38, "task": "memory_agent", "watchdog": watchdog}
    if idle_write_agent_is_running():
        return {"stage": "writing", "label": "撰写中", "percent": 52, "task": "idle_write", "watchdog": watchdog}
    can_run, reason = idle_agent_can_run(force=False)
    progress = idle_agent_progress_from_reason("idle" if can_run else reason)
    progress["task"] = "idle_worker"
    progress["watchdog"] = watchdog
    if row and progress.get("stage") == "waiting":
        progress.update(
            {
                "last_run_id": int(row["id"]),
                "last_status": str(row["status"] or ""),
                "last_updated_at": str(row["updated_at"] or ""),
            }
        )
    return progress


def list_idle_worker_activity(limit: int = 20, offset: int = 0) -> List[Dict[str, object]]:
    event_types = {
        "idle_worker_tick",
        "idle_worker_tick_done",
        "idle_worker_skip",
        "idle_worker_error",
        "warning_idle_worker_watchdog",
        "opening_cache_idle_refresh",
        "opening_cache_refresh_error",
        "memory_dedupe_agent_run",
        "memory_dedupe_agent_error",
        "memory_refine_agent_run",
        "memory_refine_agent_error",
        "idle_agent_artifact_created",
        "idle_agent_error",
    }
    placeholders = ",".join("?" for _ in event_types)
    max_rows = min(max(int(limit), 1), 501)
    start_row = max(int(offset), 0)
    with connect_db() as conn:
        rows = conn.execute(
            f"""
            SELECT id, event_type, visitor_ip, created_at, metadata_json
            FROM events
            WHERE event_type IN ({placeholders})
            ORDER BY datetime(created_at) DESC, id DESC
            LIMIT ? OFFSET ?
            """,
            (*sorted(event_types), max_rows, start_row),
        ).fetchall()
    return [
        {
            "id": int(row["id"]),
            "event_type": str(row["event_type"]),
            "visitor_ip": str(row["visitor_ip"] or "local"),
            "created_at": str(row["created_at"] or ""),
            "updated_at": str(row["created_at"] or ""),
            "metadata": parse_event_metadata(str(row["metadata_json"] or "{}")),
        }
        for row in rows
    ]


def recent_device_identities_for_opening_cache(limit: int = IDLE_OPENING_CACHE_REFRESH_LIMIT) -> List[str]:
    with connect_db() as conn:
        rows = conn.execute(
            """
            SELECT visitor_ip, MAX(updated_at) AS latest
            FROM curated_memories
            WHERE visitor_ip LIKE 'device:%'
            GROUP BY visitor_ip
            ORDER BY datetime(latest) DESC
            LIMIT ?
            """,
            (max(1, int(limit)),),
        ).fetchall()
    return [str(row["visitor_ip"] or "") for row in rows if is_device_identity(str(row["visitor_ip"] or ""))]


def opening_cache_fixed_refresh_slot(now: Optional[datetime] = None) -> str:
    hours = tuple(IDLE_OPENING_CACHE_FIXED_REFRESH_HOURS)
    if not hours:
        return ""
    tz = local_timezone()
    current = now or datetime.now(tz)
    if current.tzinfo is None:
        current = current.replace(tzinfo=tz)
    else:
        current = current.astimezone(tz)

    due_hours = [hour for hour in hours if current.hour >= hour]
    slot_date = current.date()
    slot_hour = due_hours[-1] if due_hours else hours[-1]
    if not due_hours:
        slot_date = (current - timedelta(days=1)).date()
    return f"{slot_date.isoformat()}T{slot_hour:02d}:00{current.strftime('%z')}"


def run_opening_cache_refresh_once(force: bool = False) -> Dict[str, object]:
    started_at = utc_now()
    started = time.perf_counter()
    fixed_slot = opening_cache_fixed_refresh_slot()
    fixed_due = bool(fixed_slot) and get_app_setting("idle_opening_cache_fixed_refresh_slot", "") != fixed_slot
    if not force:
        last = get_app_setting("idle_opening_cache_refresh_last_at", "")
        age = iso_seconds_ago(last) if last else None
        if not fixed_due and age is not None and age < IDLE_OPENING_CACHE_REFRESH_INTERVAL_SECONDS:
            return {"status": "skipped", "reason": "recent_prompt_cache", "started_at": started_at, "duration_ms": 0.0}
    try:
        devices = recent_device_identities_for_opening_cache()
        refreshed = 0
        for device_id in devices:
            refresh_cached_opening_prompt(device_id)
            refreshed += 1
        set_app_setting("idle_opening_cache_refresh_last_at", utc_now())
        if fixed_due:
            set_app_setting("idle_opening_cache_fixed_refresh_slot", fixed_slot)
        duration_ms = round((time.perf_counter() - started) * 1000, 3)
        result = {
            "status": "completed" if refreshed else "skipped",
            "reason": "fixed_schedule_refreshed" if fixed_due and refreshed else ("refreshed" if refreshed else "no_devices"),
            "device_count": refreshed,
            "refreshed_devices": devices[:10],
            "fixed_refresh_slot": fixed_slot if fixed_due else "",
            "started_at": started_at,
            "duration_ms": duration_ms,
        }
        record_event(None, "opening_cache_idle_refresh", "local", result)
        return result
    except Exception as exc:
        duration_ms = round((time.perf_counter() - started) * 1000, 3)
        result = {"status": "failed", "reason": "error", "error": str(exc), "started_at": started_at, "duration_ms": duration_ms}
        record_event(None, "opening_cache_refresh_error", "local", result)
        return result


def artifact_memory_text(
    artifact_id: int,
    title: str,
    artifact_type: str,
    content: str,
    series_title: str = "",
    episode_index: Optional[int] = None,
    summary: str = "",
) -> str:
    clean_title = normalize_idle_artifact_terms(title).strip()
    clean_type = normalize_idle_artifact_terms(artifact_type).strip()
    clean_content = normalize_idle_artifact_content_text(content)
    clean_summary = normalize_idle_artifact_terms(summary)
    series = normalize_idle_artifact_terms(series_title).strip()
    episode_text = f"第 {int(episode_index)} 集" if episode_index is not None else ""
    short_summary = clean_summary.strip() or compact_idle_artifact_content(clean_content, 220)
    parts = [
        f"作品记忆：已创作成果 #{artifact_id}《{clean_title or '未命名成果'}》。",
        f"类型：{clean_type or 'other'}。",
    ]
    if series:
        parts.append(f"系列：{series}。")
    if episode_text:
        parts.append(f"进度：{episode_text}。")
    if short_summary:
        parts.append(f"摘要：{short_summary}")
    return "".join(parts)


def create_artifact_memory(
    artifact_id: int,
    title: str,
    artifact_type: str,
    content: str,
    series_title: str = "",
    episode_index: Optional[int] = None,
    summary: str = "",
) -> int:
    text = artifact_memory_text(
        artifact_id,
        title,
        artifact_type,
        content,
        series_title=series_title,
        episode_index=episode_index,
        summary=summary,
    )
    memory_id = save_curated_memory(
        source_session_id=f"artifact-{int(artifact_id)}",
        start_message_id=int(artifact_id),
        end_message_id=int(artifact_id),
        content=text,
        importance_label="artifact",
        confidence=0.85,
    )
    vector = embedding_client.embed_text(text)
    upsert_curated_memory_vector(memory_id, vector, embedding_client.EMBEDDING_MODEL)
    return memory_id


PREQUEL_ARTIFACT_MARKERS = (
    "前传",
    "外传",
    "番外",
    "起源",
    "过去篇",
    "特别篇",
    "origin",
    "prequel",
)


def is_prequel_idle_artifact(title: str, content: str = "") -> bool:
    text = f"{title}\n{content}".lower()
    return any(marker.lower() in text for marker in PREQUEL_ARTIFACT_MARKERS)


def current_series_mainline_episode(series_title: str) -> int:
    clean_series = normalize_idle_artifact_terms(series_title).strip()
    if not clean_series:
        return 0
    with connect_db() as conn:
        row = conn.execute(
            """
            SELECT MAX(episode_index) AS max_episode
            FROM idle_agent_artifacts
            WHERE series_title = ?
              AND episode_index IS NOT NULL
            """,
            (clean_series,),
        ).fetchone()
    return int(row["max_episode"] or 0) if row else 0


def resolve_idle_series_episode_index(
    series_title: str,
    requested_episode: object,
    title: str = "",
    content: str = "",
) -> Optional[int]:
    clean_series = normalize_idle_artifact_terms(series_title).strip()
    if not clean_series:
        return None
    if is_prequel_idle_artifact(title, content):
        return None
    current_episode = current_series_mainline_episode(clean_series)
    next_episode = current_episode + 1
    try:
        requested = int(requested_episode) if requested_episode not in (None, "", "null") else None
    except Exception:
        requested = None
    if requested == next_episode:
        return requested
    return next_episode


def renumber_idle_series_mainline_episodes(series_title: str) -> Dict[str, int]:
    clean_series = normalize_idle_artifact_terms(series_title).strip()
    if not clean_series:
        return {"updated": 0}
    updated_ids: List[int] = []
    with connect_db() as conn:
        rows = conn.execute(
            """
            SELECT id
            FROM idle_agent_artifacts
            WHERE series_title = ?
              AND episode_index IS NOT NULL
            ORDER BY created_at ASC, id ASC
            """,
            (clean_series,),
        ).fetchall()
        updated = 0
        for index, row in enumerate(rows, start=1):
            cur = conn.execute(
                """
                UPDATE idle_agent_artifacts
                SET episode_index = ?
                WHERE id = ?
                  AND COALESCE(episode_index, -1) != ?
                """,
                (index, int(row["id"]), index),
            )
            if cur.rowcount:
                updated += int(cur.rowcount or 0)
                updated_ids.append(int(row["id"]))
    reindexed = 0
    for artifact_id in updated_ids:
        try:
            index_idle_agent_artifact(artifact_id)
            reindexed += 1
        except Exception as exc:
            record_event(None, "idle_artifact_index_error", "local", {
                "artifact_id": artifact_id,
                "error": str(exc),
            })
    return {"updated": updated, "reindexed": reindexed, "total": len(rows)}


def save_idle_agent_artifact(
    run_id: int,
    title: str,
    artifact_type: str,
    content: str,
    series_title: str = "",
    episode_index: Optional[int] = None,
    summary: str = "",
) -> int:
    clean_title = normalize_idle_artifact_terms(title)
    clean_series = normalize_idle_artifact_terms(series_title)
    clean_summary = normalize_idle_artifact_terms(summary)
    text = normalize_idle_artifact_content_text(content).strip()
    clean_type = normalize_artifact_type(artifact_type, clean_title, text)
    if not text:
        raise ValueError("idle artifact content is empty")
    artifact_id = 0
    series_value = clean_series.strip() or None
    episode_value = resolve_idle_series_episode_index(
        series_value or "",
        episode_index,
        title=clean_title,
        content=text,
    )
    summary_value = clean_summary.strip() or compact_idle_artifact_content(text, 260)
    with connect_db() as conn:
        cur = conn.execute(
            """
            INSERT INTO idle_agent_artifacts (
                run_id, title, artifact_type, content,
                series_title, episode_index, summary, created_at
            )
            VALUES (?, ?, ?, ?, ?, ?, ?, ?)
            """,
            (
                int(run_id),
                clean_title.strip() or "未命名成果",
                clean_type or "other",
                text,
                series_value,
                episode_value,
                summary_value,
                utc_now(),
            ),
        )
        artifact_id = int(cur.lastrowid)
    try:
        index_idle_agent_artifact(artifact_id)
    except Exception as exc:
        record_event(None, "idle_artifact_index_error", "local", {
            "artifact_id": artifact_id,
            "error": str(exc),
        })
    return artifact_id


def compact_idle_artifact_content(content: str, max_chars: int) -> str:
    text = " ".join(content.strip().split())
    if not text:
        return ""
    pieces = re.split(r"(?<=[。！？.!?])\s*", text)
    seen = set()
    selected: List[str] = []
    total = 0
    for piece in pieces:
        clean = piece.strip()
        if not clean:
            continue
        key = clean[:120]
        if key in seen:
            continue
        seen.add(key)
        if total + len(clean) > max_chars and selected:
            break
        selected.append(clean)
        total += len(clean)
    body = "".join(selected).strip() if selected else text
    if len(body) > max_chars:
        body = body[:max_chars].rstrip() + "..."
    return body


def load_idle_artifact_term_replacements() -> Dict[str, str]:
    replacements: Dict[str, str] = {}
    replacements.update(DEFAULT_IDLE_ARTIFACT_TERM_REPLACEMENTS)

    def merge_payload(payload: object) -> None:
        if not isinstance(payload, dict):
            return
        for source, target in payload.items():
            source_text = str(source).strip()
            target_text = str(target).strip()
            if source_text and target_text:
                replacements[source_text] = target_text

    if IDLE_ARTIFACT_TERM_REPLACEMENTS_FILE:
        try:
            payload = json.loads(Path(IDLE_ARTIFACT_TERM_REPLACEMENTS_FILE).read_text(encoding="utf-8"))
            merge_payload(payload)
        except Exception:
            pass
    if IDLE_ARTIFACT_TERM_REPLACEMENTS:
        try:
            payload = json.loads(IDLE_ARTIFACT_TERM_REPLACEMENTS)
            merge_payload(payload)
        except Exception:
            pass
    return replacements


def replace_idle_artifact_terms(text: str, replacements: Dict[str, str]) -> str:
    if not isinstance(text, str):
        return ""
    normalized = text
    for source, target in sorted(replacements.items(), key=lambda item: len(item[0]), reverse=True):
        normalized = re.sub(re.escape(source), target, normalized, flags=re.I)
    return normalized


def strip_idle_artifact_unicode_noise(text: str) -> str:
    if not isinstance(text, str):
        return ""
    cleaned = text.replace("\ufffd", "")
    cleaned = re.sub(r"[\x00-\x08\x0b\x0c\x0e-\x1f\x7f]", "", cleaned)
    for match in re.finditer(r"(?:\\u[0-9a-fA-F]{4}){3,}", cleaned):
        run = match.group(0).lower()
        if "\\ufffd" in run or re.search(r"\\u00(?:0[0-8bcef]|1[0-9a-f]|7f)", run):
            return cleaned[: match.start()].rstrip()
    cleaned = re.sub(r"\\ufffd", "", cleaned, flags=re.I)
    cleaned = re.sub(r"\\u00(?:0[0-8bcef]|1[0-9a-f]|7f)", "", cleaned, flags=re.I)
    return cleaned


def unescape_idle_artifact_markdown_marks(text: str) -> str:
    if not isinstance(text, str):
        return ""
    return re.sub(r"\\+([*_~`#\[\]\(\)>-])", r"\1", text)


def normalize_idle_artifact_terms(text: str) -> str:
    replaced = replace_idle_artifact_terms(text, load_idle_artifact_term_replacements())
    return strip_idle_artifact_unicode_noise(replaced)


def normalize_idle_artifact_content_text(text: str) -> str:
    normalized = normalize_idle_artifact_terms(text)
    return unescape_idle_artifact_markdown_marks(normalized)


class TermReplacementStreamFilter:
    def __init__(self) -> None:
        self.replacements = load_idle_artifact_term_replacements()
        self.keep_chars = max((len(key) for key in self.replacements), default=1) - 1
        self.buffer = ""

    def feed(self, text: str) -> str:
        if not text:
            return ""
        self.buffer += text
        if self.keep_chars <= 0:
            chunk, self.buffer = self.buffer, ""
            return replace_idle_artifact_terms(chunk, self.replacements)
        if len(self.buffer) <= self.keep_chars:
            return ""
        chunk = self.buffer[:-self.keep_chars]
        self.buffer = self.buffer[-self.keep_chars:]
        return replace_idle_artifact_terms(chunk, self.replacements)

    def flush(self) -> str:
        chunk, self.buffer = self.buffer, ""
        return replace_idle_artifact_terms(chunk, self.replacements)


def format_idle_artifact_index_text(
    title: str,
    artifact_type: str,
    content: str,
    series_title: str = "",
    episode_index: Optional[int] = None,
    summary: str = "",
) -> str:
    body = compact_idle_artifact_content(content, 1600)
    series_line = f"系列：{series_title.strip()}\n" if series_title and series_title.strip() else ""
    episode_line = f"集数：{int(episode_index)}\n" if episode_index is not None else ""
    summary_line = f"摘要：{summary.strip()}\n" if summary and summary.strip() else ""
    return (
        f"标题：{title.strip() or '未命名成果'}\n"
        f"类型：{artifact_type.strip() or 'other'}\n"
        f"{series_line}"
        f"{episode_line}"
        f"{summary_line}"
        f"内容摘要：{body}"
    )


def index_idle_agent_artifact(artifact_id: int) -> None:
    with connect_db() as conn:
        row = conn.execute(
            """
            SELECT id, title, artifact_type, content, series_title, episode_index, summary
            FROM idle_agent_artifacts
            WHERE id = ?
            """,
            (int(artifact_id),),
        ).fetchone()
    if row is None:
        raise ValueError(f"idle artifact not found: {artifact_id}")

    index_text = format_idle_artifact_index_text(
        str(row["title"]),
        str(row["artifact_type"]),
        str(row["content"]),
        str(row["series_title"] or ""),
        int(row["episode_index"]) if row["episode_index"] is not None else None,
        str(row["summary"] or ""),
    )
    vector = embedding_client.embed_text(index_text)
    upsert_idle_artifact_vector(int(row["id"]), vector, embedding_client.EMBEDDING_MODEL, index_text)


def upsert_idle_artifact_vector(
    artifact_id: int,
    vector: object,
    model_name: str,
    index_text: str,
) -> None:
    arr = vector_memory.normalize_vector(vector)
    with connect_db() as conn:
        conn.execute(
            """
            INSERT INTO idle_artifact_vectors (
                artifact_id, dim, vector, model_name, index_text, created_at
            )
            VALUES (?, ?, ?, ?, ?, ?)
            ON CONFLICT(artifact_id) DO UPDATE SET
                dim = excluded.dim,
                vector = excluded.vector,
                model_name = excluded.model_name,
                index_text = excluded.index_text,
                created_at = excluded.created_at
            """,
            (
                int(artifact_id),
                int(arr.shape[0]),
                arr.tobytes(),
                model_name,
                index_text,
                utc_now(),
            ),
        )


def retrieve_idle_artifacts(query_vector: object) -> List[Dict[str, object]]:
    query = vector_memory.normalize_vector(query_vector)
    with connect_db() as conn:
        rows = conn.execute(
            """
            SELECT a.id, a.title, a.artifact_type, a.content,
                   a.series_title, a.episode_index, a.summary, a.created_at,
                   v.dim, v.vector, v.model_name
            FROM idle_agent_artifacts a
            JOIN idle_artifact_vectors v ON v.artifact_id = a.id
            ORDER BY a.id ASC
            """
        ).fetchall()

    scored: List[Dict[str, object]] = []
    for row in rows:
        vector = vector_memory.blob_to_vector(row["vector"], int(row["dim"]))
        if vector.shape != query.shape:
            continue
        score = float(vector.dot(query))
        if score < IDLE_ARTIFACT_MIN_SCORE:
            continue
        scored.append(
            {
                "id": int(row["id"]),
                "title": str(row["title"]),
                "artifact_type": str(row["artifact_type"]),
                "content": str(row["content"]),
                "series_title": str(row["series_title"] or ""),
                "episode_index": int(row["episode_index"]) if row["episode_index"] is not None else None,
                "summary": str(row["summary"] or ""),
                "created_at": str(row["created_at"]),
                "score": score,
            }
        )
    scored.sort(key=lambda item: (-float(item["score"]), int(item["id"])))
    return scored[:IDLE_ARTIFACT_TOP_K]


def format_idle_artifact_context(artifacts: List[Dict[str, object]]) -> str:
    if not artifacts:
        return ""
    lines = [
        "以下是模型空闲时创作过的成果，仅在当前话题相关时参考。",
        "不要强行复述作品；可以用它们作为设定、角色、风格或前文创作的线索。",
        "",
    ]
    for index, item in enumerate(artifacts, start=1):
        content = str(item.get("summary") or "").strip()
        if not content:
            content = compact_idle_artifact_content(str(item["content"]), IDLE_ARTIFACT_CONTEXT_CHARS)
        lines.append(
            f"[空闲创作成果 {index}] score={float(item['score']):.3f} "
            f"type={item['artifact_type']} title={item['title']} "
            f"series={item.get('series_title') or '-'} episode={item.get('episode_index') or '-'}"
        )
        lines.append(content)
        lines.append("")
    return "\n".join(lines).strip()


def backfill_idle_artifact_vectors(limit: int = 10000) -> Dict[str, int]:
    max_rows = min(max(int(limit), 1), 100000)
    with connect_db() as conn:
        rows = conn.execute(
            """
            SELECT a.id
            FROM idle_agent_artifacts a
            LEFT JOIN idle_artifact_vectors v ON v.artifact_id = a.id
            WHERE v.artifact_id IS NULL
            ORDER BY a.id ASC
            LIMIT ?
            """,
            (max_rows,),
        ).fetchall()

    indexed = 0
    failed = 0
    for row in rows:
        try:
            index_idle_agent_artifact(int(row["id"]))
            indexed += 1
        except Exception:
            failed += 1
    return {"indexed": indexed, "failed": failed}


def load_idle_series_context(
    max_series: int = IDLE_SERIES_CONTEXT_MAX_SERIES,
    max_episodes: int = IDLE_SERIES_CONTEXT_MAX_EPISODES,
) -> List[Dict[str, object]]:
    series_limit = min(max(int(max_series), 1), 12)
    episode_limit = min(max(int(max_episodes), 1), 8)
    with connect_db() as conn:
        series_rows = conn.execute(
            """
            SELECT series_title,
                   COUNT(*) AS total_count,
                   MAX(COALESCE(episode_index, 0)) AS max_episode,
                   MAX(id) AS newest_id
            FROM idle_agent_artifacts
            WHERE series_title IS NOT NULL
              AND TRIM(series_title) != ''
            GROUP BY series_title
            ORDER BY newest_id DESC
            LIMIT ?
            """,
            (series_limit,),
        ).fetchall()
        contexts: List[Dict[str, object]] = []
        for row in series_rows:
            series_title = str(row["series_title"])
            episode_rows = conn.execute(
                """
                SELECT id, title, episode_index, summary, content, created_at
                FROM idle_agent_artifacts
                WHERE series_title = ?
                ORDER BY
                    CASE WHEN episode_index IS NULL THEN 1 ELSE 0 END,
                    episode_index DESC,
                    id DESC
                LIMIT ?
                """,
                (series_title, episode_limit),
            ).fetchall()
            episode_items = [row_to_dict(item) for item in episode_rows]
            episode_items.sort(
                key=lambda item: (
                    1 if item.get("episode_index") is None else 0,
                    int(item.get("episode_index") or 0),
                    int(item.get("id") or 0),
                )
            )
            contexts.append(
                {
                    "series_title": series_title,
                    "total_count": int(row["total_count"] or 0),
                    "max_episode": int(row["max_episode"] or 0),
                    "episodes": episode_items,
                }
            )
    return contexts


def load_idle_series_catalog(limit: int = IDLE_SERIES_PLANNER_MAX_CATALOG) -> List[Dict[str, object]]:
    max_rows = max(1, min(int(limit), 200))
    with connect_db() as conn:
        series_rows = conn.execute(
            """
            SELECT series_title,
                   COUNT(*) AS total_count,
                   MAX(COALESCE(episode_index, 0)) AS max_episode,
                   MAX(id) AS newest_id
            FROM idle_agent_artifacts
            WHERE series_title IS NOT NULL
              AND TRIM(series_title) != ''
            GROUP BY series_title
            ORDER BY newest_id DESC
            LIMIT ?
            """,
            (max_rows,),
        ).fetchall()
        catalog: List[Dict[str, object]] = []
        for row in series_rows:
            title = str(row["series_title"] or "").strip()
            latest = conn.execute(
                """
                SELECT id, title, summary, created_at
                FROM idle_agent_artifacts
                WHERE series_title = ?
                ORDER BY id DESC
                LIMIT 1
                """,
                (title,),
            ).fetchone()
            catalog.append(
                {
                    "series_title": title,
                    "total_count": int(row["total_count"] or 0),
                    "max_episode": int(row["max_episode"] or 0),
                    "newest_id": int(row["newest_id"] or 0),
                    "latest_title": str(latest["title"] or "") if latest else "",
                    "latest_summary": str(latest["summary"] or "") if latest else "",
                    "latest_created_at": str(latest["created_at"] or "") if latest else "",
                }
            )
    return catalog


def idle_series_candidate_titles(custom_prompt: str, catalog: List[Dict[str, object]]) -> List[str]:
    focus = normalize_idle_artifact_terms(custom_prompt or "")
    quoted_titles = [item.strip() for item in re.findall(r"《([^》]{1,120})》", focus) if item.strip()]
    directive = idle_series_directive_from_prompt(focus)
    selected: List[str] = []

    def add(title: str) -> None:
        clean = canonical_idle_series_title(title)
        if clean and clean not in selected:
            selected.append(clean)

    if directive.get("explicit_series"):
        add(str(directive.get("series_title") or ""))
    for item in catalog:
        title = str(item.get("series_title") or "").strip()
        if not title:
            continue
        canonical = canonical_idle_series_title(title)
        if canonical in focus or any(quoted and (quoted in canonical or canonical in quoted) for quoted in quoted_titles):
            add(title)
    return selected[: max(1, IDLE_SERIES_PLANNER_MAX_FULL_SERIES)]


def load_complete_idle_series_works(series_titles: List[str]) -> Dict[str, List[Dict[str, object]]]:
    result: Dict[str, List[Dict[str, object]]] = {}
    clean_titles = [canonical_idle_series_title(item) for item in series_titles if str(item or "").strip()]
    if not clean_titles:
        return result
    with connect_db() as conn:
        for title in clean_titles:
            variants = idle_series_title_variants(title) or [title]
            in_clause, params = sql_in_clause_params(variants)
            rows = conn.execute(
                f"""
                SELECT id, title, artifact_type, series_title, episode_index, summary, content, created_at
                FROM idle_agent_artifacts
                WHERE series_title IN {in_clause}
                   OR series_title LIKE ?
                   OR (TRIM(COALESCE(series_title, '')) = '' AND title LIKE ?)
                ORDER BY
                    CASE WHEN episode_index IS NULL THEN 1 ELSE 0 END,
                    COALESCE(episode_index, id) ASC,
                    id ASC
                """,
                (*params, f"{title}·%", f"%{title}%"),
            ).fetchall()
            result[title] = [row_to_dict(row) for row in rows]
    return result


def format_complete_idle_series_works(series_works: Dict[str, List[Dict[str, object]]]) -> str:
    if not series_works:
        return "无完整系列正文。"
    lines = [
        "同系列全部前序作品：",
        "以下内容供剧情规划 agent 阅读并分析发展状况；如果本轮不续写对应系列，不要把这些旧作品当成写作任务。",
    ]
    for series_title, rows in series_works.items():
        lines.append("")
        lines.append(f"## 系列《{series_title}》：共 {len(rows)} 篇")
        for row in rows:
            episode_index = row.get("episode_index")
            episode = f"第 {int(episode_index)} 集" if episode_index is not None else "前传/番外/外传/独立篇"
            lines.append("")
            lines.append(f"### {episode} #{row.get('id')}《{row.get('title') or '未命名成果'}》")
            if row.get("summary"):
                lines.append(f"摘要：{row.get('summary')}")
            lines.append(f"正文：{row.get('content') or ''}")
    return "\n".join(lines).strip()


def build_idle_series_planner_context(
    custom_prompt: str,
    catalog: List[Dict[str, object]],
    series_works: Dict[str, List[Dict[str, object]]],
) -> str:
    lines = [
        "用户配置创作 prompt：",
        custom_prompt.strip() or "（无）",
        "",
        "可用系列目录：",
    ]
    if catalog:
        for item in catalog:
            lines.append(
                f"- 《{item['series_title']}》 total={item['total_count']} "
                f"max_episode={item['max_episode']} newest=#{item['newest_id']} "
                f"latest={item['latest_title'] or '未命名'} summary={item['latest_summary'] or ''}"
            )
    else:
        lines.append("（当前没有已登记系列）")
    lines.append("")
    lines.append(format_complete_idle_series_works(series_works))
    return "\n".join(lines).strip()


def default_idle_series_plan(reason: str = "") -> Dict[str, object]:
    return {
        "use_series": False,
        "series_title": "",
        "episode_policy": "new",
        "next_episode_index": None,
        "target_episode_count": None,
        "release_prompt_after_this": False,
        "title_idea": "",
        "intent": "",
        "must_obey": [],
        "candidate_characters": [],
        "setting_plan": "",
        "beats": [],
        "anti_repetition_strategy": "",
        "image_plan_brief": "",
        "reason": reason,
    }


def parse_idle_series_planner_response(text: str) -> Dict[str, object]:
    cleaned = str(text or "").strip()
    if cleaned.startswith("```"):
        cleaned = re.sub(r"^```(?:json)?\s*", "", cleaned)
        cleaned = re.sub(r"\s*```$", "", cleaned)
    candidates = [cleaned]
    match = re.search(r"\{.*\}", cleaned, flags=re.S)
    if match:
        candidates.append(match.group(0))
    for candidate in candidates:
        try:
            payload = json.loads(candidate, strict=False)
        except Exception:
            continue
        if isinstance(payload, dict):
            plan = default_idle_series_plan()
            plan.update(
                {
                    "use_series": bool(payload.get("use_series")),
                    "series_title": normalize_idle_artifact_terms(str(payload.get("series_title") or "")).strip(),
                    "episode_policy": str(payload.get("episode_policy") or "new").strip() or "new",
                    "release_prompt_after_this": bool(payload.get("release_prompt_after_this")),
                    "title_idea": str(payload.get("title_idea") or "").strip(),
                    "intent": str(payload.get("intent") or "").strip(),
                    "setting_plan": str(payload.get("setting_plan") or "").strip(),
                    "anti_repetition_strategy": str(payload.get("anti_repetition_strategy") or "").strip(),
                    "image_plan_brief": str(payload.get("image_plan_brief") or "").strip(),
                    "reason": str(payload.get("reason") or "").strip(),
                }
            )
            try:
                plan["next_episode_index"] = (
                    int(payload.get("next_episode_index"))
                    if payload.get("next_episode_index") not in (None, "", "null")
                    else None
                )
            except Exception:
                plan["next_episode_index"] = None
            try:
                plan["target_episode_count"] = (
                    int(payload.get("target_episode_count"))
                    if payload.get("target_episode_count") not in (None, "", "null")
                    else None
                )
            except Exception:
                plan["target_episode_count"] = None
            for key in ("must_obey", "candidate_characters", "beats"):
                value = payload.get(key)
                if isinstance(value, list):
                    plan[key] = [str(item).strip() for item in value if str(item).strip()]
                elif isinstance(value, str) and value.strip():
                    plan[key] = [value.strip()]
            return plan
    return default_idle_series_plan("planner_invalid_json")


def call_idle_series_planner_model(context: str) -> Dict[str, object]:
    client, http_client, model_slot = openai_client_for_slot(MODEL_SLOT_BACKGROUND, timeout=IDLE_SERIES_PLANNER_TIMEOUT)
    try:
        resp = client.chat.completions.create(
            **model_completion_kwargs(model_slot),
            messages=[
                {"role": "system", "content": IDLE_SERIES_PLANNER_SYSTEM_PROMPT},
                {"role": "user", "content": context},
            ],
            temperature=IDLE_SERIES_PLANNER_TEMPERATURE,
            top_p=IDLE_SERIES_PLANNER_TOP_P,
            max_tokens=IDLE_SERIES_PLANNER_MAX_TOKENS,
        )
        _, answer = split_think_text(resp.choices[0].message.content or "")
        return parse_idle_series_planner_response(answer)
    finally:
        http_client.close()


def idle_series_plan_for_prompt(custom_prompt: str) -> Dict[str, object]:
    if not IDLE_SERIES_PLANNER_ENABLED or not custom_prompt.strip():
        return default_idle_series_plan("no_custom_prompt")
    directive = idle_series_directive_from_prompt(custom_prompt)
    target_count = directive.get("target_count")
    directive_title = canonical_idle_series_title(directive.get("series_title"))
    if directive_title and target_count:
        status = idle_series_status(directive_title)
        if int(status.get("max_episode") or 0) >= int(target_count) or int(status.get("total_count") or 0) >= int(target_count):
            plan = default_idle_series_plan("series_target_reached")
            plan.update(
                {
                    "use_series": False,
                    "series_title": directive_title,
                    "target_episode_count": int(target_count),
                    "release_prompt_after_this": True,
                    "reason": f"系列《{directive_title}》已达到用户要求的 {int(target_count)} 篇，停止继续写作该 prompt。",
                }
            )
            record_event(None, "idle_series_planner_result", "local", {"candidate_series": [directive_title], "plan": plan})
            return plan
    catalog = load_idle_series_catalog()
    candidate_titles = idle_series_candidate_titles(custom_prompt, catalog)
    series_works = load_complete_idle_series_works(candidate_titles)
    context = build_idle_series_planner_context(custom_prompt, catalog, series_works)
    try:
        plan = call_idle_series_planner_model(context)
    except Exception as exc:
        plan = default_idle_series_plan(f"planner_error: {exc}")
        record_event(None, "idle_series_planner_error", "local", {"error": str(exc)})
    if plan.get("use_series") and not plan.get("series_title") and candidate_titles:
        plan["series_title"] = candidate_titles[0]
    planned_title = str(plan.get("series_title") or "").strip()
    if plan.get("use_series") and planned_title and planned_title not in series_works:
        series_works = load_complete_idle_series_works([planned_title])
        context = build_idle_series_planner_context(custom_prompt, catalog, series_works)
        try:
            plan = call_idle_series_planner_model(context)
            if plan.get("use_series") and not plan.get("series_title"):
                plan["series_title"] = planned_title
        except Exception as exc:
            record_event(None, "idle_series_planner_second_pass_error", "local", {"error": str(exc), "series_title": planned_title})
    if directive.get("explicit_series"):
        plan = apply_idle_series_directive_to_plan(plan, directive)
    record_event(
        None,
        "idle_series_planner_result",
        "local",
        {
            "candidate_series": candidate_titles,
            "plan": plan,
        },
    )
    return plan


def format_idle_series_plan_context(plan: Dict[str, object]) -> str:
    if not plan or str(plan.get("reason") or "") == "no_custom_prompt":
        return ""
    if not plan.get("use_series") and str(plan.get("reason") or "").startswith(("planner_error", "planner_invalid")):
        return ""
    lines = [
        "剧情规划 agent 结果：",
        f"use_series={bool(plan.get('use_series'))}",
        f"series_title={plan.get('series_title') or ''}",
        f"episode_policy={plan.get('episode_policy') or 'new'}",
        f"next_episode_index={plan.get('next_episode_index')}",
        f"target_episode_count={plan.get('target_episode_count')}",
        f"release_prompt_after_this={bool(plan.get('release_prompt_after_this'))}",
    ]
    if plan.get("use_series") and plan.get("series_title"):
        lines.extend(
            [
                "系列命名与编号硬约束：",
                f"- series_title 必须精确输出为：{plan.get('series_title')}",
                "- 不要给 series_title 增减书名号、空格、副标题、Dating/日记/观察等别名。",
                "- title 可以有本集副标题，但必须服从规划的 next_episode_index，不要自行重排、跳号或复用旧编号。",
            ]
        )
    for key, label in (
        ("title_idea", "标题方向"),
        ("intent", "表达意图"),
        ("setting_plan", "场景计划"),
        ("anti_repetition_strategy", "结构避重复策略"),
        ("image_plan_brief", "配图方向"),
        ("reason", "规划理由"),
    ):
        value = str(plan.get(key) or "").strip()
        if value:
            lines.append(f"{label}：{value}")
    for key, label in (
        ("must_obey", "必须执行的创作 prompt 要求"),
        ("candidate_characters", "候选出场人物"),
        ("beats", "剧情节拍"),
    ):
        values = [str(item).strip() for item in plan.get(key) or [] if str(item).strip()]
        if values:
            lines.append(f"{label}：")
            for item in values:
                lines.append(f"- {item}")
    return "\n".join(lines).strip()


def format_idle_series_context(series_context: List[Dict[str, object]]) -> str:
    if not series_context:
        return ""
    lines = [
        "已有连续系列资料：",
        "只有在本篇确实需要续写时才使用；不要因为这里出现某个系列就默认续写它。",
        "如果选择续写其中某个系列，必须先承接以下前情；主线 episode_index 只能使用提示中的下一集编号。",
        "前传、番外、起源故事可以丰富人物过去，但 episode_index 必须填 null，避免污染主线编号。",
        "如果不续写某系列，以下资料仅用于避开重复题材、重复场景和重复对白。",
    ]
    for series in series_context:
        title = str(series.get("series_title") or "").strip()
        max_episode = int(series.get("max_episode") or 0)
        next_episode = max_episode + 1
        total_count = int(series.get("total_count") or 0)
        lines.append("")
        lines.append(
            f"系列《{title}》：已有作品 {total_count} 个，主线最大集数 {max_episode}；"
            f"如果续写主线，episode_index 下一集必须填写 {next_episode}。"
        )
        lines.append("近期剧情目录（只用于判断是否真的需要续写；不要模仿这些作品的开场、场景、笑点或句式）：")
        episodes = list(series.get("episodes") or [])
        omitted = max(0, total_count - len(episodes))
        if omitted:
            lines.append(f"- 已省略更早的 {omitted} 条旧摘要，避免旧桥段过度污染本篇。")
        for item in episodes:
            episode_index = item.get("episode_index")
            episode = f"第 {int(episode_index)} 集" if episode_index is not None else "前传/番外"
            summary = str(item.get("summary") or "").strip() or compact_idle_artifact_content(
                str(item.get("content") or ""),
                160,
            )
            lines.append(
                f"- {episode} #{item.get('id')}《{item.get('title') or '未命名成果'}》："
                f"{compact_idle_artifact_content(summary, 90)}"
            )
        recent = episodes[-IDLE_SERIES_CONTEXT_RECENT_CONTENT:]
        if recent:
            lines.append("最近细节片段（用于衔接角色状态和伏笔，不要原样复读）：")
            for item in recent:
                episode_index = item.get("episode_index")
                episode = f"第 {int(episode_index)} 集" if episode_index is not None else "前传/番外"
                content = compact_idle_artifact_content(
                    str(item.get("content") or ""),
                    IDLE_SERIES_CONTEXT_RECENT_CHARS,
                )
                if content:
                    lines.append(f"[{episode} #{item.get('id')}] {content}")
    return "\n".join(lines)


def recent_idle_artifact_repetition_context(limit: int = 10) -> str:
    max_rows = max(1, min(int(limit), 20))
    with connect_db() as conn:
        rows = conn.execute(
            """
            SELECT id, title, artifact_type, series_title, episode_index, summary, content, created_at
            FROM idle_agent_artifacts
            ORDER BY id DESC
            LIMIT ?
            """,
            (max_rows,),
        ).fetchall()
    if not rows:
        return ""
    lines = [
        "近期成果结构参考：",
        "以下内容只用于识别近期已经写过的叙事骨架，不是禁用清单，也不是续写要求。",
        "可以续写同一系列或使用同一角色，但不能复制同一套场景功能、人物功能、对白功能、冲突解法和结尾功能。",
        "如果创作 prompt 明确要求某个地点、系列、角色或题材，必须执行 prompt；避重复只负责提醒你换一种写法，而不是取消 prompt。",
    ]
    for row in rows:
        episode = f" 第{row['episode_index']}集" if row["episode_index"] is not None else ""
        series = f"《{row['series_title']}》" if row["series_title"] else ""
        summary = compact_idle_artifact_content(str(row["summary"] or row["content"] or ""), 120)
        lines.append(f"- #{row['id']} {series}{episode} {row['title'] or '未命名成果'}：{summary}")
    return "\n".join(lines).strip()


def idle_recent_repetition_flags_from_rows(rows: List[sqlite3.Row]) -> List[str]:
    repeated_flags: List[str] = []
    for row in rows:
        text = f"{row['title'] or ''}\n{row['summary'] or ''}\n{row['content'] or ''}"
        for phrase in (
            "空气动力学阻力",
            "这种风格的衣服",
            "显影咖啡厅",
            "咖啡厅",
            "理工男",
            "约会实验",
            "非理性偏差实验",
            "城市心跳",
            "观念约会",
            "活着的装置",
            "艺术学院",
            "新维利亚",
        ):
            if phrase in text and phrase not in repeated_flags:
                repeated_flags.append(phrase)
    return repeated_flags


def idle_recent_repetition_flags(limit: int = 10) -> List[str]:
    max_rows = max(1, min(int(limit), 20))
    with connect_db() as conn:
        rows = conn.execute(
            """
            SELECT title, summary, content
            FROM idle_agent_artifacts
            ORDER BY id DESC
            LIMIT ?
            """,
            (max_rows,),
        ).fetchall()
    return idle_recent_repetition_flags_from_rows(rows)


def idle_story_pattern_variation_context(limit: int = 10) -> str:
    max_rows = max(1, min(int(limit), 20))
    with connect_db() as conn:
        rows = conn.execute(
            """
            SELECT id, title, summary
            FROM idle_agent_artifacts
            ORDER BY id DESC
            LIMIT ?
            """,
            (max_rows,),
        ).fetchall()
    if not rows:
        return ""
    lines = [
        "叙事变体要求：",
        "创作 prompt 是硬约束；变体要求只解决“不要把同一个故事换名重写”的问题，不能取消 prompt 指定的地点、系列、角色或题材。",
        "如果继续同一题材或同一系列，至少改变其中两到三项：叙述视角、人物关系位置、场景的社会功能、事件触发方式、主角主动选择、对白节奏、结尾余味、配图重点。",
        "不要只替换名词。真正的变体应让人物想要的东西、误会来源、行动路径或最后付出的代价发生变化。",
        "如果是约会、社交或角色互动题材，互动对象必须是一个有自己目标和困境的人，而不是负责评估主角、解释设定或抛出概念问题的功能装置。",
        "人物关系要从具体动作推进，而不是靠旁白宣布。让角色做事、等待、寻找、帮忙、拒绝、改变主意、承担后果。",
        "不要把故事写成“通过 A 与 B 的碰撞探讨 C”的命题作文；先让人物处理一件具体事情，再让意义从行动里自然露出来。",
        "职业、能力和世界观设定只负责制造具体处境，不负责输出术语或概念。人物要先像人一样说话和行动。",
        "抽象词可以出现在诗歌或设定里；叙事类作品不要用抽象概念代替角色正在经历的事。",
        "近期成果目录，仅用于识别已经出现过的骨架：",
    ]
    for row in rows:
        lines.append(f"- #{row['id']} {row['title'] or '未命名成果'}")
    return "\n".join(lines).strip()


def idle_final_quality_gate_context() -> str:
    return "\n".join(
        [
            "最终质量闸门：",
            "第一优先级：检查是否完整执行用户配置的创作 prompt。prompt 指定的地点、系列、人物、关系、体裁和事件不能被质量闸门取消。",
            "第二优先级：检查是否把旧作品的完整功能骨架复制了一遍。如果只是换名、换物件、换一句笑点，必须重写结构，而不是润色措辞。",
            "第三优先级：检查作品类型是否匹配。诗歌可以短，可以有抽象意象；设定集可以说明；小说、剧本和小剧场必须有具体行动、具体场景和自然对白。",
            "叙事类作品不需要每篇都有强冲突；正常聊天、一起走路、一起等车、吃东西、避雨、买东西、赶时间、排练、逛展、临时帮忙也可以构成关系推进。",
            "人物之间的吸引力、尴尬、冲突或靠近必须来自各自正在做的事、想要的事和承担的后果，而不是旁白贴标签。",
            "约会/社交对象如果只是评估、分析、纠正或审视主角，说明人物功能失败；必须改写成一个有自身目标、压力、缺点和选择的人。",
            "如果草稿像论文提纲、概念展板或设定说明，先删掉抽象命题，改成一个可被镜头拍到的动作链和自然对白。",
            "如果草稿主角被长期导演指令、旧系列或未点名角色抢走，而创作 prompt 已经点名主角或题材，必须改回 prompt 核心。",
            "如果本篇需要续写系列，必须遵守剧情规划 agent 对全量前情的分析；如果规划 agent 判断不续写，不要硬贴旧系列名。",
        ]
    )


def recent_curated_memory_summaries(limit: int = 12) -> List[Dict[str, object]]:
    with connect_db() as conn:
        rows = conn.execute(
            """
            SELECT id, content, importance_label, updated_at
            FROM curated_memories
            WHERE (
                visitor_ip LIKE 'device:%'
                OR (visitor_ip IS NULL AND importance_label = 'characters')
              )
              AND importance_label NOT IN ('identity', 'persona', 'preference', 'rule', 'characters', 'artifact')
            ORDER BY id DESC
            LIMIT ?
            """,
            (int(limit),),
        ).fetchall()
    return [
        {
            "id": int(row["id"]),
            "content": str(row["content"]),
            "importance_label": str(row["importance_label"]),
            "updated_at": str(row["updated_at"]),
        }
        for row in rows
    ]


def build_active_recall_context(
    session_id: str,
    visitor_ip: str = "",
    limit: int = 12,
) -> str:
    ip = normalize_visitor_ip(visitor_ip) if visitor_ip else ""
    max_rows = min(max(int(limit), 1), 30)
    with connect_db() as conn:
        scope = binding_scope_for_device(conn, ip) if ip and is_device_identity(ip) else {}
        scoped_devices = list(scope.get("device_ids") or ([ip] if ip and is_device_identity(ip) else []))
        profile_owner_device_id = str(scope.get("profile_owner_device_id") or "")
        in_clause, params = sql_in_clause_params(scoped_devices)
        memory_rows = conn.execute(
            f"""
            SELECT id, content, importance_label, visitor_ip, timeline_at, supersedes_id, confidence, updated_at
            FROM curated_memories
            WHERE (
                visitor_ip IN {in_clause}
                OR (visitor_ip IS NULL AND importance_label = 'characters')
            )
            ORDER BY
              CASE WHEN visitor_ip = ? THEN 0 ELSE 1 END,
              CASE importance_label
                WHEN 'identity' THEN 0
                WHEN 'preference' THEN 1
                WHEN 'persona' THEN 2
                WHEN 'artifact' THEN 3
                WHEN 'characters' THEN 4
                ELSE 5
              END,
              COALESCE(timeline_at, updated_at) DESC,
              id DESC
            LIMIT ?
            """,
            (*params, ip, max_rows),
        ).fetchall()
        artifact_rows = conn.execute(
            """
            SELECT id, title, artifact_type, series_title, episode_index, summary, created_at
            FROM idle_agent_artifacts
            ORDER BY id DESC
            LIMIT 6
            """
        ).fetchall()

    if not memory_rows and not artifact_rows:
        return ""

    lines = [
        "主动回忆上下文：用户正在要求你主动想起你们之间的事。",
        "不要只按字面相似度回答；请综合长期记忆、作品记忆和时间线，挑一件最有意义的事。",
        "如果记忆冲突，较新的记忆和 confidence 更高的记忆优先。",
        "",
    ]
    if memory_rows:
        lines.append("可用长期记忆：")
        for row in memory_rows:
            memory_ip = str(row["visitor_ip"] or "")
            label = str(row["importance_label"] or "other")
            if memory_ip != ip and is_device_local_memory_label(label):
                if not profile_owner_device_id or memory_ip != profile_owner_device_id:
                    continue
            supersedes = f" supersedes=#{row['supersedes_id']}" if row["supersedes_id"] is not None else ""
            lines.append(
                f"- #{row['id']} [{label}] "
                f"timeline={row['timeline_at'] or row['updated_at']} "
                f"confidence={float(row['confidence'] or 0.7):.2f}{supersedes}: "
                f"{str(row['content']).strip()}"
            )
    if artifact_rows:
        lines.append("")
        lines.append("近期作品线索：")
        for row in artifact_rows:
            episode = f" 第{row['episode_index']}集" if row["episode_index"] is not None else ""
            series = f"《{row['series_title']}》" if row["series_title"] else ""
            summary = str(row["summary"] or "").strip()
            lines.append(
                f"- 作品 #{row['id']} {series}{episode} {row['title']} "
                f"[{row['artifact_type']}]: {summary}"
            )
    return "\n".join(lines).strip()


def build_idle_agent_prompt() -> Tuple[str, str, Dict[str, object]]:
    memories = recent_curated_memory_summaries()
    stored_custom_prompt = get_idle_agent_custom_prompt()
    custom_prompt = effective_idle_agent_custom_prompt(stored_custom_prompt)
    story_seeds = load_idle_story_seeds()
    series_plan = idle_series_plan_for_prompt(custom_prompt)
    planned_series_title = str(series_plan.get("series_title") or "").strip() if series_plan.get("use_series") else ""
    lines = [
        "请选择一个你认为值得在空闲时完成的小作品，保持自主性和创造性。",
        "默认目标是写出可以在网络上连载、改编为漫画/电影脚本，或成为有记忆点的诗歌/短篇的作品。",
        "",
        "创作前先确定：本篇主角是谁、他/她想要什么、阻碍是什么、选择是什么、结尾留下什么余味。",
    ]
    if custom_prompt:
        lines.extend(
            [
                "",
                "本轮用户配置 prompt 具有最高题材优先级：",
                custom_prompt,
                "这段 prompt 高于一切。它明确点名的地点、主角、题材、关系、体裁和事件必须执行；角色库、旧系列、近期成果、避重复规则和导演指令只能作为补充素材，不能把作品改写成其他任务。",
                "如果 prompt 写明咖啡厅，作品必须发生在咖啡厅，或至少有关键段落发生在咖啡厅；避重复规则只能要求换写法，不能取消咖啡厅。",
                "如果这段 prompt 点名了角色库中的固定角色，应优先注入并使用该角色的完整角色卡；该角色一旦出场，必须保留其外形、性格、背景、关系和说话气质，不能只借名字另造角色。",
                "如果 prompt 包含 dating、约会、社交、日常等方向，作品必须围绕 prompt 点名对象的约会/社交/日常推进；不要改写成未点名角色的排练室、超英城市档案、战斗支线或设定展示。",
                "叙事类作品开篇两段内应进入具体可见的场景和人物动作；诗歌、设定、札记按对应体裁写，不套小说开场规则。",
                "用户 prompt 是核心导演指令；角色库、长期出场愿望、旧系列和历史导演指令只是可选素材，不能反客为主。",
            ]
        )
    series_plan_context = format_idle_series_plan_context(series_plan)
    if series_plan_context:
        lines.append("")
        lines.append(series_plan_context)
        lines.append(
            "写作前先按上面的剧情规划确定 title、表达意图、出场人物、主要动作和配图功能；"
            "最终只输出成果 JSON，不要把规划过程写成额外说明。"
        )
    lines.append("")
    lines.append(GROSS_STORY_CONTENT_RULE)
    lines.append("你可以写短篇小说、诗歌、剧本、世界观、角色档案、自我设定或连续作品。")
    repeat_context = recent_idle_artifact_repetition_context()
    if repeat_context:
        lines.append("")
        lines.append(repeat_context)
    pattern_context = idle_story_pattern_variation_context()
    if pattern_context:
        lines.append("")
        lines.append(pattern_context)
    try:
        artifact_directive_context = format_hidden_artifact_directives_for_artifacts(
            focus_text=custom_prompt,
            series_title=planned_series_title,
        )
    except Exception as exc:
        artifact_directive_context = ""
        record_event(None, "hidden_artifact_directive_context_error", "local", {"error": str(exc)})
    if artifact_directive_context:
        lines.append("")
        lines.append(artifact_directive_context)
    try:
        character_context = format_hidden_character_context_for_artifacts(focus_text=custom_prompt)
    except Exception as exc:
        character_context = ""
        record_event(None, "hidden_character_artifact_context_error", "local", {"error": str(exc)})
    if character_context:
        lines.append("")
        lines.append(character_context)
    if memories:
        lines.append("")
        lines.append("以下是近期长期记忆摘要，只能作为弱灵感或现实状态参考，不要复述原文，不要让它压过角色库和作品质量：")
        for item in memories:
            lines.append(f"- #{item['id']} [{item['importance_label']}] {item['content']}")
    formatted_series_context = ""
    if planned_series_title and not series_plan_context:
        formatted_series_context = format_idle_series_context(
            [
                item
                for item in load_idle_series_context(
                    max_series=IDLE_SERIES_CONTEXT_MAX_SERIES,
                    max_episodes=IDLE_SERIES_CONTEXT_MAX_EPISODES,
                )
                if str(item.get("series_title") or "").strip() == planned_series_title
            ]
        )
        if formatted_series_context:
            lines.append("")
            lines.append(formatted_series_context)
    if story_seeds:
        lines.append("以下是用户配置的可选创作种子，不是强制任务；请在空闲时轮换选择：")
        lines.extend(story_seeds)
    if planned_series_title:
        lines.append(
            "本轮已由剧情规划 agent 选择续写系列：series_title 必须与规划结果完全一致；"
            "主线连载 episode_index 必须填写规划结果指定的下一集编号；"
            "前传、番外、起源故事可以写，但 episode_index 必须填 null，标题需明确标注前传/番外/起源；"
            "summary 必须写成本集对主线、角色状态或设定变化的摘要。"
            "如果规划结果要求完结，release_prompt_after_this 输出 true。"
        )
    else:
        lines.append(
            "本轮没有选择续写系列；除非用户配置 prompt 已明确要求开始某个新系列，否则 series_title 和 episode_index 留空，写随机的独立作品。"
        )
    if custom_prompt:
        lines.append("")
        lines.append("再次确认用户配置的空闲创作 prompt：")
        lines.append(custom_prompt)
        lines.append(
            "请把用户配置 prompt 理解为必须执行的创作任务。"
            "如果其中的地点、人物类型或冲突模型已在近期反复出现，必须保留 prompt 指定内容，但更换叙事骨架、关系推进和对白功能。"
            "不能抛弃 prompt 点名的地点、核心主角、系列、体裁和核心题材。"
            "如果 prompt 点名了角色库角色，必须优先使用该角色的角色卡保持人物保真。"
            "如果角色库或导演指令与本轮 prompt 争抢主角，优先服从本轮 prompt；未被点名的长期角色可以完全不出场。"
        )
    lines.append("")
    lines.append(idle_final_quality_gate_context())
    summary = (
        f"curated_memories={len(memories)};"
        f"story_seeds={len(story_seeds)};"
        f"series_plan={'series' if planned_series_title else 'new'};"
        f"planned_series={planned_series_title or '-'};"
        f"planned_episode={series_plan.get('next_episode_index') or '-'};"
        f"target_episode_count={series_plan.get('target_episode_count') or '-'};"
        f"planner_release={'true' if bool(series_plan.get('release_prompt_after_this')) else 'false'};"
        f"repeat_context={'set' if repeat_context else 'empty'};"
        f"pattern_context={'set' if pattern_context else 'empty'};"
        f"artifact_directives={'set' if artifact_directive_context else 'empty'};"
        f"character_context={'set' if character_context else 'empty'};"
        f"stored_prompt_completed={'true' if str(stored_custom_prompt or '').strip() and not custom_prompt else 'false'};"
        f"custom_prompt={'set' if custom_prompt else 'empty'}"
    )
    return "\n".join(lines), summary, {"series_plan": series_plan}


def fallback_idle_agent_payload(text: str) -> Dict[str, object]:
    cleaned = normalize_idle_artifact_content_text(text).strip()
    return {
        "task_type": "notes",
        "title": "未命名成果",
        "content": cleaned,
        "series_title": "",
        "episode_index": None,
        "summary": "idle agent returned malformed JSON; saved raw content",
        "release_prompt_after_this": False,
        "image_count": 1,
        "image_plan": [{"title": "封面", "brief": compact_idle_artifact_content(cleaned, 220), "role": "cover"}],
    }


def load_idle_agent_json_payload(cleaned: str) -> Dict[str, object]:
    candidates = [cleaned]
    if cleaned.startswith("{") and not cleaned.rstrip().endswith("}"):
        candidates.append(f"{cleaned.rstrip()}}}")
    match = re.search(r"\{.*\}", cleaned, flags=re.S)
    if match:
        candidates.append(match.group(0))

    seen = set()
    for candidate in candidates:
        candidate = candidate.strip()
        if not candidate or candidate in seen:
            continue
        seen.add(candidate)
        try:
            payload = json.loads(candidate, strict=False)
            if isinstance(payload, dict):
                return payload
        except Exception:
            continue
    return fallback_idle_agent_payload(cleaned)


def parse_idle_agent_response(text: str) -> Dict[str, object]:
    cleaned = text.strip()
    if cleaned.startswith("```"):
        cleaned = re.sub(r"^```(?:json)?\s*", "", cleaned)
        cleaned = re.sub(r"\s*```$", "", cleaned)
    payload = load_idle_agent_json_payload(cleaned)
    raw_image_plan = payload.get("image_plan")
    image_plan = raw_image_plan if isinstance(raw_image_plan, list) else []
    normalized_image_plan: List[Dict[str, str]] = []
    for item in image_plan[:4]:
        if not isinstance(item, dict):
            continue
        title = normalize_idle_artifact_terms(str(item.get("title") or "配图")).strip() or "配图"
        brief = normalize_idle_artifact_terms(str(item.get("brief") or item.get("prompt") or "")).strip()
        role = normalize_idle_artifact_terms(str(item.get("role") or "")).strip() or ("cover" if not normalized_image_plan else "inline")
        if brief:
            normalized_image_plan.append({"title": title, "brief": brief, "role": role})
    if not normalized_image_plan:
        fallback_brief = normalize_idle_artifact_content_text(
            str(payload.get("summary") or payload.get("title") or payload.get("content") or "")
        ).strip()
        normalized_image_plan = [{"title": "封面", "brief": compact_idle_artifact_content(fallback_brief, 220), "role": "cover"}]
    try:
        image_count = int(payload.get("image_count") or len(normalized_image_plan) or 1)
    except Exception:
        image_count = len(normalized_image_plan) or 1
    image_count = max(1, min(4, image_count))
    normalized_image_plan = normalized_image_plan[:image_count]
    return {
        "task_type": normalize_idle_artifact_terms(str(payload.get("task_type", "other"))).strip() or "other",
        "title": normalize_idle_artifact_terms(str(payload.get("title", "未命名成果"))).strip() or "未命名成果",
        "content": normalize_idle_artifact_content_text(str(payload.get("content", ""))).strip(),
        "series_title": normalize_idle_artifact_terms(str(payload.get("series_title", ""))).strip(),
        "episode_index": payload.get("episode_index"),
        "summary": normalize_idle_artifact_terms(str(payload.get("summary", ""))).strip(),
        "release_prompt_after_this": bool(payload.get("release_prompt_after_this")),
        "image_count": image_count,
        "image_plan": normalized_image_plan,
    }


def idle_agent_jsonish_key_pattern(key: str) -> str:
    return r'"' + re.escape(key) + r'"\s*:'


def decode_idle_agent_jsonish_text(value: object) -> str:
    text = normalize_idle_artifact_terms(str(value or "")).strip()
    if not text:
        return ""
    text = text.strip().strip(",")
    if text.startswith('"'):
        text = text[1:]
    if text.endswith('"'):
        text = text[:-1]
    text = text.replace("\\n", "\n").replace("\\t", "\t").replace('\\"', '"')
    text = text.replace("\\/", "/")
    return normalize_idle_artifact_terms(text).strip()


def extract_idle_agent_jsonish_value(raw_text: str, key: str) -> object:
    text = str(raw_text or "")
    match = re.search(idle_agent_jsonish_key_pattern(key), text)
    if not match:
        return None
    tail = text[match.end():].lstrip()
    decoder = json.JSONDecoder(strict=False)
    try:
        value, _ = decoder.raw_decode(tail)
        if not (key == "content" and value == "" and len(tail) > 2 and not tail[2:].lstrip().startswith(",")):
            return value
    except Exception:
        pass
    if not tail.startswith('"'):
        primitive = re.match(r"([^,\}\n]+)", tail)
        return primitive.group(1).strip() if primitive else None
    body = tail[1:]
    if key == "content" and body.startswith('"'):
        body = body[1:]
    next_key = re.search(
        r'"\s*,\s*"(task_type|title|content|series_title|episode_index|summary|release_prompt_after_this|image_count|image_plan)"\s*:',
        body,
        flags=re.S,
    )
    if next_key:
        return body[: next_key.start()]
    end = body.rfind('"')
    return body[:end] if end > 0 else body


def infer_idle_agent_title_from_content(content: str, raw_text: str = "") -> str:
    text = normalize_idle_artifact_terms(content or "").strip()
    for pattern in (
        r"^\s*#+\s*([^#\n]{2,80})",
        r"^\s*《([^》]{2,80})》",
        r"^\s*([^。\n\r]{2,48})[。！？!?]",
    ):
        match = re.search(pattern, text)
        if match:
            return normalize_idle_artifact_terms(match.group(1)).strip(" ：:《》\"'")
    raw_title = extract_idle_agent_jsonish_value(raw_text, "title")
    if raw_title:
        return decode_idle_agent_jsonish_text(raw_title)[:80]
    first_line = next((line.strip() for line in text.splitlines() if line.strip()), "")
    return normalize_idle_artifact_terms(first_line[:48]).strip(" ：:《》\"'") or UNNAMED_IDLE_ARTIFACT_TITLE


def deterministic_repair_idle_agent_payload(raw_text: str, fallback: Dict[str, object]) -> Dict[str, object]:
    raw = str(raw_text or "")
    fallback_content = normalize_idle_artifact_content_text(str(fallback.get("content") or raw)).strip()
    task_type = decode_idle_agent_jsonish_text(extract_idle_agent_jsonish_value(raw, "task_type")) or str(fallback.get("task_type") or "other")
    title = decode_idle_agent_jsonish_text(extract_idle_agent_jsonish_value(raw, "title"))
    content = decode_idle_agent_jsonish_text(extract_idle_agent_jsonish_value(raw, "content")) or fallback_content
    series_title = decode_idle_agent_jsonish_text(extract_idle_agent_jsonish_value(raw, "series_title"))
    summary = decode_idle_agent_jsonish_text(extract_idle_agent_jsonish_value(raw, "summary"))
    if not title or title == UNNAMED_IDLE_ARTIFACT_TITLE:
        title = infer_idle_agent_title_from_content(content, raw)
    if not summary or summary == MALFORMED_IDLE_ARTIFACT_SUMMARY:
        summary = compact_idle_artifact_content(content, 260)
    episode_index = extract_idle_agent_jsonish_value(raw, "episode_index")
    if str(episode_index).strip().lower() in ("", "none", "null"):
        episode_index = None
    try:
        image_count = int(extract_idle_agent_jsonish_value(raw, "image_count") or fallback.get("image_count") or 1)
    except Exception:
        image_count = 1
    image_count = max(1, min(4, image_count))
    image_plan = fallback.get("image_plan") if isinstance(fallback.get("image_plan"), list) else []
    if not image_plan:
        image_plan = [{"title": "封面", "brief": compact_idle_artifact_content(summary or content or title, 220), "role": "cover"}]
    return {
        "task_type": normalize_artifact_type(str(task_type or "other"), title, content),
        "title": normalize_idle_artifact_terms(title).strip() or UNNAMED_IDLE_ARTIFACT_TITLE,
        "content": normalize_idle_artifact_content_text(content).strip(),
        "series_title": normalize_idle_artifact_terms(series_title).strip(),
        "episode_index": episode_index,
        "summary": normalize_idle_artifact_terms(summary).strip(),
        "release_prompt_after_this": False,
        "image_count": image_count,
        "image_plan": image_plan[:image_count],
    }


def call_idle_agent_repair_model(raw_text: str, source_prompt: str) -> Dict[str, object]:
    client, http_client, model_slot = openai_client_for_slot(MODEL_SLOT_BACKGROUND, timeout=REQUEST_TIMEOUT)
    try:
        repair_context = (
            "# 原始创作任务\n"
            f"{str(source_prompt or '')[:12000]}\n\n"
            "# 解析失败的 idle agent 输出\n"
            f"{str(raw_text or '')[:60000]}"
        )
        resp = client.chat.completions.create(
            **model_completion_kwargs(model_slot),
            messages=[
                {"role": "system", "content": IDLE_AGENT_REPAIR_SYSTEM_PROMPT},
                {"role": "user", "content": repair_context},
            ],
            temperature=0.1,
            top_p=0.9,
            max_tokens=max(4096, min(int(IDLE_AGENT_MAX_TOKENS), 12000)),
        )
        _, answer = split_think_text(resp.choices[0].message.content or "")
        return parse_idle_agent_response(answer)
    finally:
        http_client.close()


def repair_idle_agent_decision_if_needed(
    decision: Dict[str, object],
    raw_text: str,
    source_prompt: str = "",
) -> Dict[str, object]:
    if not idle_agent_decision_needs_repair(decision):
        return decision
    started = time.perf_counter()
    fallback = deterministic_repair_idle_agent_payload(raw_text, decision)
    if not idle_agent_decision_needs_repair(fallback):
        record_event(None, "idle_agent_json_repaired", "local", {
            "method": "deterministic",
            "title": fallback.get("title"),
            "duration_ms": round((time.perf_counter() - started) * 1000, 3),
        })
        return fallback
    try:
        repaired = call_idle_agent_repair_model(raw_text, source_prompt)
        if not idle_agent_decision_needs_repair(repaired):
            record_event(None, "idle_agent_json_repaired", "local", {
                "method": "model",
                "title": repaired.get("title"),
                "duration_ms": round((time.perf_counter() - started) * 1000, 3),
            })
            return repaired
        record_event(None, "idle_agent_json_repair_model_incomplete", "local", {
            "title": repaired.get("title"),
            "summary": repaired.get("summary"),
        })
    except Exception as exc:
        record_event(None, "idle_agent_json_repair_model_error", "local", {"error": str(exc)})
    record_event(None, "idle_agent_json_repaired", "local", {
        "method": "deterministic",
        "title": fallback.get("title"),
        "duration_ms": round((time.perf_counter() - started) * 1000, 3),
    })
    return fallback


def call_idle_agent_model(prompt: str) -> Dict[str, str]:
    client, http_client, model_slot = openai_client_for_slot(MODEL_SLOT_BACKGROUND, timeout=REQUEST_TIMEOUT)
    try:
        stream = client.chat.completions.create(
            **model_completion_kwargs(model_slot),
            messages=[
                {"role": "system", "content": IDLE_AGENT_SYSTEM_PROMPT},
                {"role": "user", "content": prompt},
            ],
            temperature=IDLE_AGENT_TEMPERATURE,
            top_p=IDLE_AGENT_TOP_P,
            max_tokens=IDLE_AGENT_MAX_TOKENS,
            stream=True,
        )
        chunks: List[str] = []
        for chunk in stream:
            if IDLE_AGENT_CANCEL_EVENT.is_set():
                return {
                    "task_type": "other",
                    "title": "已中断",
                    "content": "",
                    "cancelled": "true",
                }
            if not chunk.choices:
                continue
            content = extract_delta_content(chunk.choices[0].delta)
            if content:
                chunks.append(content)
        _, answer = split_think_text("".join(chunks))
        decision = parse_idle_agent_response(answer)
        return repair_idle_agent_decision_if_needed(decision, answer, prompt)
    finally:
        http_client.close()
