# Generated by splitting app.py background dashboard helpers. Keep execution order in wangcai_app/startup/loader.py.
import subprocess


BACKGROUND_TABLES = (
    "sessions",
    "messages",
    "events",
    "analysis_trace_events",
    "curated_memories",
    "curated_memory_vectors",
    "memory_agent_jobs",
    "memory_retrieval_logs",
    "user_recent_states",
    "idle_agent_runs",
    "idle_agent_artifacts",
    "idle_artifact_vectors",
    "idle_artifact_comments",
    "generated_images",
    "artifact_images",
    "hidden_character_profiles",
    "hidden_character_profile_events",
    "hidden_artifact_directives",
    "hidden_artifact_directive_events",
    "app_settings",
)

BACKGROUND_TABLE_DESCRIPTIONS = {
    "sessions": "聊天会话",
    "messages": "聊天消息",
    "session_context_links": "会话续接关系",
    "events": "系统事件与后台日志",
    "analysis_trace_events": "分析模式 trace 明细",
    "memory_compression_cache": "记忆压缩缓存",
    "curated_memories": "长期记忆正文",
    "visitor_profiles": "旧画像兼容资料",
    "visitor_ip_links": "设备身份兼容链接",
    "shared_user_bindings": "共享用户绑定",
    "curated_memory_vectors": "长期记忆向量",
    "memory_agent_jobs": "记忆写入任务队列",
    "memory_retrieval_logs": "记忆召回日志",
    "user_recent_states": "用户近期状态",
    "idle_agent_runs": "成果生成运行记录",
    "idle_agent_artifacts": "成果正文",
    "idle_artifact_vectors": "成果向量索引",
    "idle_artifact_comments": "成果评论",
    "generated_images": "生成图片记录",
    "artifact_images": "成果配图关联",
    "hidden_character_profiles": "角色库资料",
    "hidden_character_profile_events": "角色库变更事件",
    "hidden_artifact_directives": "成果导演指令",
    "hidden_artifact_directive_events": "导演指令变更事件",
    "app_settings": "全局配置",
}

BACKGROUND_AGENT_DESCRIPTIONS = {
    "main_chat_stream": "主聊天大模型：结合消息、记忆和上下文生成最终回复",
    "fast_opening_stream": "快速开场大模型：浏览器刷新或打开时生成预缓存开场回复",
    "cached_opening_start": "缓存开场启动",
    "main_chat_empty_retry": "主聊天大模型：空输出后重试生成回复",
    "memory_agent_model": "长期记忆大模型：判断本轮对话中哪些事实值得写入记忆",
    "memory_recall_gate": "记忆召回大模型：判断本轮是否需要加载长期记忆",
    "memory_query_planner": "记忆查询大模型：把用户意图改写为记忆检索查询",
    "memory_candidate_judge": "记忆候选大模型：初筛候选记忆是否有保存价值",
    "memory_candidate_validation": "长期记忆大模型：核验候选记忆是否可靠、可写入",
    "memory_query_embedding": "Embedding：把记忆查询转为向量用于召回",
    "memory_write_embedding": "Embedding：把新长期记忆转为向量写入索引",
    "memory_agent_item_skipped": "长期记忆去重跳过",
    "idle_worker_tick": "后台成果 worker 心跳",
    "idle_agent_model": "成果创作大模型：根据导演指令和记忆生成作品",
    "artifact_image_prompt": "成果配图大模型：为作品生成画图 Prompt",
    "artifact_directive_agent_model": "导演指令大模型：从对话中整理作品创作偏好",
    "hidden_character_agent_model": "角色库大模型：从对话中整理隐藏角色资料",
    "event_memory_updater_model": "事件记忆大模型：更新日程、约定和事件类记忆",
    "recent_state_agent": "近期状态大模型：分析用户近一周/月的心理与生活状态",
    "draw_prompt_classify": "画图大模型：判断画图请求类型和意图",
    "draw_prompt_translate": "画图大模型：把画图需求转换为英文视觉描述",
    "draw_prompt_agent_model": "画图大模型：抽取角色特征并生成完整画图 Prompt",
    "draw_prompt_optimize": "画图大模型：优化最终画图 Prompt",
    "draw_reference_image_parse": "画图大模型：解析参考图内容",
    "draw_memory_gate": "画图大模型：判断画图是否需要读取角色/记忆",
    "draw_memory_query_embedding": "Embedding：把画图相关记忆查询转为向量",
    "draw_image_generation": "本地画图模型：调用 HiDream 生成图片",
    "search_planner": "联网搜索大模型：规划搜索关键词和信息需求",
    "read_page": "联网搜索逐页读取候选网页",
}

BACKGROUND_GPU_ROLE_DEFAULTS = (
    ("WANGCAI_BACKGROUND_LLM_GPU_INDICES", "本地 LLM", "6,7"),
    ("WANGCAI_BACKGROUND_EMBEDDING_GPU_INDICES", "Embedding", "5"),
    ("WANGCAI_BACKGROUND_IMAGE_GPU_INDICES", "本地画图", "4"),
)

BACKGROUND_VISIBLE_AGENT_STEPS = {
    "main_chat_stream",
    "fast_opening_stream",
    "main_chat_empty_retry",
    "memory_agent_model",
    "memory_recall_gate",
    "memory_query_planner",
    "memory_candidate_judge",
    "memory_candidate_validation",
    "memory_query_embedding",
    "memory_write_embedding",
    "idle_agent_model",
    "artifact_image_prompt",
    "artifact_directive_agent_model",
    "hidden_character_agent_model",
    "event_memory_updater_model",
    "recent_state_agent",
    "draw_prompt_classify",
    "draw_prompt_translate",
    "draw_prompt_agent_model",
    "draw_prompt_optimize",
    "draw_reference_image_parse",
    "draw_memory_gate",
    "draw_memory_query_embedding",
    "draw_image_generation",
    "search_planner",
}

BACKGROUND_VISIBLE_AGENT_EVENT_TYPES = (
    "model_call",
    "model_call_error",
    "embedding",
    "embedding_error",
    "draw_image_batch",
    "draw_prompt",
)

BACKGROUND_FAST_OPENING_EVENT_TYPES = (
    "fast_opening_stream_model_call",
    "fast_opening_stream_model_call_error",
)

BACKGROUND_EVENT_MODEL_CALL_STEPS = {
    "fast_opening_stream_model_call": "fast_opening_stream",
    "fast_opening_stream_model_call_error": "fast_opening_stream",
    "main_chat_stream_model_call": "main_chat_stream",
    "main_chat_stream_model_call_error": "main_chat_stream",
}

BACKGROUND_WINDOWS = (
    ("hour", "1小时", 3600),
    ("day", "24小时", 86400),
    ("month", "30天", 2592000),
)


def background_parse_json(value: object) -> Dict[str, object]:
    try:
        payload = json.loads(str(value or "{}"))
    except Exception:
        return {}
    return payload if isinstance(payload, dict) else {}


def background_cutoff(seconds: int) -> str:
    return (datetime.now(timezone.utc) - timedelta(seconds=int(seconds))).isoformat(timespec="seconds")


def background_table_columns(conn: sqlite3.Connection, table_name: str) -> set:
    try:
        return {str(row["name"]) for row in conn.execute(f"PRAGMA table_info({table_name})").fetchall()}
    except Exception:
        return set()


def background_count_recent(
    conn: sqlite3.Connection,
    table_name: str,
    seconds: int,
    preferred_columns: Tuple[str, ...] = ("created_at", "updated_at", "started_at"),
) -> int:
    columns = background_table_columns(conn, table_name)
    time_column = next((column for column in preferred_columns if column in columns), "")
    if not time_column:
        return 0
    try:
        row = conn.execute(
            f"SELECT COUNT(*) AS c FROM {table_name} WHERE {time_column} >= ?",
            (background_cutoff(seconds),),
        ).fetchone()
        return int(row["c"] or 0)
    except Exception:
        return 0


def background_table_stats(conn: sqlite3.Connection) -> List[Dict[str, object]]:
    rows: List[Dict[str, object]] = []
    table_counts: Dict[str, int] = {}
    table_size_bytes = background_table_size_bytes(conn)
    for table_name in BACKGROUND_TABLES:
        try:
            count_row = conn.execute(f"SELECT COUNT(*) AS c FROM {table_name}").fetchone()
            count = int(count_row["c"] or 0)
            error = ""
        except Exception as exc:
            count = 0
            error = str(exc)
        table_counts[table_name] = count
        rows.append(
            {
                "name": table_name,
                "description": BACKGROUND_TABLE_DESCRIPTIONS.get(table_name, "系统表"),
                "rows": count,
                "recent_1h": background_count_recent(conn, table_name, 3600),
                "recent_24h": background_count_recent(conn, table_name, 86400),
                "recent_30d": background_count_recent(conn, table_name, 2592000),
                "size_bytes": int(table_size_bytes.get(table_name, 0)),
                "error": error,
            }
        )
    if not table_size_bytes:
        db_size = DB_PATH.stat().st_size if DB_PATH.exists() else 0
        total_count = sum(count for count in table_counts.values() if count > 0)
        for row in rows:
            count = int(row.get("rows") or 0)
            row["size_bytes"] = int(round(db_size * (count / total_count))) if db_size > 0 and total_count > 0 and count > 0 else 0
    rows.sort(key=lambda item: int(item.get("rows") or 0), reverse=True)
    return rows


def background_table_size_bytes(conn: sqlite3.Connection) -> Dict[str, int]:
    try:
        rows = conn.execute(
            """
            SELECT name, SUM(pgsize) AS bytes
            FROM dbstat
            GROUP BY name
            """
        ).fetchall()
    except Exception:
        return {}
    table_names = set(BACKGROUND_TABLES)
    result: Dict[str, int] = {}
    for row in rows:
        name = str(row["name"] or "")
        if name in table_names:
            result[name] = int(row["bytes"] or 0)
    return result


def background_token_usage(payload: Dict[str, object]) -> Dict[str, int]:
    usage = payload.get("usage")
    if not isinstance(usage, dict):
        usage = payload

    def read_int(*keys: str) -> int:
        for key in keys:
            value = usage.get(key) if isinstance(usage, dict) else None
            try:
                if value is not None:
                    return int(value)
            except Exception:
                continue
        return 0

    prompt_tokens = read_int("prompt_tokens", "input_tokens")
    completion_tokens = read_int("completion_tokens", "output_tokens")
    total_tokens = read_int("total_tokens")
    if not (prompt_tokens or completion_tokens or total_tokens):
        estimated = background_estimate_token_usage(payload)
        prompt_tokens = estimated["input_tokens"]
        completion_tokens = estimated["output_tokens"]
        total_tokens = estimated["total_tokens"]
    if not total_tokens:
        total_tokens = prompt_tokens + completion_tokens
    return {
        "input_tokens": prompt_tokens,
        "output_tokens": completion_tokens,
        "total_tokens": total_tokens,
    }


def background_estimate_text_tokens(value: object) -> int:
    text = str(value or "")
    if not text:
        return 0
    return max(1, int((len(text) + 1) / 2))


def background_estimate_token_usage(payload: Dict[str, object]) -> Dict[str, int]:
    input_tokens = 0
    output_tokens = 0
    input_keys = {
        "message",
        "messages",
        "prompt",
        "input",
        "input_preview",
        "query",
        "request",
        "source",
        "user_message",
        "content",
    }
    output_keys = {
        "answer",
        "response",
        "result",
        "decision",
        "summary",
        "output",
        "optimized_prompt",
        "translation",
        "memory",
    }

    def walk(value: object, hint: str = "") -> None:
        nonlocal input_tokens, output_tokens
        if isinstance(value, dict):
            for key, child in value.items():
                lower_key = str(key).lower()
                if lower_key == "answer_chars":
                    try:
                        output_tokens += background_estimate_text_tokens("x" * int(child or 0))
                    except Exception:
                        pass
                    continue
                if lower_key in {"prompt_chars", "input_chars"}:
                    try:
                        input_tokens += background_estimate_text_tokens("x" * int(child or 0))
                    except Exception:
                        pass
                    continue
                next_hint = hint
                if lower_key in output_keys:
                    next_hint = "output"
                elif lower_key in input_keys:
                    next_hint = "input"
                walk(child, next_hint)
            return
        if isinstance(value, list):
            for child in value:
                walk(child, hint)
            return
        if not isinstance(value, str) or not value:
            return
        tokens = background_estimate_text_tokens(value)
        if hint == "output":
            output_tokens += tokens
        else:
            input_tokens += tokens

    walk(payload)
    total_tokens = input_tokens + output_tokens
    return {
        "input_tokens": input_tokens,
        "output_tokens": output_tokens,
        "total_tokens": total_tokens,
    }


def background_empty_usage_window(label: str, seconds: int) -> Dict[str, object]:
    return {
        "label": label,
        "seconds": seconds,
        "calls": 0,
        "failures": 0,
        "input_tokens": 0,
        "output_tokens": 0,
        "total_tokens": 0,
        "total_duration_ms": 0.0,
        "avg_duration_ms": 0.0,
    }


def background_agent_description(step_name: str) -> str:
    if step_name in BACKGROUND_AGENT_DESCRIPTIONS:
        return BACKGROUND_AGENT_DESCRIPTIONS[step_name]
    if step_name.startswith("read_page_"):
        return BACKGROUND_AGENT_DESCRIPTIONS["read_page"]
    if step_name.startswith("memory_"):
        return "长期记忆模型流程"
    if step_name.startswith("idle_"):
        return "成果生成模型流程"
    if "embedding" in step_name:
        return "Embedding 向量化调用"
    if "image" in step_name or "artifact" in step_name:
        return "成果或配图模型流程"
    return "模型调用步骤"


def background_normalize_step_name(step_name: str) -> str:
    if re.fullmatch(r"read_page_\d+", step_name):
        return "read_page"
    return step_name


def background_is_visible_agent_step(step_name: str, event_type: str) -> bool:
    if step_name in BACKGROUND_VISIBLE_AGENT_STEPS:
        return True
    lowered_event = event_type.lower()
    return any(lowered_event == item for item in BACKGROUND_VISIBLE_AGENT_EVENT_TYPES) and not step_name.endswith("_prompt")


def background_model_description(model_name: str) -> str:
    lowered = model_name.lower()
    if "hidream" in lowered or "image" in lowered:
        return "本地画图模型"
    if "embedding" in lowered or "embed" in lowered:
        return "本地 Embedding 模型"
    if "qwen" in lowered:
        return "本地 LLM"
    if "deepseek" in lowered:
        return "云端聊天模型"
    return "模型调用"


def background_new_windowed_row(key_name: str, key_value: str, description: str = "") -> Dict[str, object]:
    row = {key_name: key_value, "description": description, "last_seen_at": ""}
    for window_key, label, seconds in BACKGROUND_WINDOWS:
        row[window_key] = background_empty_usage_window(label, seconds)
    return row


def background_window_sort_key(item: Dict[str, object], name_key: str) -> Tuple[int, int, int, float, str]:
    month = item.get("month") if isinstance(item.get("month"), dict) else {}
    day = item.get("day") if isinstance(item.get("day"), dict) else {}
    hour = item.get("hour") if isinstance(item.get("hour"), dict) else {}
    return (
        int(month.get("calls") or 0),
        int(day.get("calls") or 0),
        int(hour.get("calls") or 0),
        float(month.get("total_duration_ms") or 0.0),
        str(item.get(name_key) or ""),
    )


def background_add_usage(row: Dict[str, object], created_at: object, duration_ms: float, failed: bool, usage: Dict[str, int]) -> None:
    parsed = parse_utc_iso(created_at)
    if parsed is None:
        return
    now = datetime.now(timezone.utc)
    age_seconds = (now - parsed).total_seconds()
    for window_key, _label, seconds in BACKGROUND_WINDOWS:
        if age_seconds > seconds:
            continue
        bucket = row[window_key]
        bucket["calls"] = int(bucket["calls"]) + 1
        bucket["failures"] = int(bucket["failures"]) + (1 if failed else 0)
        bucket["input_tokens"] = int(bucket["input_tokens"]) + int(usage.get("input_tokens", 0))
        bucket["output_tokens"] = int(bucket["output_tokens"]) + int(usage.get("output_tokens", 0))
        bucket["total_tokens"] = int(bucket["total_tokens"]) + int(usage.get("total_tokens", 0))
        bucket["total_duration_ms"] = round(float(bucket["total_duration_ms"]) + float(duration_ms or 0.0), 3)
        calls = max(1, int(bucket["calls"]))
        bucket["avg_duration_ms"] = round(float(bucket["total_duration_ms"]) / calls, 3)


def background_trace_rows(conn: sqlite3.Connection) -> Tuple[List[Dict[str, object]], List[Dict[str, object]]]:
    rows = conn.execute(
        """
        SELECT event_type, step_name, duration_ms, payload_json, created_at
        FROM analysis_trace_events
        WHERE created_at >= ?
        ORDER BY id DESC
        LIMIT 10000
        """,
        (background_cutoff(2592000),),
    ).fetchall()
    agent_map: Dict[str, Dict[str, object]] = {}
    model_map: Dict[str, Dict[str, object]] = {}
    for row in rows:
        raw_step_name = str(row["step_name"] or "unknown")
        step_name = background_normalize_step_name(raw_step_name)
        event_type = str(row["event_type"] or "")
        payload = background_parse_json(row["payload_json"])
        duration = float(row["duration_ms"] or 0.0)
        failed = "error" in event_type.lower() or str(payload.get("status") or "").lower() in {"failed", "error"}
        usage = background_token_usage(payload)
        if background_is_visible_agent_step(step_name, event_type):
            agent = agent_map.setdefault(step_name, background_new_windowed_row("step_name", step_name, background_agent_description(step_name)))
            if not agent.get("last_seen_at"):
                agent["last_seen_at"] = str(row["created_at"] or "")
            background_add_usage(agent, row["created_at"], duration, failed, usage)
        model = str(payload.get("model") or payload.get("model_name") or "").strip()
        if not model:
            continue
        model_row = model_map.setdefault(model, background_new_windowed_row("model", model, background_model_description(model)))
        if not model_row.get("last_seen_at"):
            model_row["last_seen_at"] = str(row["created_at"] or "")
        background_add_usage(model_row, row["created_at"], duration, failed, usage)
    background_add_event_model_call_rows(conn, agent_map, model_map)
    background_add_image_model_rows(conn, model_map)

    agent_rows = list(agent_map.values())
    model_rows = list(model_map.values())
    agent_rows.sort(key=lambda item: background_window_sort_key(item, "step_name"), reverse=True)
    model_rows.sort(key=lambda item: background_window_sort_key(item, "model"), reverse=True)
    return agent_rows[:80], model_rows[:80]


def background_add_event_model_call_rows(
    conn: sqlite3.Connection,
    agent_map: Dict[str, Dict[str, object]],
    model_map: Dict[str, Dict[str, object]],
) -> None:
    event_types = tuple(BACKGROUND_EVENT_MODEL_CALL_STEPS.keys())
    try:
        rows = conn.execute(
            f"""
            SELECT event_type, metadata_json, created_at
            FROM events
            WHERE event_type IN ({",".join("?" for _ in event_types)})
              AND created_at >= ?
            ORDER BY id DESC
            LIMIT 10000
            """,
            (*event_types, background_cutoff(2592000)),
        ).fetchall()
    except Exception:
        return
    for row in rows:
        step_name = BACKGROUND_EVENT_MODEL_CALL_STEPS.get(str(row["event_type"] or ""))
        if not step_name:
            continue
        payload = background_parse_json(row["metadata_json"])
        duration = float(payload.get("duration_ms") or 0.0)
        failed = "error" in str(row["event_type"] or "").lower() or str(payload.get("status") or "").lower() in {"failed", "error"}
        usage = background_token_usage(payload)
        agent = agent_map.setdefault(
            step_name,
            background_new_windowed_row(
                "step_name",
                step_name,
                background_agent_description(step_name),
            ),
        )
        if not agent.get("last_seen_at"):
            agent["last_seen_at"] = str(row["created_at"] or "")
        background_add_usage(agent, row["created_at"], duration, failed, usage)
        model = str(payload.get("model") or "").strip()
        if not model:
            continue
        model_row = model_map.setdefault(model, background_new_windowed_row("model", model, background_model_description(model)))
        if not model_row.get("last_seen_at"):
            model_row["last_seen_at"] = str(row["created_at"] or "")
        background_add_usage(model_row, row["created_at"], duration, failed, usage)


def background_add_image_model_rows(conn: sqlite3.Connection, model_map: Dict[str, Dict[str, object]]) -> None:
    try:
        rows = conn.execute(
            """
            SELECT model_name, status, created_at
            FROM generated_images
            WHERE created_at >= ?
            ORDER BY id DESC
            LIMIT 10000
            """,
            (background_cutoff(2592000),),
        ).fetchall()
    except Exception:
        return
    for row in rows:
        model_name = str(row["model_name"] or "image-generation").strip() or "image-generation"
        model_row = model_map.setdefault(
            model_name,
            background_new_windowed_row("model", model_name, background_model_description(model_name)),
        )
        if not model_row.get("last_seen_at"):
            model_row["last_seen_at"] = str(row["created_at"] or "")
        status = str(row["status"] or "").lower()
        failed = status not in {"completed", "succeeded", "success", "done"}
        background_add_usage(model_row, row["created_at"], 0.0, failed, {"input_tokens": 0, "output_tokens": 0, "total_tokens": 0})


def background_recent_windows(conn: sqlite3.Connection) -> List[Dict[str, object]]:
    windows = [("5分钟", 300), ("1小时", 3600), ("24小时", 86400)]
    result = []
    for label, seconds in windows:
        events = background_count_recent(conn, "events", seconds)
        messages = background_count_recent(conn, "messages", seconds)
        traces = background_count_recent(conn, "analysis_trace_events", seconds)
        result.append(
            {
                "label": label,
                "seconds": seconds,
                "events": events,
                "messages": messages,
                "trace_events": traces,
                "event_qps": round(events / max(1, seconds), 4),
                "message_qps": round(messages / max(1, seconds), 4),
            }
        )
    return result


def background_read_proc_meminfo() -> Dict[str, object]:
    info: Dict[str, int] = {}
    try:
        with open("/proc/meminfo", "r", encoding="utf-8") as handle:
            for line in handle:
                key, _, rest = line.partition(":")
                value = rest.strip().split()[0]
                info[key] = int(value) * 1024
    except Exception as exc:
        return {"available": False, "error": str(exc)}
    total = int(info.get("MemTotal", 0))
    available = int(info.get("MemAvailable", 0))
    used = max(0, total - available)
    return {
        "available": True,
        "total_bytes": total,
        "available_bytes": available,
        "used_bytes": used,
        "used_percent": round((used / total) * 100, 2) if total else 0.0,
    }


def background_read_current_process() -> Dict[str, object]:
    status: Dict[str, str] = {}
    try:
        with open("/proc/self/status", "r", encoding="utf-8") as handle:
            for line in handle:
                key, _, value = line.partition(":")
                status[key] = value.strip()
    except Exception as exc:
        return {"pid": os.getpid(), "available": False, "error": str(exc)}

    def kb_value(key: str) -> int:
        raw = status.get(key, "0").split()[0]
        try:
            return int(raw) * 1024
        except Exception:
            return 0

    return {
        "available": True,
        "pid": os.getpid(),
        "name": status.get("Name", "wangcai"),
        "rss_bytes": kb_value("VmRSS"),
        "peak_rss_bytes": kb_value("VmHWM"),
        "virtual_bytes": kb_value("VmSize"),
        "threads": int(status.get("Threads", "0") or 0),
        "active_generations": len(ACTIVE_GENERATIONS),
        "process_time_seconds": round(time.process_time(), 3),
    }


def background_disk_usage() -> Dict[str, object]:
    try:
        stat = os.statvfs(str(DB_PATH.parent))
        total = int(stat.f_blocks * stat.f_frsize)
        available = int(stat.f_bavail * stat.f_frsize)
        used = max(0, total - available)
        db_size = DB_PATH.stat().st_size if DB_PATH.exists() else 0
        return {
            "available": True,
            "path": str(DB_PATH.parent),
            "total_bytes": total,
            "available_bytes": available,
            "used_bytes": used,
            "used_percent": round((used / total) * 100, 2) if total else 0.0,
            "db_size_bytes": db_size,
        }
    except Exception as exc:
        return {"available": False, "error": str(exc), "db_size_bytes": 0}


def background_generated_image_storage() -> Dict[str, object]:
    output_dir = STATIC_DIR / "generated_images"
    public_prefix = "/static/generated_images"
    try:
        files = [path for path in output_dir.iterdir() if path.is_file()]
        total_bytes = sum(path.stat().st_size for path in files)
        latest = max((path.stat().st_mtime for path in files), default=0)
        return {
            "available": True,
            "path": str(output_dir),
            "public_prefix": public_prefix,
            "file_count": len(files),
            "total_bytes": total_bytes,
            "latest_mtime": latest,
        }
    except Exception as exc:
        return {
            "available": False,
            "path": str(output_dir),
            "public_prefix": public_prefix,
            "file_count": 0,
            "total_bytes": 0,
            "error": str(exc),
        }


def background_cpu_usage() -> Dict[str, object]:
    try:
        load_avg = os.getloadavg()
    except Exception:
        load_avg = (0.0, 0.0, 0.0)
    return {
        "available": True,
        "cpu_count": os.cpu_count() or 0,
        "load_average": [round(float(value), 3) for value in load_avg],
    }


def background_mask_process_args(args: str) -> str:
    text = str(args or "")
    text = re.sub(r"(?i)(api[_-]?key|token|password|secret)=\S+", r"\1=***", text)
    return text[:160]


def background_process_list() -> List[Dict[str, object]]:
    try:
        proc = subprocess.run(
            ["ps", "-eo", "pid,ppid,pcpu,pmem,rss,comm,args", "--sort=-rss"],
            check=False,
            capture_output=True,
            text=True,
            timeout=2,
        )
        lines = proc.stdout.splitlines()[1:16]
    except Exception:
        return []
    current_pid = os.getpid()
    processes: List[Dict[str, object]] = []
    for line in lines:
        parts = line.split(None, 6)
        if len(parts) < 7:
            continue
        try:
            pid = int(parts[0])
            ppid = int(parts[1])
            cpu_percent = float(parts[2])
            memory_percent = float(parts[3])
            rss_bytes = int(parts[4]) * 1024
        except Exception:
            continue
        processes.append(
            {
                "pid": pid,
                "ppid": ppid,
                "cpu_percent": cpu_percent,
                "memory_percent": memory_percent,
                "rss_bytes": rss_bytes,
                "command": parts[5],
                "args": background_mask_process_args(parts[6]),
                "is_current_service": pid == current_pid,
            }
        )
    return processes


def background_gpu_usage() -> Dict[str, object]:
    try:
        proc = subprocess.run(
            [
                "nvidia-smi",
                "--query-gpu=index,uuid,name,utilization.gpu,memory.used,memory.total,temperature.gpu,power.draw",
                "--format=csv,noheader,nounits",
            ],
            check=False,
            capture_output=True,
            text=True,
            timeout=3,
        )
    except Exception as exc:
        return {"available": False, "error": str(exc), "gpus": [], "processes": []}
    if proc.returncode != 0:
        return {"available": False, "error": proc.stderr.strip() or "nvidia-smi failed", "gpus": []}
    gpus: List[Dict[str, object]] = []
    for line in proc.stdout.splitlines():
        parts = [part.strip() for part in line.split(",")]
        if len(parts) < 8:
            continue
        try:
            used = float(parts[4])
            total = float(parts[5])
        except Exception:
            used = 0.0
            total = 0.0
        gpus.append(
            {
                "index": parts[0],
                "uuid": parts[1],
                "name": parts[2],
                "utilization_percent": float(parts[3]) if parts[3] else 0.0,
                "memory_used_mb": used,
                "memory_total_mb": total,
                "memory_used_percent": round((used / total) * 100, 2) if total else 0.0,
                "temperature_c": float(parts[6]) if parts[6] else 0.0,
                "power_w": float(parts[7]) if parts[7] not in {"", "[N/A]", "N/A"} else 0.0,
            }
        )
    role_by_index = background_gpu_role_indices()
    selected = []
    for item in gpus:
        index = str(item.get("index") or "")
        if index in role_by_index:
            selected.append({**item, "role": role_by_index[index]})
    if not selected:
        return {
            "available": True,
            "error": "",
            "gpus": [],
            "selection": "未配置本地 LLM、Embedding 或画图 GPU",
        }
    return {
        "available": True,
        "error": "",
        "gpus": selected,
        "selection": "仅显示本地 LLM、Embedding、画图服务 GPU",
    }


def background_gpu_role_indices() -> Dict[str, str]:
    role_by_index = background_detect_gpu_role_indices()
    for env_name, role, default_value in BACKGROUND_GPU_ROLE_DEFAULTS:
        raw = os.getenv(env_name)
        if raw is None and not role_by_index:
            raw = default_value
        if raw is None:
            continue
        for index in background_parse_gpu_indices(raw):
            role_by_index[index] = role
    return role_by_index


def background_parse_gpu_indices(raw: object) -> List[str]:
    indices: List[str] = []
    for part in str(raw or "").split(","):
        value = part.strip()
        if not value:
            continue
        if "-" in value:
            start, _, end = value.partition("-")
            try:
                for index in range(int(start), int(end) + 1):
                    indices.append(str(index))
            except Exception:
                continue
        else:
            indices.append(value)
    return indices


def background_detect_gpu_role_indices() -> Dict[str, str]:
    role_by_index: Dict[str, str] = {}
    for pid_text in os.listdir("/proc"):
        if not pid_text.isdigit():
            continue
        pid = int(pid_text)
        cmdline = background_process_args_for_pid(pid)
        if not cmdline:
            continue
        environ = background_process_environ_for_pid(pid)
        visible_devices = environ.get("CUDA_VISIBLE_DEVICES", "")
        if not visible_devices:
            continue
        text = f"{cmdline} {' '.join(f'{key}={value}' for key, value in environ.items())}".lower()
        role = ""
        if "hidream" in text or "imggen" in text:
            role = "本地画图"
        elif "embedding" in text or "--runner pooling" in text or "convert embed" in text:
            role = "Embedding"
        elif "qwen3.6" in text or "qwen3-35" in text or "vllm serve" in text:
            role = "本地 LLM"
        if not role:
            continue
        for index in background_parse_gpu_indices(visible_devices):
            role_by_index[index] = role
    return role_by_index


def background_gpu_processes() -> List[Dict[str, object]]:
    try:
        proc = subprocess.run(
            [
                "nvidia-smi",
                "--query-compute-apps=gpu_uuid,pid,process_name,used_memory",
                "--format=csv,noheader,nounits",
            ],
            check=False,
            capture_output=True,
            text=True,
            timeout=3,
        )
    except Exception:
        return []
    if proc.returncode != 0:
        return []
    rows: List[Dict[str, object]] = []
    for line in proc.stdout.splitlines():
        parts = [part.strip() for part in line.split(",")]
        if len(parts) < 4:
            continue
        try:
            pid = int(parts[1])
        except Exception:
            pid = 0
        rows.append(
            {
                "gpu_uuid": parts[0],
                "pid": pid,
                "process_name": background_mask_process_args(parts[2]),
                "used_memory_mb": float(parts[3]) if parts[3] else 0.0,
                "is_current_service": pid == os.getpid(),
            }
        )
    return rows


def background_is_local_model_gpu_process(process: Dict[str, object]) -> bool:
    text = f"{process.get('process_name', '')} {background_process_args_for_pid(int(process.get('pid') or 0))}".lower()
    keywords = (
        "vllm",
        "qwen",
        "embedding",
        "hidream",
        "imggen",
        "sglang",
        "ollama",
        "openai",
        "serve",
    )
    return any(keyword in text for keyword in keywords)


def background_process_args_for_pid(pid: int) -> str:
    if pid <= 0:
        return ""
    try:
        with open(f"/proc/{pid}/cmdline", "rb") as handle:
            raw = handle.read().replace(b"\x00", b" ")
    except Exception:
        return ""
    return background_mask_process_args(raw.decode("utf-8", errors="ignore"))


def background_process_environ_for_pid(pid: int) -> Dict[str, str]:
    if pid <= 0:
        return {}
    try:
        with open(f"/proc/{pid}/environ", "rb") as handle:
            raw = handle.read()
    except Exception:
        return {}
    environ: Dict[str, str] = {}
    for item in raw.split(b"\x00"):
        if not item or b"=" not in item:
            continue
        key, _, value = item.partition(b"=")
        environ[key.decode("utf-8", errors="ignore")] = value.decode("utf-8", errors="ignore")
    return environ


def build_background_overview() -> Dict[str, object]:
    init_db()
    generated_at = utc_now()
    with connect_db() as conn:
        table_stats = background_table_stats(conn)
        agent_rows, model_rows = background_trace_rows(conn)
        recent_windows = background_recent_windows(conn)
        summary = {
            "sessions": next((int(item["rows"]) for item in table_stats if item["name"] == "sessions"), 0),
            "messages": next((int(item["rows"]) for item in table_stats if item["name"] == "messages"), 0),
            "memories": next((int(item["rows"]) for item in table_stats if item["name"] == "curated_memories"), 0),
            "artifacts": next((int(item["rows"]) for item in table_stats if item["name"] == "idle_agent_artifacts"), 0),
            "images": next((int(item["rows"]) for item in table_stats if item["name"] == "generated_images"), 0),
            "characters": next((int(item["rows"]) for item in table_stats if item["name"] == "hidden_character_profiles"), 0),
            "pending_memory_jobs": 0,
            "running_memory_jobs": 0,
        }
        try:
            job_rows = conn.execute(
                """
                SELECT status, COUNT(*) AS c
                FROM memory_agent_jobs
                WHERE status IN ('pending', 'running')
                GROUP BY status
                """
            ).fetchall()
            for row in job_rows:
                summary[f"{row['status']}_memory_jobs"] = int(row["c"] or 0)
        except Exception:
            pass
    resource = {
        "cpu": background_cpu_usage(),
        "memory": background_read_proc_meminfo(),
        "disk": background_disk_usage(),
        "current_process": background_read_current_process(),
        "gpus": background_gpu_usage(),
        "image_storage": background_generated_image_storage(),
    }
    summary["db_size_bytes"] = int(resource["disk"].get("db_size_bytes", 0)) if isinstance(resource.get("disk"), dict) else 0
    summary["active_generations"] = len(ACTIVE_GENERATIONS)
    return {
        "generated_at": generated_at,
        "summary": summary,
        "agent_rows": agent_rows,
        "model_rows": model_rows,
        "table_stats": table_stats,
        "recent_windows": recent_windows,
        "resource": resource,
    }
