# Generated by splitting app.py lines 4030-6190. Keep execution order in wangcai_app/startup/loader.py.
def load_memory_agent_source_messages(
    session_id: str,
    start_message_id: int,
    end_message_id: int,
    context_turns: int = MEMORY_AGENT_CONTEXT_TURNS,
) -> List[Dict[str, object]]:
    with connect_db() as conn:
        anchor_users = conn.execute(
            """
            SELECT id
            FROM messages
            WHERE session_id = ?
              AND id <= ?
              AND status = 'completed'
              AND role = 'user'
              AND COALESCE(json_extract(metadata_json, '$.hidden'), 0) != 1
            ORDER BY id DESC
            LIMIT ?
            """,
            (session_id, int(start_message_id), max(1, int(context_turns))),
        ).fetchall()
        if not anchor_users:
            return []
        context_start_id = min(int(row["id"]) for row in anchor_users)
        opening_rows = conn.execute(
            """
            SELECT id, role, content, created_at, metadata_json
            FROM messages
            WHERE session_id = ?
              AND id < ?
              AND status = 'completed'
              AND role = 'assistant'
              AND COALESCE(json_extract(metadata_json, '$.opening_turn'), 0) = 1
            ORDER BY id DESC
            LIMIT 1
            """,
            (session_id, context_start_id),
        ).fetchall()
        rows = conn.execute(
            """
            SELECT id, role, content, created_at, metadata_json
            FROM messages
            WHERE session_id = ?
              AND id BETWEEN ? AND ?
              AND status = 'completed'
              AND role IN ('user', 'assistant')
            ORDER BY id ASC
            """,
            (session_id, context_start_id, int(end_message_id)),
        ).fetchall()
    merged_rows = list(reversed(opening_rows)) + list(rows)
    return [{key: row[key] for key in row.keys()} for row in merged_rows]


def format_messages_for_memory_agent(messages: List[Dict[str, object]]) -> str:
    lines = [
        "以下是最近对话片段。assistant_context_only 行仅用于理解上下文，不能作为记忆事实来源；只能从 user 行抽取长期记忆。",
        "",
        "[recent_dialogue]",
    ]
    has_visible_user = False
    last_user_was_visible = False
    for message in messages:
        role = str(message.get("role", "")).strip()
        content = str(message.get("content", "")).strip()
        if not content:
            continue
        timestamp = format_message_time_for_model(message.get("created_at", ""))
        time_part = f" time={timestamp}" if timestamp else ""
        if role == "user":
            if message_is_hidden(message):
                last_user_was_visible = False
                continue
            has_visible_user = True
            last_user_was_visible = True
            lines.append(f"[user{time_part}] {content}")
        elif role == "assistant" and message_is_opening_turn(message):
            lines.append(f"[assistant_context_only{time_part}] {content}")
            last_user_was_visible = False
        elif role == "assistant" and has_visible_user and last_user_was_visible:
            lines.append(f"[assistant_context_only{time_part}] {content}")
    if not has_visible_user:
        return ""
    return "\n".join(lines)


def memory_agent_context_message_window(
    session_id: str,
    start_message_id: int,
    end_message_id: int,
    context_turns: int = MEMORY_AGENT_CONTEXT_TURNS,
) -> Dict[str, object]:
    with connect_db() as conn:
        anchor_users = conn.execute(
            """
            SELECT id, created_at
            FROM messages
            WHERE session_id = ?
              AND id <= ?
              AND status = 'completed'
              AND role = 'user'
              AND COALESCE(json_extract(metadata_json, '$.hidden'), 0) != 1
            ORDER BY id DESC
            LIMIT ?
            """,
            (session_id, int(start_message_id), max(1, int(context_turns))),
        ).fetchall()
        end_row = conn.execute(
            "SELECT created_at FROM messages WHERE session_id = ? AND id = ?",
            (session_id, int(end_message_id)),
        ).fetchone()
    if not anchor_users:
        return {}
    context_start_id = min(int(row["id"]) for row in anchor_users)
    context_start_at = ""
    for row in anchor_users:
        if int(row["id"]) == context_start_id:
            context_start_at = str(row["created_at"] or "")
            break
    return {
        "start_message_id": context_start_id,
        "end_message_id": int(end_message_id),
        "start_at": context_start_at,
        "end_at": str(end_row["created_at"] or "") if end_row else utc_now(),
    }


def retrieve_recent_recalled_memories_for_agent(
    session_id: str,
    start_message_id: int,
    end_message_id: int,
    context_turns: int = MEMORY_AGENT_CONTEXT_TURNS,
    limit: int = 24,
) -> List[Dict[str, object]]:
    window = memory_agent_context_message_window(
        session_id,
        start_message_id,
        end_message_id,
        context_turns=context_turns,
    )
    if not window:
        return []
    with connect_db() as conn:
        retrieval_rows = conn.execute(
            """
            SELECT memory_ids_json, created_at
            FROM memory_retrieval_logs
            WHERE session_id = ?
              AND created_at >= ?
              AND created_at <= ?
            ORDER BY id ASC
            """,
            (session_id, str(window["start_at"]), str(window["end_at"])),
        ).fetchall()
        memory_ids: List[int] = []
        seen_ids = set()
        for row in retrieval_rows:
            for memory_id in safe_json_loads(row["memory_ids_json"]):
                try:
                    normalized_id = int(memory_id)
                except (TypeError, ValueError):
                    continue
                if normalized_id in seen_ids:
                    continue
                seen_ids.add(normalized_id)
                memory_ids.append(normalized_id)
                if len(memory_ids) >= max(1, int(limit)):
                    break
            if len(memory_ids) >= max(1, int(limit)):
                break
        if not memory_ids:
            return []
        in_clause, params = sql_in_clause_params(memory_ids)
        rows = conn.execute(
            f"""
            SELECT id, content, importance_label, timeline_at, timeline_start_at,
                   timeline_end_at, timeline_kind, confidence, updated_at
            FROM curated_memories
            WHERE id IN {in_clause}
              AND NOT EXISTS (
                SELECT 1 FROM curated_memories newer WHERE newer.supersedes_id = curated_memories.id
              )
            """,
            params,
        ).fetchall()
    by_id = {int(row["id"]): row for row in rows}
    memories: List[Dict[str, object]] = []
    for memory_id in memory_ids:
        row = by_id.get(memory_id)
        if row is None:
            continue
        memories.append(
            {
                "id": int(row["id"]),
                "content": str(row["content"] or "").strip(),
                "importance_label": str(row["importance_label"] or "other"),
                "timeline_at": str(row["timeline_at"] or row["updated_at"] or ""),
                "timeline_start_at": str(row["timeline_start_at"] or ""),
                "timeline_end_at": str(row["timeline_end_at"] or ""),
                "timeline_kind": str(row["timeline_kind"] or ""),
                "confidence": float(row["confidence"]) if row["confidence"] is not None else 0.7,
            }
        )
    return memories


def format_memory_reference_context_for_agent(
    session_id: str,
    start_message_id: Optional[int] = None,
    end_message_id: Optional[int] = None,
    limit: int = 8,
) -> str:
    with connect_db() as conn:
        session_row = conn.execute(
            "SELECT visitor_ip FROM sessions WHERE id = ?",
            (session_id,),
        ).fetchone()
    if not session_row:
        return ""
    visitor = normalize_visitor_ip(str(session_row["visitor_ip"] or ""))
    if not visitor or not is_device_identity(visitor):
        return ""

    recalled_memories: List[Dict[str, object]] = []
    if start_message_id is not None and end_message_id is not None:
        recalled_memories = retrieve_recent_recalled_memories_for_agent(
            session_id,
            int(start_message_id),
            int(end_message_id),
            limit=max(int(limit), 24),
        )
    future_events = retrieve_future_event_memories(visitor, limit=limit)
    recent_diary = retrieve_recent_diary_memories_for_opening(visitor, limit=limit)
    if not recalled_memories and not future_events and not recent_diary:
        return ""

    lines = [
        "[known_memory_context]",
        "以下是当前后台记忆整理覆盖的前 3 轮聊天中，聊天模型实际用过或最近开场可能注入过的长期记忆参考。",
        "它只用于判断 assistant_context_only 是否可能来自既有长期记忆，以及避免重复写入；不是新的 user 行事实来源。",
    ]
    if recalled_memories:
        lines.append("[recent_recalled_memories]")
        for item in recalled_memories:
            lines.append(
                f"- id={item.get('id')} time={item.get('timeline_at', '')} "
                f"label={item.get('importance_label', 'other')} "
                f"confidence={float(item.get('confidence', 0.7)):.2f} "
                f"content={str(item.get('content', '')).strip()}"
            )
    if future_events:
        lines.append("[known_events]")
        for item in future_events:
            lines.append(
                f"- id={item.get('id')} time={timeline_display_text(item)} "
                f"confidence={float(item.get('confidence', 0.7)):.2f} "
                f"content={str(item.get('content', '')).strip()}"
            )
    if recent_diary:
        lines.append("[known_recent_diary]")
        for item in recent_diary:
            lines.append(
                f"- id={item.get('id')} time={item.get('timeline_at', '')} "
                f"label={item.get('importance_label', 'diary')} "
                f"confidence={float(item.get('confidence', 0.7)):.2f} "
                f"content={str(item.get('content', '')).strip()}"
            )
    return "\n".join(lines).strip()


def append_memory_reference_context_for_agent(
    source: str,
    session_id: str,
    start_message_id: Optional[int] = None,
    end_message_id: Optional[int] = None,
) -> str:
    base = str(source or "").strip()
    reference_context = format_memory_reference_context_for_agent(
        session_id,
        start_message_id=start_message_id,
        end_message_id=end_message_id,
    )
    if not base or not reference_context:
        return base
    return f"{base}\n\n{reference_context}"


def memory_agent_user_text_from_source(source: str) -> str:
    user_lines = []
    for line in str(source or "").splitlines():
        if line.startswith("[user"):
            _, _, content = line.partition("]")
            user_lines.append(content.strip())
    return "\n".join(user_lines).strip()


def memory_agent_assistant_context_text_from_source(source: str) -> str:
    assistant_lines = []
    for line in str(source or "").splitlines():
        if line.startswith("[assistant_context_only"):
            _, _, content = line.partition("]")
            assistant_lines.append(content.strip())
    return "\n".join(assistant_lines).strip()


def normalize_compact_text(text: str) -> str:
    return re.sub(r"\s+", "", str(text or "")).strip()


def memory_write_dedupe_threshold(label: str) -> float:
    normalized = normalize_memory_label(label)
    if normalized == "event":
        return MEMORY_WRITE_EVENT_DEDUPE_THRESHOLD
    if normalized in {"diary", "risk"}:
        return MEMORY_WRITE_DIARY_DEDUPE_THRESHOLD
    return MEMORY_WRITE_DEDUPE_THRESHOLD


def build_memory_agent_user_prompt(source: str) -> str:
    return (
        f"当前真实时间：{opening_time_text()}。\n"
        "请判断下面这一段最近对话是否值得写入长期记忆。"
        "注意：assistant_context_only 只是语境，不是事实来源；最终记忆只能来自 user 行及其前后文指代。\n\n"
        f"{source}"
    )


def build_memory_validation_user_prompt(item: Dict[str, object], source: str) -> str:
    label = normalize_memory_label(item.get("label", "other"))
    memory_text = str(item.get("memory", "")).strip()
    timeline_fields = timeline_item_fields(item)
    return (
        f"当前真实时间：{opening_time_text()}。\n\n"
        "[候选记忆]\n"
        f"label: {label}\n"
        f"timeline_at: {timeline_fields['timeline_at']}\n"
        f"timeline_start_at: {timeline_fields['timeline_start_at']}\n"
        f"timeline_end_at: {timeline_fields['timeline_end_at']}\n"
        f"timeline_kind: {timeline_fields['timeline_kind']}\n"
        f"memory: {memory_text}\n\n"
        "[最近对话片段]\n"
        f"{source}\n\n"
        "请核验该候选记忆是否确实来自 user 行。"
    )


def parse_memory_validation_response(text: str) -> Dict[str, object]:
    cleaned = str(text or "").strip()
    if cleaned.startswith("```"):
        cleaned = re.sub(r"^```(?:json)?\s*", "", cleaned)
        cleaned = re.sub(r"\s*```$", "", cleaned)
    try:
        parsed = json.loads(cleaned)
    except json.JSONDecodeError:
        match = re.search(r"\{.*\}", cleaned, flags=re.S)
        parsed = json.loads(match.group(0)) if match else {}
    decision = {
        "valid": bool(parsed.get("valid")),
        "reason": clean_search_text(str(parsed.get("reason", "") or ""), 1000),
    }
    corrected_item = parsed.get("corrected_item")
    if isinstance(corrected_item, dict):
        memory_text = clean_search_text(str(corrected_item.get("memory", "") or ""), 1200)
        if memory_text:
            decision["corrected_item"] = {
                "label": str(corrected_item.get("label", "other") or "other"),
                "memory": memory_text,
                "timeline_at": str(corrected_item.get("timeline_at", "") or ""),
                "timeline_start_at": str(corrected_item.get("timeline_start_at", "") or ""),
                "timeline_end_at": str(corrected_item.get("timeline_end_at", "") or ""),
                "timeline_kind": str(corrected_item.get("timeline_kind", "") or ""),
                "confidence": corrected_item.get("confidence", 0.7),
            }
    return decision


def call_memory_validation_model(
    item: Dict[str, object],
    source: str,
    session_id: str = "",
    visitor_ip: str = "local",
    analysis_trace_id: str = "",
) -> Dict[str, object]:
    messages = [
        {"role": "system", "content": MEMORY_VALIDATION_SYSTEM_PROMPT},
        {"role": "user", "content": build_memory_validation_user_prompt(item, source)},
    ]
    started = time.perf_counter()
    client, http_client, model_slot = openai_client_for_slot(
        MODEL_SLOT_BACKGROUND,
        timeout=MEMORY_VALIDATION_TIMEOUT,
    )
    try:
        resp = client.chat.completions.create(
            **model_completion_kwargs(model_slot),
            messages=messages,
            temperature=MEMORY_VALIDATION_TEMPERATURE,
            top_p=0.8,
            max_tokens=MEMORY_VALIDATION_MAX_TOKENS,
        )
        content = resp.choices[0].message.content or ""
        _, answer = split_think_text(content)
        decision = parse_memory_validation_response(answer)
        if analysis_trace_id:
            record_analysis_trace(
                session_id=session_id,
                trace_id=analysis_trace_id,
                event_type="model_call",
                visitor_ip=visitor_ip,
                step_name="memory_candidate_validation",
                duration_ms=round((time.perf_counter() - started) * 1000, 3),
                payload={
                    "model": model_slot.get("model", MODEL_NAME),
                    "messages": messages,
                    "decision": decision,
                },
            )
        return decision
    except Exception as exc:
        if analysis_trace_id:
            record_analysis_trace(
                session_id=session_id,
                trace_id=analysis_trace_id,
                event_type="model_call_error",
                visitor_ip=visitor_ip,
                step_name="memory_candidate_validation",
                duration_ms=round((time.perf_counter() - started) * 1000, 3),
                payload={
                    "model": model_slot.get("model", MODEL_NAME),
                    "messages": messages,
                    "error": str(exc),
                },
            )
        return {"valid": True, "reason": f"validation unavailable: {exc}"}
    finally:
        http_client.close()


def event_update_candidate_keywords(source: str) -> bool:
    text = memory_agent_user_text_from_source(source)
    if not text:
        return False
    markers = (
        "完成", "结束", "搞定", "处理了", "提交", "交了", "已请假", "请假了", "不去了", "取消",
        "改成", "改为", "换成", "不是", "而是", "说错", "更正", "调整", "提前", "推迟", "延期",
        "地点", "时间", "要求", "提醒", "日程", "会议", "演出", "考试", "截止", "ddl", "DDL",
    )
    return any(marker in text for marker in markers)


def load_event_update_candidates(session_id: str, limit: int = EVENT_MEMORY_UPDATER_CANDIDATE_LIMIT) -> List[Dict[str, object]]:
    max_rows = min(max(int(limit), 1), 30)
    with connect_db() as conn:
        session_row = conn.execute(
            "SELECT visitor_ip FROM sessions WHERE id = ?",
            (session_id,),
        ).fetchone()
        if session_row is None:
            return []
        device_id = normalize_visitor_ip(str(session_row["visitor_ip"] or ""))
        if not device_id or not is_device_identity(device_id):
            return []
        scope = binding_scope_for_device(conn, device_id)
        scoped_devices = list(scope.get("device_ids") or [device_id])
        if device_id not in scoped_devices:
            scoped_devices.insert(0, device_id)
        in_clause, params = sql_in_clause_params(scoped_devices)
        rows = conn.execute(
            f"""
            SELECT id, content, importance_label, visitor_ip,
                   timeline_at, timeline_start_at, timeline_end_at, timeline_kind,
                   supersedes_id, confidence, updated_at
            FROM curated_memories
            WHERE visitor_ip IN {in_clause}
              AND importance_label = 'event'
              AND id NOT IN (
                SELECT supersedes_id FROM curated_memories WHERE supersedes_id IS NOT NULL
              )
            ORDER BY
              CASE WHEN visitor_ip = ? THEN 0 ELSE 1 END,
              COALESCE(timeline_at, timeline_start_at, timeline_end_at, updated_at) DESC,
              id DESC
            LIMIT ?
            """,
            (*params, device_id, max_rows),
        ).fetchall()
    return [row_to_dict(row) for row in rows]


def build_event_memory_updater_prompt(source: str, candidates: List[Dict[str, object]]) -> str:
    lines = [
        f"当前真实时间：{opening_time_text()}。",
        "请判断最近对话是否在实时修改、完成、取消或更正已有 event 记忆。",
        "只根据 user 行的新信息行动；assistant_context_only 仅用于理解前文指代。",
        "",
        source,
        "",
        "[candidate_events]",
    ]
    for item in candidates:
        lines.append(
            f"ID: {item.get('id')}\n"
            f"time: {timeline_display_text(item) or item.get('updated_at') or ''}\n"
            f"content: {str(item.get('content') or '').strip()}\n"
            f"confidence: {float(item.get('confidence') or 0.7):.2f}\n"
            "---"
        )
    return "\n".join(lines).strip()


def parse_event_memory_updater_response(text: str) -> Dict[str, object]:
    cleaned = str(text or "").strip()
    if cleaned.startswith("```"):
        cleaned = re.sub(r"^```(?:json)?\s*", "", cleaned)
        cleaned = re.sub(r"\s*```$", "", cleaned)
    match = re.search(r"\{.*\}", cleaned, flags=re.S)
    if match:
        cleaned = match.group(0)
    try:
        payload = json.loads(cleaned)
    except Exception:
        return {"action": "noop", "rationale": "event updater returned invalid json", "items": []}
    if not isinstance(payload, dict):
        return {"action": "noop", "rationale": "event updater returned non-object", "items": []}
    action = str(payload.get("action") or "noop").strip().lower()
    if action not in {"noop", "update", "complete", "cancel"}:
        action = "noop"
    label = normalize_memory_label(payload.get("label") or "event")
    if label not in {"event", "diary"}:
        label = "event"
    try:
        supersedes_id = int(payload.get("supersedes_id")) if payload.get("supersedes_id") is not None else None
    except Exception:
        supersedes_id = None
    try:
        confidence = min(1.0, max(0.0, float(payload.get("confidence", 0.75))))
    except Exception:
        confidence = 0.75
    return {
        "action": action,
        "rationale": str(payload.get("rationale") or "").strip(),
        "supersedes_id": supersedes_id,
        "label": label,
        "memory": str(payload.get("memory") or "").strip(),
        "timeline_at": str(payload.get("timeline_at") or "").strip(),
        "timeline_start_at": str(payload.get("timeline_start_at") or "").strip(),
        "timeline_end_at": str(payload.get("timeline_end_at") or "").strip(),
        "timeline_kind": normalize_timeline_kind(payload.get("timeline_kind")),
        "confidence": confidence,
    }


def call_event_memory_updater_model(
    source: str,
    candidates: List[Dict[str, object]],
    session_id: str = "",
    trace_id: str = "",
    visitor: str = "local",
) -> Dict[str, object]:
    prompt = build_event_memory_updater_prompt(source, candidates)
    if trace_id:
        record_analysis_trace(
            session_id=session_id,
            trace_id=trace_id,
            event_type="memory_agent",
            visitor_ip=visitor,
            step_name="event_memory_updater_prompt",
            payload={"prompt": prompt, "candidate_count": len(candidates)},
    )
    started = time.perf_counter()
    client, http_client, model_slot = openai_client_for_slot(MODEL_SLOT_BACKGROUND, timeout=REQUEST_TIMEOUT)
    try:
        resp = client.chat.completions.create(
            **model_completion_kwargs(model_slot),
            messages=[
                {"role": "system", "content": EVENT_MEMORY_UPDATER_SYSTEM_PROMPT},
                {"role": "user", "content": prompt},
            ],
            temperature=0.2,
            top_p=0.8,
            max_tokens=1024,
        )
        msg = resp.choices[0].message
        _reasoning, answer = split_think_text(getattr(msg, "content", "") or "")
        decision = parse_event_memory_updater_response(answer)
        if trace_id:
            record_analysis_trace(
                session_id=session_id,
                trace_id=trace_id,
                event_type="model_call",
                visitor_ip=visitor,
                step_name="event_memory_updater_model",
                duration_ms=round((time.perf_counter() - started) * 1000, 3),
                payload={"model": model_slot.get("model", MODEL_NAME), "decision": decision},
            )
        return decision
    except Exception as exc:
        if trace_id:
            record_analysis_trace(
                session_id=session_id,
                trace_id=trace_id,
                event_type="model_call_error",
                visitor_ip=visitor,
                step_name="event_memory_updater_model",
                duration_ms=round((time.perf_counter() - started) * 1000, 3),
                payload={"model": model_slot.get("model", MODEL_NAME), "error": str(exc)},
            )
        return {"action": "noop", "rationale": f"event updater error: {exc}"}
    finally:
        http_client.close()


def run_event_memory_updater(
    session_id: str,
    start_message_id: int,
    end_message_id: int,
    source: str,
    trace_id: str = "",
    visitor: str = "local",
) -> Dict[str, object]:
    if not event_update_candidate_keywords(source):
        return {"status": "skipped", "reason": "no_event_update_marker"}
    candidates = load_event_update_candidates(session_id)
    if not candidates:
        return {"status": "skipped", "reason": "no_event_candidates"}
    decision = call_event_memory_updater_model(source, candidates, session_id=session_id, trace_id=trace_id, visitor=visitor)
    action = str(decision.get("action") or "noop")
    if action == "noop":
        return {"status": "noop", "decision": decision, "candidate_count": len(candidates)}
    supersedes_id = decision.get("supersedes_id")
    candidate_ids = {int(item.get("id")) for item in candidates if item.get("id") is not None}
    if supersedes_id is None or int(supersedes_id) not in candidate_ids:
        return {"status": "skipped", "reason": "invalid_supersedes", "decision": decision, "candidate_count": len(candidates)}
    memory_text = str(decision.get("memory") or "").strip()
    if not memory_text:
        return {"status": "skipped", "reason": "empty_memory", "decision": decision, "candidate_count": len(candidates)}
    label = normalize_memory_label(decision.get("label") or "event")
    if label not in {"event", "diary"}:
        label = "event"
    memory_id = save_curated_memory(
        session_id,
        int(start_message_id),
        int(end_message_id),
        memory_text,
        importance_label=label,
        timeline_at=str(decision.get("timeline_at") or "").strip() or None,
        timeline_start_at=str(decision.get("timeline_start_at") or "").strip() or None,
        timeline_end_at=str(decision.get("timeline_end_at") or "").strip() or None,
        timeline_kind=str(decision.get("timeline_kind") or "").strip() or None,
        supersedes_id=int(supersedes_id),
        confidence=float(decision.get("confidence") or 0.75),
    )
    try:
        vector = embedding_client.embed_text(memory_text)
        upsert_curated_memory_vector(memory_id, vector, embedding_client.EMBEDDING_MODEL)
    except Exception as exc:
        record_analysis_trace(
            "memory-agent",
            event_type="embedding_error",
            visitor_ip="local",
            step_name="event_memory_update_embedding",
            payload={"memory_id": memory_id, "error": str(exc)},
        )
    record_event(
        session_id,
        "event_memory_live_update",
        "local",
        {
            "action": action,
            "memory_id": memory_id,
            "supersedes_id": int(supersedes_id),
            "label": label,
            "rationale": decision.get("rationale"),
        },
    )
    return {
        "status": "updated",
        "action": action,
        "memory_id": memory_id,
        "supersedes_id": int(supersedes_id),
        "label": label,
        "decision": decision,
    }


def memory_source_hash(session_id: str, start_message_id: int, end_message_id: int, source: str) -> str:
    payload = {
        "session_id": session_id,
        "start_message_id": int(start_message_id),
        "end_message_id": int(end_message_id),
        "source_hash": vector_memory.content_hash(source),
    }
    return vector_memory.content_hash(json.dumps(payload, ensure_ascii=False, sort_keys=True))


def save_curated_memory(
    source_session_id: str,
    start_message_id: int,
    end_message_id: int,
    content: str,
    importance_label: str = "other",
    timeline_at: Optional[str] = None,
    timeline_start_at: Optional[str] = None,
    timeline_end_at: Optional[str] = None,
    timeline_kind: Optional[str] = None,
    supersedes_id: Optional[int] = None,
    confidence: float = 0.7,
) -> int:
    text = content.strip()
    if not text:
        raise ValueError("curated memory content is empty")
    source_digest = memory_source_hash(source_session_id, start_message_id, end_message_id, text)
    now = utc_now()
    timeline_value = timeline_at or now
    timeline_start_value = (timeline_start_at or "").strip() or None
    timeline_end_value = (timeline_end_at or "").strip() or None
    timeline_kind_value = normalize_timeline_kind(timeline_kind)
    confidence_value = min(1.0, max(0.0, float(confidence)))
    with connect_db() as conn:
        visitor_ip = None
        profile_id = None
        session_row = conn.execute(
            "SELECT visitor_ip, user_agent FROM sessions WHERE id = ?",
            (source_session_id,),
        ).fetchone()
        if session_row and is_device_identity(str(session_row["visitor_ip"])):
            source_device_ip = normalize_visitor_ip(str(session_row["visitor_ip"]))
            visitor_ip = shared_memory_owner_device_id(conn, source_device_ip, text, importance_label or "other")
            profile_id = observe_visitor_identity(
                conn,
                visitor_ip,
                str(session_row["user_agent"] or ""),
            )
        conn.execute(
            """
            INSERT INTO curated_memories (
                source_session_id, start_message_id, end_message_id, source_hash,
                content, importance_label, visitor_ip, profile_id,
                timeline_at, timeline_start_at, timeline_end_at, timeline_kind,
                supersedes_id, confidence, created_at, updated_at
            )
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            ON CONFLICT(source_hash) DO UPDATE SET
                content = excluded.content,
                importance_label = excluded.importance_label,
                visitor_ip = excluded.visitor_ip,
                profile_id = excluded.profile_id,
                timeline_at = excluded.timeline_at,
                timeline_start_at = excluded.timeline_start_at,
                timeline_end_at = excluded.timeline_end_at,
                timeline_kind = excluded.timeline_kind,
                supersedes_id = excluded.supersedes_id,
                confidence = excluded.confidence,
                updated_at = excluded.updated_at
            """,
            (
                source_session_id,
                int(start_message_id),
                int(end_message_id),
                source_digest,
                text,
                importance_label or "other",
                visitor_ip,
                profile_id,
                timeline_value,
                timeline_start_value,
                timeline_end_value,
                timeline_kind_value,
                int(supersedes_id) if supersedes_id is not None else None,
                confidence_value,
                now,
                now,
            ),
        )
        row = conn.execute(
            "SELECT id FROM curated_memories WHERE source_hash = ?",
            (source_digest,),
        ).fetchone()
    memory_id = int(row["id"])
    if visitor_ip:
        try:
            refresh_binding_scoped_opening_prompts(visitor_ip)
        except Exception:
            pass
    return memory_id


def upsert_curated_memory_vector(memory_id: int, vector: object, model_name: str) -> None:
    arr = vector_memory.normalize_vector(vector)
    with connect_db() as conn:
        conn.execute(
            """
            INSERT INTO curated_memory_vectors (memory_id, dim, vector, model_name, created_at)
            VALUES (?, ?, ?, ?, ?)
            ON CONFLICT(memory_id) DO UPDATE SET
                dim = excluded.dim,
                vector = excluded.vector,
                model_name = excluded.model_name,
                created_at = excluded.created_at
            """,
            (int(memory_id), int(arr.shape[0]), arr.tobytes(), model_name, utc_now()),
        )


def upsert_global_character_memory(
    character_id: int,
    content: str,
    owner_device_id: str,
    confidence: float = 0.85,
) -> int:
    text = str(content or "").strip()
    if int(character_id) <= 0:
        raise ValueError("character_id must be positive")
    if not text:
        raise ValueError("global character memory content is empty")
    owner_device = normalize_visitor_ip(owner_device_id)
    if not owner_device or not is_device_identity(owner_device):
        raise ValueError("character memory owner device is required")
    source_session_id = f"character-profile-{int(character_id)}"
    source_digest = memory_source_hash(source_session_id, 0, int(character_id), "global-character-profile")
    now = utc_now()
    confidence_value = min(1.0, max(0.0, float(confidence)))
    vector = embedding_client.embed_text(text)
    with connect_db() as conn:
        conn.execute(
            """
            INSERT INTO curated_memories (
                source_session_id, start_message_id, end_message_id, source_hash,
                content, importance_label, visitor_ip, profile_id,
                timeline_at, timeline_start_at, timeline_end_at, timeline_kind,
                confidence, created_at, updated_at
            )
            VALUES (?, 0, ?, ?, ?, 'characters', ?, NULL, ?, NULL, NULL, 'point', ?, ?, ?)
            ON CONFLICT(source_hash) DO UPDATE SET
                content = excluded.content,
                importance_label = 'characters',
                visitor_ip = excluded.visitor_ip,
                profile_id = NULL,
                timeline_at = excluded.timeline_at,
                timeline_start_at = NULL,
                timeline_end_at = NULL,
                timeline_kind = 'point',
                confidence = excluded.confidence,
                updated_at = excluded.updated_at
            """,
            (
                source_session_id,
                int(character_id),
                source_digest,
                text,
                owner_device,
                now,
                confidence_value,
                now,
                now,
            ),
        )
        row = conn.execute(
            "SELECT id FROM curated_memories WHERE source_hash = ? LIMIT 1",
            (source_digest,),
        ).fetchone()
    memory_id = int(row["id"])
    upsert_curated_memory_vector(memory_id, vector, embedding_client.EMBEDDING_MODEL)
    return memory_id


def delete_global_character_memory(character_id: int) -> int:
    source_session_id = f"character-profile-{int(character_id)}"
    with connect_db() as conn:
        cur = conn.execute(
            """
            DELETE FROM curated_memories
            WHERE source_session_id = ?
              AND importance_label = 'characters'
            """,
            (source_session_id,),
        )
    return int(cur.rowcount or 0)


def refresh_duplicate_curated_memory(memory_id: int) -> bool:
    now = utc_now()
    with connect_db() as conn:
        cur = conn.execute(
            """
            UPDATE curated_memories
            SET timeline_at = ?,
                updated_at = ?
            WHERE id = ?
            """,
            (now, now, int(memory_id)),
        )
    return cur.rowcount > 0


def find_similar_curated_memory(candidate_vector: object, label: str = "") -> Optional[Dict[str, object]]:
    return find_similar_curated_memory_in_scope(candidate_vector, label=label)


def memory_write_scope_device_ids(source_session_id: str, label: str = "other") -> List[str]:
    with connect_db() as conn:
        row = conn.execute(
            "SELECT visitor_ip FROM sessions WHERE id = ?",
            (source_session_id,),
        ).fetchone()
        if row is None:
            return []
        source_device_id = normalize_visitor_ip(str(row["visitor_ip"] or ""))
        if not source_device_id or not is_device_identity(source_device_id):
            return []
        owner_device_id = shared_memory_owner_device_id(conn, source_device_id, "", label or "other")
        if owner_device_id:
            return [owner_device_id]
        scope = binding_scope_for_device(conn, source_device_id)
        return list(scope.get("device_ids") or [source_device_id])


def find_similar_curated_memory_in_scope(
    candidate_vector: object,
    label: str = "",
    device_ids: Optional[List[str]] = None,
) -> Optional[Dict[str, object]]:
    query = vector_memory.normalize_vector(candidate_vector)
    clauses = ["m.importance_label != 'artifact'"]
    params: List[object] = []
    if device_ids is not None:
        if not device_ids:
            return None
        in_clause, in_params = sql_in_clause_params(device_ids)
        clauses.append(f"m.visitor_ip IN {in_clause}")
        params.extend(in_params)
    else:
        clauses.append("m.visitor_ip LIKE 'device:%'")
    if label:
        clauses.append("m.importance_label = ?")
        params.append(label)
    where = " AND ".join(clauses)
    with connect_db() as conn:
        rows = conn.execute(
            f"""
            SELECT m.id, m.content, m.importance_label, v.dim, v.vector
            FROM curated_memories m
            JOIN curated_memory_vectors v ON v.memory_id = m.id
            WHERE {where}
            ORDER BY m.id DESC
            LIMIT 1000
            """,
            params,
        ).fetchall()
    best: Optional[Dict[str, object]] = None
    for row in rows:
        vector = vector_memory.blob_to_vector(row["vector"], int(row["dim"]))
        if vector.shape != query.shape:
            continue
        score = float(vector.dot(query))
        if best is None or score > float(best["score"]):
            best = {
                "id": int(row["id"]),
                "content": str(row["content"]),
                "importance_label": str(row["importance_label"]),
                "score": score,
            }
    return best


def normalized_memory_similarity(left: str, right: str) -> float:
    left_norm = normalize_compact_text(left)
    right_norm = normalize_compact_text(right)
    if not left_norm or not right_norm:
        return 0.0
    if left_norm == right_norm:
        return 1.0
    if left_norm in right_norm or right_norm in left_norm:
        return 0.94
    return SequenceMatcher(None, left_norm, right_norm).ratio()


def recent_memory_write_duplicate(
    source_session_id: str,
    memory_text: str,
    label: str,
    device_ids: Optional[List[str]] = None,
    limit: int = 3,
) -> Optional[Dict[str, object]]:
    scoped_devices = device_ids if device_ids is not None else memory_write_scope_device_ids(source_session_id, label)
    if not scoped_devices:
        return None
    in_clause, params = sql_in_clause_params(scoped_devices)
    with connect_db() as conn:
        rows = conn.execute(
            f"""
            SELECT id, content, importance_label, updated_at
            FROM curated_memories
            WHERE visitor_ip IN {in_clause}
              AND importance_label = ?
              AND importance_label != 'artifact'
            ORDER BY id DESC
            LIMIT ?
            """,
            (*params, label, max(1, int(limit))),
        ).fetchall()
    for row in rows:
        score = normalized_memory_similarity(memory_text, str(row["content"] or ""))
        if score >= MEMORY_RECENT_WRITE_TEXT_SIMILARITY:
            return {
                "id": int(row["id"]),
                "content": str(row["content"] or ""),
                "importance_label": str(row["importance_label"] or ""),
                "score": score,
            }
    return None


def memory_text_has_explicit_change(text: str) -> bool:
    markers = ("改为", "更改", "变成", "不再", "以后", "从现在起", "纠正", "不是", "而是")
    return bool(text) and any(marker in text for marker in markers)


def create_admin_memory(
    content: str,
    importance_label: str = "other",
    visitor_ip: str = "",
    timeline_at: str = "",
    timeline_start_at: str = "",
    timeline_end_at: str = "",
    timeline_kind: str = "",
) -> int:
    text = content.strip()
    if not text:
        raise ValueError("admin memory content is empty")
    label = (importance_label or "other").strip() or "other"
    timeline = (timeline_at or "").strip() or utc_now()
    timeline_start = (timeline_start_at or "").strip() or None
    timeline_end = (timeline_end_at or "").strip() or None
    timeline_kind_value = normalize_timeline_kind(timeline_kind)
    vector = embedding_client.embed_text(text)
    source_session_id = f"admin-{uuid.uuid4().hex}"
    source_digest = memory_source_hash(source_session_id, 0, 0, text)
    now = utc_now()
    ip = normalize_visitor_ip(visitor_ip) if visitor_ip and visitor_ip.strip() else None
    profile_id = None
    with connect_db() as conn:
        if ip:
            ip = shared_memory_owner_device_id(conn, ip, text, label)
            profile_id = observe_visitor_identity(conn, ip, "admin")
        cur = conn.execute(
            """
            INSERT INTO curated_memories (
                source_session_id, start_message_id, end_message_id, source_hash,
                content, importance_label, visitor_ip, profile_id,
                timeline_at, timeline_start_at, timeline_end_at, timeline_kind,
                confidence, created_at, updated_at
            )
            VALUES (?, 0, 0, ?, ?, ?, ?, ?, ?, ?, ?, ?, 0.8, ?, ?)
            """,
            (
                source_session_id,
                source_digest,
                text,
                label,
                ip,
                profile_id,
                timeline,
                timeline_start,
                timeline_end,
                timeline_kind_value,
                now,
                now,
            ),
        )
        memory_id = int(cur.lastrowid)
    upsert_curated_memory_vector(memory_id, vector, embedding_client.EMBEDDING_MODEL)
    if ip:
        try:
            refresh_binding_scoped_opening_prompts(ip)
        except Exception:
            pass
    return memory_id


def update_admin_memory(
    memory_id: int,
    content: str,
    importance_label: str = "other",
    timeline_at: Optional[str] = None,
    timeline_start_at: Optional[str] = None,
    timeline_end_at: Optional[str] = None,
    timeline_kind: Optional[str] = None,
    visitor_ip: Optional[str] = None,
) -> bool:
    text = content.strip()
    if not text:
        raise ValueError("admin memory content is empty")
    label = (importance_label or "other").strip() or "other"
    timeline = (timeline_at or "").strip() if timeline_at is not None else None
    should_update_timeline = timeline_at is not None
    timeline_start = (timeline_start_at or "").strip() if timeline_start_at is not None else None
    timeline_end = (timeline_end_at or "").strip() if timeline_end_at is not None else None
    normalized_kind = normalize_timeline_kind(timeline_kind) if timeline_kind is not None else None
    should_update_timeline_range = (
        timeline_start_at is not None or timeline_end_at is not None or timeline_kind is not None
    )
    vector = embedding_client.embed_text(text)
    memory_ip = ""
    with connect_db() as conn:
        row = conn.execute(
            "SELECT visitor_ip FROM curated_memories WHERE id = ?",
            (int(memory_id),),
        ).fetchone()
        if row is None:
            return False
        old_ip = str(row["visitor_ip"] or "")
        new_ip = old_ip
        profile_id = None
        if visitor_ip is not None:
            requested_ip = normalize_visitor_ip(visitor_ip) if visitor_ip.strip() else None
            new_ip = requested_ip or ""
            if requested_ip:
                profile_id = observe_visitor_identity(conn, requested_ip, "admin")
        elif old_ip:
            profile_id = observe_visitor_identity(conn, old_ip, "admin")
        memory_ip = new_ip or old_ip
        cur = conn.execute(
            """
            UPDATE curated_memories
            SET content = ?,
                importance_label = ?,
                visitor_ip = ?,
                profile_id = ?,
                timeline_at = CASE WHEN ? THEN ? ELSE timeline_at END,
                timeline_start_at = CASE WHEN ? THEN ? ELSE timeline_start_at END,
                timeline_end_at = CASE WHEN ? THEN ? ELSE timeline_end_at END,
                timeline_kind = CASE WHEN ? THEN ? ELSE timeline_kind END,
                updated_at = ?
            WHERE id = ?
            """,
            (
                text,
                label,
                new_ip or None,
                profile_id,
                int(should_update_timeline),
                timeline or None,
                int(should_update_timeline_range),
                timeline_start or None,
                int(should_update_timeline_range),
                timeline_end or None,
                int(should_update_timeline_range),
                normalized_kind or None,
                utc_now(),
                int(memory_id),
            ),
        )
        updated = cur.rowcount > 0
    if updated:
        upsert_curated_memory_vector(int(memory_id), vector, embedding_client.EMBEDDING_MODEL)
        if memory_ip:
            try:
                refresh_binding_scoped_opening_prompts(memory_ip)
            except Exception:
                pass
    return updated


def delete_admin_memory(memory_id: int) -> bool:
    with connect_db() as conn:
        row = conn.execute(
            "SELECT visitor_ip FROM curated_memories WHERE id = ?",
            (int(memory_id),),
        ).fetchone()
        memory_ip = str(row["visitor_ip"] or "") if row else ""
        cur = conn.execute("DELETE FROM curated_memories WHERE id = ?", (int(memory_id),))
    if cur.rowcount > 0 and memory_ip:
        try:
            refresh_binding_scoped_opening_prompts(memory_ip)
        except Exception:
            pass
    return cur.rowcount > 0


def list_admin_memories(
    keyword: str = "",
    label: str = "",
    visitor_ip_filter: str = "",
    limit: int = 200,
    device_ids: Optional[List[str]] = None,
) -> Dict[str, object]:
    if device_ids is not None and not device_ids:
        return {"total": 0, "items": []}
    clauses = [
        "importance_label NOT IN ('artifact', 'characters')",
        "source_session_id NOT LIKE 'artifact-%'",
        "source_session_id NOT LIKE 'character-profile-%'",
    ]
    params: List[object] = []
    if device_ids is not None:
        placeholders = ", ".join("?" for _ in device_ids)
        clauses.append(f"visitor_ip IN ({placeholders})")
        params.extend(device_ids)
    if keyword.strip():
        clauses.append("content LIKE ?")
        params.append(f"%{keyword.strip()}%")
    if label.strip():
        clauses.append("importance_label = ?")
        params.append(label.strip())
    if visitor_ip_filter.strip():
        clauses.append("visitor_ip = ?")
        params.append(normalize_visitor_ip(visitor_ip_filter))
    where = f"WHERE {' AND '.join(clauses)}" if clauses else ""
    max_rows = min(max(int(limit), 1), 1000)
    with connect_db() as conn:
        rows = conn.execute(
            f"""
            SELECT id, source_session_id, start_message_id, end_message_id,
                   content, importance_label, visitor_ip, profile_id,
                   timeline_at, timeline_start_at, timeline_end_at, timeline_kind,
                   supersedes_id, confidence,
                   refine_status, refined_at, refined_from_id, refine_reason,
                   created_at, updated_at
            FROM curated_memories
            {where}
            ORDER BY id DESC
            LIMIT ?
            """,
            (*params, max_rows),
        ).fetchall()
        total = conn.execute(
            f"SELECT COUNT(*) AS c FROM curated_memories {where}",
            params,
        ).fetchone()["c"]
    return {
        "total": int(total),
        "items": [
            {
                "id": int(row["id"]),
                "source_session_id": str(row["source_session_id"]),
                "message_range": [int(row["start_message_id"]), int(row["end_message_id"])],
                "content": str(row["content"]),
                "importance_label": str(row["importance_label"]),
                "visitor_ip": str(row["visitor_ip"]) if row["visitor_ip"] else None,
                "device_id": str(row["visitor_ip"]) if row["visitor_ip"] else None,
                "profile_id": int(row["profile_id"]) if row["profile_id"] is not None else None,
                "timeline_at": str(row["timeline_at"] or ""),
                "timeline_start_at": str(row["timeline_start_at"] or ""),
                "timeline_end_at": str(row["timeline_end_at"] or ""),
                "timeline_kind": str(row["timeline_kind"] or ""),
                "supersedes_id": int(row["supersedes_id"]) if row["supersedes_id"] is not None else None,
                "confidence": float(row["confidence"]) if row["confidence"] is not None else 0.7,
                "refine_status": str(row["refine_status"] or ""),
                "refined_at": str(row["refined_at"] or ""),
                "refined_from_id": int(row["refined_from_id"]) if row["refined_from_id"] is not None else None,
                "refine_reason": str(row["refine_reason"] or ""),
                "created_at": str(row["created_at"]),
                "updated_at": str(row["updated_at"]),
            }
            for row in rows
        ],
    }


MEMORY_TOPIC_GROUPS = (
    ("语文", "数学", "英语", "物理", "化学", "生物", "历史", "地理", "政治"),
    ("北京", "河北", "上海", "广东", "浙江", "江苏", "河南", "山东", "四川", "湖北", "湖南"),
)
MEMORY_GENERIC_RETRIEVAL_TERMS = {
    "用户",
    "助手",
    "偏好",
    "身份",
    "规则",
    "长期规则",
    "长期记忆",
    "历史对话",
    "共同经历",
}
MEMORY_SEMANTIC_TERM_GROUPS = (
    ("食物", "饮食", "吃", "口味", "火锅", "冰激凌", "冰淇淋", "甜食", "菜", "饮料"),
    ("称呼", "名字", "叫作", "叫做", "旺财"),
    ("作品", "故事", "小说", "剧本", "角色", "设定"),
)


def memory_topic_conflicts(user_message: str, memory_content: str) -> bool:
    query_text = clean_search_text(user_message, 240).lower()
    content_text = clean_search_text(memory_content, 800).lower()
    for group in MEMORY_TOPIC_GROUPS:
        query_markers = [marker.lower() for marker in group if marker.lower() in query_text]
        if not query_markers:
            continue
        content_markers = [marker.lower() for marker in group if marker.lower() in content_text]
        if content_markers and not any(marker in content_text for marker in query_markers):
            return True
    return False


def memory_text_relevance(user_message: str, memory_content: str) -> float:
    query_text = clean_search_text(user_message, 240).lower()
    content_text = clean_search_text(memory_content, 800).lower()
    if not query_text or not content_text:
        return 1.0

    if memory_topic_conflicts(query_text, content_text):
        return 0.0

    terms = extract_relevance_terms(query_text)
    if not terms:
        return 1.0
    if all(term in MEMORY_GENERIC_RETRIEVAL_TERMS for term in terms):
        return 1.0
    hits = sum(1 for term in terms if term and term in content_text)
    for group in MEMORY_SEMANTIC_TERM_GROUPS:
        query_has_group = any(term in query_text for term in group)
        content_has_group = any(term in content_text for term in group)
        if query_has_group and content_has_group:
            hits += 1
    return round(min(1.0, hits / max(1, len(terms))), 3)


def retrieve_curated_memories(
    query_vector: object,
    current_session_id: str = "",
    current_visitor_ip: str = "",
    query_text: str = "",
) -> List[Dict[str, object]]:
    query = vector_memory.normalize_vector(query_vector)
    current_ip = normalize_visitor_ip(current_visitor_ip) if current_visitor_ip else ""
    with connect_db() as conn:
        scope = binding_scope_for_device(conn, current_ip) if current_ip else {}
        scoped_devices = list(scope.get("device_ids") or ([current_ip] if current_ip else []))
        profile_owner_device_id = str(scope.get("profile_owner_device_id") or "")
        local_priority_buckets = (
            device_local_prompt_priority_buckets(conn, current_ip)
            if current_ip and str(scope.get("shared_user_id") or "")
            else set()
        )
        in_clause, params = sql_in_clause_params(scoped_devices)
        rows = conn.execute(
            f"""
            SELECT m.id, m.source_session_id, m.content, m.importance_label,
                   m.visitor_ip, m.profile_id,
                   m.timeline_at, m.timeline_start_at, m.timeline_end_at, m.timeline_kind,
                   m.supersedes_id, m.confidence,
                   v.dim, v.vector, v.model_name
            FROM curated_memories m
            JOIN curated_memory_vectors v ON v.memory_id = m.id
            WHERE m.visitor_ip IN {in_clause}
            ORDER BY m.id ASC
            """,
            params,
        ).fetchall()

    scored: List[Dict[str, object]] = []
    for row in rows:
        if current_session_id and str(row["source_session_id"]) == str(current_session_id):
            continue
        content = str(row["content"] or "")
        label = str(row["importance_label"] or "other")
        memory_ip = str(row["visitor_ip"] or "")
        if memory_ip and current_ip and memory_ip not in scoped_devices:
            continue
        if memory_ip and not current_ip:
            continue
        if memory_ip != current_ip and is_device_local_memory_label(label):
            if not profile_owner_device_id or memory_ip != profile_owner_device_id:
                continue
        if memory_ip != current_ip:
            bucket = prompt_priority_memory_bucket(content, label)
            if bucket and bucket in local_priority_buckets:
                continue
        vector = vector_memory.blob_to_vector(row["vector"], int(row["dim"]))
        if vector.shape != query.shape:
            continue
        score = float(vector.dot(query))
        if score < CURATED_MEMORY_MIN_SCORE:
            continue
        if query_text and memory_topic_conflicts(query_text, content):
            continue
        text_relevance = memory_text_relevance(query_text, content) if query_text else 1.0
        if text_relevance < MEMORY_TEXT_MIN_RELEVANCE and score < MEMORY_TEXT_GATE_MIN_VECTOR_SCORE:
            continue
        scored.append(
            {
                "id": int(row["id"]),
                "content": content,
                "importance_label": label,
                "visitor_ip": memory_ip or None,
                "profile_id": int(row["profile_id"]) if row["profile_id"] is not None else None,
                "timeline_at": str(row["timeline_at"] or ""),
                "timeline_start_at": str(row["timeline_start_at"] or ""),
                "timeline_end_at": str(row["timeline_end_at"] or ""),
                "timeline_kind": str(row["timeline_kind"] or ""),
                "supersedes_id": int(row["supersedes_id"]) if row["supersedes_id"] is not None else None,
                "confidence": float(row["confidence"]) if row["confidence"] is not None else 0.7,
                "score": score,
                "text_relevance": text_relevance,
                "device_priority": 0 if memory_ip == current_ip else 1,
            }
        )
    scored.sort(
        key=lambda item: (
            int(item.get("device_priority", 1)),
            -(float(item["score"]) * float(item.get("text_relevance", 1.0))),
            int(item["id"]),
        )
    )
    return scored[:CURATED_MEMORY_TOP_K]


def retrieve_curated_memory_recall_pool(
    query_vector: object,
    current_session_id: str = "",
    current_visitor_ip: str = "",
    query_text: str = "",
    limit: int = CURATED_MEMORY_RECALL_POOL_SIZE,
) -> List[Dict[str, object]]:
    query = vector_memory.normalize_vector(query_vector)
    current_ip = normalize_visitor_ip(current_visitor_ip) if current_visitor_ip else ""
    with connect_db() as conn:
        scope = binding_scope_for_device(conn, current_ip) if current_ip else {}
        scoped_devices = list(scope.get("device_ids") or ([current_ip] if current_ip else []))
        profile_owner_device_id = str(scope.get("profile_owner_device_id") or "")
        local_priority_buckets = (
            device_local_prompt_priority_buckets(conn, current_ip)
            if current_ip and str(scope.get("shared_user_id") or "")
            else set()
        )
        in_clause, params = sql_in_clause_params(scoped_devices)
        rows = conn.execute(
            f"""
            SELECT m.id, m.source_session_id, m.content, m.importance_label,
                   m.visitor_ip, m.profile_id,
                   m.timeline_at, m.timeline_start_at, m.timeline_end_at, m.timeline_kind,
                   m.supersedes_id, m.confidence,
                   v.dim, v.vector, v.model_name
            FROM curated_memories m
            JOIN curated_memory_vectors v ON v.memory_id = m.id
            WHERE m.visitor_ip IN {in_clause}
            ORDER BY m.id ASC
            """,
            params,
        ).fetchall()

    candidates: List[Dict[str, object]] = []
    for row in rows:
        if current_session_id and str(row["source_session_id"]) == str(current_session_id):
            continue
        content = str(row["content"] or "")
        label = str(row["importance_label"] or "other")
        memory_ip = str(row["visitor_ip"] or "")
        if memory_ip and current_ip and memory_ip not in scoped_devices:
            continue
        if memory_ip and not current_ip:
            continue
        if memory_ip != current_ip and is_device_local_memory_label(label):
            if not profile_owner_device_id or memory_ip != profile_owner_device_id:
                continue
        if memory_ip != current_ip:
            bucket = prompt_priority_memory_bucket(content, label)
            if bucket and bucket in local_priority_buckets:
                continue
        vector = vector_memory.blob_to_vector(row["vector"], int(row["dim"]))
        if vector.shape != query.shape:
            continue
        score = float(vector.dot(query))
        if score < CURATED_MEMORY_MIN_SCORE:
            continue
        text_relevance = memory_text_relevance(query_text, content) if query_text else 1.0
        candidates.append(
            {
                "id": int(row["id"]),
                "content": content,
                "importance_label": label,
                "visitor_ip": memory_ip or None,
                "profile_id": int(row["profile_id"]) if row["profile_id"] is not None else None,
                "timeline_at": str(row["timeline_at"] or ""),
                "timeline_start_at": str(row["timeline_start_at"] or ""),
                "timeline_end_at": str(row["timeline_end_at"] or ""),
                "timeline_kind": str(row["timeline_kind"] or ""),
                "supersedes_id": int(row["supersedes_id"]) if row["supersedes_id"] is not None else None,
                "confidence": float(row["confidence"]) if row["confidence"] is not None else 0.7,
                "score": score,
                "text_relevance": text_relevance,
                "filter_reason": "candidate",
                "device_priority": 0 if memory_ip == current_ip else 1,
            }
        )
    candidates.sort(
        key=lambda item: (
            int(item.get("device_priority", 1)),
            -float(item.get("score", 0.0)),
            -float(item.get("text_relevance", 0.0)),
            int(item["id"]),
        )
    )
    return candidates[: max(1, int(limit))]


def build_memory_judge_messages(
    user_message: str,
    retrieval_query: str,
    candidates: List[Dict[str, object]],
    max_selected: int = CURATED_MEMORY_TOP_K,
) -> List[Dict[str, str]]:
    candidate_lines = []
    for item in candidates:
        content = clean_search_text(str(item.get("content", "")), 520)
        candidate_lines.append(
            "\n".join(
                [
                    f"ID: {int(item.get('id', 0))}",
                    f"label: {item.get('importance_label', 'other')}",
                    f"score: {float(item.get('score', 0.0)):.4f}",
                    f"text_relevance: {float(item.get('text_relevance', 0.0)):.3f}",
                    f"timeline: {timeline_display_text(item) or '-'}",
                    f"content: {content}",
                ]
            )
        )
    return [
        {"role": "system", "content": MEMORY_JUDGE_SYSTEM_PROMPT},
        {
            "role": "user",
            "content": (
                f"当前用户问题：{user_message}\n"
                f"检索 query：{retrieval_query}\n"
                f"最多选择 {max_selected} 条。\n\n"
                "候选记忆：\n\n"
                + "\n\n---\n\n".join(candidate_lines)
            ),
        },
    ]


def parse_memory_judge_response(text: str, candidate_ids: List[int]) -> Dict[str, object]:
    cleaned = (text or "").strip()
    if cleaned.startswith("```"):
        cleaned = re.sub(r"^```(?:json)?\s*", "", cleaned)
        cleaned = re.sub(r"\s*```$", "", cleaned)
    match = re.search(r"\{.*\}", cleaned, flags=re.S)
    if match:
        cleaned = match.group(0)
    payload = json.loads(cleaned)
    allowed = {int(item) for item in candidate_ids}
    selected: List[int] = []
    raw_ids = payload.get("selected_ids", [])
    if isinstance(raw_ids, list):
        for raw in raw_ids:
            try:
                memory_id = int(raw)
            except Exception:
                continue
            if memory_id in allowed and memory_id not in selected:
                selected.append(memory_id)
    return {
        "selected_ids": selected,
        "rationale": clean_search_text(str(payload.get("rationale", "")), 240),
    }


def judge_curated_memories_with_model(
    user_message: str,
    retrieval_query: str,
    candidates: List[Dict[str, object]],
    session_id: str = "",
    visitor_ip: str = "unknown",
    analysis_trace_id: str = "",
) -> List[Dict[str, object]]:
    if not candidates:
        return []
    candidate_ids = [int(item["id"]) for item in candidates]
    messages = build_memory_judge_messages(user_message, retrieval_query, candidates, CURATED_MEMORY_TOP_K)
    started = time.perf_counter()
    client, http_client, model_slot = openai_client_for_slot(
        MODEL_SLOT_BACKGROUND,
        timeout=MEMORY_JUDGE_TIMEOUT,
    )
    try:
        resp = client.chat.completions.create(
            **model_completion_kwargs(model_slot),
            messages=messages,
            temperature=0.05,
            top_p=0.8,
            max_tokens=MEMORY_JUDGE_MAX_TOKENS,
        )
        content = resp.choices[0].message.content or ""
        _, answer = split_think_text(content)
        decision = parse_memory_judge_response(answer, candidate_ids)
        selected_ids = [int(item) for item in decision.get("selected_ids", [])][:CURATED_MEMORY_TOP_K]
        selected = [item for item in candidates if int(item["id"]) in selected_ids]
        if analysis_trace_id:
            record_analysis_trace(
                session_id=session_id,
                trace_id=analysis_trace_id,
                event_type="model_call",
                visitor_ip=visitor_ip,
                step_name="memory_candidate_judge",
                duration_ms=round((time.perf_counter() - started) * 1000, 3),
                payload={
                    "model": model_slot.get("model", MODEL_NAME),
                    "messages": messages,
                    "decision": decision,
                    "selected_count": len(selected),
                    "candidate_count": len(candidates),
                },
            )
        return selected
    except Exception as exc:
        fallback = sorted(candidates, key=lambda item: -float(item.get("score", 0.0)))[:CURATED_MEMORY_TOP_K]
        if analysis_trace_id:
            record_analysis_trace(
                session_id=session_id,
                trace_id=analysis_trace_id,
                event_type="model_call_error",
                visitor_ip=visitor_ip,
                step_name="memory_candidate_judge",
                duration_ms=round((time.perf_counter() - started) * 1000, 3),
                payload={
                    "model": model_slot.get("model", MODEL_NAME),
                    "messages": messages,
                    "error": str(exc),
                    "fallback_selected": analysis_memory_result_payload(fallback),
                },
            )
        return fallback
    finally:
        http_client.close()


def analysis_memory_result_payload(memories: List[Dict[str, object]]) -> List[Dict[str, object]]:
    return [
        {
            "memory_id": int(item.get("id", 0)),
            "content": str(item.get("content", "")),
            "score": round(float(item.get("score", 0.0)), 6),
            "label": str(item.get("importance_label", "other")),
            "timeline_at": str(item.get("timeline_at", "")),
            "text_relevance": round(float(item.get("text_relevance", 1.0)), 3),
            "visitor_ip": item.get("visitor_ip"),
            "profile_id": item.get("profile_id"),
            "confidence": round(float(item.get("confidence", 0.0)), 3),
        }
        for item in memories
    ]


def analysis_memory_candidate_payload(candidates: List[Dict[str, object]]) -> List[Dict[str, object]]:
    return [
        {
            "memory_id": int(item.get("id", 0)),
            "content": str(item.get("content", "")),
            "score": round(float(item.get("score", 0.0)), 6),
            "text_relevance": round(float(item.get("text_relevance", 1.0)), 3),
            "filter_reason": str(item.get("filter_reason", "")),
            "label": str(item.get("importance_label", "other")),
            "timeline_at": str(item.get("timeline_at", "")),
            "visitor_ip": item.get("visitor_ip"),
            "profile_id": item.get("profile_id"),
            "confidence": round(float(item.get("confidence", 0.0)), 3),
        }
        for item in candidates
    ]


def explain_curated_memory_candidates(
    query_vector: object,
    current_session_id: str = "",
    current_visitor_ip: str = "",
    query_text: str = "",
    limit: int = 12,
) -> List[Dict[str, object]]:
    query = vector_memory.normalize_vector(query_vector)
    current_ip = normalize_visitor_ip(current_visitor_ip) if current_visitor_ip else ""
    with connect_db() as conn:
        scope = binding_scope_for_device(conn, current_ip) if current_ip else {}
        scoped_devices = set(scope.get("device_ids") or ([current_ip] if current_ip else []))
        profile_owner_device_id = str(scope.get("profile_owner_device_id") or "")
        current_profile_id = None
        if current_ip:
            row = conn.execute(
                "SELECT profile_id FROM visitor_ip_links WHERE visitor_ip = ?",
                (current_ip,),
            ).fetchone()
            current_profile_id = int(row["profile_id"]) if row else None
        rows = conn.execute(
            """
            SELECT m.id, m.source_session_id, m.content, m.importance_label,
                   m.visitor_ip, m.profile_id, m.timeline_at, m.supersedes_id, m.confidence,
                   v.dim, v.vector, v.model_name
            FROM curated_memories m
            JOIN curated_memory_vectors v ON v.memory_id = m.id
            ORDER BY m.id ASC
            """
        ).fetchall()

    candidates: List[Dict[str, object]] = []
    for row in rows:
        reason = "selected"
        if current_session_id and str(row["source_session_id"]) == str(current_session_id):
            reason = "filtered_current_session"
        memory_ip = str(row["visitor_ip"] or "")
        label = str(row["importance_label"] or "other")
        memory_profile_id = int(row["profile_id"]) if row["profile_id"] is not None else None
        if reason == "selected" and memory_ip and current_ip and memory_ip != current_ip and is_device_local_memory_label(label):
            if not profile_owner_device_id or memory_ip != profile_owner_device_id:
                reason = "filtered_device_local_memory"
        if (
            reason == "selected"
            and memory_ip
            and current_ip
            and memory_ip != current_ip
            and memory_ip not in scoped_devices
            and memory_profile_id != current_profile_id
        ):
            reason = "filtered_different_ip_or_profile"
        if reason == "selected" and memory_ip and not current_ip:
            reason = "filtered_ip_memory_without_current_ip"
        vector = vector_memory.blob_to_vector(row["vector"], int(row["dim"]))
        if vector.shape != query.shape:
            score = 0.0
            text_relevance = 0.0
            reason = "filtered_vector_dim_mismatch"
        else:
            score = float(vector.dot(query))
            if reason == "selected" and score < CURATED_MEMORY_MIN_SCORE:
                reason = "filtered_low_vector_score"
            if reason == "selected" and query_text and memory_topic_conflicts(query_text, str(row["content"])):
                reason = "filtered_topic_conflict"
            text_relevance = memory_text_relevance(query_text, str(row["content"])) if query_text else 1.0
            if reason == "selected" and text_relevance < MEMORY_TEXT_MIN_RELEVANCE and score < MEMORY_TEXT_GATE_MIN_VECTOR_SCORE:
                reason = "filtered_low_text_relevance"
        candidates.append(
            {
                "id": int(row["id"]),
                "content": str(row["content"]),
                "importance_label": label,
                "visitor_ip": memory_ip or None,
                "profile_id": memory_profile_id,
                "timeline_at": str(row["timeline_at"] or ""),
                "confidence": float(row["confidence"]) if row["confidence"] is not None else 0.7,
                "score": score,
                "text_relevance": text_relevance,
                "filter_reason": reason,
            }
        )
    candidates.sort(key=lambda item: (-float(item.get("score", 0.0)), -float(item.get("text_relevance", 0.0)), int(item["id"])))
    return candidates[: max(1, int(limit))]


def retrieve_curated_memories_by_text(
    query_text: str,
    current_session_id: str = "",
    current_visitor_ip: str = "",
) -> List[Dict[str, object]]:
    current_ip = normalize_visitor_ip(current_visitor_ip) if current_visitor_ip else ""
    with connect_db() as conn:
        scope = binding_scope_for_device(conn, current_ip) if current_ip else {}
        scoped_devices = list(scope.get("device_ids") or ([current_ip] if current_ip else []))
        profile_owner_device_id = str(scope.get("profile_owner_device_id") or "")
        local_priority_buckets = (
            device_local_prompt_priority_buckets(conn, current_ip)
            if current_ip and str(scope.get("shared_user_id") or "")
            else set()
        )
        in_clause, params = sql_in_clause_params(scoped_devices)
        rows = conn.execute(
            f"""
            SELECT id, source_session_id, content, importance_label,
                   visitor_ip, profile_id,
                   timeline_at, timeline_start_at, timeline_end_at, timeline_kind,
                   supersedes_id, confidence
            FROM curated_memories
            WHERE visitor_ip IN {in_clause}
            ORDER BY id DESC
            LIMIT 1000
            """,
            params,
        ).fetchall()

    scored: List[Dict[str, object]] = []
    for row in rows:
        if current_session_id and str(row["source_session_id"]) == str(current_session_id):
            continue
        memory_ip = str(row["visitor_ip"] or "")
        if memory_ip and current_ip and memory_ip not in scoped_devices:
            continue
        if memory_ip and not current_ip:
            continue
        content = str(row["content"])
        label = str(row["importance_label"] or "other")
        if memory_ip != current_ip and is_device_local_memory_label(label):
            if not profile_owner_device_id or memory_ip != profile_owner_device_id:
                continue
        if memory_ip != current_ip:
            bucket = prompt_priority_memory_bucket(content, label)
            if bucket and bucket in local_priority_buckets:
                continue
        if query_text and memory_topic_conflicts(query_text, content):
            continue
        text_relevance = memory_text_relevance(query_text, content) if query_text else 1.0
        if text_relevance < MEMORY_TEXT_MIN_RELEVANCE:
            continue
        confidence = float(row["confidence"]) if row["confidence"] is not None else 0.7
        scored.append(
            {
                "id": int(row["id"]),
                "content": content,
                "importance_label": label,
                "visitor_ip": memory_ip or None,
                "profile_id": int(row["profile_id"]) if row["profile_id"] is not None else None,
                "timeline_at": str(row["timeline_at"] or ""),
                "timeline_start_at": str(row["timeline_start_at"] or ""),
                "timeline_end_at": str(row["timeline_end_at"] or ""),
                "timeline_kind": str(row["timeline_kind"] or ""),
                "supersedes_id": int(row["supersedes_id"]) if row["supersedes_id"] is not None else None,
                "confidence": confidence,
                "score": text_relevance,
                "text_relevance": text_relevance,
                "device_priority": 0 if memory_ip == current_ip else 1,
            }
        )
    scored.sort(
        key=lambda item: (
            int(item.get("device_priority", 1)),
            -float(item.get("text_relevance", 0.0)),
            -float(item.get("confidence", 0.0)),
            -int(item["id"]),
        )
    )
    return scored[:CURATED_MEMORY_TOP_K]


def format_curated_memory_context(memories: List[Dict[str, object]]) -> str:
    if not memories:
        return ""
    lines = [
        "以下是已整理长期记忆，仅供参考，不是当前回答模板。",
        "请只提取有用事实、偏好和长期设定；不要复述记忆原文。",
        "这些记忆带有时间线；如果出现冲突，优先相信较新的记忆和 confidence 更高的记忆。",
        "",
    ]
    for index, item in enumerate(memories, start=1):
        timeline = timeline_display_text(item) or "unknown"
        supersedes = item.get("supersedes_id")
        confidence = float(item.get("confidence", 0.7))
        supersedes_text = f" supersedes=#{supersedes}" if supersedes else ""
        lines.append(
            f"[长期记忆 {index}] score={float(item['score']):.3f} "
            f"label={item['importance_label']} timeline={timeline} "
            f"confidence={confidence:.2f}{supersedes_text}"
        )
        lines.append(str(item["content"]).strip())
        lines.append("")
    return "\n".join(lines).strip()


PROFILE_CONTEXT_LABELS = {"identity", "persona", "preference"}
OPENING_PROFILE_TERMS = (
    "开场",
    "开篇",
    "第一次",
    "第一条",
    "见到",
    "见面",
    "打招呼",
    "问好",
    "问候",
    "高呼",
    "opening",
)
ASSISTANT_STYLE_PROFILE_TERMS = (
    "助手",
    "回复",
    "回答",
    "语气",
    "风格",
    "称呼",
    "叫作",
    "叫做",
    "叫我",
    "叫他",
    "叫她",
    "叫你",
    "调皮",
    "正式",
    "简短",
    "详细",
    "幽默",
    "黑色幽默",
    "装逼",
    "温柔",
    "毒舌",
    "严肃",
    "活泼",
    "不要",
)


def is_opening_context_memory(content: str, label: str) -> bool:
    normalized_label = (label or "other").strip()
    if normalized_label not in {"preference", "rule"}:
        return False
    text = clean_search_text(content, 600)
    return any(term in text for term in OPENING_PROFILE_TERMS)


def is_profile_context_memory(content: str, label: str) -> bool:
    normalized_label = (label or "other").strip()
    text = clean_search_text(content, 600)
    if is_opening_context_memory(content, normalized_label):
        return False
    if normalized_label in {"identity", "persona"}:
        return True
    if normalized_label == "rule":
        return any(term in text for term in ASSISTANT_STYLE_PROFILE_TERMS)
    if normalized_label != "preference":
        return False
    return any(term in text for term in ASSISTANT_STYLE_PROFILE_TERMS)


def assistant_profile_source_device_id(conn: sqlite3.Connection, current_ip: str) -> str:
    scope = binding_scope_for_device(conn, current_ip)
    return str(scope.get("profile_owner_device_id") or current_ip)


def retrieve_profile_context_memories(
    current_visitor_ip: str = "",
    limit: int = 10,
) -> List[Dict[str, object]]:
    current_ip = normalize_visitor_ip(current_visitor_ip) if current_visitor_ip else ""
    if not current_ip or not is_device_identity(current_ip):
        return []
    max_rows = min(max(int(limit), 1), 30)
    with connect_db() as conn:
        profile_device_id = assistant_profile_source_device_id(conn, current_ip)
        rows = conn.execute(
            """
            SELECT id, content, importance_label, visitor_ip, profile_id,
                   timeline_at, supersedes_id, confidence, updated_at
            FROM curated_memories
            WHERE visitor_ip = ?
              AND importance_label IN ('identity', 'persona', 'preference', 'rule')
            ORDER BY
              CASE importance_label
                WHEN 'rule' THEN 0
                WHEN 'identity' THEN 1
                WHEN 'persona' THEN 2
                WHEN 'preference' THEN 3
                ELSE 3
              END,
              COALESCE(timeline_at, updated_at) DESC,
              confidence DESC,
              id DESC
            LIMIT 140
            """,
            (profile_device_id,),
        ).fetchall()

    profile_memories: List[Dict[str, object]] = []
    seen_contents = set()
    for row in rows:
        content = str(row["content"]).strip()
        label = str(row["importance_label"])
        if not content or not is_profile_context_memory(content, label):
            continue
        dedupe_key = clean_search_text(content, 300)
        if dedupe_key in seen_contents:
            continue
        seen_contents.add(dedupe_key)
        profile_memories.append(
            {
                "id": int(row["id"]),
                "content": content,
                "importance_label": label,
                "visitor_ip": row["visitor_ip"],
                "profile_id": row["profile_id"],
                "timeline_at": str(row["timeline_at"] or row["updated_at"] or ""),
                "supersedes_id": int(row["supersedes_id"]) if row["supersedes_id"] is not None else None,
                "confidence": float(row["confidence"]) if row["confidence"] is not None else 0.7,
            }
        )
        if len(profile_memories) >= max_rows:
            break
    return profile_memories


def retrieve_opening_context_memories(
    current_visitor_ip: str = "",
    limit: int = 6,
) -> List[Dict[str, object]]:
    current_ip = normalize_visitor_ip(current_visitor_ip) if current_visitor_ip else ""
    if not current_ip or not is_device_identity(current_ip):
        return []
    max_rows = min(max(int(limit), 1), 500)
    with connect_db() as conn:
        profile_device_id = assistant_profile_source_device_id(conn, current_ip)
        rows = conn.execute(
            """
            SELECT id, content, importance_label, visitor_ip, profile_id,
                   timeline_at, supersedes_id, confidence, updated_at
            FROM curated_memories
            WHERE visitor_ip = ?
              AND importance_label IN ('preference', 'rule')
            ORDER BY
              COALESCE(timeline_at, updated_at) DESC,
              confidence DESC,
              id DESC
            LIMIT 120
            """,
            (profile_device_id,),
        ).fetchall()

    memories: List[Dict[str, object]] = []
    seen_contents = set()
    for row in rows:
        content = str(row["content"]).strip()
        label = str(row["importance_label"])
        if not content or not is_opening_context_memory(content, label):
            continue
        dedupe_key = clean_search_text(content, 300)
        if dedupe_key in seen_contents:
            continue
        seen_contents.add(dedupe_key)
        memories.append(
            {
                "id": int(row["id"]),
                "content": content,
                "importance_label": label,
                "visitor_ip": row["visitor_ip"],
                "profile_id": row["profile_id"],
                "timeline_at": str(row["timeline_at"] or row["updated_at"] or ""),
                "supersedes_id": int(row["supersedes_id"]) if row["supersedes_id"] is not None else None,
                "confidence": float(row["confidence"]) if row["confidence"] is not None else 0.7,
            }
        )
        if len(memories) >= max_rows:
            break
    return memories


def format_profile_context(memories: List[Dict[str, object]]) -> str:
    if not memories:
        return ""
    lines = [
        "当前用户稳定画像（每轮都应参考；优先级高于普通长期记忆）：",
        "这些内容用于称呼、身份、语气和交互风格，不是要复述给用户的原文。",
        "如果画像之间冲突，优先采用时间线更新、confidence 更高的条目。",
        "",
    ]
    for index, item in enumerate(memories, start=1):
        timeline = str(item.get("timeline_at") or "unknown")
        confidence = float(item.get("confidence", 0.7))
        lines.append(
            f"[画像 {index}] label={item['importance_label']} "
            f"timeline={timeline} confidence={confidence:.2f}"
        )
        lines.append(str(item["content"]).strip())
        lines.append("")
    return "\n".join(lines).strip()


def format_opening_context(memories: List[Dict[str, object]]) -> str:
    if not memories:
        return ""
    lines = [
        "开场专用偏好（只用于浏览器打开后的第一句开场；后续普通对话不要继续套用）：",
        "如果这些偏好要求固定落款、笑话或问候格式，只在开场回复中使用一次。",
        "",
    ]
    for index, item in enumerate(memories, start=1):
        timeline = str(item.get("timeline_at") or "unknown")
        confidence = float(item.get("confidence", 0.7))
        lines.append(
            f"[开场偏好 {index}] label={item['importance_label']} "
            f"timeline={timeline} confidence={confidence:.2f}"
        )
        lines.append(str(item["content"]).strip())
        lines.append("")
    return "\n".join(lines).strip()


def safe_json_loads(text: str) -> object:
    try:
        return json.loads(text or "{}")
    except Exception:
        return {}


def sanitize_metadata(metadata: object) -> object:
    if isinstance(metadata, dict):
        blocked = {"content", "message", "text", "prompt", "user_message", "answer", "response"}
        clean: Dict[str, object] = {}
        for key, value in metadata.items():
            lowered = str(key).lower()
            if lowered in blocked or any(part in lowered for part in ("content", "message", "prompt", "answer")):
                clean[str(key)] = "[hidden]"
            else:
                clean[str(key)] = sanitize_metadata(value)
        return clean
    if isinstance(metadata, list):
        return [sanitize_metadata(item) for item in metadata]
    if isinstance(metadata, (str, int, float, bool)) or metadata is None:
        return metadata
    return str(metadata)


def sanitize_analysis_payload(payload: object) -> object:
    if isinstance(payload, dict):
        clean: Dict[str, object] = {}
        for key, value in payload.items():
            lowered = str(key).lower()
            if lowered in {"vector", "vectors", "embedding_vector", "raw_vector", "raw_embedding"}:
                continue
            clean[str(key)] = sanitize_analysis_payload(value)
        return clean
    if isinstance(payload, list):
        return [sanitize_analysis_payload(item) for item in payload]
    if isinstance(payload, (str, int, float, bool)) or payload is None:
        return payload
    return str(payload)


def record_analysis_trace(
    session_id: str,
    event_type: str,
    visitor_ip: str,
    step_name: str,
    payload: Optional[Dict[str, object]] = None,
    duration_ms: Optional[float] = None,
    trace_id: Optional[str] = None,
) -> str:
    active_trace_id = trace_id or str(uuid.uuid4())
    safe_payload = sanitize_analysis_payload(payload or {})
    with connect_db() as conn:
        conn.execute(
            """
            INSERT INTO analysis_trace_events (
                session_id, trace_id, event_type, visitor_ip, step_name,
                duration_ms, payload_json, created_at
            )
            VALUES (?, ?, ?, ?, ?, ?, ?, ?)
            """,
            (
                session_id,
                active_trace_id,
                event_type,
                visitor_ip or "unknown",
                step_name,
                duration_ms,
                json.dumps(safe_payload, ensure_ascii=False),
                utc_now(),
            ),
        )
    return active_trace_id


def list_analysis_traces(
    session_id: str = "",
    trace_id: str = "",
    limit: int = 200,
    visitor_ips: Optional[List[str]] = None,
) -> List[Dict[str, object]]:
    clauses = []
    params: List[object] = []
    if session_id.strip():
        clauses.append("session_id = ?")
        params.append(session_id.strip())
    if trace_id.strip():
        clauses.append("trace_id = ?")
        params.append(trace_id.strip())
    normalized_visitors = [
        normalize_visitor_ip(item)
        for item in (visitor_ips or [])
        if normalize_visitor_ip(item)
    ]
    if visitor_ips is not None:
        if not normalized_visitors:
            return []
        in_clause, visitor_params = sql_in_clause_params(normalized_visitors)
        clauses.append(f"visitor_ip IN {in_clause}")
        params.extend(visitor_params)
    where = f"WHERE {' AND '.join(clauses)}" if clauses else ""
    max_rows = min(max(int(limit), 1), 1000)
    with connect_db() as conn:
        rows = conn.execute(
            f"""
            SELECT id, session_id, trace_id, event_type, visitor_ip,
                   step_name, duration_ms, payload_json, created_at
            FROM analysis_trace_events
            {where}
            ORDER BY id ASC
            LIMIT ?
            """,
            (*params, max_rows),
        ).fetchall()
    return [
        {
            "id": int(row["id"]),
            "session_id": str(row["session_id"]),
            "trace_id": str(row["trace_id"]),
            "event_type": str(row["event_type"]),
            "visitor_ip": str(row["visitor_ip"]),
            "device_id": str(row["visitor_ip"]),
            "step_name": str(row["step_name"]),
            "duration_ms": (
                float(row["duration_ms"])
                if row["duration_ms"] is not None
                else None
            ),
            "payload": safe_json_loads(str(row["payload_json"])),
            "created_at": str(row["created_at"]),
        }
        for row in rows
    ]


def latest_analysis_trace_id(session_id: str) -> str:
    with connect_db() as conn:
        row = conn.execute(
            """
            SELECT trace_id
            FROM analysis_trace_events
            WHERE session_id = ?
            ORDER BY id DESC
            LIMIT 1
            """,
            (session_id,),
        ).fetchone()
    return str(row["trace_id"]) if row else ""


def record_memory_retrieval(
    session_id: str,
    user_message: str,
    memories: List[Dict[str, object]],
) -> None:
    memory_ids = [int(item["id"]) for item in memories]
    scores = [round(float(item.get("score", 0.0)), 6) for item in memories]
    labels = [str(item.get("importance_label", "other")) for item in memories]
    with connect_db() as conn:
        conn.execute(
            """
            INSERT INTO memory_retrieval_logs (
                session_id, query_hash, result_count,
                memory_ids_json, scores_json, labels_json, created_at
            )
            VALUES (?, ?, ?, ?, ?, ?, ?)
            """,
            (
                session_id,
                vector_memory.content_hash(user_message.strip()),
                len(memories),
                json.dumps(memory_ids, ensure_ascii=False),
                json.dumps(scores, ensure_ascii=False),
                json.dumps(labels, ensure_ascii=False),
                utc_now(),
            ),
        )


def list_memory_dashboard_memories(
    keyword: str = "",
    label: str = "",
    limit: int = 100,
    device_ids: Optional[List[str]] = None,
) -> Dict[str, object]:
    if device_ids is not None and not device_ids:
        return {"total": 0, "items": []}
    clauses = [
        "m.importance_label NOT IN ('artifact', 'characters')",
        "m.source_session_id NOT LIKE 'artifact-%'",
        "m.source_session_id NOT LIKE 'character-profile-%'",
    ]
    params: List[object] = []
    if device_ids is not None:
        placeholders = ", ".join("?" for _ in device_ids)
        clauses.append(f"m.visitor_ip IN ({placeholders})")
        params.extend(device_ids)
    if keyword.strip():
        clauses.append("m.content LIKE ?")
        params.append(f"%{keyword.strip()}%")
    if label.strip():
        clauses.append("m.importance_label = ?")
        params.append(label.strip())
    where = f"WHERE {' AND '.join(clauses)}" if clauses else ""
    max_rows = min(max(int(limit), 1), 500)
    sql = f"""
        SELECT m.id, m.content, m.importance_label, m.visitor_ip, m.created_at, m.updated_at,
               m.timeline_at, m.timeline_start_at, m.timeline_end_at, m.timeline_kind,
               m.supersedes_id, m.confidence,
               m.refine_status, m.refined_at, m.refined_from_id, m.refine_reason,
               CASE WHEN v.memory_id IS NULL THEN 0 ELSE 1 END AS has_vector,
               v.dim, v.model_name
        FROM curated_memories m
        LEFT JOIN curated_memory_vectors v ON v.memory_id = m.id
        {where}
        ORDER BY m.id DESC
        LIMIT ?
    """
    with connect_db() as conn:
        rows = conn.execute(sql, (*params, max_rows)).fetchall()
        total = conn.execute(f"SELECT COUNT(*) AS c FROM curated_memories m {where}", params).fetchone()["c"]
    return {
        "total": int(total),
        "items": [
            {
                "id": int(row["id"]),
                "content": str(row["content"]),
                "importance_label": str(row["importance_label"]),
                "visitor_ip": str(row["visitor_ip"]) if row["visitor_ip"] else None,
                "timeline_at": str(row["timeline_at"] or ""),
                "timeline_start_at": str(row["timeline_start_at"] or ""),
                "timeline_end_at": str(row["timeline_end_at"] or ""),
                "timeline_kind": str(row["timeline_kind"] or ""),
                "supersedes_id": int(row["supersedes_id"]) if row["supersedes_id"] is not None else None,
                "confidence": float(row["confidence"]) if row["confidence"] is not None else 0.7,
                "refine_status": str(row["refine_status"] or ""),
                "refined_at": str(row["refined_at"] or ""),
                "refined_from_id": int(row["refined_from_id"]) if row["refined_from_id"] is not None else None,
                "refine_reason": str(row["refine_reason"] or ""),
                "created_at": str(row["created_at"]),
                "updated_at": str(row["updated_at"]),
                "has_vector": bool(row["has_vector"]),
                "vector_dim": int(row["dim"]) if row["dim"] is not None else None,
                "vector_model": str(row["model_name"]) if row["model_name"] else None,
            }
            for row in rows
        ],
    }


def list_memory_dashboard_retrievals(
    memory_id: Optional[int] = None,
    limit: int = 100,
    device_ids: Optional[List[str]] = None,
) -> Dict[str, object]:
    if device_ids is not None and not device_ids:
        return {"total": 0, "items": []}
    max_rows = min(max(int(limit), 1), 500)
    clauses = []
    params: List[object] = []
    join_sessions = ""
    if device_ids is not None:
        placeholders = ", ".join("?" for _ in device_ids)
        join_sessions = "JOIN sessions s ON s.id = r.session_id"
        clauses.append(f"s.visitor_ip IN ({placeholders})")
        params.extend(device_ids)
    where = f"WHERE {' AND '.join(clauses)}" if clauses else ""
    with connect_db() as conn:
        rows = conn.execute(
            f"""
            SELECT r.id, r.session_id, r.query_hash, r.result_count,
                   r.memory_ids_json, r.scores_json, r.labels_json, r.created_at
            FROM memory_retrieval_logs r
            {join_sessions}
            {where}
            ORDER BY r.id DESC
            LIMIT ?
            """,
            (*params, max_rows),
        ).fetchall()
    items = []
    for row in rows:
        memory_ids = safe_json_loads(row["memory_ids_json"])
        if memory_id is not None and int(memory_id) not in memory_ids:
            continue
        items.append(
            {
                "id": int(row["id"]),
                "session_id": str(row["session_id"])[:8],
                "query_hash": str(row["query_hash"])[:16],
                "result_count": int(row["result_count"]),
                "memory_ids": memory_ids,
                "scores": safe_json_loads(row["scores_json"]),
                "labels": safe_json_loads(row["labels_json"]),
                "created_at": str(row["created_at"]),
            }
        )
    return {"total": len(items), "items": items[:max_rows]}


def list_memory_dashboard_operations(
    kind: str = "",
    status: str = "",
    event_type: str = "",
    limit: int = 120,
    device_ids: Optional[List[str]] = None,
) -> Dict[str, object]:
    if device_ids is not None and not device_ids:
        return {"total": 0, "items": []}
    max_rows = min(max(int(limit), 1), 500)
    items: List[Dict[str, object]] = []
    include_jobs = kind in ("", "memory_agent_job")
    include_events = kind in ("", "event")

    if include_jobs:
        clauses = []
        params: List[object] = []
        join_sessions = ""
        if device_ids is not None:
            placeholders = ", ".join("?" for _ in device_ids)
            join_sessions = "JOIN sessions s ON s.id = j.session_id"
            clauses.append(f"s.visitor_ip IN ({placeholders})")
            params.extend(device_ids)
        if status.strip():
            clauses.append("j.status = ?")
            params.append(status.strip())
        where = f"WHERE {' AND '.join(clauses)}" if clauses else ""
        with connect_db() as conn:
            rows = conn.execute(
                f"""
                SELECT j.id, j.session_id, j.start_message_id, j.end_message_id,
                       j.status, j.reason, j.error, j.created_at, j.updated_at
                FROM memory_agent_jobs j
                {join_sessions}
                {where}
                ORDER BY j.id DESC
                LIMIT ?
                """,
                (*params, max_rows),
            ).fetchall()
        for row in rows:
            items.append(
                {
                    "kind": "memory_agent_job",
                    "id": int(row["id"]),
                    "session_id": str(row["session_id"])[:8],
                    "status": str(row["status"]),
                    "operation": str(row["reason"]),
                    "message_range": [int(row["start_message_id"]), int(row["end_message_id"])],
                    "error": str(row["error"]) if row["error"] else None,
                    "created_at": str(row["created_at"]),
                    "updated_at": str(row["updated_at"]),
                }
            )

    if include_events:
        clauses = []
        params = []
        if device_ids is not None:
            placeholders = ", ".join("?" for _ in device_ids)
            clauses.append(
                f"(e.visitor_ip IN ({placeholders}) "
                f"OR e.session_id IN (SELECT id FROM sessions WHERE visitor_ip IN ({placeholders})))"
            )
            params.extend(device_ids)
            params.extend(device_ids)
        if event_type.strip():
            clauses.append("e.event_type = ?")
            params.append(event_type.strip())
        where = f"WHERE {' AND '.join(clauses)}" if clauses else ""
        with connect_db() as conn:
            rows = conn.execute(
                f"""
                SELECT e.id, e.session_id, e.event_type, e.created_at, e.metadata_json
                FROM events e
                {where}
                ORDER BY e.id DESC
                LIMIT ?
                """,
                (*params, max_rows),
            ).fetchall()
        for row in rows:
            items.append(
                {
                    "kind": "event",
                    "id": int(row["id"]),
                    "session_id": str(row["session_id"])[:8] if row["session_id"] else None,
                    "operation": str(row["event_type"]),
                    "metadata": sanitize_metadata(safe_json_loads(row["metadata_json"])),
                    "created_at": str(row["created_at"]),
                    "updated_at": str(row["created_at"]),
                }
            )

    items.sort(key=lambda item: (str(item["created_at"]), int(item["id"])), reverse=True)
    return {"total": len(items[:max_rows]), "items": items[:max_rows]}


def memory_dashboard_scope_device_ids(request: Request) -> List[str]:
    current_visitor = visitor_ip(request)
    current_device = normalize_visitor_ip(current_visitor)
    if not current_device or not is_device_identity(current_device):
        return []
    device_ids = binding_related_device_ids(current_device)
    return device_ids or [current_device]


def memory_id_in_device_scope(memory_id: int, device_ids: List[str]) -> bool:
    if not device_ids:
        return False
    placeholders = ", ".join("?" for _ in device_ids)
    with connect_db() as conn:
        row = conn.execute(
            f"""
            SELECT 1
            FROM curated_memories
            WHERE id = ?
              AND visitor_ip IN ({placeholders})
              AND importance_label NOT IN ('artifact', 'characters')
              AND source_session_id NOT LIKE 'artifact-%'
              AND source_session_id NOT LIKE 'character-profile-%'
            LIMIT 1
            """,
            (int(memory_id), *device_ids),
        ).fetchone()
    return row is not None
