# Generated by splitting app.py lines 1695-3274. Keep execution order in wangcai_app/startup/loader.py.
def html_response(filename: str) -> FileResponse:
    return FileResponse(
        STATIC_DIR / filename,
        headers={
            "Cache-Control": "no-store, max-age=0",
            "Pragma": "no-cache",
        },
    )


def utc_now() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="seconds")


def parse_utc_iso(value: object) -> Optional[datetime]:
    text = str(value or "").strip()
    if not text:
        return None
    if text.endswith("Z"):
        text = f"{text[:-1]}+00:00"
    try:
        parsed = datetime.fromisoformat(text)
    except ValueError:
        return None
    if parsed.tzinfo is None:
        parsed = parsed.replace(tzinfo=timezone.utc)
    return parsed.astimezone(timezone.utc)


def format_message_time_for_model(created_at: object) -> str:
    parsed = parse_utc_iso(created_at)
    if parsed is None:
        return ""
    local = parsed.astimezone(local_timezone())
    return local.strftime("%Y-%m-%d %H:%M:%S %Z")


def timed_text_for_model(content: str, created_at: object) -> str:
    timestamp = format_message_time_for_model(created_at)
    body = str(content or "")
    if not timestamp:
        return body
    return f"[message_time: {timestamp}]\n{body}"


def connect_db() -> sqlite3.Connection:
    DB_PATH.parent.mkdir(parents=True, exist_ok=True)
    conn = sqlite3.connect(str(DB_PATH))
    conn.row_factory = sqlite3.Row
    conn.execute("PRAGMA journal_mode=WAL")
    conn.execute("PRAGMA foreign_keys=ON")
    return conn


def ensure_column(conn: sqlite3.Connection, table_name: str, column_name: str, column_sql: str) -> None:
    rows = conn.execute(f"PRAGMA table_info({table_name})").fetchall()
    if column_name not in {str(row["name"]) for row in rows}:
        conn.execute(f"ALTER TABLE {table_name} ADD COLUMN {column_name} {column_sql}")


def normalize_artifact_type(artifact_type: str, title: str = "", content: str = "") -> str:
    raw_type = normalize_idle_artifact_terms(artifact_type).strip().lower()
    text = f"{title}\n{content}"
    if raw_type in {"poem", "poetry", "诗", "诗歌", "七言绝句", "五言绝句"}:
        return "poetry"
    if any(token in text for token in ("七言绝句", "五言绝句", "律诗", "绝句", "诗歌", "诗作")):
        return "poetry"
    allowed = {"novel", "script", "worldbuilding", "persona", "notes", "other"}
    return raw_type if raw_type in allowed else "other"


def init_db() -> None:
    with connect_db() as conn:
        conn.executescript(
            """
            CREATE TABLE IF NOT EXISTS sessions (
                id TEXT PRIMARY KEY,
                visitor_ip TEXT NOT NULL,
                user_agent TEXT NOT NULL,
                started_at TEXT NOT NULL,
                ended_at TEXT,
                end_reason TEXT
            );

            CREATE TABLE IF NOT EXISTS messages (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                session_id TEXT NOT NULL,
                role TEXT NOT NULL CHECK(role IN ('user', 'assistant', 'system')),
                content TEXT NOT NULL,
                status TEXT NOT NULL DEFAULT 'completed',
                created_at TEXT NOT NULL,
                FOREIGN KEY(session_id) REFERENCES sessions(id)
            );

            CREATE TABLE IF NOT EXISTS session_context_links (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                current_session_id TEXT NOT NULL,
                source_session_id TEXT NOT NULL,
                order_index INTEGER NOT NULL,
                loaded_at TEXT NOT NULL,
                UNIQUE(current_session_id, source_session_id),
                FOREIGN KEY(current_session_id) REFERENCES sessions(id) ON DELETE CASCADE,
                FOREIGN KEY(source_session_id) REFERENCES sessions(id) ON DELETE CASCADE
            );

            CREATE TABLE IF NOT EXISTS events (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                session_id TEXT,
                event_type TEXT NOT NULL,
                visitor_ip TEXT NOT NULL,
                created_at TEXT NOT NULL,
                metadata_json TEXT NOT NULL DEFAULT '{}',
                FOREIGN KEY(session_id) REFERENCES sessions(id)
            );

            CREATE TABLE IF NOT EXISTS analysis_trace_events (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                session_id TEXT NOT NULL,
                trace_id TEXT NOT NULL,
                event_type TEXT NOT NULL,
                visitor_ip TEXT NOT NULL,
                step_name TEXT NOT NULL,
                duration_ms REAL,
                payload_json TEXT NOT NULL DEFAULT '{}',
                created_at TEXT NOT NULL,
                FOREIGN KEY(session_id) REFERENCES sessions(id)
            );

            CREATE INDEX IF NOT EXISTS idx_messages_session_created
                ON messages(session_id, id);
            CREATE INDEX IF NOT EXISTS idx_session_context_current
                ON session_context_links(current_session_id, order_index);
            CREATE INDEX IF NOT EXISTS idx_session_context_source
                ON session_context_links(source_session_id);
            CREATE INDEX IF NOT EXISTS idx_events_session_created
                ON events(session_id, id);
            CREATE INDEX IF NOT EXISTS idx_analysis_trace_session_created
                ON analysis_trace_events(session_id, id);
            CREATE INDEX IF NOT EXISTS idx_analysis_trace_trace_id
                ON analysis_trace_events(trace_id, id);
            CREATE INDEX IF NOT EXISTS idx_sessions_started
                ON sessions(started_at);

            CREATE TABLE IF NOT EXISTS memory_compression_cache (
                cache_key TEXT PRIMARY KEY,
                user_message TEXT NOT NULL,
                segment_ids_json TEXT NOT NULL,
                summary TEXT NOT NULL,
                created_at TEXT NOT NULL
            );

            CREATE TABLE IF NOT EXISTS curated_memories (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                source_session_id TEXT NOT NULL,
                start_message_id INTEGER NOT NULL,
                end_message_id INTEGER NOT NULL,
                source_hash TEXT NOT NULL UNIQUE,
                content TEXT NOT NULL,
                importance_label TEXT NOT NULL,
                visitor_ip TEXT,
                profile_id INTEGER,
                created_at TEXT NOT NULL,
                updated_at TEXT NOT NULL
            );

            CREATE TABLE IF NOT EXISTS visitor_profiles (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                profile_key TEXT NOT NULL UNIQUE,
                display_name TEXT NOT NULL,
                summary TEXT NOT NULL,
                confidence REAL NOT NULL DEFAULT 0.5,
                created_at TEXT NOT NULL,
                updated_at TEXT NOT NULL
            );

            CREATE TABLE IF NOT EXISTS visitor_ip_links (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                profile_id INTEGER NOT NULL,
                visitor_ip TEXT NOT NULL UNIQUE,
                user_agent TEXT NOT NULL DEFAULT '',
                seen_count INTEGER NOT NULL DEFAULT 1,
                confidence REAL NOT NULL DEFAULT 0.65,
                first_seen_at TEXT NOT NULL,
                last_seen_at TEXT NOT NULL,
                FOREIGN KEY(profile_id) REFERENCES visitor_profiles(id) ON DELETE CASCADE
            );

            CREATE TABLE IF NOT EXISTS shared_user_bindings (
                device_id TEXT PRIMARY KEY,
                shared_user_id TEXT NOT NULL DEFAULT '',
                share_chat_history INTEGER NOT NULL DEFAULT 0,
                is_host INTEGER NOT NULL DEFAULT 0,
                created_at TEXT NOT NULL,
                updated_at TEXT NOT NULL,
                host_updated_at TEXT,
                inherit_assistant_profile INTEGER NOT NULL DEFAULT 0,
                profile_owner_updated_at TEXT
            );

            CREATE TABLE IF NOT EXISTS curated_memory_vectors (
                memory_id INTEGER PRIMARY KEY,
                dim INTEGER NOT NULL,
                vector BLOB NOT NULL,
                model_name TEXT NOT NULL,
                created_at TEXT NOT NULL,
                FOREIGN KEY(memory_id) REFERENCES curated_memories(id) ON DELETE CASCADE
            );

            CREATE TABLE IF NOT EXISTS memory_agent_jobs (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                session_id TEXT NOT NULL,
                start_message_id INTEGER NOT NULL,
                end_message_id INTEGER NOT NULL,
                source_hash TEXT NOT NULL UNIQUE,
                status TEXT NOT NULL DEFAULT 'pending',
                reason TEXT NOT NULL,
                error TEXT,
                created_at TEXT NOT NULL,
                updated_at TEXT NOT NULL
            );

            CREATE TABLE IF NOT EXISTS memory_retrieval_logs (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                session_id TEXT NOT NULL,
                query_hash TEXT NOT NULL,
                result_count INTEGER NOT NULL,
                memory_ids_json TEXT NOT NULL,
                scores_json TEXT NOT NULL,
                labels_json TEXT NOT NULL,
                created_at TEXT NOT NULL
            );

            CREATE TABLE IF NOT EXISTS idle_agent_runs (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                task_type TEXT NOT NULL,
                title TEXT NOT NULL,
                prompt_summary TEXT NOT NULL,
                status TEXT NOT NULL,
                interrupted_reason TEXT,
                started_at TEXT NOT NULL,
                finished_at TEXT,
                updated_at TEXT NOT NULL
            );

            CREATE TABLE IF NOT EXISTS idle_agent_artifacts (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                run_id INTEGER NOT NULL,
                title TEXT NOT NULL,
                artifact_type TEXT NOT NULL,
                content TEXT NOT NULL,
                created_at TEXT NOT NULL,
                FOREIGN KEY(run_id) REFERENCES idle_agent_runs(id) ON DELETE CASCADE
            );

            CREATE TABLE IF NOT EXISTS idle_artifact_vectors (
                artifact_id INTEGER PRIMARY KEY,
                dim INTEGER NOT NULL,
                vector BLOB NOT NULL,
                model_name TEXT NOT NULL,
                index_text TEXT NOT NULL,
                created_at TEXT NOT NULL,
                FOREIGN KEY(artifact_id) REFERENCES idle_agent_artifacts(id) ON DELETE CASCADE
            );

            CREATE TABLE IF NOT EXISTS idle_artifact_comments (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                artifact_id INTEGER NOT NULL,
                parent_id INTEGER,
                root_id INTEGER,
                role TEXT NOT NULL,
                author TEXT NOT NULL,
                content TEXT NOT NULL,
                created_at TEXT NOT NULL,
                updated_at TEXT NOT NULL,
                FOREIGN KEY(artifact_id) REFERENCES idle_agent_artifacts(id) ON DELETE CASCADE,
                FOREIGN KEY(parent_id) REFERENCES idle_artifact_comments(id) ON DELETE CASCADE,
                FOREIGN KEY(root_id) REFERENCES idle_artifact_comments(id) ON DELETE CASCADE
            );

            CREATE TABLE IF NOT EXISTS generated_images (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                batch_id TEXT NOT NULL,
                source_type TEXT NOT NULL,
                source_id TEXT NOT NULL,
                file_path TEXT NOT NULL,
                public_url TEXT NOT NULL,
                original_prompt TEXT NOT NULL DEFAULT '',
                optimized_prompt TEXT NOT NULL DEFAULT '',
                negative_prompt TEXT NOT NULL DEFAULT '',
                aspect_ratio TEXT NOT NULL DEFAULT '1:1',
                model_name TEXT NOT NULL DEFAULT '',
                status TEXT NOT NULL DEFAULT 'completed',
                error TEXT NOT NULL DEFAULT '',
                created_at TEXT NOT NULL
            );

            CREATE TABLE IF NOT EXISTS artifact_images (
                artifact_id INTEGER NOT NULL,
                image_id INTEGER NOT NULL,
                position INTEGER NOT NULL DEFAULT 0,
                is_cover INTEGER NOT NULL DEFAULT 0,
                PRIMARY KEY (artifact_id, image_id),
                FOREIGN KEY(artifact_id) REFERENCES idle_agent_artifacts(id) ON DELETE CASCADE,
                FOREIGN KEY(image_id) REFERENCES generated_images(id) ON DELETE CASCADE
            );

            CREATE TABLE IF NOT EXISTS hidden_character_profiles (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                canonical_name TEXT NOT NULL,
                name_key TEXT NOT NULL UNIQUE,
                aliases_json TEXT NOT NULL DEFAULT '[]',
                visual_prompt TEXT NOT NULL DEFAULT '',
                negative_prompt TEXT NOT NULL DEFAULT '',
                personality TEXT NOT NULL DEFAULT '',
                background TEXT NOT NULL DEFAULT '',
                relationships_json TEXT NOT NULL DEFAULT '[]',
                reference_image_ids_json TEXT NOT NULL DEFAULT '[]',
                avatar_image_ids_json TEXT NOT NULL DEFAULT '[]',
                source_session_id TEXT NOT NULL DEFAULT '',
                source_message_ids_json TEXT NOT NULL DEFAULT '[]',
                source_visitor_ip TEXT NOT NULL DEFAULT '',
                scope TEXT NOT NULL DEFAULT 'artifact_public',
                status TEXT NOT NULL DEFAULT 'active',
                confidence REAL NOT NULL DEFAULT 0.7,
                revision_count INTEGER NOT NULL DEFAULT 1,
                created_at TEXT NOT NULL,
                updated_at TEXT NOT NULL
            );

            CREATE TABLE IF NOT EXISTS hidden_character_profile_events (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                character_id INTEGER NOT NULL,
                event_type TEXT NOT NULL,
                source_type TEXT NOT NULL,
                source_session_id TEXT NOT NULL DEFAULT '',
                source_message_ids_json TEXT NOT NULL DEFAULT '[]',
                patch_json TEXT NOT NULL DEFAULT '{}',
                reason TEXT NOT NULL DEFAULT '',
                created_at TEXT NOT NULL,
                FOREIGN KEY(character_id) REFERENCES hidden_character_profiles(id) ON DELETE CASCADE
            );

            CREATE TABLE IF NOT EXISTS hidden_artifact_directives (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                directive_key TEXT NOT NULL UNIQUE,
                directive_type TEXT NOT NULL DEFAULT 'other',
                subject TEXT NOT NULL DEFAULT '',
                directive TEXT NOT NULL,
                characters_json TEXT NOT NULL DEFAULT '[]',
                series_title TEXT NOT NULL DEFAULT '',
                scope TEXT NOT NULL DEFAULT 'persistent',
                status TEXT NOT NULL DEFAULT 'active',
                priority INTEGER NOT NULL DEFAULT 50,
                confidence REAL NOT NULL DEFAULT 0.7,
                source_session_id TEXT NOT NULL DEFAULT '',
                source_message_ids_json TEXT NOT NULL DEFAULT '[]',
                source_visitor_ip TEXT NOT NULL DEFAULT '',
                revision_count INTEGER NOT NULL DEFAULT 1,
                created_at TEXT NOT NULL,
                updated_at TEXT NOT NULL
            );

            CREATE TABLE IF NOT EXISTS hidden_artifact_directive_events (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                directive_id INTEGER NOT NULL,
                event_type TEXT NOT NULL,
                source_session_id TEXT NOT NULL DEFAULT '',
                source_message_ids_json TEXT NOT NULL DEFAULT '[]',
                patch_json TEXT NOT NULL DEFAULT '{}',
                reason TEXT NOT NULL DEFAULT '',
                created_at TEXT NOT NULL,
                FOREIGN KEY(directive_id) REFERENCES hidden_artifact_directives(id) ON DELETE CASCADE
            );

            CREATE TABLE IF NOT EXISTS app_settings (
                key TEXT PRIMARY KEY,
                value TEXT NOT NULL,
                updated_at TEXT NOT NULL
            );

            CREATE INDEX IF NOT EXISTS idx_curated_memories_source
                ON curated_memories(source_session_id, start_message_id, end_message_id);
            CREATE INDEX IF NOT EXISTS idx_visitor_ip_links_profile
                ON visitor_ip_links(profile_id);
            CREATE INDEX IF NOT EXISTS idx_shared_user_bindings_user
                ON shared_user_bindings(shared_user_id, updated_at);
            CREATE INDEX IF NOT EXISTS idx_shared_user_bindings_host
                ON shared_user_bindings(shared_user_id, is_host, host_updated_at, updated_at);
            CREATE INDEX IF NOT EXISTS idx_memory_agent_jobs_status
                ON memory_agent_jobs(status, id);
            CREATE INDEX IF NOT EXISTS idx_memory_retrieval_logs_created
                ON memory_retrieval_logs(created_at, id);
            CREATE INDEX IF NOT EXISTS idx_idle_agent_runs_status
                ON idle_agent_runs(status, id);
            CREATE INDEX IF NOT EXISTS idx_idle_agent_artifacts_type
                ON idle_agent_artifacts(artifact_type, id);
            CREATE INDEX IF NOT EXISTS idx_idle_artifact_vectors_model
                ON idle_artifact_vectors(model_name, artifact_id);
            CREATE INDEX IF NOT EXISTS idx_idle_artifact_comments_artifact
                ON idle_artifact_comments(artifact_id, created_at, id);
            CREATE INDEX IF NOT EXISTS idx_idle_artifact_comments_parent
                ON idle_artifact_comments(parent_id, id);
            CREATE INDEX IF NOT EXISTS idx_generated_images_source
                ON generated_images(source_type, source_id, id);
            CREATE INDEX IF NOT EXISTS idx_generated_images_batch
                ON generated_images(batch_id, id);
            CREATE INDEX IF NOT EXISTS idx_artifact_images_artifact
                ON artifact_images(artifact_id, position, image_id);
            CREATE INDEX IF NOT EXISTS idx_hidden_character_profiles_status
                ON hidden_character_profiles(status, updated_at);
            CREATE INDEX IF NOT EXISTS idx_hidden_character_profile_events_character
                ON hidden_character_profile_events(character_id, id);
            CREATE INDEX IF NOT EXISTS idx_hidden_artifact_directives_status
                ON hidden_artifact_directives(status, priority, updated_at);
            CREATE INDEX IF NOT EXISTS idx_hidden_artifact_directive_events_directive
                ON hidden_artifact_directive_events(directive_id, id);
            """
        )
        ensure_column(conn, "curated_memories", "visitor_ip", "TEXT")
        ensure_column(conn, "curated_memories", "profile_id", "INTEGER")
        ensure_column(conn, "curated_memories", "timeline_at", "TEXT")
        ensure_column(conn, "curated_memories", "timeline_start_at", "TEXT")
        ensure_column(conn, "curated_memories", "timeline_end_at", "TEXT")
        ensure_column(conn, "curated_memories", "timeline_kind", "TEXT")
        ensure_column(conn, "curated_memories", "supersedes_id", "INTEGER")
        ensure_column(conn, "curated_memories", "confidence", "REAL NOT NULL DEFAULT 0.7")
        ensure_column(conn, "curated_memories", "refine_status", "TEXT NOT NULL DEFAULT ''")
        ensure_column(conn, "curated_memories", "refined_at", "TEXT")
        ensure_column(conn, "curated_memories", "refined_from_id", "INTEGER")
        ensure_column(conn, "curated_memories", "refine_reason", "TEXT")
        ensure_column(conn, "messages", "metadata_json", "TEXT NOT NULL DEFAULT '{}'")
        ensure_column(conn, "idle_agent_artifacts", "series_title", "TEXT")
        ensure_column(conn, "idle_agent_artifacts", "episode_index", "INTEGER")
        ensure_column(conn, "idle_agent_artifacts", "summary", "TEXT")
        ensure_column(conn, "idle_agent_artifacts", "likes", "INTEGER NOT NULL DEFAULT 0")
        ensure_column(conn, "generated_images", "batch_id", "TEXT NOT NULL DEFAULT ''")
        ensure_column(conn, "generated_images", "source_type", "TEXT NOT NULL DEFAULT ''")
        ensure_column(conn, "generated_images", "source_id", "TEXT NOT NULL DEFAULT ''")
        ensure_column(conn, "generated_images", "file_path", "TEXT NOT NULL DEFAULT ''")
        ensure_column(conn, "generated_images", "public_url", "TEXT NOT NULL DEFAULT ''")
        ensure_column(conn, "generated_images", "original_prompt", "TEXT NOT NULL DEFAULT ''")
        ensure_column(conn, "generated_images", "optimized_prompt", "TEXT NOT NULL DEFAULT ''")
        ensure_column(conn, "generated_images", "negative_prompt", "TEXT NOT NULL DEFAULT ''")
        ensure_column(conn, "generated_images", "aspect_ratio", "TEXT NOT NULL DEFAULT '1:1'")
        ensure_column(conn, "generated_images", "model_name", "TEXT NOT NULL DEFAULT ''")
        ensure_column(conn, "generated_images", "status", "TEXT NOT NULL DEFAULT 'completed'")
        ensure_column(conn, "generated_images", "error", "TEXT NOT NULL DEFAULT ''")
        ensure_column(conn, "generated_images", "created_at", "TEXT")
        ensure_column(conn, "hidden_character_profiles", "source_visitor_ip", "TEXT NOT NULL DEFAULT ''")
        ensure_column(conn, "hidden_character_profiles", "avatar_image_ids_json", "TEXT NOT NULL DEFAULT '[]'")
        ensure_column(conn, "hidden_character_profiles", "scope", "TEXT NOT NULL DEFAULT 'artifact_public'")
        ensure_column(conn, "hidden_character_profiles", "status", "TEXT NOT NULL DEFAULT 'active'")
        ensure_column(conn, "hidden_character_profiles", "revision_count", "INTEGER NOT NULL DEFAULT 1")
        ensure_column(conn, "hidden_artifact_directives", "source_visitor_ip", "TEXT NOT NULL DEFAULT ''")
        ensure_column(conn, "hidden_artifact_directives", "revision_count", "INTEGER NOT NULL DEFAULT 1")
        ensure_column(conn, "shared_user_bindings", "shared_user_id", "TEXT NOT NULL DEFAULT ''")
        ensure_column(conn, "shared_user_bindings", "share_chat_history", "INTEGER NOT NULL DEFAULT 0")
        ensure_column(conn, "shared_user_bindings", "is_host", "INTEGER NOT NULL DEFAULT 0")
        ensure_column(conn, "shared_user_bindings", "created_at", "TEXT")
        ensure_column(conn, "shared_user_bindings", "updated_at", "TEXT")
        ensure_column(conn, "shared_user_bindings", "host_updated_at", "TEXT")
        ensure_column(conn, "shared_user_bindings", "inherit_assistant_profile", "INTEGER NOT NULL DEFAULT 0")
        ensure_column(conn, "shared_user_bindings", "profile_owner_updated_at", "TEXT")
        conn.execute(
            """
            CREATE INDEX IF NOT EXISTS idx_shared_user_bindings_profile_owner
                ON shared_user_bindings(shared_user_id, inherit_assistant_profile, profile_owner_updated_at, updated_at)
            """
        )
        conn.execute(
            """
            UPDATE idle_agent_artifacts
            SET artifact_type = 'poetry'
            WHERE artifact_type != 'poetry'
              AND (
                title LIKE '%七言绝句%'
                OR title LIKE '%五言绝句%'
                OR title LIKE '%诗歌%'
                OR title LIKE '%诗作%'
                OR content LIKE '%七言绝句%'
                OR content LIKE '%五言绝句%'
                OR content LIKE '%律诗%'
                OR content LIKE '%绝句%'
              )
            """
        )
        conn.execute(
            """
            CREATE INDEX IF NOT EXISTS idx_curated_memories_visitor
                ON curated_memories(visitor_ip, profile_id)
            """
        )
        conn.execute(
            """
            CREATE INDEX IF NOT EXISTS idx_curated_memories_timeline
                ON curated_memories(timeline_at, id)
            """
        )
        conn.execute(
            """
            CREATE INDEX IF NOT EXISTS idx_idle_agent_artifacts_series
                ON idle_agent_artifacts(series_title, episode_index, id)
            """
        )
        conn.execute(
            """
            CREATE INDEX IF NOT EXISTS idx_idle_agent_artifacts_likes
                ON idle_agent_artifacts(likes, id)
            """
        )
        conn.execute(
            """
            DELETE FROM curated_memories
            WHERE importance_label = 'artifact'
               OR source_session_id LIKE 'artifact-%'
            """
        )
        if IDLE_AGENT_CUSTOM_PROMPT_DEFAULT:
            conn.execute(
                """
                INSERT INTO app_settings (key, value, updated_at)
                VALUES ('idle_agent_custom_prompt', ?, ?)
                ON CONFLICT(key) DO NOTHING
                """,
                (IDLE_AGENT_CUSTOM_PROMPT_DEFAULT, utc_now()),
            )
        memory.init_memory_tables(conn)
        vector_memory.init_vector_memory_tables(conn)


def row_to_dict(row: Optional[sqlite3.Row]) -> Optional[Dict[str, str]]:
    if row is None:
        return None
    return {key: row[key] for key in row.keys()}


def get_app_setting(key: str, default: str = "") -> str:
    with connect_db() as conn:
        row = conn.execute("SELECT value FROM app_settings WHERE key = ?", (key,)).fetchone()
    return str(row["value"]) if row else default


def set_app_setting(key: str, value: str) -> None:
    with connect_db() as conn:
        conn.execute(
            """
            INSERT INTO app_settings (key, value, updated_at)
            VALUES (?, ?, ?)
            ON CONFLICT(key) DO UPDATE SET
                value = excluded.value,
                updated_at = excluded.updated_at
            """,
            (key, value, utc_now()),
        )


def delete_app_setting(key: str) -> None:
    with connect_db() as conn:
        conn.execute("DELETE FROM app_settings WHERE key = ?", (key,))


def get_idle_agent_custom_prompt() -> str:
    return get_app_setting("idle_agent_custom_prompt", IDLE_AGENT_CUSTOM_PROMPT_DEFAULT)


def is_idle_agent_paused() -> bool:
    return get_app_setting("idle_agent_paused", "0").strip() == "1"


def set_idle_agent_paused(paused: bool) -> bool:
    set_app_setting("idle_agent_paused", "1" if paused else "0")
    if paused:
        IDLE_AGENT_CANCEL_EVENT.set()
    else:
        IDLE_AGENT_CANCEL_EVENT.clear()
    return paused


def load_idle_story_seeds() -> List[str]:
    # Story seeds were an early bootstrap mechanism. The current artifact chain
    # is driven by the user creative prompt, series planner, character cards and
    # dynamic anti-repetition context, so old seeds must not silently steer new work.
    return []


def set_idle_agent_custom_prompt(prompt: str) -> None:
    set_app_setting("idle_agent_custom_prompt", prompt.strip())


def get_session(session_id: str) -> Optional[Dict[str, str]]:
    with connect_db() as conn:
        row = conn.execute("SELECT * FROM sessions WHERE id = ?", (session_id,)).fetchone()
    return row_to_dict(row)


def create_session(visitor_ip: str, user_agent: str) -> str:
    session_id = uuid.uuid4().hex
    now = utc_now()
    with connect_db() as conn:
        observe_visitor_identity(conn, visitor_ip, user_agent)
        conn.execute(
            """
            INSERT INTO sessions (id, visitor_ip, user_agent, started_at)
            VALUES (?, ?, ?, ?)
            """,
            (session_id, visitor_ip or "unknown", user_agent or "", now),
        )
        conn.execute(
            """
            INSERT INTO events (session_id, event_type, visitor_ip, created_at, metadata_json)
            VALUES (?, 'session_start', ?, ?, '{}')
            """,
            (session_id, visitor_ip or "unknown", now),
        )
    return session_id


def normalize_visitor_ip(visitor_ip: str) -> str:
    return (visitor_ip or "unknown").strip() or "unknown"


def clean_device_id(value: str) -> str:
    candidate = (value or "").strip()
    if candidate.startswith("device:"):
        candidate = candidate.split(":", 1)[1]
    if not candidate or len(candidate) > 96:
        return ""
    if not re.fullmatch(r"[A-Za-z0-9_-]{12,96}", candidate):
        return ""
    return f"device:{candidate}"


def clean_reported_client_ip(value: str) -> str:
    # Legacy cleanup helper only. New request identity never uses client IP.
    candidate = (value or "").split(",")[0].strip().strip('"[]')
    if not candidate:
        return ""
    try:
        parsed = ipaddress.ip_address(candidate)
    except ValueError:
        return ""
    if parsed.is_loopback or parsed.is_unspecified:
        return ""
    return str(parsed)


def clean_reported_identity(value: str) -> str:
    # Only browser device identities are accepted as live identities.
    return clean_device_id(value)


def is_device_identity(value: str) -> bool:
    return normalize_visitor_ip(value).startswith("device:")


def is_anonymous_identity(value: str) -> bool:
    return normalize_visitor_ip(value).lower() in {"", "unknown", "anonymous", "local", "localhost"}


def is_placeholder_visitor_ip(value: str) -> bool:
    ip = normalize_visitor_ip(value).lower()
    if is_anonymous_identity(ip):
        return True
    try:
        parsed = ipaddress.ip_address(ip)
    except ValueError:
        return False
    return parsed.is_loopback or parsed.is_unspecified


def clean_shared_user_id(value: str) -> str:
    text = str(value or "").strip()
    if not text:
        return ""
    return clean_search_text(text, SHARED_USER_ID_MAX_CHARS)


DEVICE_LOCAL_MEMORY_LABELS = {"identity", "persona", "preference", "rule"}


def is_device_local_memory_label(label: str) -> bool:
    return (label or "other").strip() in DEVICE_LOCAL_MEMORY_LABELS


def prompt_priority_memory_bucket(content: str, label: str) -> str:
    normalized_label = (label or "other").strip()
    if is_opening_context_memory(content, normalized_label):
        return f"opening:{normalized_label}"
    if is_profile_context_memory(content, normalized_label):
        return f"profile:{normalized_label}"
    return ""


def device_local_prompt_priority_buckets(
    conn: sqlite3.Connection,
    device_id: str,
) -> set:
    current_ip = normalize_visitor_ip(device_id)
    if not current_ip or not is_device_identity(current_ip):
        return set()
    rows = conn.execute(
        """
        SELECT content, importance_label
        FROM curated_memories
        WHERE visitor_ip = ?
          AND importance_label IN ('identity', 'persona', 'preference', 'rule')
        ORDER BY id DESC
        LIMIT 200
        """,
        (current_ip,),
    ).fetchall()
    buckets = set()
    for row in rows:
        bucket = prompt_priority_memory_bucket(str(row["content"] or ""), str(row["importance_label"] or ""))
        if bucket:
            buckets.add(bucket)
    return buckets


def binding_row_to_dict(
    row: Optional[sqlite3.Row],
    host_device_id: str = "",
    profile_owner_device_id: str = "",
) -> Dict[str, object]:
    if row is None:
        return {
            "shared_user_id": "",
            "share_chat_history": False,
            "is_host": False,
            "host_device_id": host_device_id or "",
            "inherit_assistant_profile": False,
            "profile_owner_device_id": profile_owner_device_id or "",
            "updated_at": "",
        }
    shared_user_id = clean_shared_user_id(str(row["shared_user_id"] or ""))
    current_is_host = bool(row["is_host"]) if host_device_id == str(row["device_id"] or "") else False
    if not host_device_id and bool(row["is_host"]):
        host_device_id = str(row["device_id"] or "")
        current_is_host = True
    current_is_profile_owner = (
        bool(row["inherit_assistant_profile"])
        if profile_owner_device_id == str(row["device_id"] or "")
        else False
    )
    if not profile_owner_device_id and bool(row["inherit_assistant_profile"]):
        profile_owner_device_id = str(row["device_id"] or "")
        current_is_profile_owner = True
    return {
        "shared_user_id": shared_user_id,
        "share_chat_history": bool(row["share_chat_history"]),
        "is_host": current_is_host,
        "host_device_id": host_device_id or "",
        "inherit_assistant_profile": current_is_profile_owner,
        "profile_owner_device_id": profile_owner_device_id or "",
        "updated_at": str(row["updated_at"] or ""),
    }


def effective_host_device_id(conn: sqlite3.Connection, shared_user_id: str) -> str:
    normalized_user = clean_shared_user_id(shared_user_id)
    if not normalized_user:
        return ""
    row = conn.execute(
        """
        SELECT device_id
        FROM shared_user_bindings
        WHERE shared_user_id = ?
          AND is_host = 1
        ORDER BY COALESCE(host_updated_at, updated_at) DESC, updated_at DESC, device_id DESC
        LIMIT 1
        """,
        (normalized_user,),
    ).fetchone()
    return str(row["device_id"]) if row else ""


def effective_profile_owner_device_id(conn: sqlite3.Connection, shared_user_id: str) -> str:
    normalized_user = clean_shared_user_id(shared_user_id)
    if not normalized_user:
        return ""
    row = conn.execute(
        """
        SELECT device_id
        FROM shared_user_bindings
        WHERE shared_user_id = ?
          AND inherit_assistant_profile = 1
        ORDER BY COALESCE(profile_owner_updated_at, updated_at) DESC, updated_at DESC, device_id DESC
        LIMIT 1
        """,
        (normalized_user,),
    ).fetchone()
    return str(row["device_id"]) if row else ""


def binding_scope_for_device(
    conn: sqlite3.Connection,
    current_visitor_ip: str,
) -> Dict[str, object]:
    current_ip = normalize_visitor_ip(current_visitor_ip) if current_visitor_ip else ""
    default_scope = {
        "current_device_id": current_ip,
        "shared_user_id": "",
        "share_chat_history": False,
        "device_ids": [current_ip] if current_ip and is_device_identity(current_ip) else [],
        "host_device_id": "",
        "is_host": False,
        "profile_owner_device_id": "",
        "inherit_assistant_profile": False,
    }
    if not current_ip or not is_device_identity(current_ip):
        return default_scope
    row = conn.execute(
        """
        SELECT device_id, shared_user_id, share_chat_history, is_host,
               inherit_assistant_profile, updated_at
        FROM shared_user_bindings
        WHERE device_id = ?
        """,
        (current_ip,),
    ).fetchone()
    shared_user_id = clean_shared_user_id(str(row["shared_user_id"] or "")) if row else ""
    if not shared_user_id:
        return default_scope
    device_rows = conn.execute(
        """
        SELECT device_id
        FROM shared_user_bindings
        WHERE shared_user_id = ?
        ORDER BY updated_at DESC, device_id ASC
        """,
        (shared_user_id,),
    ).fetchall()
    device_ids = []
    seen = set()
    for item in device_rows:
        device_id = normalize_visitor_ip(str(item["device_id"] or ""))
        if not device_id or not is_device_identity(device_id) or device_id in seen:
            continue
        seen.add(device_id)
        device_ids.append(device_id)
    if current_ip not in seen:
        device_ids.insert(0, current_ip)
    host_device_id = effective_host_device_id(conn, shared_user_id)
    profile_owner_device_id = effective_profile_owner_device_id(conn, shared_user_id)
    return {
        "current_device_id": current_ip,
        "shared_user_id": shared_user_id,
        "share_chat_history": bool(row["share_chat_history"]) if row else False,
        "device_ids": device_ids,
        "host_device_id": host_device_id,
        "is_host": host_device_id == current_ip and bool(host_device_id),
        "profile_owner_device_id": profile_owner_device_id,
        "inherit_assistant_profile": profile_owner_device_id == current_ip and bool(profile_owner_device_id),
    }


def binding_related_device_ids(current_visitor_ip: str) -> List[str]:
    current_ip = normalize_visitor_ip(current_visitor_ip) if current_visitor_ip else ""
    if not current_ip or not is_device_identity(current_ip):
        return []
    with connect_db() as conn:
        scope = binding_scope_for_device(conn, current_ip)
    return list(scope.get("device_ids") or [current_ip])


def shared_memory_owner_device_id(
    conn: sqlite3.Connection,
    source_device_id: str,
    content: str,
    importance_label: str,
) -> str:
    source_ip = normalize_visitor_ip(source_device_id)
    if not source_ip or not is_device_identity(source_ip):
        return source_ip
    scope = binding_scope_for_device(conn, source_ip)
    if is_device_local_memory_label(importance_label):
        return str(scope.get("profile_owner_device_id") or "") or source_ip
    host_device_id = str(scope.get("host_device_id") or "")
    if not host_device_id or host_device_id == source_ip:
        return source_ip
    return host_device_id


def refresh_binding_scoped_opening_prompts(current_visitor_ip: str) -> None:
    device_ids = binding_related_device_ids(current_visitor_ip)
    if not device_ids:
        return
    for device_id in device_ids:
        try:
            refresh_cached_opening_prompt(device_id)
        except Exception:
            continue


def delete_opening_prompt_caches_for_devices(device_ids: List[str]) -> None:
    seen = set()
    for device_id in device_ids:
        normalized = normalize_visitor_ip(device_id)
        if not normalized or not is_device_identity(normalized) or normalized in seen:
            continue
        seen.add(normalized)
        delete_app_setting(opening_prompt_cache_key(normalized))


def sql_in_clause_params(items: List[object]) -> Tuple[str, List[object]]:
    values = list(items)
    if not values:
        return "(NULL)", []
    return f"({','.join('?' for _ in values)})", values


def get_user_memory_binding(current_visitor_ip: str) -> Dict[str, object]:
    current_ip = normalize_visitor_ip(current_visitor_ip)
    if not current_ip or not is_device_identity(current_ip):
        return {
            "device_id": current_ip,
            "shared_user_id": "",
            "share_chat_history": False,
            "is_host": False,
            "host_device_id": "",
            "host_label": "",
            "inherit_assistant_profile": False,
            "profile_owner_device_id": "",
            "profile_owner_label": "",
            "updated_at": "",
        }
    with connect_db() as conn:
        row = conn.execute(
            """
            SELECT device_id, shared_user_id, share_chat_history, is_host,
                   inherit_assistant_profile, updated_at
            FROM shared_user_bindings
            WHERE device_id = ?
            """,
            (current_ip,),
        ).fetchone()
        host_device_id = effective_host_device_id(conn, str(row["shared_user_id"] or "")) if row else ""
        profile_owner_device_id = effective_profile_owner_device_id(conn, str(row["shared_user_id"] or "")) if row else ""
    payload = binding_row_to_dict(
        row,
        host_device_id=host_device_id,
        profile_owner_device_id=profile_owner_device_id,
    )
    payload["device_id"] = current_ip
    payload["host_label"] = "主机" if payload.get("is_host") else ""
    payload["profile_owner_label"] = "助手设定来源" if payload.get("inherit_assistant_profile") else ""
    return payload


def upsert_user_memory_binding(
    current_visitor_ip: str,
    shared_user_id: str,
    share_chat_history: bool = False,
    is_host: bool = False,
    inherit_assistant_profile: bool = False,
) -> Dict[str, object]:
    current_ip = normalize_visitor_ip(current_visitor_ip)
    if not current_ip or not is_device_identity(current_ip):
        raise HTTPException(status_code=400, detail="device identity required")
    normalized_user = clean_shared_user_id(shared_user_id)
    now = utc_now()
    cache_devices_to_clear: List[str] = []
    with connect_db() as conn:
        old_scope = binding_scope_for_device(conn, current_ip)
        old_user = str(old_scope.get("shared_user_id") or "")
        old_devices = list(old_scope.get("device_ids") or [current_ip])
        existing = conn.execute(
            """
            SELECT device_id, shared_user_id, share_chat_history, is_host,
                   inherit_assistant_profile, created_at
            FROM shared_user_bindings
            WHERE device_id = ?
            """,
            (current_ip,),
        ).fetchone()
        if not normalized_user:
            conn.execute("DELETE FROM shared_user_bindings WHERE device_id = ?", (current_ip,))
            cache_devices_to_clear = old_devices
            result = {
                "device_id": current_ip,
                "shared_user_id": "",
                "share_chat_history": False,
                "is_host": False,
                "host_device_id": "",
                "host_label": "",
                "inherit_assistant_profile": False,
                "profile_owner_device_id": "",
                "profile_owner_label": "",
                "updated_at": now,
                "left_previous_shared_user": bool(old_user),
            }
        else:
            if is_host:
                conn.execute(
                    """
                    UPDATE shared_user_bindings
                    SET is_host = 0,
                        updated_at = ?
                    WHERE shared_user_id = ?
                    """,
                    (now, normalized_user),
                )
            if inherit_assistant_profile:
                conn.execute(
                    """
                    UPDATE shared_user_bindings
                    SET inherit_assistant_profile = 0,
                        profile_owner_updated_at = NULL,
                        updated_at = ?
                    WHERE shared_user_id = ?
                    """,
                    (now, normalized_user),
                )
            created_at = str(existing["created_at"] or now) if existing else now
            conn.execute(
                """
                INSERT INTO shared_user_bindings (
                    device_id, shared_user_id, share_chat_history, is_host,
                    inherit_assistant_profile, created_at, updated_at,
                    host_updated_at, profile_owner_updated_at
                )
                VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
                ON CONFLICT(device_id) DO UPDATE SET
                    shared_user_id = excluded.shared_user_id,
                    share_chat_history = excluded.share_chat_history,
                    is_host = excluded.is_host,
                    inherit_assistant_profile = excluded.inherit_assistant_profile,
                    updated_at = excluded.updated_at,
                    host_updated_at = excluded.host_updated_at,
                    profile_owner_updated_at = excluded.profile_owner_updated_at
                """,
                (
                    current_ip,
                    normalized_user,
                    1 if share_chat_history else 0,
                    1 if is_host else 0,
                    1 if inherit_assistant_profile else 0,
                    created_at,
                    now,
                    now if is_host else None,
                    now if inherit_assistant_profile else None,
                ),
            )
            new_scope = binding_scope_for_device(conn, current_ip)
            host_device_id = str(new_scope.get("host_device_id") or "")
            profile_owner_device_id = str(new_scope.get("profile_owner_device_id") or "")
            cache_devices_to_clear = list(set(old_devices) | set(new_scope.get("device_ids") or [current_ip]))
            result = {
                "device_id": current_ip,
                "shared_user_id": normalized_user,
                "share_chat_history": bool(share_chat_history),
                "is_host": host_device_id == current_ip and bool(host_device_id),
                "host_device_id": host_device_id,
                "host_label": "主机" if host_device_id == current_ip and bool(host_device_id) else "",
                "inherit_assistant_profile": profile_owner_device_id == current_ip and bool(profile_owner_device_id),
                "profile_owner_device_id": profile_owner_device_id,
                "profile_owner_label": "助手设定来源"
                if profile_owner_device_id == current_ip and bool(profile_owner_device_id)
                else "",
                "updated_at": now,
                "left_previous_shared_user": bool(old_user and old_user != normalized_user),
            }
    delete_opening_prompt_caches_for_devices(cache_devices_to_clear)
    return result


def refresh_session_visitor_ip(session_id: str, visitor_ip: str, user_agent: str = "") -> bool:
    refreshed_ip = clean_reported_identity(visitor_ip)
    if not refreshed_ip:
        return False
    now = utc_now()
    with connect_db() as conn:
        row = conn.execute(
            "SELECT visitor_ip FROM sessions WHERE id = ?",
            (session_id,),
        ).fetchone()
        if not row:
            return False
        old_ip = normalize_visitor_ip(str(row["visitor_ip"]))
        observe_visitor_identity(conn, refreshed_ip, user_agent)
        if old_ip == refreshed_ip:
            return False
        if not is_placeholder_visitor_ip(old_ip):
            return False
        conn.execute(
            """
            UPDATE sessions
            SET visitor_ip = ?,
                user_agent = CASE WHEN COALESCE(user_agent, '') = '' THEN ? ELSE user_agent END
            WHERE id = ?
            """,
            (refreshed_ip, user_agent or "", session_id),
        )
        conn.execute(
            """
            INSERT INTO events (session_id, event_type, visitor_ip, created_at, metadata_json)
            VALUES (?, 'session_identity_refreshed', ?, ?, ?)
            """,
            (
                session_id,
                refreshed_ip,
                now,
                json.dumps({"old_identity": old_ip, "new_identity": refreshed_ip}, ensure_ascii=False),
            ),
        )
    return True


def publicize_legacy_identity_data() -> Dict[str, int]:
    with connect_db() as conn:
        memory_cur = conn.execute(
            """
            UPDATE curated_memories
            SET visitor_ip = NULL,
                profile_id = NULL,
                updated_at = ?
            WHERE visitor_ip IS NOT NULL
              AND visitor_ip NOT LIKE 'device:%'
            """,
            (utc_now(),),
        )
        session_cur = conn.execute(
            """
            UPDATE sessions
            SET visitor_ip = 'anonymous'
            WHERE visitor_ip IS NOT NULL
              AND visitor_ip NOT LIKE 'device:%'
              AND visitor_ip <> 'anonymous'
            """
        )
        event_cur = conn.execute(
            """
            UPDATE events
            SET visitor_ip = 'anonymous'
            WHERE visitor_ip IS NOT NULL
              AND visitor_ip NOT LIKE 'device:%'
              AND visitor_ip NOT IN ('anonymous', 'local')
            """
        )
        link_cur = conn.execute(
            """
            DELETE FROM visitor_ip_links
            WHERE visitor_ip IS NOT NULL
              AND visitor_ip NOT LIKE 'device:%'
            """
        )
        profile_cur = conn.execute(
            """
            DELETE FROM visitor_profiles
            WHERE id NOT IN (
                SELECT DISTINCT profile_id FROM visitor_ip_links
                UNION
                SELECT DISTINCT profile_id FROM curated_memories WHERE profile_id IS NOT NULL
            )
            """
        )
    return {
        "publicized_memories": int(memory_cur.rowcount or 0),
        "anonymized_sessions": int(session_cur.rowcount or 0),
        "anonymized_events": int(event_cur.rowcount or 0),
        "deleted_legacy_links": int(link_cur.rowcount or 0),
        "deleted_orphan_profiles": int(profile_cur.rowcount or 0),
    }


def observe_visitor_identity(conn: sqlite3.Connection, visitor_ip: str, user_agent: str = "") -> Optional[int]:
    ip = normalize_visitor_ip(visitor_ip)
    if is_anonymous_identity(ip):
        return None
    now = utc_now()
    row = conn.execute(
        """
        SELECT profile_id, seen_count
        FROM visitor_ip_links
        WHERE visitor_ip = ?
        """,
        (ip,),
    ).fetchone()
    if row:
        conn.execute(
            """
            UPDATE visitor_ip_links
            SET seen_count = seen_count + 1,
                user_agent = ?,
                last_seen_at = ?
            WHERE visitor_ip = ?
            """,
            (user_agent or "", now, ip),
        )
        profile_id = int(row["profile_id"])
        conn.execute(
            """
            UPDATE visitor_profiles
            SET updated_at = ?
            WHERE id = ?
            """,
            (now, profile_id),
        )
        return profile_id

    cur = conn.execute(
        """
        INSERT INTO visitor_profiles (
            profile_key, display_name, summary, confidence, created_at, updated_at
        )
        VALUES (?, ?, ?, ?, ?, ?)
        """,
        (
            f"visitor:{ip}",
            "陌生来访者",
            "目前只知道这个来访者的浏览器身份，还没有形成稳定身份画像。",
            0.5,
            now,
            now,
        ),
    )
    profile_id = int(cur.lastrowid)
    conn.execute(
        """
        INSERT INTO visitor_ip_links (
            profile_id, visitor_ip, user_agent, seen_count,
            confidence, first_seen_at, last_seen_at
        )
        VALUES (?, ?, ?, 1, ?, ?, ?)
        """,
        (profile_id, ip, user_agent or "", 0.65, now, now),
    )
    return profile_id


def lookup_visitor_identity(visitor_ip: str) -> Optional[Dict[str, object]]:
    ip = normalize_visitor_ip(visitor_ip)
    with connect_db() as conn:
        row = conn.execute(
            """
            SELECT p.id AS profile_id, p.display_name, p.summary,
                   p.confidence AS profile_confidence,
                   l.visitor_ip, l.seen_count, l.confidence AS ip_confidence,
                   l.first_seen_at, l.last_seen_at
            FROM visitor_ip_links l
            JOIN visitor_profiles p ON p.id = l.profile_id
            WHERE l.visitor_ip = ?
            """,
            (ip,),
        ).fetchone()
        if row is None:
            return None
        memory_count = conn.execute(
            """
            SELECT COUNT(*) AS c
            FROM curated_memories
            WHERE visitor_ip = ? OR profile_id = ?
            """,
            (ip, int(row["profile_id"])),
        ).fetchone()["c"]
    item = {key: row[key] for key in row.keys()}
    item["memory_count"] = int(memory_count)
    return item


def format_visitor_identity_context(visitor_ip: str) -> str:
    ip = normalize_visitor_ip(visitor_ip)
    identity = lookup_visitor_identity(ip)
    if identity is None:
        return (
            "当前设备信息：\n"
            f"- 当前设备身份：{ip}\n"
            "- 识别状态：陌生设备。\n"
            "- 使用方式：不要假装认识对方；可以通过对话内容逐步确认是否是旧用户。"
        )

    seen_count = int(identity.get("seen_count", 0))
    memory_count = int(identity.get("memory_count", 0))
    recognized = seen_count >= 2 or memory_count > 0
    status = "熟悉的设备" if recognized else "陌生设备"
    lines = [
        "当前设备信息：",
        f"- 当前设备身份：{ip}",
        f"- 识别状态：{status}。",
        f"- 该设备身份已出现次数：{seen_count}。",
        f"- 关联长期记忆数量：{memory_count}。",
        f"- 画像摘要：{identity.get('summary')}",
        "- 使用方式：设备身份用于区分上下文；如内容证据冲突，优先通过对话确认身份。",
    ]
    return "\n".join(lines)


def is_known_device_identity(visitor_ip: str) -> bool:
    ip = normalize_visitor_ip(visitor_ip)
    if not is_device_identity(ip):
        return False
    with connect_db() as conn:
        link = conn.execute(
            """
            SELECT profile_id, seen_count
            FROM visitor_ip_links
            WHERE visitor_ip = ?
            """,
            (ip,),
        ).fetchone()
        if link and int(link["seen_count"] or 0) > 0:
            return True
        scope = binding_scope_for_device(conn, ip)
        device_ids = list(scope.get("device_ids") or [ip])
        in_clause, params = sql_in_clause_params(device_ids)
        memory_count = conn.execute(
            f"SELECT COUNT(*) AS c FROM curated_memories WHERE visitor_ip IN {in_clause}",
            params,
        ).fetchone()["c"]
    return int(memory_count or 0) > 0


def opening_time_text(now: Optional[datetime] = None) -> str:
    tz = local_timezone()
    current = now or datetime.now(tz)
    if current.tzinfo is None:
        current = current.replace(tzinfo=tz)
    else:
        current = current.astimezone(tz)
    weekdays = ["星期一", "星期二", "星期三", "星期四", "星期五", "星期六", "星期日"]
    return (
        f"现在是 {current.year}年{current.month}月{current.day}日 "
        f"{current.strftime('%H:%M')}，{weekdays[current.weekday()]}，"
        f"时区 {LOCAL_TIMEZONE_NAME}"
    )


def parse_datetime_for_timeline(value: object) -> Optional[datetime]:
    text = str(value or "").strip()
    if not text:
        return None
    if text.endswith("Z"):
        text = f"{text[:-1]}+00:00"
    try:
        parsed = datetime.fromisoformat(text)
    except Exception:
        return None
    tz = local_timezone()
    if parsed.tzinfo is None:
        parsed = parsed.replace(tzinfo=tz)
    return parsed.astimezone(tz)


def normalize_timeline_kind(value: object) -> str:
    kind = str(value or "").strip().lower()
    return kind if kind in {"point", "range", "deadline"} else ""


def timeline_item_fields(item: Dict[str, object]) -> Dict[str, str]:
    return {
        "timeline_at": str(item.get("timeline_at", "") or "").strip(),
        "timeline_start_at": str(item.get("timeline_start_at", "") or "").strip(),
        "timeline_end_at": str(item.get("timeline_end_at", "") or "").strip(),
        "timeline_kind": normalize_timeline_kind(item.get("timeline_kind", "")),
    }


def timeline_display_text(item: Dict[str, object]) -> str:
    fields = timeline_item_fields(item)
    point = fields["timeline_at"]
    start = fields["timeline_start_at"]
    end = fields["timeline_end_at"]
    kind = fields["timeline_kind"]
    if start and end:
        label = "deadline" if kind == "deadline" else "range"
        return f"{label}={start} -> {end}; main={point or end}"
    if end:
        return f"deadline={end}; main={point or end}" if kind == "deadline" else f"end={end}; main={point or end}"
    if start:
        return f"start={start}; main={point or start}"
    return point


def timeline_event_sort_datetime(row: Dict[str, object]) -> Optional[datetime]:
    return (
        parse_datetime_for_timeline(row.get("timeline_at"))
        or parse_datetime_for_timeline(row.get("timeline_start_at"))
        or parse_datetime_for_timeline(row.get("timeline_end_at"))
        or parse_datetime_for_timeline(row.get("updated_at"))
    )


def timeline_event_active_until_datetime(row: Dict[str, object]) -> Optional[datetime]:
    return (
        parse_datetime_for_timeline(row.get("timeline_end_at"))
        or parse_datetime_for_timeline(row.get("timeline_at"))
        or parse_datetime_for_timeline(row.get("timeline_start_at"))
        or parse_datetime_for_timeline(row.get("updated_at"))
    )


def retrieve_future_event_memories(
    current_visitor_ip: str,
    now: Optional[datetime] = None,
    limit: int = OPENING_FUTURE_EVENT_LIMIT,
) -> List[Dict[str, object]]:
    current_ip = normalize_visitor_ip(current_visitor_ip) if current_visitor_ip else ""
    if not current_ip or not is_device_identity(current_ip):
        return []

    tz = local_timezone()
    current = now or datetime.now(tz)
    if current.tzinfo is None:
        current = current.replace(tzinfo=tz)
    current = current.astimezone(tz)
    window_end = current + timedelta(days=max(1, OPENING_FUTURE_EVENT_WINDOW_DAYS))
    max_rows = min(max(int(limit), 1), 30)

    with connect_db() as conn:
        scope = binding_scope_for_device(conn, current_ip)
        device_ids = list(scope.get("device_ids") or [current_ip])
        in_clause, params = sql_in_clause_params(device_ids)
        rows = conn.execute(
            f"""
            SELECT id, content, importance_label, visitor_ip, profile_id,
                   timeline_at, timeline_start_at, timeline_end_at, timeline_kind,
                   confidence, updated_at
            FROM curated_memories
            WHERE importance_label = 'event'
              AND visitor_ip IN {in_clause}
              AND NOT EXISTS (
                SELECT 1 FROM curated_memories newer WHERE newer.supersedes_id = curated_memories.id
              )
            ORDER BY
              CASE WHEN visitor_ip = ? THEN 0 ELSE 1 END,
              COALESCE(timeline_at, timeline_start_at, timeline_end_at, updated_at) ASC,
              id ASC
            LIMIT 240
            """,
            (*params, current_ip),
        ).fetchall()

    events: List[Dict[str, object]] = []
    seen = set()
    for row in rows:
        row_dict = row_to_dict(row)
        sort_at = timeline_event_sort_datetime(row_dict)
        active_until = timeline_event_active_until_datetime(row_dict)
        if sort_at is None or active_until is None:
            continue
        if active_until < current:
            continue
        start_at = parse_datetime_for_timeline(row_dict.get("timeline_start_at"))
        if sort_at > window_end and (start_at is None or start_at > window_end):
            continue
        content = str(row["content"] or "").strip()
        if not content:
            continue
        start_text = start_at.isoformat(timespec="minutes") if start_at else ""
        end_at = parse_datetime_for_timeline(row_dict.get("timeline_end_at"))
        end_text = end_at.isoformat(timespec="minutes") if end_at else ""
        timeline_text = sort_at.isoformat(timespec="minutes")
        dedupe_key = (content, timeline_text, start_text, end_text)
        if dedupe_key in seen:
            continue
        seen.add(dedupe_key)
        events.append(
            {
                "id": int(row["id"]),
                "content": content,
                "timeline_at": timeline_text,
                "timeline_start_at": start_text,
                "timeline_end_at": end_text,
                "timeline_kind": normalize_timeline_kind(row_dict.get("timeline_kind")),
                "confidence": float(row["confidence"]) if row["confidence"] is not None else 0.7,
            }
        )
        if len(events) >= max_rows:
            break
    return events


def retrieve_recent_diary_memories_for_opening(
    current_visitor_ip: str,
    now: Optional[datetime] = None,
    limit: int = OPENING_RECENT_DIARY_LIMIT,
) -> List[Dict[str, object]]:
    current_ip = normalize_visitor_ip(current_visitor_ip) if current_visitor_ip else ""
    if not current_ip or not is_device_identity(current_ip):
        return []

    tz = local_timezone()
    current = now or datetime.now(tz)
    if current.tzinfo is None:
        current = current.replace(tzinfo=tz)
    current = current.astimezone(tz)
    window_start = current - timedelta(days=max(1, OPENING_RECENT_DIARY_WINDOW_DAYS))
    max_rows = min(max(int(limit), 1), 500)

    with connect_db() as conn:
        scope = binding_scope_for_device(conn, current_ip)
        device_ids = list(scope.get("device_ids") or [current_ip])
        in_clause, params = sql_in_clause_params(device_ids)
        rows = conn.execute(
            f"""
            SELECT id, content, importance_label, visitor_ip, profile_id,
                   timeline_at, confidence, updated_at
            FROM curated_memories
            WHERE importance_label IN ('diary', 'risk')
              AND visitor_ip IN {in_clause}
              AND NOT EXISTS (
                SELECT 1 FROM curated_memories newer WHERE newer.supersedes_id = curated_memories.id
              )
            ORDER BY
              CASE WHEN visitor_ip = ? THEN 0 ELSE 1 END,
              COALESCE(timeline_at, updated_at) DESC,
              confidence DESC,
              id DESC
            LIMIT 160
            """,
            (*params, current_ip),
        ).fetchall()

    memories: List[Dict[str, object]] = []
    seen = set()
    for row in rows:
        memory_at = parse_datetime_for_timeline(row["timeline_at"] or row["updated_at"])
        if memory_at is None:
            continue
        memory_at = memory_at.astimezone(tz)
        if memory_at < window_start or memory_at > current:
            continue
        content = str(row["content"] or "").strip()
        if not content:
            continue
        dedupe_key = clean_search_text(content, 300)
        if dedupe_key in seen:
            continue
        seen.add(dedupe_key)
        memories.append(
            {
                "id": int(row["id"]),
                "content": content,
                "importance_label": str(row["importance_label"] or "diary"),
                "timeline_at": memory_at.isoformat(timespec="minutes"),
                "confidence": float(row["confidence"]) if row["confidence"] is not None else 0.7,
            }
        )
        if len(memories) >= max_rows:
            break
    return memories


def format_opening_recent_diary_context(memories: List[Dict[str, object]]) -> str:
    if not memories:
        return ""
    lines = [
        "最近一周的状态/日记（开篇必须体贴参考）：",
        "这些是用户近期生活、身体、情绪、愿望或状态片段；开场时要自然体现关心，但不要逐条复述，不要说你读取了记忆。",
        "如果某个状态可能已经变化，用温和确认的方式提起。",
    ]
    for index, item in enumerate(memories, start=1):
        lines.append(
            f"{index}. time={item['timeline_at']} label={item['importance_label']} "
            f"confidence={float(item.get('confidence', 0.7)):.2f} content={item['content']}"
        )
    return "\n".join(lines).strip()


def format_future_events_context(events: List[Dict[str, object]]) -> str:
    if not events:
        return ""
    lines = [
        "即将到来的事件/日程提醒（开篇必须优先参考）：",
        "这些是结构化日程事件，不是普通画像；请在开篇自然提醒用户近期事项，不要泄露内部编号。",
    ]
    for index, item in enumerate(events, start=1):
        lines.append(
            f"{index}. time={timeline_display_text(item)} "
            f"confidence={float(item.get('confidence', 0.7)):.2f} "
            f"{str(item['content']).strip()}"
        )
    return "\n".join(lines)


TIMELINE_QUERY_SCHEDULE_TERMS = (
    "日程",
    "活动",
    "安排",
    "会议",
    "组会",
    "演出",
    "请假",
    "截止",
    "提醒",
    "约定",
    "预约",
    "ddl",
    "deadline",
    "什么事",
    "有事",
)

TIMELINE_QUERY_TIME_TERMS = (
    "今天",
    "明天",
    "后天",
    "本周",
    "下周",
    "这周",
    "周一",
    "周二",
    "周三",
    "周四",
    "周五",
    "周六",
    "周日",
    "星期一",
    "星期二",
    "星期三",
    "星期四",
    "星期五",
    "星期六",
    "星期日",
    "礼拜一",
    "礼拜二",
    "礼拜三",
    "礼拜四",
    "礼拜五",
    "礼拜六",
    "礼拜日",
    "上午",
    "下午",
    "晚上",
    "之后",
    "以后",
    "未来",
    "几号",
    "几点",
)

WEEKDAY_ALIASES = (
    ("周一", 0),
    ("星期一", 0),
    ("礼拜一", 0),
    ("周二", 1),
    ("星期二", 1),
    ("礼拜二", 1),
    ("周三", 2),
    ("星期三", 2),
    ("礼拜三", 2),
    ("周四", 3),
    ("星期四", 3),
    ("礼拜四", 3),
    ("周五", 4),
    ("星期五", 4),
    ("礼拜五", 4),
    ("周六", 5),
    ("星期六", 5),
    ("礼拜六", 5),
    ("周日", 6),
    ("星期日", 6),
    ("礼拜日", 6),
    ("周天", 6),
    ("星期天", 6),
    ("礼拜天", 6),
)


def is_timeline_event_query(user_message: str) -> bool:
    text = clean_search_text(user_message, 300).lower()
    if not text:
        return False
    has_schedule_term = any(term in text for term in TIMELINE_QUERY_SCHEDULE_TERMS)
    has_time_term = any(term in text for term in TIMELINE_QUERY_TIME_TERMS)
    if has_schedule_term and has_time_term:
        return True
    if has_schedule_term and any(term in text for term in ("有什么", "有没有", "查一下", "看看", "记得")):
        return True
    return False


def start_of_local_day(value: datetime) -> datetime:
    tz = local_timezone()
    current = value.astimezone(tz) if value.tzinfo else value.replace(tzinfo=tz)
    return current.replace(hour=0, minute=0, second=0, microsecond=0)


def next_weekday_start(now: datetime, weekday: int) -> datetime:
    today = start_of_local_day(now)
    delta_days = (weekday - today.weekday()) % 7
    return today + timedelta(days=delta_days)


def event_query_time_window(user_message: str, now: Optional[datetime] = None) -> Tuple[datetime, datetime]:
    tz = local_timezone()
    current = now or datetime.now(tz)
    if current.tzinfo is None:
        current = current.replace(tzinfo=tz)
    current = current.astimezone(tz)
    text = clean_search_text(user_message, 300)
    default_end = current + timedelta(days=max(1, OPENING_FUTURE_EVENT_WINDOW_DAYS))

    for alias, weekday in WEEKDAY_ALIASES:
        if alias not in text:
            continue
        day_start = next_weekday_start(current, weekday)
        if any(marker in text for marker in (f"{alias}及之后", f"{alias}之后", f"{alias}以后", f"{alias}起")):
            today_start = start_of_local_day(current)
            current_week_day_start = today_start + timedelta(days=weekday - today_start.weekday())
            return current_week_day_start, default_end
        return day_start, day_start + timedelta(days=1)

    if "后天" in text:
        day_start = start_of_local_day(current + timedelta(days=2))
        return day_start, day_start + timedelta(days=1)
    if "明天" in text:
        day_start = start_of_local_day(current + timedelta(days=1))
        return day_start, day_start + timedelta(days=1)
    if "今天" in text:
        day_start = start_of_local_day(current)
        return day_start, day_start + timedelta(days=1)
    return current, default_end


def format_regular_timeline_events_context(events: List[Dict[str, object]]) -> str:
    if not events:
        return ""
    lines = [
        "普通聊天中可参考的未来事件/日程：",
        "这些是用户曾明确提供或后台整理的结构化 event；当用户询问日程、活动、提醒、会议或日期范围时，必须优先依据这些事件回答。",
        "如果这些事件中没有匹配项，只能说目前没有记录到对应日程；不要根据用户身份、学校或常识泛泛猜测。",
        "",
    ]
    for index, item in enumerate(events, start=1):
        lines.append(
            f"[未来事件 {index}] time={timeline_display_text(item)} "
            f"confidence={float(item.get('confidence', 0.7)):.2f}"
        )
        lines.append(str(item["content"]).strip())
        lines.append("")
    return "\n".join(lines).strip()


def build_regular_timeline_events_context(
    user_message: str,
    visitor_ip: str,
    session_id: str = "",
    analysis_trace_id: str = "",
) -> str:
    if not is_timeline_event_query(user_message):
        return ""
    now = datetime.now(local_timezone())
    window_start, window_end = event_query_time_window(user_message, now)
    events = retrieve_future_event_memories(
        visitor_ip,
        now=window_start,
        limit=min(max(OPENING_FUTURE_EVENT_LIMIT, 8), 20),
    )
    filtered: List[Dict[str, object]] = []
    for event in events:
        event_start = (
            parse_datetime_for_timeline(event.get("timeline_start_at"))
            or parse_datetime_for_timeline(event.get("timeline_at"))
        )
        event_end = (
            parse_datetime_for_timeline(event.get("timeline_end_at"))
            or parse_datetime_for_timeline(event.get("timeline_at"))
            or event_start
        )
        if event_start is None or event_end is None:
            continue
        if event_end < window_start or event_start >= window_end:
            continue
        filtered.append(event)
    if analysis_trace_id:
        record_analysis_trace(
            session_id=session_id,
            trace_id=analysis_trace_id,
            event_type="memory_agent",
            visitor_ip=visitor_ip,
            step_name="timeline_event_lookup",
            payload={
                "query": user_message[:240],
                "window_start": window_start.isoformat(timespec="minutes"),
                "window_end": window_end.isoformat(timespec="minutes"),
                "results": [
                    {
                        "memory_id": item.get("id"),
                        "timeline_at": item.get("timeline_at"),
                        "timeline_start_at": item.get("timeline_start_at"),
                        "timeline_end_at": item.get("timeline_end_at"),
                        "timeline_kind": item.get("timeline_kind"),
                        "confidence": item.get("confidence"),
                        "content": item.get("content"),
                    }
                    for item in filtered
                ],
            },
        )
    return format_regular_timeline_events_context(filtered)
