# Generated by splitting app.py recent user state helpers. Keep execution order in wangcai_app/startup/loader.py.
RECENT_STATE_MEMORY_LABELS = {"diary", "risk", "event"}
RECENT_STATE_DIAGNOSTIC_TERMS = (
    "焦虑型人格",
    "回避型人格",
    "依恋障碍",
    "人格障碍",
    "抑郁症",
    "躁郁症",
    "双相障碍",
    "病理",
    "诊断为",
    "患者",
    "病人",
)


def user_recent_state_scope_key(visitor_ip: str) -> str:
    ip = normalize_visitor_ip(visitor_ip)
    if not is_device_identity(ip):
        return ip
    try:
        with connect_db() as conn:
            scope = binding_scope_for_device(conn, ip)
    except Exception:
        return ip
    shared_user_id = clean_shared_user_id(str(scope.get("shared_user_id") or ""))
    if shared_user_id:
        return f"shared:{shared_user_id}"
    return ip


def user_recent_state_scope_device_ids(scope_key: str) -> List[str]:
    scope = str(scope_key or "").strip()
    if scope.startswith("shared:"):
        shared_user_id = clean_shared_user_id(scope.split(":", 1)[1])
        if not shared_user_id:
            return []
        with connect_db() as conn:
            rows = conn.execute(
                """
                SELECT device_id
                FROM shared_user_bindings
                WHERE shared_user_id = ?
                ORDER BY updated_at DESC, device_id ASC
                """,
                (shared_user_id,),
            ).fetchall()
        return [
            normalize_visitor_ip(str(row["device_id"] or ""))
            for row in rows
            if is_device_identity(str(row["device_id"] or ""))
        ]
    normalized = normalize_visitor_ip(scope)
    return [normalized] if is_device_identity(normalized) else []


def sanitize_recent_state_text(value: object, max_chars: int = 360) -> str:
    text = clean_search_text(str(value or ""), max_chars)
    for term in RECENT_STATE_DIAGNOSTIC_TERMS:
        text = text.replace(term, "")
    text = re.sub(r"\s+", " ", text).strip(" ，。；、")
    return text[:max_chars].strip()


def sanitize_recent_state_list(value: object, limit: int = 4) -> List[str]:
    if not isinstance(value, list):
        return []
    items: List[str] = []
    for raw in value:
        text = sanitize_recent_state_text(raw, 160)
        if text and text not in items:
            items.append(text)
        if len(items) >= limit:
            break
    return items


def normalize_user_recent_state_payload(payload: object) -> Dict[str, object]:
    raw = payload if isinstance(payload, dict) else {}
    try:
        confidence = float(raw.get("confidence", 0.5))
    except Exception:
        confidence = 0.5
    return {
        "state_summary": sanitize_recent_state_text(raw.get("state_summary", ""), 420),
        "emotional_weather": sanitize_recent_state_text(raw.get("emotional_weather", ""), 220),
        "core_needs": sanitize_recent_state_list(raw.get("core_needs"), 4),
        "friction_points": sanitize_recent_state_list(raw.get("friction_points"), 4),
        "care_suggestions": sanitize_recent_state_list(raw.get("care_suggestions"), 5),
        "avoid_suggestions": sanitize_recent_state_list(raw.get("avoid_suggestions"), 5),
        "confidence": min(1.0, max(0.0, confidence)),
        "rationale": sanitize_recent_state_text(raw.get("rationale", ""), 240),
    }


def user_recent_state_expires_at(updated_at: str) -> str:
    parsed = parse_utc_iso(updated_at) or datetime.now(timezone.utc)
    return (parsed + timedelta(days=3)).isoformat(timespec="seconds")


def save_user_recent_state(
    scope_key: str,
    window_days: int,
    state: Dict[str, object],
    source_memory_ids: Optional[List[int]] = None,
    updated_at: str = "",
) -> Dict[str, object]:
    normalized_scope = str(scope_key or "").strip()
    if not normalized_scope:
        raise ValueError("scope_key is required")
    normalized_days = max(1, int(window_days))
    normalized_state = normalize_user_recent_state_payload(state)
    now = updated_at or utc_now()
    memory_ids = [int(item) for item in (source_memory_ids or []) if str(item).strip().isdigit()]
    with connect_db() as conn:
        conn.execute(
            """
            INSERT INTO user_recent_states (
                scope_key, window_days, state_json, source_memory_ids_json,
                source_memory_count, updated_at, expires_at
            )
            VALUES (?, ?, ?, ?, ?, ?, ?)
            ON CONFLICT(scope_key, window_days) DO UPDATE SET
                state_json = excluded.state_json,
                source_memory_ids_json = excluded.source_memory_ids_json,
                source_memory_count = excluded.source_memory_count,
                updated_at = excluded.updated_at,
                expires_at = excluded.expires_at
            """,
            (
                normalized_scope,
                normalized_days,
                json.dumps(normalized_state, ensure_ascii=False),
                json.dumps(memory_ids, ensure_ascii=False),
                len(memory_ids),
                now,
                user_recent_state_expires_at(now),
            ),
        )
    return normalized_state


def load_user_recent_state(scope_key: str, window_days: int) -> Optional[Dict[str, object]]:
    normalized_scope = str(scope_key or "").strip()
    if not normalized_scope:
        return None
    with connect_db() as conn:
        row = conn.execute(
            """
            SELECT scope_key, window_days, state_json, source_memory_ids_json,
                   source_memory_count, updated_at, expires_at
            FROM user_recent_states
            WHERE scope_key = ? AND window_days = ?
            """,
            (normalized_scope, int(window_days)),
        ).fetchone()
    if not row:
        return None
    try:
        state = json.loads(str(row["state_json"] or "{}"))
    except Exception:
        state = {}
    try:
        source_ids = json.loads(str(row["source_memory_ids_json"] or "[]"))
    except Exception:
        source_ids = []
    return {
        "scope_key": str(row["scope_key"]),
        "window_days": int(row["window_days"]),
        "state": normalize_user_recent_state_payload(state),
        "source_memory_ids": source_ids if isinstance(source_ids, list) else [],
        "source_memory_count": int(row["source_memory_count"] or 0),
        "updated_at": str(row["updated_at"] or ""),
        "expires_at": str(row["expires_at"] or ""),
    }


def should_refresh_user_recent_state(scope_key: str, window_days: int, now_iso: str = "") -> bool:
    item = load_user_recent_state(scope_key, window_days)
    if not item:
        return True
    now = parse_utc_iso(now_iso or utc_now()) or datetime.now(timezone.utc)
    updated = parse_utc_iso(item.get("updated_at")) or datetime.fromtimestamp(0, timezone.utc)
    if now.date() > updated.date():
        return True
    return (now - updated).total_seconds() >= USER_RECENT_STATE_UPDATE_INTERVAL_SECONDS


def recent_state_cutoff_iso(window_days: int) -> str:
    return (datetime.now(timezone.utc) - timedelta(days=max(1, int(window_days)))).isoformat(timespec="seconds")


def load_user_recent_state_source_memories(scope_key: str, window_days: int) -> List[Dict[str, object]]:
    device_ids = user_recent_state_scope_device_ids(scope_key)
    if not device_ids:
        return []
    in_clause, params = sql_in_clause_params(device_ids)
    label_clause, label_params = sql_in_clause_params(sorted(RECENT_STATE_MEMORY_LABELS))
    with connect_db() as conn:
        rows = conn.execute(
            f"""
            SELECT id, content, importance_label, visitor_ip,
                   timeline_at, timeline_start_at, timeline_end_at, timeline_kind,
                   confidence, created_at, updated_at
            FROM curated_memories
            WHERE visitor_ip IN {in_clause}
              AND importance_label IN {label_clause}
              AND updated_at >= ?
              AND NOT EXISTS (
                SELECT 1 FROM curated_memories newer WHERE newer.supersedes_id = curated_memories.id
              )
            ORDER BY COALESCE(timeline_at, updated_at) DESC, updated_at DESC, id DESC
            LIMIT ?
            """,
            [*params, *label_params, recent_state_cutoff_iso(window_days), int(USER_RECENT_STATE_SOURCE_LIMIT)],
        ).fetchall()
    return [dict(row) for row in rows]


def extract_user_recent_state_json_object(text: str) -> Dict[str, object]:
    cleaned = str(text or "").strip()
    if cleaned.startswith("```"):
        cleaned = re.sub(r"^```(?:json)?\s*", "", cleaned)
        cleaned = re.sub(r"\s*```$", "", cleaned)
    try:
        payload = json.loads(cleaned or "{}")
    except Exception:
        match = re.search(r"\{.*\}", cleaned, flags=re.S)
        if not match:
            return {}
        try:
            payload = json.loads(match.group(0))
        except Exception:
            return {}
    return payload if isinstance(payload, dict) else {}


def parse_user_recent_state_agent_response(text: str) -> Dict[str, object]:
    return normalize_user_recent_state_payload(extract_user_recent_state_json_object(text))


def call_user_recent_state_agent_model(
    window_days: int,
    memories: List[Dict[str, object]],
    previous_state: Optional[Dict[str, object]] = None,
) -> Dict[str, object]:
    client, http_client, model_slot = openai_client_for_slot(MODEL_SLOT_BACKGROUND, timeout=USER_RECENT_STATE_TIMEOUT)
    try:
        resp = client.chat.completions.create(
            **model_completion_kwargs(model_slot),
            messages=[
                {"role": "system", "content": USER_RECENT_STATE_AGENT_SYSTEM_PROMPT},
                {
                    "role": "user",
                    "content": build_user_recent_state_agent_user_prompt(window_days, memories, previous_state),
                },
            ],
            temperature=USER_RECENT_STATE_TEMPERATURE,
            top_p=USER_RECENT_STATE_TOP_P,
            max_tokens=USER_RECENT_STATE_MAX_TOKENS,
        )
        content = (resp.choices[0].message.content or "").strip()
        _, answer = split_think_text(content)
        return parse_user_recent_state_agent_response(answer)
    finally:
        http_client.close()


def format_user_recent_state_context(visitor_ip: str) -> str:
    scope_key = user_recent_state_scope_key(visitor_ip)
    windows = USER_RECENT_STATE_WINDOWS_DAYS or (7, 30)
    blocks: List[str] = []
    for window_days in windows:
        item = load_user_recent_state(scope_key, int(window_days))
        if not item:
            continue
        state = item.get("state") if isinstance(item.get("state"), dict) else {}
        summary = str(state.get("state_summary") or "").strip()
        if not summary:
            continue
        lines = [f"- {int(window_days)}天状态：{summary}"]
        emotional_weather = str(state.get("emotional_weather") or "").strip()
        if emotional_weather:
            lines.append(f"  情绪天气：{emotional_weather}")
        core_needs = state.get("core_needs") if isinstance(state.get("core_needs"), list) else []
        if core_needs:
            lines.append("  近期更需要：" + "；".join(str(item) for item in core_needs[:4]))
        care = state.get("care_suggestions") if isinstance(state.get("care_suggestions"), list) else []
        if care:
            lines.append("  回应方式：" + "；".join(str(item) for item in care[:5]))
        avoid = state.get("avoid_suggestions") if isinstance(state.get("avoid_suggestions"), list) else []
        if avoid:
            lines.append("  避免：" + "；".join(str(item) for item in avoid[:5]))
        blocks.append("\n".join(lines))
    if not blocks:
        return ""
    return (
        "近期陪伴提示：以下内容是后台根据近期 diary/risk/event 形成的隐性状态假设，"
        "只作为温柔假设和回应风格参考，不是诊断、标签或永久身份；"
        "如果用户当下表达与它冲突，必须以用户当下表达为准。不要主动暴露具体隐私事件。\n"
        + "\n".join(blocks)
    )


def recent_state_candidate_scope_keys(limit: int = USER_RECENT_STATE_SCOPE_LIMIT) -> List[str]:
    with connect_db() as conn:
        rows = conn.execute(
            """
            SELECT visitor_ip, MAX(updated_at) AS latest
            FROM curated_memories
            WHERE visitor_ip LIKE 'device:%'
              AND importance_label IN ('diary', 'risk', 'event')
            GROUP BY visitor_ip
            ORDER BY latest DESC
            LIMIT ?
            """,
            (max(1, int(limit)) * 3,),
        ).fetchall()
    keys: List[str] = []
    seen = set()
    for row in rows:
        scope_key = user_recent_state_scope_key(str(row["visitor_ip"] or ""))
        if not scope_key or scope_key in seen:
            continue
        seen.add(scope_key)
        keys.append(scope_key)
        if len(keys) >= max(1, int(limit)):
            break
    return keys


def _record_recent_state_event(event_type: str, metadata: Dict[str, object]) -> None:
    try:
        record_event(None, event_type, "local", metadata)
    except Exception:
        pass


def run_user_recent_state_agent_once(force: bool = False) -> Dict[str, object]:
    started_at = utc_now()
    timer = time.perf_counter()
    if not USER_RECENT_STATE_AGENT_ENABLED:
        return {"status": "skipped", "reason": "user_recent_state_disabled", "started_at": started_at}
    if not force:
        try:
            cleanup_stale_active_generations()
            with ACTIVE_GENERATIONS_LOCK:
                if ACTIVE_GENERATIONS:
                    return {"status": "busy", "reason": "active_generation", "started_at": started_at}
        except Exception:
            pass
        if time.time() - LAST_USER_ACTIVITY_AT < IDLE_AGENT_MIN_IDLE_SECONDS:
            return {"status": "skipped", "reason": "idle_wait", "started_at": started_at}

    updated = 0
    skipped = 0
    failed = 0
    max_updates = max(1, int(USER_RECENT_STATE_MAX_UPDATES_PER_RUN))
    windows = USER_RECENT_STATE_WINDOWS_DAYS or (7, 30)
    for scope_key in recent_state_candidate_scope_keys():
        for window_days in windows:
            if updated >= max_updates:
                break
            try:
                if not force and not should_refresh_user_recent_state(scope_key, int(window_days)):
                    skipped += 1
                    continue
                memories = load_user_recent_state_source_memories(scope_key, int(window_days))
                if not memories:
                    skipped += 1
                    continue
                previous = load_user_recent_state(scope_key, int(window_days))
                previous_state = previous.get("state") if previous else None
                state = call_user_recent_state_agent_model(int(window_days), memories, previous_state)
                if not state.get("state_summary"):
                    skipped += 1
                    continue
                save_user_recent_state(
                    scope_key,
                    int(window_days),
                    state,
                    source_memory_ids=[int(item["id"]) for item in memories if item.get("id")],
                )
                updated += 1
            except Exception as exc:
                failed += 1
                _record_recent_state_event(
                    "user_recent_state_agent_error",
                    {"scope_key": scope_key, "window_days": int(window_days), "error": str(exc)},
                )
        if updated >= max_updates:
            break
    status = "completed" if updated else ("failed" if failed and not skipped else "skipped")
    return {
        "status": status,
        "reason": "updated" if updated else "no_due_scope",
        "updated": updated,
        "skipped": skipped,
        "failed": failed,
        "started_at": started_at,
        "duration_ms": round((time.perf_counter() - timer) * 1000, 3),
    }
